### ISSUE TITLE
Add export options --update

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#100]
Add ability to resume a cancelled/failed export and option to only export files if newer than destination (e.g. update an export)

**Comment by RhetTbull** [comment]
checkpoint settings in .osxphotos?

**Comment by RhetTbull** [comment]
also add --update-metadata that would only update metadata if changed? If user used --exiftool, check to see if metadata changed and if so update with exiftool, for --sidecar, rewrite all the sidecars

**Comment by NiccoStar86** [comment]
this could be useful to avoid the re-copy of the files if already in the destination! for an "incremental" scenario for big archives is great!

**Comment by RhetTbull** [comment]
Thinking of an interface like this:

`osxphotos export --update --exiftool /path/to/export`

If --update, check to see if photo exists and if so, is the one in Photos newer. If newer, export it. 

If --exiftool or --sidecar, would also check to see if any metadata changed and if so, write new metadata

**Comment by NiccoStar86** [comment]
I think that in this way is totally modular, like the rest of the options! If added --exiftool or --sidecar, if a file already exist the procedure will check only the metadata, and if different update it, not re-copy the entire file, right?

**Comment by RhetTbull** [comment]
@NiccoStar86 yes, intent with update would be to not re-copy the entire file.  However, to update exifdata embedded in the file it must be re-written using exiftool.  It would still be faster because the current export does 2 copies -- one to get file out of the library then a second to apply metadata.  This same interface could be used to stop and re-start an export.  For example, if you needed to cancel out of a long-running export, you could use --update to re-start where you left off.

**Comment by NiccoStar86** [comment]
@RhetTbull Perfect explanation! The new option --update will make osxphotos even better. Waiting to test it :)

**Comment by felciano** [comment]
Thanks for the pointer @RhetTbull. Is there a technical / architectural design gating this e.g. re figuring out how to efficiently cache do the metadata comparison? And I assume there is no way to dereference the photo directly within the library and skip that first copy step you describe in https://github.com/RhetTbull/osxphotos/issues/100#issuecomment-623127493

**Comment by RhetTbull** [comment]
@felciano no particular technical issues, just time to implement.  I've actually started working on the design.   I'll likely add this as an option to `PhotoInfo.export()`.  Comparing the files is straightforward -- [filecmp.cmp](https://docs.python.org/3/library/filecmp.html) is probably sufficient.  However, if the user applied metadata with the `--exiftool` option, the files won't be the same so I'll then need to read the exif data from the destination file and compare it to the exif data in the Photos library, again not difficult, just need to think through the implementation.  For example, using the `--keyword-template` option, the user can apply additional keywords such as album, person in image, etc. to the destination file's exif data.  I'll need to compute the keywords that would have been written and ensure they're identical to the keywords in the destination file.  

Regarding your question about the first copy step, I don't think there's any easy way given current design to do this.  Exporting a photo with `--exiftool` option looks like this now:
1. Copy file out of Photos to destination path using `ditto` command which preserves extended attributes and other metadata about the file.
2. Use exiftool to modify the exif data.
3. exiftool creates a temporary copy, rewrites the data with the new exif header, then removes the original copy and renames the file to the original name

I don't think exiftool has an option to specify the destination file which I think is what you're referring to thus the initial copy still needs to be done.

There is a new option to use hardlinks when exporting which avoids the initial copy.  However, if this is used with `--exiftool`, exiftool still creates the duplicate file which breaks the hardlink (this is a bug in implementation I need to work through).

**Comment by RhetTbull** [comment]
I also don't know if exiftool preserves all the metadata (extended attributes, resource fork) associated with the file when rewriting.  Need to check this (I bet it does not preserve the data).  If not, I could use [osxmetadata](https://github.com/RhetTbull/osxmetadata) to rewrite the extended attributes but the resource fork would be lost.

**Comment by RhetTbull** [comment]
I have this mostly implemented but have run into an issue that will take some engineering to resolve.  It is possible for a file in Photos to have the same original name as another file (this is quite common, e.g. two files named `IMG_0001.JPG`).  If these happen to be in the same export directory, osxphotos will normally detect a collision and increment the second file: e.g. it will be exported as `IMG_0001 (1).JPG`, `IMG_0001 (2).JPG`, and so on.  However, with `--update`, osxphotos has no way of associating the exported image with the original image in the case where more than one image of the same name is in the same directory.  

To fix this, osxphotos will have to associate some sort of metadata with each exported image to map it back to the original file in the Photos library.  In Photos 5, Photos writes an extended attribute `com.apple.assetsd.UUID` to the original file which is preserved in the export and could be used to map back but this does not apply to the raw photo and doesn't work on earlier versions.  One option is to create a file in each export directory, for example `.osxphotos` that preserves some state information about the export, e.g. the original UUID mapped to the exported file name.  Another option is write custom metadata via an extended attribute (e.g. `com.osxphotos.uuid` to do the mapping.  

The extended attribute is probably the most elegant and transparent but would be more difficult to implement because of the extra steps involved with checking every file increment.  Using a dot-file, I could simply write out a serialized json dictionary mapping `{uuid: exported_filename}`.

**Comment by NiccoStar86** [comment]
The option to create a ".osxphotos" file inside each directory would be great, but how do you manage the case of two photos with the same filename? Adding a progressive counter IMG_0001 (1).JPG, IMG_0001 (2).JPG, and so on? If this is easy to implement should work well.

Another fastest solution could be that when the option --update is used, osxphotos force the filename of the files exported to "photos_uuid.exstension" to have the uniqueness assured. Not very elegant but works :)

**Comment by RhetTbull** [comment]
@NiccoStar86 because I know the UUID of the photo prior to export, it would be possible to create a dictionary that maps from UUID to filename, for example:
```json
{"UUID1": "filename.jpg", 
 "UUID2": "filename (1).jpg"
}
```
Your idea to add uuid to the filename would work but I want the user to be able to have control over the destination filename -- for example, I intend to extend the templating system currently used for `--directory` to allow user to specify output file with a template.  Also, I want `--update` to work even if user didn't specify `--update` in initial export.  For example:

`osxphotos export ~/path/to/export`
then later
`osxphotos export ~/path/to/export --update`
would only update new files

In the first case, if a collision is detected, osxphotos automatically increments the filename and so the second case will need a way to know this when doing the update.

I'll experiment with a couple different ways of storing the mapping from UUID to filename and hopefully get this implemented soon.  The rest of the `--update` code appears to be working.

**Comment by NiccoStar86** [comment]
@RhetTbull as usual, very clear explanation! Yes, my idea was quite "crude" ;) but I understand the clear vision of the project and the endless possibilities of "customization" that you want to give to everyone. Thank you

**Comment by RhetTbull** [comment]
I have `--update` working for photos, now working on updating metadata (`--exiftool`, `--sidecar`).  I settled on writing the UUID of the photo to a custom extended attribute `com.osxphotos.uuid` upon export so osxphotos can map the exported image back to original.  This should work on all Mac filesystems and be completely transparent to the user with no need for additional files to store state.

**Comment by felciano** [comment]
How would this work for files on e.g. a NAS? Would using the `rsync -X` option preserve this new attribute?

**Comment by NiccoStar86** [comment]
Good question, which interests me too @felciano ... My destination is a folder on a Synology mounted via SMB on my iMac, and during the previous test I used the option `--no-extended-attributes` because without I have received an error during the export!

**Comment by RhetTbull** [comment]
Good question.  If the NAS supports extended attributes, this should work fine.  If not, then `--update` as currently implemented wouldn't work.  

@felciano `rsync -E` will preserve extended attributes and I just confirmed it does preserve the custom xattr.  If this is a big issue, I'll come up with another solution for `--update`.  I implemented this in a way that it's not difficult to re-engineer a new solution.  The code requires 2 methods: `get_uuid_for_file` and  `set_uuid_for_file`.  Those could be refactored to use a serialized dictionary or even a sqlite database to store the data.

@NiccoStar86 take a look at [this](https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X) article; another `osxphotos` user found it helpful for configuring SMB so he didn't need to use `--no-extended-attributes`

**Comment by RhetTbull** [comment]
I've rewritten the UUID check for `--update` to use a sqlite file which will be created in the export destination.  Currently it's called `/path/to/export/.osxphotos_export.db`.  Though I like the elegance of the extended attributes solution, it may cause problems for those exporting to NAS volumes.  Having a full database associated with the export will provide a means to add other functionality in the future, e.g. perhaps to remember to all the options the original export was called with and re-use those automatically.  

For example, you could do:
`osxphotos export /path/to/export --directory "{created.year}/{created.month}" --keyword-template "{person}" --keyword-template "{label}" --exiftool`

then later, simply

`osxphotos export --update /path/to/export` 

and all the settings would be read from the database

**Comment by felciano** [comment]
@RhetTbull love the idea. How would it work for directory trees? For example, if the intent is to create a fairly common YYYY/MM/DD tree structure for the files, would there be an `.osxphotos_export_db` at each level or just the root? And would it contain metadata just for the photo files immediately within that directory, or for those within subdirectories as well?

**Comment by RhetTbull** [comment]
@felciano for simplicity and performance I think a single database at the top level of the export is best so we don't have to have possibly hundreds of file handles open.  My plan is to store the relative path to the files from the top level export.  So if export structure looks like this:

```
/path/to/export/2020/05/16/IMG_002.JPG
/path/to/export/2020/05/15/IMG_001.JPG
...and so on
```
the database would be:
`/path/to/export/.osxphotos_export.db`

and each file, uuid pair would be stored as:
`2020/05/16/IMG_002.JPG: UUID`
`2020/05/15/IMG_001.JPG: UUID`

That way, if you moved the entire export tree, everything would still work transparently to the user.

**Comment by felciano** [comment]
Got it. And would the `.osxphotos_export_db` contain just the UID-to-filename mappings, or would it contain additional metadata information such as faces etc?

**Comment by RhetTbull** [comment]
Right now I only plan to store the UUID to filename mapping and in the future, possibly the options that `osxphotos` was called with.  I'm not sure what the utility of storing the other metadata would be as it wouldn't be easily accessible to the user.  Do you have a use case in mind?  If the user wants to preserve the metadata, I recommend either doing this in the EXIF headers using `--exiftool` or in a JSON or XMP sidecar file using the `--sidecar` option.

**Comment by NiccoStar86** [comment]
@RhetTbull great idea to use a sqlite, and expandable for the future ;) ... Now I'll read and test the link suggested, thank you!

**Comment by felciano** [comment]
> Do you have a use case in mind?

A few use cases to think through based on my experience with similar approaches elsewhere. I hesitate to call these "use cases" -- they are more "edge cases" to think through because someone will do them, so should have clarified system behavior as such:

1. If I do `osxphotos export /path/to/export etc` at one point, and then at another point someone (maybe me) does `osxphotos export /path/to/export/subdirectory ...`. This would likely result in 2 SQLite files at different levels of the hierarchy with different metadata caches. A simple solution is to forbid this: walk up the tree and fail the command if you find another `.osxphotos_export.db` upstream. A more elegant (but harder) solution might be to make sure both databases are in sync somehow, but I'm not sure it is worth the effort.

2. Similarly, perhaps refuse to accept a given destination root path if that path already exists and has a metadata database in one of its subdirectories. That would indicate that you are syncing to the parent of a previously existing destination, and you'd need to clarify which database has precedence (and whether your overwrite/delete the existing one).

3. Similarly, someone will at some point copy just one subdirectory (e.g. the `2020/05` directory in your example) to a new location, and thus disconnect it from the metadata stored at the root. If the only information lost are the UUIDs and the only consequence is no longer being able to efficiently do a `diff` then that sounds like a reasonable tradeoff provided it is documented. If more information/capabilities are lost for a user that does such a copy, then the design might be worth revisiting, but it doesn't sound like that is the case.

Again, I don't think these are true use cases, but probably worth clarifying the behavior for users in the docs.

**Comment by RhetTbull** [comment]
Thanks @felciano -- all good edge cases.  I'll consider adding an issue to perform the check for existing database file and warn user if one is found.  However, in all these cases the worst thing that happens is the user re-exports a bunch of photos, possibly in the wrong location which isn't critical but in all cases, does add complexity to the code.  Another similar case is the user runs an update in the same directory but with different options, or example, `--directory "{created.year}/{created.month}"` the first time then `--directory "{album}"` the second time.  This might be intentional but might not so I plan to eventually store the arguments that `osxphotos` was called with in the database to be able to warn the user if they are updating with different options.   Of course, that has all sorts of edge cases too, for example, the user might have exported without metadata the first time then wants to update but add metadata via `--exiftool`.  In this case the "correct" behavior is to not re-export the photo but to apply the metadata in-situ.

In the same vein of helping the user do the right thing, would you prefer the database file be hidden (e.g. `.osxphotos_export.db`) or not (e.g. `osxphotos_export.db`).  My expectation is the person who's running a python app from the terminal is savy enough to understand about dot files (and the cognizant of the fact these won't show in the Finder) but perhaps that's expecting too much?

**Comment by NiccoStar86** [comment]
@RhetTbull I vote for the "hidden" database, if only to avoid the mistake of deleting it ... Then in the documentation you can explain in detail what is saved in the database and where it is, but I would avoid leaving it easily "accessible" via Finder

**Comment by felciano** [comment]
> My expectation is the person who's running a python app from the terminal is savy enough to understand about dot files (and the cognizant of the fact these won't show in the Finder) but perhaps that's expecting too much?

This seems like a reasonable explanation. Probably also willing to RTFM so as long as the edge case behavior is documented I suspect you'll be fine.

**Comment by RhetTbull** [comment]
This is getting closer.  I've added checks to try to find matching files in the destination if there is no DB that way if user ran --update against a library previously exported with older version of `osxphotos` or if the DB file got deleted, the update still works without having to re-export everything (and builds the DB in the process).  Now working on the metadata update.

**Comment by RhetTbull** [comment]
Working on the metadata cache to compare metadata.  Instead of reading metadata directly from each file to compare, which will be slow, I've experimenting with caching a JSON representation of everything known about the photo in the export database.  This adds about 2kB per photo exported which seems reasonable.  Access will be much quicker than reading EXIF data directly from each file.

**Comment by RhetTbull** [comment]
This is going to be more complex than I thought.  If user uses `--exiftool`, the destination file will always be different than the source file due to being re-written by `exiftool` and so the file comparison will fail and the file will get updated every time --update is run.  In addition to comparing the cached metadata, I'll also have to cache and compare a hash of the file before and after it's been written to by exiftool and use those for comparison.

**Comment by RhetTbull** [comment]
I think this is done in version [0.29.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.29.0)!  It took significant re-factoring to make this work but I believe it's working now and all tests passing for expected edge cases.   Thanks much @felciano and @NiccoStar86 for the feedback during the development process.  Let me know if you encounter any issues.

**Comment by NiccoStar86** [comment]
Thank you to you @RhetTbull for this great job! I'll test the new version asap and I'll update you!

**Comment by NiccoStar86** [comment]
Dear @RhetTbull I tested the --update option and works very well! But during the execution I receive some "WARNING" that I believe related to the export of some files. Even if I use the --verbose option in the log I don't find any errors. Is there any test that I can do to try to find out more precisely, what generates these errors? Thank you!
<img width="1333" alt="Schermata 2020-06-05 alle 11 58 03" src="https://user-images.githubusercontent.com/7814756/83921822-80b12680-a77f-11ea-85b3-5c65e8471b2e.png">

**Comment by RhetTbull** [comment]
@NiccoStar86 thanks -- the .tiff warnings can be ignored -- I'll add a fix for those so you don't get the warning.  Has to do with sometimes Photos saves as .tiff and sometimes as .tif.  This also happens with .jpg and .jpeg.  However, the warning on the JPG being saved as PNG indicates a bug.  I'll add some debug code and push a new version if you don't mind trying it.

**Comment by NiccoStar86** [comment]
Absolutely @RhetTbull, I will gladly a try as soon as the new version is available.
