### ISSUE TITLE
Identify RAW photos with JPEG previews

### ISSUE THREAD

**Issue by jhfarrell** [RhetTbull/osxphotos#101]
If a raw image is in the library and it has a separate jpeg preview file, only the jpeg file is reported by osxphotos.  If the raw image is set as the original, then that version is found.  Either way, the accompanying image is ignored.  Should be a way to identify and report these image pairs.

**Comment by RhetTbull** [comment]
@jhfarrell thanks for the issue report.  I've been able to replicate the behavior you indicated.  I agree that osxphotos should provide access both the the RAW image and the associated .jpeg.  I'll look into this.

**Comment by RhetTbull** [comment]
Trying to figure out how to find the associated raw file -- as best as I can tell, it's not referenced by name anywhere in the database.  

A few thoughts:
The raw file is in originals with same uuid as the jpeg but has _4 added to end of basename.  

```
./originals/F/F29B54CF-1CA3-41B2-BA38-3D49E14F232A_4.cr2
./originals/F/F29B54CF-1CA3-41B2-BA38-3D49E14F232A.jpeg
```

```sql
SELECT
ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME, 
ZINTERNALRESOURCE.ZDATALENGTH, 
ZINTERNALRESOURCE.ZUNIFORMTYPEIDENTIFIER, 
ZINTERNALRESOURCE.ZDATASTORESUBTYPE,
ZINTERNALRESOURCE.ZRESOURCETYPE
FROM ZADDITIONALASSETATTRIBUTES
JOIN ZINTERNALRESOURCE ON ZINTERNALRESOURCE.ZASSET = ZADDITIONALASSETATTRIBUTES.ZASSET 
```

|ZORIGINALFILENAME | ZDATALENGTH | ZUNIFORMTYPEIDENTIFIER | ZDATASTORESUBTYPE | ZRESOURCETYPE|
|-----|----|-----|----|----|
|IMG_1994.JPG | 16128420 | 1 | 17 | 4|
|IMG_1994.JPG | 2901554 | 2 | 1 | 0|
|IMG_1994.JPG | 126110 | 2 | 0 | 0|

Notice the raw image (longest data length and UTI of 1==`com.canon.cr2-raw-image` in this case, has ZRESOURCETYPE of 4 -- is this associated with "_4" in the cr2 file?

I also need to do "Use RAW as original" in Photos then compare the two databases to see what changes.

**Comment by RhetTbull** [comment]
Comparing delta between using jpeg as original (default) and using RAW as original:

```
csv-diff ZGENERICASSET.csv ~/Desktop/raw2/Photos/ZGENERICASSET.csv --key=Z_PK
1 row changed

  Z_PK: 1
    Z_OPT: "8" => "3"
    ZLOCALRESOURCESSTATE: "0" => "-1"
    ZPACKEDBADGEATTRIBUTES: "2" => "4"
    ZTHUMBNAILINDEX: "1" => "0"
    ZCOMPUTEDATTRIBUTES: "1" => ""
    ZANALYSISSTATEMODIFICATIONDATE: "608661637.309458" => ""
    ZCURATIONSCORE: "0.5" => "0.0"
    ZMODIFICATIONDATE: "608661996.36019" => "608664350"
    ZIMAGEREQUESTHINTS: "b'\x00,_F\t@\x00\x00\x00\x00\x00\xc8\x94E\tH\x00\x00\x00\x00\xaeG\xa9D\tL\x00\x00\x00\x00\xaeG\xa9B\x0c\x03\x0c\xa8q\x92\x00\x00\xc8\x94A\x0c\x03\x0c"\r\x90\x00\x00\x00\x80?\x0c\x03\x00\x82\x0c\x90\x00'"" => "b'\x00,_F\t\x00\x00\x00\x00\x00\x00\xc8\x94E\t\x08\x00\x00\x00\x00\xaeG\xa9D\t\x0c\x00\x00\x00\x00\xaeG\xa9B\x0c\x03\x0c\xa8q\x92\x00\x00\xc8\x94A\x0c\x03\x0c"\r\x90\x00\x00\x00\x80?\x0c\x03\x00\x00\x00\x80\x00'""
```

```
csv-diff ZADDITIONALASSETATTRIBUTES.csv ~/Desktop/raw2/Photos/ZADDITIONALASSETATTRIBUTES.csv --key=Z_PK
1 row changed

  Z_PK: 1
    Z_OPT: "4" => "2"
    ZORIGINALRESOURCECHOICE: "1" => "0"
    ZREVERSELOCATIONDATAISVALID: "1" => "0"
    ZSHIFTEDLOCATIONISVALID: "1" => "0"
```

When "Use RAW as original" selected, `ZORIGINALRESOURCECHOICE = 1`

**Comment by RhetTbull** [comment]
Have got initial support for associated RAW images (for 10.15/Photos 5 only) in the latest version.  Adds `PhotoInfo.has_raw`, `PhotoInfo.uti_raw`, and `PhotoInfo.path_raw`.  

Now I need to work on the CLI interface.  Probably something like --export-raw to export associated raw images.  

If "Use RAW as original" set in Photos, the database still thinks "original_filename" is the JPG so need to handle that too.  In this case, should the default export from `osxphotos export` be the raw image?

**Comment by RhetTbull** [comment]
Latest version on github adds a --export-raw option to `osxphotos export` that should address this issue.  I still need to add test cases and work on the version for Photos <= 4

**Comment by RhetTbull** [comment]
Photos 4 also creates a "fullsizeoutput_a.jpeg" for a raw image imported w/o an associated jpeg.  Add option to export this?
