### ISSUE TITLE
Type error when exporting photos library

### ISSUE THREAD

**Issue by ianmmoir** [RhetTbull/osxphotos#1014]
Installed with pipe and updated to osxphotos, version 0.58.0

Simply exporting the system library using:

osxphotos export /Volumes/MediaDrive/export/

produces  the following crash:

osxphotos crash log
Created: 2023-03-09 11:17:50.776507
osxphotos version: 0.58.0
Platform: macOS-13.2.1-x86_64-i386-64bit
Python version: 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
sys.argv: ['/Users/ian/.local/bin/osxphotos', 'export', '/Volumes/MediaDrive/export/']
CRASH_DATA:
locals: {'ctx': <click.core.Context object at 0x10cb9c940>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x10cb9e410>, 'db': '/Users/ian/Pictures/System.photoslibrary', 'photos_library': (), 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': False, 'alt_copy': False, 'append': False, 'beta': False, 'burst': False, 'cleanup': False, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'directory': None, 'download_missing': False, 'duplicate': False, 'edited': False, 'edited_suffix': '_edited', 'exif': (), 'exiftool': False, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': None, 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': 1.0, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': None, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_edited': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': False, 'only_photos': False, 'original_suffix': '', 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': '_preview', 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': 0, 'save_config': None, 'screenshot': False, 'selected': False, 'selfie': False, 'shared': False, 'sidecar_drop_ext': False, 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': False, 'update': False, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'xattr_template': (), 'year': (), 'verbose': <function noop at 0x114ec7130>, 'verbose_flag': 0, 'locals_': {...}, 'cfg': <osxphotos.configoptions.ConfigOptions object at 0x11542ef80>, 'exclusive_options': [('burst', 'not_burst'), ('cloudasset', 'not_cloudasset'), ('deleted', 'deleted_only'), ('description', 'no_description'), ('edited', 'not_edited'), ('export_as_hardlink', 'convert_to_jpeg'), ('export_as_hardlink', 'download_missing'), ('export_as_hardlink', 'exiftool'), ('export_by_date', 'directory'), ('favorite', 'not_favorite'), ('has_comment', 'no_comment'), ('has_likes', 'no_likes'), ('hdr', 'not_hdr'), ('hidden', 'not_hidden'), ('in_album', 'not_in_album'), ('incloud', 'not_incloud'), ('is_reference', 'not_reference'), ('keyword', 'no_keyword'), ('live', 'not_live'), ('location', 'no_location'), ('missing', 'not_missing'), ('only_photos', 'only_movies'), ('panorama', 'not_panorama'), ('place', 'no_place'), ('portrait', 'not_portrait'), ('screenshot', 'not_screenshot'), ('selfie', 'not_selfie'), ('shared', 'not_shared'), ('skip_edited', 'skip_original_if_edited'), ('slow_mo', 'not_slow_mo'), ('time_lapse', 'not_time_lapse'), ('title', 'no_title')], 'dependent_options': [('append', 'report'), ('exiftool_merge_keywords', ('exiftool', 'sidecar')), ('exiftool_merge_persons', ('exiftool', 'sidecar')), ('exiftool_option', 'exiftool'), ('favorite_rating', ('exiftool', 'sidecar')), ('ignore_signature', ('update', 'force_update')), ('jpeg_quality', 'convert_to_jpeg'), ('keep', 'cleanup'), ('missing', ('download_missing', 'use_photos_export')), ('only_new', ('update', 'force_update')), ('update_errors', 'update')], 'report_writer': <osxphotos.cli.report_writer.ReportWriterNoOp object at 0x11542e110>, 'export_edited': True, 'export_bursts': True, 'export_live': True, 'export_raw': True, 'photos': True, 'movies': True, 'cli_db': None, 'export_db_path': '/Volumes/MediaDrive/export/.osxphotos_export.db', 'other_db_files': [], 'export_db': <osxphotos.export_db.ExportDB object at 0x11542dc90>, 'fileutil': <class 'osxphotos.fileutil.FileUtil'>, 'upgraded': (), 'dest': '/Volumes/MediaDrive/export', 'dry_run': False, 'sidecar': (), 'skip_uuid': (), 'missing_bursts': (True,), 'burst_photos': True}
osxphotos version: 0.58.0
Error: unsupported operand type(s) for +: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/Users/ian/.local/pipx/venvs/osxphotos/lib/python3.10/site-packages/osxphotos/crash_reporter.py", line 36, in wrapped
    return func(*args, **kwargs)
  File "/Users/ian/.local/pipx/venvs/osxphotos/lib/python3.10/site-packages/osxphotos/cli/export.py", line 1351, in export
    photosdb = osxphotos.PhotosDB(
  File "/Users/ian/.local/pipx/venvs/osxphotos/lib/python3.10/site-packages/osxphotos/photosdb/photosdb.py", line 373, in __init__
    self._process_database5()
  File "/Users/ian/.local/pipx/venvs/osxphotos/lib/python3.10/site-packages/osxphotos/photosdb/photosdb.py", line 2017, in _process_database5
    imagedate = datetime.fromtimestamp(row[5] + TIME_DELTA)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by RhetTbull** [comment]
@all-contributors please add @ianmmoir for bug

**Comment by RhetTbull** [comment]
@ianmmoir Try upgrading to version [0.58.1](https://github.com/RhetTbull/osxphotos/releases/tag/v0.58.1) and see if that fixes the error.

Note that your export command will export all photos to a single directory as you've not specified an output directory (`--directory`) or used `--export-by-date`

**Comment by ianmmoir** [comment]
This resolves the issue for me. Thanks for the speedy resolution!
