### ISSUE TITLE
Error: Invalid value for '--query-function': 'bad_photos.py' does not appear to be a file

### ISSUE THREAD

**Issue by furqanshaikh** [RhetTbull/osxphotos#1022]
installed with pipx: `pipx upgrade osxphotos`

command : `osxphotos query --query-function bad_photos.py::bad_photos --add-to-album "Bad Photos"`

Error msg : 
Usage: osxphotos query [OPTIONS] [PHOTOS_LIBRARY]...
Try 'osxphotos query -h' for help.

Error: Invalid value for '--query-function': 'bad_photos.py' does not appear to be a file

when executing this : `pipx upgrade osxphotos`
output `osxphotos is already at latest version 0.58.2 (location: /Users/****/.local/pipx/venvs/osxphotos)`

latest version of macOS is used.

**Comment by RhetTbull** [comment]
You must provide the full path to the query function or execute osxphotos from the same folder as the function exists in. Where did you save `bad_photos.py`? cd to that folder then run osxphotos.

**Comment by furqanshaikh** [comment]
when installed via pipx, and osxphotos are under path, should not we have these functions available there too. Are these examples not part of the package installed ?

**Comment by furqanshaikh** [comment]
@RhetTbull Thanks for the prompt response. It does work when provided the path to the function.
