### ISSUE TITLE
Unable to run osxphotos successfully

### ISSUE THREAD

**Issue by OmarWazzan** [RhetTbull/osxphotos#1023]
**Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

- If you installed with pipx: `pipx upgrade osxphotos`
- If you installed with pip: `pip install --upgrade osxphotos`
- If you installed the pre-built binary, download and install the latest [release](https://github.com/RhetTbull/osxphotos/releases)

OSXPhotos is upgraded to the latest version.

**Describe the bug**

When running a command, whether or not I specify the library path using --library or --db, or letting it default, the command fails and errors out, but have tried various differences in the commands, but can never get it to work.

**To Reproduce**
1. What' the full command line you used with osxphotos?
2. What was the error output?

1: command is

```
osxphotos export ~/Desktop/osxphotos \
--library "/Users/omar/Pictures/Photos Library.photoslibrary" \
--export-by-date \
--download-missing \
--use-photokit \
--exportdb \
--retry 3 \filename “{original_name}” \
--exiftool \
--person-keyword \
--sidecar xmp \
--touch-file
```

2: Error is:

```
WARNING: photos_library is deprecated. The PHOTOS_LIBRARY argument is deprecated and will be removed in a future version of osxphotos. Use --library instead to specify the Photos Library path.
WARNING: photos_library is deprecated. The PHOTOS_LIBRARY argument is deprecated and will be removed in a future version of osxphotos. Use --library instead to specify the Photos Library path.
Usage: osxphotos export [OPTIONS] [PHOTOS_LIBRARY]... DEST
Try 'osxphotos export -h' for help.

Error: Invalid value for '[PHOTOS_LIBRARY]...': Path '3' does not exist.
```

**Expected behavior**

A successful run of osxphotos

**Desktop (please complete the following information):**
 - OS: 11.7.4
 - osxphotos version 0.58.2

Thanks, appreciated!

**Comment by RhetTbull** [comment]
You're missing the -- before filename so osxphotos thinks `filename` is the photos library

**Comment by OmarWazzan** [comment]
> You're missing the -- before filename so osxphotos thinks `filename` is the photos library

Ah, nice catch. However, tried again and is still errors out

**Comment by OmarWazzan** [comment]
Nevermind - worked after adding a path to --exportdb

Thank you!
