### ISSUE TITLE
Add option to use hardlinks for export

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#103]
1. Add arg to PhotoInfo.export to hardlink files instead of copying them
2. Add "--export-as-hardlink" option to CLI
3. Add "--hardlink-duplicates" option to CLI.  This would copy the first copy of an image exported and created hardlinks to that copied file for all subsequent exports.  This would be useful with multi-valued export templates e.g. "{album}" so multiple copies of a file aren't actually exported

**Comment by britiscurious** [comment]
Just was about to raise a wish. Thanks to Githubs "similar issues" I found you are already on it.
Great tool! Just found it.

**Comment by RhetTbull** [comment]
Thanks @britiscurious for the PR implementing --export-as-hardlink!  I'm going to leave this issue open for now because I'd also like to eventually add the --hardlink-duplicates option which exports the first copy but hardlinks any others (e.g. if user used a --directory template that put the photo in multiple directories).  That will be more complex though because it will require keeping track of every exported file and checking to see if it's been exported yet or not.

**Comment by RhetTbull** [comment]
Now that export uses clonefile on APFS and all modern Macs moving to APFS I don't think implementing --hardlink-duplicates is worth the effort as most of the benefits are accomplished through clonefile.  Use cases where users are exporting duplicate files are also likely rare.
