### ISSUE TITLE
Crash out part way thru Export:  Error binding parameter 14: type 'Error' is not supported

### ISSUE THREAD

**Issue by rajscode** [RhetTbull/osxphotos#1046]
Been running the osxphotos approx every month and didn't encounter this error until two days ago after upgrading to latest version (previously I'd upgraded around 1 month ago). 

Command used:
osxphotos export photo_library_backup/ --load-config osxphotos_backup.toml 

Export fails 1/4 the way through.  Error that happens after running for a good period of time is shown in picture below. Have run the exact same command a few times now and same issue occurs:
![osxphotos_crash_parameter_14_type_error_not_supported](https://user-images.githubusercontent.com/99123253/230900864-3b848d7c-6db4-44ef-a1a2-f15efdc06865.jpg)

Last 12 lines from the crash log:
[osxphotos_crash_last_12_lines.log](https://github.com/RhetTbull/osxphotos/files/11190435/osxphotos_crash_last_12_lines.log)

the TOML configuration file I use (added .txt to enable upload to GH):
[osxphotos_backup.toml.txt](https://github.com/RhetTbull/osxphotos/files/11190440/osxphotos_backup.toml.txt)

osxphotos, version 0.59.2
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
macOS 13.3.1, arm64
running on a MacBook Pro 14 2021 M1 silicon

NOTE:  Am running command again and will update if it crashes out on a different photo or the same one again.

**Comment by rajscode** [comment]
Ran it again and it crashed out again at 27% of way through, but this time on a different photo file and the error messages were different. 

[Errno 24] Too many open files: '/Volumes/WDSSD2B/Macbook_Pro_14_PhotosLibrary_Full_Originals_Backup/Photos Library.photoslibrary/resources/derivatives/0'

Something went wrong and osxphotos encountered an error:
Error binding parameter 14: type 'OSError' is not supported

![2nd_Run_osxphotos_crash_parameter_14_type_error_not_supported](https://user-images.githubusercontent.com/99123253/230918847-216260ed-3f99-4376-a330-4e4505ec59a3.jpg)


Attached last 11 lines from the crash log file as the full crash log file is 1.12 GB in size. I'd deleted the crash log file prior to running the osxphotos command again so the 1.12 GB is from this one run.  
[2nd_Run_osxphotos_crash_last_11_lines.log](https://github.com/RhetTbull/osxphotos/files/11191005/2nd_Run_osxphotos_crash_last_11_lines.log)

**Comment by rajscode** [comment]
I downgraded to 0.58.2 version and am currently rerunning the command again.   

- It's already passed 30% and hasn't failed (I fully expect it to complete successfully this time)
- The estimated time remaining and how long it's been running seem to suggest for my library at least that 0.58.2 is significantly faster vs 0.59.2 release. 

My photos library is ~ 1.6TB on disk. 

![3rd_Run_osxphotos_after_downgrade_to_0 58 2_version](https://user-images.githubusercontent.com/99123253/230932581-1ea4e7cf-c6f3-42ac-96b2-17da9d2e64d3.jpg)

**Comment by RhetTbull** [comment]
@all-contributors please add @rajscode for bug

**Comment by RhetTbull** [comment]
@rajscode I think this is fixed in [v0.59.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.59.3).  Please give that a try and let me know if you still see the error.

**Comment by rajscode** [comment]
> @rajscode I think this is fixed in [v0.59.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.59.3). Please give that a try and let me know if you still see the error.

0.59.3 bugfix release looks to be working well (Thanks!)

Some observations: 

0.59.3 (vs 0.58.2) seems to be faster:  ~ 1hr35m vs 2hr16m
going through a photos library of approx 155K items using ~ 1.6TB on disk
<img width="1051" alt="4th_Run_osxphotos_after_bugfix_to_0 59 3_version_completed" src="https://user-images.githubusercontent.com/99123253/231156230-a446438f-9d72-4508-97c5-b328ea2e53e7.png">

In regards to memory utilization - I logged 0.59.3 memory use from start to end. 
[4th_Run_0.59.3_bugfix_version_memory_usage_observations.log](https://github.com/RhetTbull/osxphotos/files/11200173/4th_Run_0.59.3_bugfix_version_memory_usage_observations.log)

Thanks again.

**Comment by oPromessa** [comment]
My results were also positive. 3:23:23 for ~90K pics exporting via 1GB LAN to NAS Server.

https://github.com/RhetTbull/osxphotos/issues/999#issuecomment-1503766386
