### ISSUE TITLE
Out of Control Memory Management?

### ISSUE THREAD

**Issue by wernerzj** [RhetTbull/osxphotos#1047]
**Describe the bug**
While attempting to digest a ~450GB Photos database, it gets to around 20-35% before it hangs and subsequently fails. At this time, the Python interpreter is sitting around 95GB of memory

**To Reproduce**
1. Command: osxphotos --library /Volumes/METAETHER/Master_Merged.photoslibrary export /Volumes/METAETHER/Exported_Master_Merged --person-keyword --album-keyword --keyword-template --update --exiftool --directory "{created.year}/{created.month}/{folder_album,Unnamed Event}"
2. No error output, please refer to attached screenshot.

**Expected behavior**
I expect for the script to run 'till completion. This appears to be either memory leak, or it is literally loading every single image into memory and not clearing the memory of the already processed images. Given the size of the memory/virtual memory, I believe the aforementioned to be the case. If I can't get this working, I'll have to resort to using elodie (which I would prefer not to use, but as a backup plan is running effortlessly (900GB of photos; on a docker container on my NAS with only 2GB of memory) for a failed PowerPhotos merge (didn't generate a database file, hence Apple Photos cannot repair it.) I have tried running it several times. First time it made it to around 25% before it failed, then second time it made it to 34% before it failed. I had to clear up ~100GB on my internal drive to make room for more virtual memory. This doesn't seem to be the expected behavior. I know there is a RAMdisk option, but I'm not using that feature.

**Screenshots**
<img width="1440" alt="Screenshot 2023-04-10 at 3 58 32 AM" src="https://user-images.githubusercontent.com/130370930/230906124-b2d8f4cc-90ba-41b4-b8ef-3a62f6af247b.png">

**Desktop (please complete the following information):**
 - OS: Ventura 13.3
 - osxphotos version (`osxphotos --version`) ? That command doesn't seem to work. It generates a trace callback.

**Additional context**
Since PowerPhotos was unable to handle the full merge, I was excited to come across osxphotos, ideally to move away from Photos permanently, or temporarily move away so I can easily separate them into different libraries by year (we're talking ~18 years worth of photos). Barring I can't get osxphotos working, I would only be able to fall back on using elodie to process the 'failed merge' from PowerPhotos; although off-topic (for clarification sake): it completed successfully, but Photos app wasn't able tor repair the library (as far as size is concerned, appeared to have worked, hence some possible utility with running elodie, but would prefer using osxphotos -- if possible since it seems more capable).

Thanks for any feedback/help and/or taking this bug report.

**Comment by RhetTbull** [comment]
> osxphotos version (osxphotos --version) ? That command doesn't seem to work. It generates a trace callback.

Something is definitely wrong with your osxphotos installation then as both `osxphotos version` and `osxphotos --version` should work (they generate slightly different output).  How did you install osxphotos?  If via `pipx` (which is what the install instructions recommend) try this: 

- `pipx uninstall osxphotos`
- `pipx install osxphotos`

Then try running the version command again.

**Comment by RhetTbull** [comment]
I was able to replicate this on a large library -- osxphotos definitely appears to have a memory leak in the latest version.  I'll investigate. In the mean time, try downgrading:

`pipx uninstall osxphotos`
`pipx install osxphotos==0.58.2`

**Comment by RhetTbull** [comment]
@all-contributors please add @wernerzj  for bug

**Comment by RhetTbull** [comment]
I believe this should be fixed in [v0.59.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.59.3)

**Comment by RhetTbull** [comment]
I've done a full export of my 36k image, 125GB library and while memory does slowly grow during the export, it completed in ~3 hours using 2GB of memory.  I'll continue to investigate memory growth but I believe the run-away memory issue is resolved.

**Comment by wernerzj** [comment]
Thanks so much for all of your efforts with this, I truly appreciate it!
