### ISSUE TITLE
Is it possible to Export the `preview` ONLY, and not export the photo itself?

### ISSUE THREAD

**Issue by ces3001** [RhetTbull/osxphotos#1079]
I’m building a travel log and only need the preview quality image. Since I don’t want to wait for all images to download if they are missing, is there a way to only export the preview image, and nothing else (other than XMP files)?
Thanks for a great tool!

**Comment by RhetTbull** [comment]
It's not currently possible to export only the preview (from the command line) but there is a `--preview-if-missing` option which exports the preview if the original is missing.

Do you know any python? It would be possible to write a short script using the osxphotos API to export just the preview images. 

Something like this pseudo code:

```python
import shutil 
import osxphotos

for photo in osxphotos.PhotosDB().photos():
    shutil.copy(photo.path_derivatives[0], destination)
```

**Comment by RhetTbull** [comment]
@ces3001 I created a small script using code from osxphotos' export command to export just the previews. You can use the full query options available to `osxphotos query` as well as the `--directory` and `--filename` template options to specify the output path.  The script is in the examples folder [here](https://raw.githubusercontent.com/RhetTbull/osxphotos/main/examples/export_previews.py). 

If you save this script to a plain text file named `export_previews.py`, you can run it with the command:

`osxphotos run export_previews.py DEST_PATH --directory "{created.year}/{created.mm}/{created/dd}"` 

for example to export to folders based on creation date:

```
osxphotos run examples/export_previews.py $TESTDIR --directory "{created.year}/{created.mm}/{created.dd} --selected"
Exporting preview for IMG_4547.jpg (3DD2C897-F19E-4CA6-8C22-B027D5A71907) to /Volumes/OWC_SSD/rhet/test/2017/06/20/IMG_4547.jpeg
Exporting preview for St James Park.jpg (DC99FBDD-7A52-4100-A5BB-344131646C30) to /Volumes/OWC_SSD/rhet/test/2018/10/13/St James Park.jpeg
Exporting preview for Tulips.jpg (6191423D-8DB8-4D4C-92BE-9BBBA308AAC4) to /Volumes/OWC_SSD/rhet/test/2019/07/04/Tulips.jpeg
Exporting preview for IMG_1994.JPG (A92D9C26-3A50-4197-9388-CB5F7DB9FA91) to /Volumes/OWC_SSD/rhet/test/2020/04/15/IMG_1994.jpeg
Exporting preview for IMG_1997.JPG (4D521201-92AC-43E5-8F7C-59BC41C37A96) to /Volumes/OWC_SSD/rhet/test/2020/04/16/IMG_1997.jpeg
Exporting preview for IMG_2000.JPG (8E1D7BC9-9321-44F9-8CFB-4083F6B9232A) to /Volumes/OWC_SSD/rhet/test/2020/04/16/IMG_2000.jpeg
Exporting preview for Pumkins2.jpg (D79B8D77-BFFC-460B-9312-034F2877D35B) to /Volumes/OWC_SSD/rhet/test/2018/09/28/Pumkins2.jpeg
Exporting preview for IMG_3092.heic (7783E8E6-9CAC-40F3-BE22-81FB7051C266) to /Volumes/OWC_SSD/rhet/test/2020/09/19/IMG_3092.jpeg
Exporting preview for Pumpkins4.jpg (A1DD1F98-2ECD-431F-9AC9-5AFEFE2D3A5C) to /Volumes/OWC_SSD/rhet/test/2018/09/28/Pumpkins4.jpeg
Exporting preview for Pumpkins3.jpg (1EB2B765-0765-43BA-A90C-0D0580E6172C) to /Volumes/OWC_SSD/rhet/test/2018/09/28/Pumpkins3.jpeg
Exporting preview for IMG_1693.tif (8846E3E6-8AC8-4857-8448-E3D025784410) to /Volumes/OWC_SSD/rhet/test/1970/01/01/IMG_1693.jpeg
Exporting preview for wedding.jpg (E9BC5C36-7CD1-40A1-A72B-8B8FAC227D51) to /Volumes/OWC_SSD/rhet/test/2019/04/15/wedding.jpeg
Exporting preview for Pumkins1.jpg (F12384F6-CD17-4151-ACBA-AE0E3688539E) to /Volumes/OWC_SSD/rhet/test/2018/09/28/Pumkins1.jpeg
Exporting preview for DSC03584.dng (D05A5FE3-15FB-49A1-A15D-AB3DA6F8B068) to /Volumes/OWC_SSD/rhet/test/2020/04/12/DSC03584.jpeg
Exported 14 preview images
```

There's a `--verbose` option to print verbose output and `--dry-run` option to preview but not actually export.

**Comment by RhetTbull** [comment]
Full code of the example here in case anyone stumbles upon this in the future. This shows how easy it is to create custom utilities using osxphotos.

```python
""" Export previews for photos in the Photos library

To run this with osxphotos on currently selected photos:

    osxphotos run export_previews.py --selected export_path
"""

from __future__ import annotations

import pathlib
import shutil

import click

import osxphotos
from osxphotos.cli import echo, echo_error, query_command, verbose
from osxphotos.cli.export import get_dirnames_from_template, get_filenames_from_template
from osxphotos.cli.param_types import TemplateString
from osxphotos.utils import pluralize


@query_command
@click.option("--dry-run", is_flag=True, help="Dry run, don't actually export")
@click.option(
    "--directory",
    type=TemplateString(),
    help="Directory to export to under export_path. This is an osxphotos template string. "
    "For example, to export previews to directories based on creation date: "
    "--directory '{created.year}/{created.mm}/{created.dd}' ",
)
@click.option(
    "--filename",
    "filename_template",
    type=TemplateString(),
    help="Filename for exported preview. "
    "This is an osxphotos template string; "
    "for example, to export previews to filename based on creation date: "
    "--filename '{original_name}-{created.year}-{created.mm}-{created.dd}' ",
)
@click.argument(
    "export_dir", type=click.Path(exists=True, file_okay=False, dir_okay=True)
)
def export_previews(
    photos: list[osxphotos.PhotoInfo],
    dry_run: bool,
    directory: str,
    filename_template: str,
    export_dir: str,
    **kwargs,
):
    """Export previews for photos in the Photos library.

    Pass one or more query options to select photos to export or use without query options
    to export all images.

    If --directory is passed, the previews will be exported to subdirectories under export_path
    based on the template string passed to --directory. For example, to export previews to
    directories based on creation date: --directory '{created.year}/{created.mm}/{created.dd}'

    If --filename is passed, the previews will be exported with the filename specified by the
    template string passed to --filename. For example, to export previews to filename based on
    creation date: --filename '{original_name}-{created.year}-{created.mm}-{created.dd}'

    If --dry-run is passed, the previews will not actually be exported but the export will be
    simulated and the export paths printed to stdout.
    """

    verbose(f"Found {len(photos)} photo(s)")
    count = 0
    for photo in photos:
        try:
            # first derivative is the largest preview, so use that one
            preview = pathlib.Path(photo.path_derivatives[0])
        except IndexError:
            echo(f"No preview for {photo.original_filename} ({photo.uuid})")
            continue

        verbose(f"Found preview for {photo.original_filename}: {preview}")
        count += export_preview_to_directory_with_filename(
            photo, preview, export_dir, directory, filename_template, dry_run
        )
    echo(f"Exported {count} preview {pluralize(count, 'image', 'images')}")


def export_preview_to_directory_with_filename(
    photo: osxphotos.PhotoInfo,
    preview_path: str,
    export_dir: str,
    directory: str,
    filename_template: str,
    dry_run: bool,
) -> int:
    """Export preview for photo to directory with filename; returns count of images exported"""
    count = 0
    for dirname in get_dirnames_from_template(
        photo=photo,
        directory=directory,
        export_by_date=False,
        dest=export_dir,
        dry_run=dry_run,
    ):
        for filename in get_filenames_from_template(
            photo=photo,
            filename_template=filename_template,
            export_dir=export_dir,
            dest_path=dirname,
            original_name=True,
        ):
            # need to change filename extension to match preview
            filename = pathlib.Path(filename).with_suffix(preview_path.suffix)
            dest_path = pathlib.Path(dirname) / filename
            echo(
                f"Exporting preview for {photo.original_filename} ({photo.uuid}) to {dest_path}"
            )
            if not dry_run:
                try:
                    shutil.copy(preview_path, dest_path)
                except Exception as e:
                    echo_error(f"Error exporting preview: {e}")
                    continue
            count += 1
    return count


if __name__ == "__main__":
    export_previews()
```

**Comment by ces3001** [comment]
Amazing! Thank you! Will try this next export cycle.
For now, I just did this work-around: 
`osxphotos export Photos --export-by-date --skip-original-if-edited --skip-live --skip-bursts --skip-raw --not-hidden --exiftool --keyword-template "{label?label:{label},}" --keyword-template 'uuid:{uuid}' --update --report export.csv --convert-to-jpeg --jpeg-quality 0 --jpeg-ext jpg --preview --preview-suffix .preview --touch-file --cleanup`
followed by
`find Photos -type f ! -name "*.preview*" -delete`

**Comment by ces3001** [comment]
> > Also asking because for some photos, the --convert-to-jpeg --jpeg-quality 0 doesn’t actually work (the exported image is the same size as original).
> 
> Is the original a JPEG or some other format? If already a JPEG, it won't be converted.

Indeed the original is a jpeg.

**Comment by RhetTbull** [comment]
The script will work with most of those options but not `--exiftool` and associated options like `--keyword-template`  It just exports the previews but does no other post processing. If your current work around is fine then I suggest you stick with that.

**Comment by ces3001** [comment]
> The script will work with most of those options but not `--exiftool` and associated options like `--keyword-template` It just exports the previews but does no other post processing. If your current work around is fine then I suggest you stick with that.

Actually none of the options work for me except `--no-hidden`. The only ones that really matters to me are `--update` in case any edits are made or metadata changes, and `--cleanup` to get rid of any deleted photos from a previous export.

**Comment by RhetTbull** [comment]
> Actually none of the options work for me except --not-hidden

Yeah, you're right. Only the query options (which select or de-select photos) will work as the others are part of the export command but not the query command which this script is based on.

`--udpate` and `--cleanup` won't work either -- this wasn't a replacement for export, just an attempt to answer the original question "how do I export only the previews".  You'll need to stick with your current export command for your use case.

**Comment by ces3001** [comment]
> > Actually none of the options work for me except --not-hidden
> 
> Yeah, you're right. Only the query options (which select or de-select photos) will work as the others are part of the export command but not the query command which this script is based on.
> 
> `--udpate` and `--cleanup` won't work either -- this wasn't a replacement for export, just an attempt to answer the original question "how do I export only the previews". You'll need to stick with your current export command for your use case.

Thank you again. Really appreciate the efforts. It’s so much faster to export with your script. Maybe the work-around now, using your script, is to delete the export folder and do it from scratch each time... still faster than the regular export that exports the actual photos in addition to the previews.

**Comment by ces3001** [comment]
Will close for now, as the original suggestion has been implemented.

**Comment by ces3001** [comment]
Will close for now, as the original suggestion has been implemented.
