### ISSUE TITLE
--db/--library ignored by import

### ISSUE THREAD

**Issue by msolo** [RhetTbull/osxphotos#1105]
`import` always imports to the most-recently-opened Photos library. 

Specifying --library or --db does nothing to switch the active Photos library (based on my reading of the code).

**To Reproduce**

1. create two photoslibrary bundles - A.photoslibrary and B.photoslibrary.
2. Open Photos with B.photoslibrary.
3. `osxphotos --library A.photoslibrary import --album DemoImport --walk ./DemoImport`
4. Observe that photos are added incorrectly to B.photoslibrary.

**Expected behavior**
All osxphotos modes should respect `--library` or rapidly error out if it can't be done.

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS] Big Sur
 - osxphotos version (`osxphotos --version`) 0.60.5

**Additional context**
There is no code in import_cli() that switches the library. The PhotosLibrary().open() opens a dialog that blocks the process, so this can no longer be run interactively. Rather than patch osxphotos, I handle it externally with this snippet:
```
pkill Photos
open Correct.photoslibrary
while ! pgrep Photos; do sleep 0.5; done
osxphotos import ...
```

**Comment by RhetTbull** [comment]
Definitely a bug. I was surprised that `import` event accepted `--db/--library` as these are not options in the actual code to the import command. Import must work on the last opened library as it interacts directly with Photos.app to do the import.   However, `--db/--library` are global options that are passed to all osxphotos subcommands.  In this case, import just ignores them. 

I will need to rework the global options to ensure they're not passed to subcommands that can't handle them. 

In the mean time, a work around is to simply open the correct library in Photos before using import.

**Comment by RhetTbull** [comment]
@all-contributors please add @msolo for bug

**Comment by RhetTbull** [comment]
The offending code is here where `@DB_OPTION` is passed to the main CLI. There are several subcommands for which this doesn't make sense. All subcommands should explicitly use `@DB_OPTION` if needed instead of passing this as a global option. 

https://github.com/RhetTbull/osxphotos/blob/889c87813888dc5f8e51fe0692dbbd112affa1c4/osxphotos/cli/cli.py#L63-L86

**Comment by RhetTbull** [comment]
I updated the documentation for `osxphotos import` and removed `--library/--db` from import and the other commands that don't support it. See [v0.60.6](https://github.com/RhetTbull/osxphotos/releases/tag/v0.60.6)
