### ISSUE TITLE
Originals in `scopes/momentshared` folders

### ISSUE THREAD

**Issue by neilpa** [RhetTbull/osxphotos#1116]
I'm running into a "shared" photo issue that I can hopefully help debug. This may be the same as #883, but starting a new issue just in case. What I think happened in my case

* Took the photos on my phone
* Shared a large enough batch via messages that an icloud link was automatically created
* Synced to Photos on my laptop some point after sharing

Here's the verbose output of the export for a single example

```
osxphotos export --verbose --skip-live --only-photos --uuid 64744EA8-8F95-4055-88B9-887640CC2488 test
osxphotos version: 0.60.7
Python version: 3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]
Platform: macOS-12.6.5-arm64-arm-64bit, 12.6.5
Verbose level: 1
Using last opened Photos library: /Users/neilpa/pics/macos.photoslibrary
Using export database /Users/neilpa/pics/test/.osxphotos_export.db
Processing database /Users/neilpa/pics/macos.photoslibrary/database/photos.db
Processing database /Users/neilpa/pics/macos.photoslibrary/database/Photos.sqlite
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Exporting 1 photo to /Users/neilpa/pics/test...
Exporting IMG_2360.HEIC (64744EA8-8F95-4055-88B9-887640CC2488.heic) (1/1)
Skipping missing original photo IMG_2360.HEIC (64744EA8-8F95-4055-88B9-887640CC2488)
Exporting 1 photos ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processed: 1 photo, exported: 0, missing: 1, error: 0
```

The original does exist on disk, but it ended up in `scopes/momentshared`

```
find macos.photoslibrary -name '*64744EA8-8F95-4055-88B9-887640CC2488*'                        
macos.photoslibrary/scopes/momentshared/resources/derivatives/6/64744EA8-8F95-4055-88B9-887640CC2488_1_105_c.jpeg
macos.photoslibrary/scopes/momentshared/resources/derivatives/masters/6/64744EA8-8F95-4055-88B9-887640CC2488_4_5005_c.jpeg
macos.photoslibrary/scopes/momentshared/originals/6/64744EA8-8F95-4055-88B9-887640CC2488.heic
macos.photoslibrary/scopes/momentshared/originals/6/64744EA8-8F95-4055-88B9-887640CC2488_3.mov
```

I emailed you the full `debug-dump` in case that's helpful too.

**Comment by RhetTbull** [comment]
osxphotos doesn't look in momentshared folder at the moment and I don't know what triggers the photos to be moved there.  Can you try the following and send the output which is better than `debug-dump`?  (I need to  update debug dump to also dump the raw data).  This will dump the raw data from the database.

`osxphotos repl`

At the REPL prompt (`>>>`):

```python
photo = get_photo("64744EA8-8F95-4055-88B9-887640CC2488")
photo.tables().ZASSET.rows_dict()
photo.tables().ZADDITIONALASSETATTRIBUTES.rows_dict()
```

**Comment by RhetTbull** [comment]
I've replicated this but have not figured out how to decode which photos these apply to yet. In my own library, some photos I've shared via Messages are moved to `scopes/momentshared` and thus osxphotos cannot access the original files.

**Comment by RhetTbull** [comment]
A clue:

These photos have `ZASSET.ZMOMENTSHARE` set to an integer which appears to be the foreign key into `ZSHARE` which includes the iCloud sharing link (`ZHAREURL`) for these photos.

**Comment by RhetTbull** [comment]
In my entire library I only have one record in `ZSHARE` and it's all photos I've recently shared via Messages (and interestingly not shared all at once, but they were all shared with the same person).  Is this a recent feature?

**Comment by RhetTbull** [comment]
I've confirmed I can now identify these photos. Will take some work to update all the path methods to look in the right folder.  Changes will be similar to what I did for syndicated photos in [v0.60.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.60.3). I'm currently working on getting alpha support out for Sonoma. Once I release that I'll work on implementing a fix for this issue.

**Comment by RhetTbull** [comment]
Also, `ZSHAREPARTICIPANT` includes info on who the photos were shared with (joined with `ZSHARE` via `ZSHAREPARTICIPANT.ZSHARE == ZSHARE.Z_PK`.   The `ZNAMECOMPONENTS` column is a binary plist include the name and other contact info for the shared participant. osxphotos should expose all this as well.

Perhaps:

`PhotoInfo.shared_moment` == new `SharedMoment` object | None

`SharedMoment` class:
`.url` = share url
`.photos` = list[PhotoInfo] of all photos in the shared moment
`participants` = new `SharedParticipant` object

`SharedParticipant` class:
`.name`
`.email`
etc.

**Comment by RhetTbull** [comment]
Slight wrinkle. Sometimes the shared moment photo is in `scopes/momentshare` and sometimes it's in `originals/`.  Thanks Apple!

**Comment by RhetTbull** [comment]
@all-contributors please add @neilpa for bug

**Comment by RhetTbull** [comment]
@neilpa I'm ~80% certain this is fixed in [v0.60.9](https://github.com/RhetTbull/osxphotos/releases/tag/v0.60.9).  I have a very small subset of data with which to test (I only had 15 photos in my library in the `momentshared` folder) and I had to take an educated guess on the heuristic to determine which folder an image should be in.  Please give the new version a try and let me know if you have any more issues with these photos.

I've also added `--shared-moment` and `--not-shared-moment` query options that can be used with `export` or `query` commands.

I'll leave this open for now as I plan to eventually add a `SharedMoment` class to get additional details about the shared moment (participants, photos, start date, end date, expiration date, url, etc.)

**Comment by neilpa** [comment]
> In my entire library I only have one record in `ZSHARE` and it's all photos I've recently shared via Messages (and interestingly not shared all at once, but they were all shared with the same person).

I have 6 records in my `ZSHARE` table. I'm pretty sure my wife is the only person I've shared photos with that would have these auto-generated icloud folders (and her with me). I'll try and dig a bit more at my data tomorrow.

> Sometimes the shared moment photo is in `scopes/momentshare` and sometimes it's in `originals/`. Thanks Apple!

I wonder if this happens depending on when the photos are synced vs when they are shared. E.g. if you share from iOS before they're synced to the Photos app they end up in `scopes/momentshare` but if they're synced normally to `originals/` and then you share them later, they're not moved.

**Comment by neilpa** [comment]
> @neilpa I'm ~80% certain this is fixed in [v0.60.9](https://github.com/RhetTbull/osxphotos/releases/tag/v0.60.9). I have a very small subset of data with which to test (I only had 15 photos in my library in the `momentshared` folder) and I had to take an educated guess on the heuristic to determine which folder an image should be in. Please give the new version a try and let me know if you have any more issues with these photos.

I did some basic testing (only using `--added-in-last "1 week"`)  and reduced the missing photos from 33 down to 3. Everything that's in `scopes/momentshared` folder seemed to be found. I also have a lot more examples if you need some more testing.

```
> find macos.photoslibrary/scopes/momentshared/originals -type f | wc -l
     594
```

The remaining missing photos are in the `scopes/syndication` folder, which appears you recently added support for. I checked them each, 2 don't have originals downloaded, but the third does and still didn't export.

```
> find macos.photoslibrary -name '*DB9CED59-08C5-45A5-939F-645E23B4C0E0*'
macos.photoslibrary/scopes/syndication/resources/derivatives/masters/D/DB9CED59-08C5-45A5-939F-645E23B4C0E0_4_5005_c.jpeg
> find macos.photoslibrary -name '*EDD48384-59D0-4DB7-AFC5-3482D5B9084E*'
macos.photoslibrary/scopes/syndication/resources/derivatives/masters/E/EDD48384-59D0-4DB7-AFC5-3482D5B9084E_4_5005_c.jpeg
> find macos.photoslibrary -name '*93F52D97-8ACD-4AE4-8640-3A7B28963C1E*'
macos.photoslibrary/scopes/syndication/resources/derivatives/9/93F52D97-8ACD-4AE4-8640-3A7B28963C1E_1_102_o.jpeg
macos.photoslibrary/scopes/syndication/resources/derivatives/masters/9/93F52D97-8ACD-4AE4-8640-3A7B28963C1E_4_5005_c.jpeg
macos.photoslibrary/scopes/syndication/originals/9/93F52D97-8ACD-4AE4-8640-3A7B28963C1E.heic
macos.photoslibrary/scopes/syndication/originals/9/93F52D97-8ACD-4AE4-8640-3A7B28963C1E_3.mov
```

Let me know if there's more details you want me to share (or if you want to track that as a different issue). I also have a ton of these in my library...

```
> find macos.photoslibrary/scopes/syndication/originals -type f | wc -l
     803
```

**Comment by RhetTbull** [comment]
Send me a `debug-dump` for the syndicated photo that has originals but didn't export. It's possible I broke something with the latest release but also possible there's something about this one that is causing osxphotos to misclassify it. I don't have tests for the syndicated and shared moments as the tests would have to be too dependent on the state of my local library.

**Comment by RhetTbull** [comment]
>I wonder if this happens depending on when the photos are synced vs when they are shared. E.g. if you share from iOS before they're synced to the Photos app they end up in scopes/momentshare but if they're synced normally to originals/ and then you share them later, they're not moved.

That's a good hypothesis. The only photos I have in meomentshare are those that I took on a recent overseas trip where I had turned off cellular data for Photos (so they photos would not have been synced to iCloud when I shared them).

**Comment by RhetTbull** [comment]
I can't figure out why the one syndicated file is not exporting (93F52D97-8ACD-4AE4-8640-3A7B28963C1E).  Try this in the REPL:

`osxphotos repl`

```python
photo = get_photo("93F52D97-8ACD-4AE4-8640-3A7B28963C1E")
photo.syndicated
photo.saved_to_library
photo.path
photo.path_derivatives
```

**Comment by RhetTbull** [comment]
Please also do the following `debug-dump` command and send me the output:

`osxphotos  debug-dump --dump _db_syndication_uuid`

**Comment by neilpa** [comment]
Something definitely doesn't seem right

```
>>> photo = get_photo("93F52D97-8ACD-4AE4-8640-3A7B28963C1E")
>>> print(photo.syndicated)
None
>>> print(photo.saved_to_library)
None
>>> print(photo.path)
None
>>> print(photo.path_derivatives)
[]
```

And no syndication id

```
> osxphotos  debug-dump --dump _db_syndication_uuid
Using last opened Photos library: /Users/neilpa/pics/macos.photoslibrary
Opening database: /Users/neilpa/pics/macos.photoslibrary
Done; took 5.51 seconds
_db_syndication_uuid:
{}
```

**Comment by neilpa** [comment]
I think I found the culprit

https://github.com/RhetTbull/osxphotos/blob/45468dd1a9b8a549b070998d08c2d8db58bc4c32/osxphotos/photosdb/_photosdb_process_syndicationinfo.py#L14-L24

```
% osxphotos  debug-dump --dump photos_version                            
Using last opened Photos library: /Users/neilpa/pics/macos.photoslibrary
Opening database: /Users/neilpa/pics/macos.photoslibrary
Done; took 5.31 seconds
photos_version:
7
```

**Comment by RhetTbull** [comment]
Aha!  I never used Monterey and thought syndicated photos were a Ventura feature. This should be an easy fix then.  I'll change this to Photos 7 & test to verify it doesn't break anything. There may be some other guards for version 8 that need to fixed as well.

**Comment by neilpa** [comment]
Thanks! I'll give a go once you push the update and let you know.

**Comment by RhetTbull** [comment]
@neilpa give version v0.60.10 a try -- I think this will fix syndicated photos on Monterey (though I've not been able to test as I don't have a Monterey library with syndicated photos)

**Comment by neilpa** [comment]
The newest version looks to have fixed the problem. I've got ~500 fewer "missing" photos on a full export of my library. I spot checked the example photo from this thread and it's now exported correctly.

AFAICT, the remaining missing photos are syndicated/shared where the originals are actually not yet downloaded. E.g. I cross-checked all the UUIDs in `originals`, `scopes/momentshared/originals`, and `scopes/syndication/originals` vs the missing ones reported in the export and there were no matches.

Thanks!!
