### ISSUE TITLE
Database error when running osxphotos

### ISSUE THREAD

**Issue by climpyaardvark** [RhetTbull/osxphotos#1144]
Confirmed on latest version - 0.61.0

**Describe the bug**

I am getting an 'Error Exporting photo' message for each image that matches my search criteria. This is reproducible despite restarting my computer and proactively repairing my iPhoto library. 

**To Reproduce**

Command:

osxphotos export ~/Library/Mobile\ Documents/com~apple~CloudDocs/Videos --exiftool --only-movies   --from-date "2011-12-25" --to-date "2012-12-31"

Error output:

osxphotos crash log
Created: 2023-08-05 09:26:35.287897
osxphotos version: 0.61.0
Platform: macOS-13.4.1-x86_64-i386-64bit
Python version: 3.11.4 (main, Jul 25 2023, 17:07:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
sys.argv: ['/Users/<redacted>/.local/bin/osxphotos', 'export', '/Users/<redacted>/Library/Mobile Documents/com~apple~CloudDocs/Videos', '--only-movies', '--from-date', '2012-12-25', '--to-date', '2012-12-31']
CRASH_DATA:
locals: {'ctx': <click.core.Context object at 0x1164b75d0>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x11083a8d0>, 'db': None, 'photos_library': (), 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': False, 'alt_copy': False, 'append': False, 'beta': False, 'burst': False, 'cleanup': False, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'dest': '/Users/<redacted>/Library/Mobile Documents/com~apple~CloudDocs/Videos', 'directory': None, 'download_missing': False, 'dry_run': False, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': False, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': None, 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': datetime.datetime(2012, 12, 25, 0, 0), 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': None, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_edited': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': True, 'only_new': False, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': None, 'save_config': None, 'screenshot': False, 'selfie': False, 'shared': False, 'export_aae': False, 'sidecar': (), 'sidecar_drop_ext': False, 'sidecar_template': (), 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid': (), 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': datetime.datetime(2012, 12, 31, 0, 0), 'to_time': None, 'touch_file': False, 'update': False, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose_flag': 0, 'xattr_template': (), 'year': (), 'syndicated': False, 'not_syndicated': False, 'saved_to_library': False, 'not_saved_to_library': False, 'shared_moment': False, 'not_shared_moment': False, 'selected': False}
osxphotos version: 0.61.0
Error: RetryError[<Future at 0x143530950 state=finished raised DatabaseError>]
Traceback (most recent call last):
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/export_db.py", line 320, in set_export_results
    c.execute(
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/crash_reporter.py", line 36, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/export.py", line 1759, in export
    export_db.set_export_results(results)
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x143530950 state=finished raised DatabaseError>]

**Expected behavior**

I expect it to output each of the videos that match the date range filter into the specified folder. The names will be formatted with ISO date followed by | followed by their original file name. It was doing this for a while and then this error started. I can't now find a way to avoid the error occurring. 

**Desktop (please complete the following information):**
macOS  13.4.1 (c) 
 - osxphotos version 0.61.0

**Comment by oPromessa** [comment]
@climpyaardvark just out of curiosity:
- did osxphotos ever worked for you or is this the first attempt on this computer?
- may you try export to a different folder say ~/Documents/export as I'm wondering if "Mobile Documents/com~apple~CloudDocs" being an iCloud Drive has some restrictions which prevent osxphotos from working. If it works and as a workaround you can then move the files over to iCloud. 
- one of the files osxphotos creates on the export folder is de export database. You can also try to change the location. Form the manual:
```
In this case, you can use --exportdb DBPATH to instruct osxphotos to store the export database at DBPATH. 
```

Hope it helps. Rhet will surely provide more accurate info.

**Comment by RhetTbull** [comment]
As @oPromessa suggests, I recommend trying a different folder first. I think the error is that osxphotos is trying to write to its export database and cannot, probably because the export folder is not writeable by osxphotos. 

If you can verify that's the case I can improve the error message.

**Comment by RhetTbull** [comment]
@climpyaardvark your export path is wrong.  This is a not an osxphotos error. You exported to `/Library/Mobile Documents...` and you meant was `~/Library/Mobile Documents...` (note the missing `~`) 

I just tried exporting to my Desktop (in iCloud) using:

`osxphotos export "/Users/rhet/Library/Mobile Documents/com~apple~CloudDocs/Desktop/test" --selected --verbose`

and it worked fine. It's frustrating that Apple hides the iCloud drive like this.

One thing you can do if you intend to work with iCloud Drive in the Terminal is create an alias. If you do this:

`ln -s "~/Library/Mobile Documents/com~apple~CloudDocs" ~/iCloudDrive`

Then you can use ~/iCloudDrive anytime you want to reference the iCloud Drive in the Terminal. 

For example:`osxphotos export ~/iCloudDrive/export ...`

**Comment by RhetTbull** [comment]
> Interestingly, the same command was working successfully earlier in the day. Subsequently, iCloud took control of the folder so it could hand off the files to cloud storage.

If you want to use iCloud for this sort of thing you must tell iCloud to keep originals on the Mac. I don't recall the setting but it's in the system settings under iCloud. By default, iCloud uploads to iCloud then deletes off the Mac leaving only a zero-length stub file. iCloud will then download the original when needed. Only Apple apps know how to deal with this stub file.  Command line tools see the file is there but the file does not contain what the app expected. I have found iCloud drive to be rather useless for cloud storage because of behaviors like this. 

If you really want the files in iCloud, you could export to a directory outside iCloud then something like ChronoSync to automatically sync the files to iCloud drive. This is a [supported use case](https://www.econtechnologies.com/chronosync/guide-backup-icloud-storage.html#backing_up_local_data_to_icloud) for [ChronoSync](https://www.econtechnologies.com/chronosync/overview.html).
