### ISSUE TITLE
Add --folder-keyword and --folder-album-keyword options to CLI

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#117]
Add option to include folder (--folder-keyword) and full folder path to album (--folder-album-keyword) that would work like --album-keyword and --person-keyword

**Comment by RhetTbull** [comment]
As I think about this it might be more useful to simply extend the template system already in place for export directory. For example:

--keyword-template "{folder_album}" 

users could then specify created.year, place.name, etc as keywords

Would need a way to not include templates that resolved to None -- unlike in a directory it is probably less useful for keywords to specify a default value

**Comment by adamshand** [comment]
That'd be great!

**Comment by RhetTbull** [comment]
@adamshand done in v0.28.13 which adds --keyword-template option

**Comment by adamshand** [comment]
Awesome, thanks!
