### ISSUE TITLE
Create MacPorts portfile for osxphotos

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#1200]
If someone would create an initial port for MacPorts I wouldn’t mind keeping it up to date. I’d think that it should be possible to let a MacPorts port install this software without using another intermediate package manager (like `pipx` or `pip`), but I don’t know enough about the Python ecosystem to do that.

I’ll ask on the MacPorts dev mailinglist if someone would be willing to create a Portfile for `osxphotos`.

_Originally posted by @breun in https://github.com/RhetTbull/osxphotos/issues/1199#issuecomment-1709504419_

**Comment by breun** [comment]
I’ve reached to the MacPorts dev mailinglist to see if someone would be willing to get this going: https://lists.macports.org/pipermail/macports-dev/2023-September/045148.html

**Comment by breun** [comment]
It looks like @catap is willing to create a MacPorts portfile for osxphotos: https://lists.macports.org/pipermail/macports-dev/2023-September/045153.html

**Comment by RhetTbull** [comment]
Great! Thank you @breun for reaching out. @catap thank you so much for being willing to help! Let me know if there's anything I need to do to make this work.

**Comment by catap** [comment]
@RhetTbull I'll try to do it in a few days. I do have unexpected hello which creates a lot of issues: GoDaddy parked domain which I've used for email and which is used to login into GoDaddy :)

So, I'm almost blind for notification these days :(

**Comment by RhetTbull** [comment]
@catap No rush and no worries! I appreciate any help you can provide when you can get to it. Good luck with the GoDaddy issue...does not sound like fun to resolve!

**Comment by catap** [comment]
@RhetTbull, @breun  would you like to be a co-maintaner of this port?

**Comment by breun** [comment]
I could help keeping it up to date with version bumps, but I’m otherwise not very familiar with Python. But fine if you add me as a maintainer.

**Comment by RhetTbull** [comment]
I'm happy to be a co-maintainer. Will need to learn how to update the portfile but it might help to keep it up to date with changes.

**Comment by catap** [comment]
@RhetTbull ok, I'll add you also as co-maintainer to some of python libraries which is dependencies of `osxphotos` and which you're an author :)

**Comment by catap** [comment]
@breun, @RhetTbull have you ever try to run it on python from MacPorts?

**Comment by breun** [comment]
> @breun, @RhetTbull have you ever try to run it on python from MacPorts?

I haven’t. Having problems with that?

**Comment by catap** [comment]
Long story short: it depends on pyobj and pyobjc stricly depends on system's libffi https://github.com/ronaldoussoren/pyobjc/issues/355, when MacPorts python uses MacPorts one. Idea mix libffi isn't easy to implement and probably will crash.

So, I'm a bit stuck.

**Comment by RhetTbull** [comment]
>

**Comment by RhetTbull** [comment]
> have you ever try to run it on python from MacPorts?

Yes. I currently run it via pipx installed through MacPorts. I've not tried it directly via Python but can give it a go today.

**Comment by RhetTbull** [comment]
@catap Yes, I just confirmed osxphotos runs from the port installed python.  I did a clean install of python 3.11.5 from port, created a venv & activated it, installed osxphotos, and ran some tests with osxphotos.

**Comment by catap** [comment]
@RhetTbull branch is ready here: https://github.com/catap/macports-ports/tree/osxphotos

Anyway, a naive approach leads to the error:
```
Traceback (most recent call last):
  File "/opt/local/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli_main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/__main__.py", line 3, in <module>
    from .cli.cli import cli_main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/__init__.py", line 49, in <module>
    from .cli import cli_main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/cli.py", line 21, in <module>
    from .exiftool_cli import exiftool
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/exiftool_cli.py", line 25, in <module>
    from .export import export, render_and_validate_report
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/export.py", line 73, in <module>
    from .cli_commands import logger
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/cli_commands.py", line 37, in <module>
    set_rich_theme(get_theme())
                   ^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/color_themes.py", line 191, in get_theme
    return get_default_theme()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/color_themes.py", line 205, in get_default_theme
    theme_manager = get_theme_manager()
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/color_themes.py", line 181, in get_theme_manager
    theme_dir=str(get_theme_dir()), themes=COLOR_THEMES.values(), update=True
                  ^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/color_themes.py", line 172, in get_theme_dir
    theme_dir = get_config_dir() / "themes"
                ^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/osxphotos/cli/common.py", line 88, in get_config_dir
    config_dir = xdg.xdg_config_home() / APP_NAME
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'xdg' has no attribute 'xdg_config_home'
```

**Comment by catap** [comment]
Ah, I see. You're using `xdg` package, and MacPorts has  `pyxdg` as `xdg`. Cleaning it up, yeah.

**Comment by catap** [comment]
Status update. All PRs to take care of dependnecies are openned:
 - https://github.com/macports/macports-ports/pull/20363
 - https://github.com/macports/macports-ports/pull/20370
 - https://github.com/macports/macports-ports/pull/20371 
 - https://github.com/macports/macports-ports/pull/20373

As soon as it merged I'll open a PR to bring osxphotos port. Locally it was suceffuly tested.

**Comment by RhetTbull** [comment]
@catap Thanks very much! I did not realize ports would also be needed for dependencies and these could not be installed from pypi.

**Comment by catap** [comment]
@RhetTbull here the part of hell which I've discovered. PyPi contains `xdg`, `xdg-base-dirs` and `pyxdg`. The first and the last is conflictinc and can't be installed.

Is it possible to switch `osxphotos` to `xdg-base-dirs`?

**Comment by catap** [comment]
> @catap Thanks very much! I did not realize ports would also be needed for dependencies and these could not be installed from pypi.

Yeah, everything should be packed into MacPorts and everything is installing in one environemnt.

**Comment by catap** [comment]
Here it is: https://github.com/macports/macports-ports/pull/20416

**Comment by RhetTbull** [comment]
@all-contributors please add @catap for code

**Comment by RhetTbull** [comment]
@all-contributors please add @breun  for maintenance

**Comment by catap** [comment]
Here it is https://ports.macports.org/port/osxphotos/details/

**Comment by breun** [comment]
@catap Sadly it's not working yet for me: https://trac.macports.org/ticket/68202

**Comment by RhetTbull** [comment]
@all-contributors please add @breun for docs

**Comment by catap** [comment]
Shall it be closed?
