### ISSUE TITLE
osxphotos does not install with pipx and Python 3.11

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#1213]
Stumbled across this tool to backup my library with metadata since Image Capture wasn't doing the job. 
But while installing on terminal (pipx install osxphotos) I get an error thrown at me saying 

`pip failed to build package:
    xattr

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit code 1

Error installing osxphotos.`

I am not the most well versed person on the terminal side of things so I am not aware of what the error is talking about. Any help with install would be appreciated!
I am running 13.5.2 Ventura on my Intel 2019 MBP for additional information.

_Originally posted by @420gofOGKush in https://github.com/RhetTbull/osxphotos/discussions/1204_

**Comment by RhetTbull** [comment]
This is a problem for osxmetadata to solve as it's pulling in version of xattr that doesn't have a python 3.11 wheel

**Comment by ZarK** [comment]
I think I solved on my M2 MacBook by setting the architecture first:

`arch -x86_64 /bin/zsh`

By default on Apple Silicon it would try ARM64, which was not supported.

**Comment by RhetTbull** [comment]
@all-contributors please add @420gofOGKush for bug

**Comment by RhetTbull** [comment]
@all-contributors please add @ZarK for bug

**Comment by RhetTbull** [comment]
@ZarK please give v0.63.3 a try. I think I've fixed the dependency issue that was causing problems with pipx.
