### ISSUE TITLE
WARNING: This module has only been tested with macOS versions you have Darwin, OS version: 13.6

### ISSUE THREAD

**Issue by khurshid-alam** [RhetTbull/osxphotos#1252]
** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

- If you installed the pre-built binary, download and install the latest [release](https://github.com/RhetTbull/osxphotos/releases)

Biunary install

**Describe the bug**
WARNING: This module has only been tested with macOS versions you have Darwin, OS version: 13.6
**To Reproduce**
1. What' the full command line you used with osxphotos?
2. What was the error output?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ventura 13.6
 - osxphotos version (`osxphotos --version`)
 - osxphotos, version 0.64.0
Python 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]

**Comment by RhetTbull** [comment]
It's not a bug...it's not been tested on 13.6.  osxphotos should work fine but until I get around to installing 13.6 and testing it, it'll output the warning. Apple does sometimes (but rarely) change the Photos database schema between minor releases which is why osxphotos warns you if it's running on an OS that has not been tested.

**Comment by khurshid-alam** [comment]
I know this is not a bug. But my script being affected as it prints out warning. How Do I disable it ?

**Comment by RhetTbull** [comment]
Just ignore it. Our if you're calling from python, try `logging.disable(logging.CRITICAL)` to disable all warnings.

**Comment by khurshid-alam** [comment]
Yes, That will work. But I am using a simple bash script here.

**Comment by RhetTbull** [comment]
> Yes, That will work. But I am using a simple bash script here.

Add this to the line where you call osxphotos: ` 2>/dev/null`. That sends stderr to null.

**Comment by khurshid-alam** [comment]
This is closed now. I was hoping to get a release with 13.6 supported ?

**Comment by RhetTbull** [comment]
Osxphotos works with 13.6. Next release will get rid of the warning

**Comment by RhetTbull** [comment]
In a week or two. I've got several fixes /features I'm trying to get in for next release.
