### ISSUE TITLE
Allow CLI logic to be called as python API

### ISSUE THREAD

**Issue by nkxco** [RhetTbull/osxphotos#1253]
Hi. 

I have used `osxphotos` manually to do incremental backups, and now I'm in the process of replacing everything I'm doing with a python script (`osxphotos` export, archive creation, gpg encryption, and cloud upload).

Now, while the `osxphotos` python API is great and nicely documented, I realise that its features are not exactly equivalent to those of the command line.

For instance, the `osxphotos export` command line will export all versions of photos including edited versions, while in the python API, `PhotoInfo.export()` or `PhotoExporter.export()` will only export one version (original or edited), as they take a `edited` parameter:

```
edited: (bool, default=False): if True will export the edited version of the photo otherwise exports the original version
```

So if I want to use Python and mimic `osxphotos export`, I actually need to re-implement part of the logic which is in `osxphotos/cli/export.py`. And I cannot directly call the function `osxphotos/cli/export.py :: export` because of all the click decorators.

Would it make sense to allow the CLI logic to be called from Python, to avoid this re-implementation?
For instance by defining `cli_<cmd>_logic` functions that are not decorated, and move all decorators around thin wrappers:

```
def cli_export_logic(<params>):
    # no decorators could be called from python
    [...]

@<keep decorators here>
def export(<params>):
    cli_export_logic(<params>)
```

**Is your feature request related to a problem? Please describe.**
I want to use python, but I don't want to re-implement existing logic.

**Describe the solution you'd like**
Allow the CLI logic to be called from python.

**Describe alternatives you've considered**
Calling `osxphotos` from python with `subprocess`

**Comment by RhetTbull** [comment]
I'm glad you're making use of osxphotos programmatically -- that was my first goal with osxphotos but I found very few people want to do this and most people just want to export photos with the CLI. The CLI export code is complex for a number of reasons. It was some of the first python code I ever wrote, it has to handle lots of edge cases, and there are many, many parameters to deal with. All this makes refactoring it a bit of a chore. Your suggestion is good but candidly this isn't high on my priority list as most users want to the use the CLI. You can call the CLI directly if you use `CliRunner` from `click.testing`, see:

https://github.com/RhetTbull/osxphotos/blob/6b232dacbff807b639bc9d520f9c87dd3b383b49/tests/test_cli.py#L1592-L1601

However, I think most of the functionality you want is already in the `export_photo()` function in `osxphotos/cli/export.py`.  It's an internal helper function that isn't well documented and isn't typed but you should be able to figure it out by looking at the code. The (many) args have the same name as the click arguments so you can pass it `**kwargs` from the main CLI function.

https://github.com/RhetTbull/osxphotos/blob/6b232dacbff807b639bc9d520f9c87dd3b383b49/osxphotos/cli/export.py#L1561-L1577

And `export_photo()` is defined here:

https://github.com/RhetTbull/osxphotos/blob/6b232dacbff807b639bc9d520f9c87dd3b383b49/osxphotos/cli/export.py#L1842-L1952

**Comment by RhetTbull** [comment]
Also, have you considered `--post-function`? This calls your custom python function following each exported photo so you can do customs processing. See [example here](https://github.com/RhetTbull/osxphotos/blob/main/examples/post_function.py)

**Comment by nkxco** [comment]
Thanks for all the suggestions!

- I had a look at `export_photo` before, but it still seemed that some logic was outside of it (like for sidecar files), so I didn't continue investigating too much.
- I'll have a look at `CliRunner`, but their website says to use that for testing only. By any chance, do you know if this is equivalent to launching a new process? (If so I'll keep the `subprocess` solution)
- I saw `--post-function` but I'm not sure it suits my use case. In my case, `osxphotos` is not the main orchestrator, but only the part exporting photos. It's called as a library by my main script which checks online and decides if a backup is needed for a given interval under multiple conditions.

**Comment by RhetTbull** [comment]
> I had a look at export_photo before, but it still seemed that some logic was outside of it (like for sidecar files), so I didn't continue investigating too much.

All the export logic is in that one function.

The sidecar logic is all in `generate_user_sidecars()`

Similarly, if you are using the Finder tags or extended attributes feature, see `write_finder_tags()` and `write_extended_attributes()`.   

So with just a few function calls you can create your own export function that does exactly what you want. You'd only have to handle the options you're using and not the entire CLI interface.

**Comment by RhetTbull** [comment]
I discovered a use for this for my own uses so I'm going to implement this (just for `export`).  You'll be able to call `export_cli()` directly but will be responsible for ensuring all types are correct as the code uses custom click types to do some conversions currently. E.g. `--from-date` converts `2023-01-01` into a `datetime.datetime` so you'll have to pass a `datetime.datetime`. I'm working on adding type hints to all the `export_cli` args.

**Comment by RhetTbull** [comment]
@all-contributors please add @nkxco for ideas
