### ISSUE TITLE
push-exif command should support the  --dry-run option

### ISSUE THREAD

**Issue by santiagoGPNC** [RhetTbull/osxphotos#1259]
**Is your feature request related to a problem? Please describe.**
It seems that the push-exif command does not support the --dry-run option. Being a potentially destroying operation, I believe this option should be available

**Describe the solution you'd like**
calling osxphotos push-exif --dry-run should display the changes that would be made without actually performing them.
This seems to have been mentioned in the [original proposal](https://github.com/RhetTbull/osxphotos/issues/160), but doesnt seem to have been implemented or doesnt work.

Calling`osxphotos push-exif --help` does not mention _--dry-run_ and using it returns: _Error: No such option: --dry-run_

My system:
```
$ osxphotos -v
osxphotos, version 0.64.3
Python 3.12.0 (main, Oct  5 2023, 15:44:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS 13.5.2, arm64
```

PS- this looks like a fantastic tool. thank you for your efforts.

**Comment by RhetTbull** [comment]
I agree.  Will implement when I have time (or happy to merge a PR if someone else wants to tackle this)

**Comment by RhetTbull** [comment]
Note there's also the `--compare` which effectively is a dry run:

    If you want to compare metadata between Photos and the original files
    without writing metadata, use the `--compare` option.  This will print a
    report of any differences between the metadata in Photos and the original
    files but will not modify any files.

**Comment by santiagoGPNC** [comment]
Thanks, I did not notice the` ---compare` option. I will give it a try.

**Comment by RhetTbull** [comment]
@all-contributors please add @santiagoGPNC for ideas

**Comment by RhetTbull** [comment]
This will be implemented in next release
