### ISSUE TITLE
Catch attempt to set export destination to Photos library

### ISSUE THREAD

**Issue by bernstbj** [RhetTbull/osxphotos#1268]
If you do the `export` function and do not specify an output / DEST directory, instead of targeting the current directory it targets the actual Photos.library that you're exporting.

Feature request is to please either warn/fail if target is inside the Photo library, or at least presume lack of DEST means current directory!

**Comment by RhetTbull** [comment]
What command did you use? This shouldn't be possible as destination is a required command line argument.

**Comment by bernstbj** [comment]
Did it with: 
`osxphotos export /Volumes/Foetoes/Photos\ Library\ FT.photoslibrary/ --exiftool --directory "{created.year}/{created.month}/{folder_album}" --verbose --report export.csv --person-keyword 2>&1 | tee OUT`

Had to re-do it as:
`osxphotos export /Volumes/Foetoes/Photos\ Library\ FT.photoslibrary/ --exiftool --directory "{created.year}/{created.month}/{folder_album}" --verbose --report export.csv --person-keyword /Volumes/Foetoes/tmp/export2/ 2>&1 | tee OUT`

**Comment by RhetTbull** [comment]
That command tells osxphotos to export to the Photos library directory so it did as directed. You didn't specify a library path so it automatically used the last opened library.

But I do see how this could be confusing so a check to verify the output directory isn't a library would be useful.

**Comment by RhetTbull** [comment]
This is the usage line from `osxphotos help export`:

`osxphotos export [OPTIONS] [PHOTOS_LIBRARY]... DEST`

DEST is the export destination and is required. You can **optionally** provide the path to the photos library before that (but this is deprecated).  I need to just remove the deprecated library path (which should now be specified via the `--library` or `--db` option).

**Comment by bernstbj** [comment]
Makes sense... I think the issue is that I initially went off the examples on the README.md which seem to regularly have options after the /path/to/export, e.g. `osxphotos export /path/to/export --exiftool --keyword-template "{keyword|remove(MyKeyword)}" --replace-keywords` (randomly picked one).

**Comment by RhetTbull** [comment]
This is fixed in the main branch and will be included in next release.
