### ISSUE TITLE
Using osxphotos to cache photos outside of the Photos library?

### ISSUE THREAD

**Issue by felciano** [RhetTbull/osxphotos#131]
Hi --

This might be a request for clarified documentation more than anything else. `osxphotos` looks quite powerful, but I can't quite tell whether it is a good fit for ongoing/regular export of photos from Apple Photos. In particular, if you wanted to keep an archival version of your photos--with metadata--in open formats for long time archival storage with minimal file format lock-in risk, `osxphotos` seems like a good match for doing that first export. 

However, how would one use it on an ongoing, incremental basis? Is there a way to tell it to skip photos that have already been exported, e.g. via generated MD5 hashes or similar?

**Comment by RhetTbull** [comment]
Currently you'd need to re-export the entire library however I have an open issue #100 to add a --update option to do just what you requested. This would only update new or changed photos. I'm still thinking through implementation-- for example, osxphotos will need to determine if metadata changes.

**Comment by RhetTbull** [comment]
Closing this and moving conversation to issue #100
