### ISSUE TITLE
--jpeg-ext generates long file names

### ISSUE THREAD

**Issue by finestream** [RhetTbull/osxphotos#1321]
** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

> osxphotos version
You have the latest version of osxphotos: 0.65.0

**Describe the bug**
When exporting with the following options 

osxphotos export \
    --update \
    --cleanup \
    --ramdb \
    --jpeg-ext jpeg \
    --filename '{created.date}_{created.hour}.{created.min}.{created.sec}' \
    --directory '{edited?{edited_version?Collection,Originals},Collection}/{created.year}/{created.mm}' \
    --touch-file \
    --sidecar XMP \
    --keyword-template '{favorite?Favorite,}' \
    --keyword-template '{photo.hidden?Private,}' \
    --library '/Users/username/Pictures/Photos Library.photoslibrary' \
    /targetdir

I get an error 

Error exporting photo (DD440259-2C03-4618-B132-A900056D4947: IMG_1087.JPG) as 2022-10-13_11.14.26.jpeg: [Errno 63] File name too long: '/<exportdir>/Collection/2022/10/2022-10-13_11.14.26 (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1).jpeg'

The following checks were made:
- There is no file starting with 2022-10-13_11.14.26 in the target directory
- if the option --jpeg-ext jpeg is removed the export concludes with no error, in this case the file is exported with extension JPG

**To Reproduce**
Not sure probably is something with my Library - if helpful I could run some specific tests

**Expected behavior**
file is exported as "2022-10-13_11.14.26.jpeg"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS] Sonoma 14.1.2
 - osxphotos version (`osxphotos --version`)
You have the latest version of osxphotos: 0.65.0

**Additional context**

**Comment by finestream** [comment]
I am not sure but possibly the picture is "special" as it comes from a DSLR Camera and maybe had also a Raw file that I later deleted. In case it helps.

**Comment by oPromessa** [comment]
While @RhetTbull comes back to you on this topic. 

What if you just run a simple test and try with `--name IMG_1087` into an empty `/test_target_dir` just to make sure it's specific to this pic and rule out other causes.

**Comment by RhetTbull** [comment]
@finestream does this happen with all images or only this one? Are the other images being exported correctly?

**Comment by RhetTbull** [comment]
Also, as @oPromessa recommended above, it would be good to export just this one photo using the `--name` option both with and without the `--jpeg-ext` option to see if there's any difference.

**Comment by finestream** [comment]
> While @RhetTbull comes back to you on this topic.
> 
> What if you just run a simple test with all your parameters and try with `--name IMG_1087` into an empty `/test_target_dir` just to make sure it's specific to this pic and rule out other causes.

- Exporting only this picture to an empty folder works properly.
- Running the same command with a new directory target works properly
- I also fully deleted the previous export and re-run it and works properly. 

I am assuming something went corrupted on my export tree and given I can't reproduce any longer I would suggest closing the issue.

For the record @RhetTbull it happened for 8 images, all from the same camera and shooting session. Other pictures from the same session were working properly. 

Thank you very much for the quick reaction time and halp!

**Comment by RhetTbull** [comment]
I've just looked at the code that increments the filename and I cannot find anything obvious that would cause this. One more test to run is to run your same command again but this time add `--debug` between `osxphotos` and `export`: `osxphotos --debug export [...rest of your options]`.  This will cause osxphotos to crash when it encounters the error instead of continuing on. When it crashes it will write a crash log `osxphotos_crash.log` when you can then post here or send to me. This will contain useful info on exactly where the error is happening.

**Comment by finestream** [comment]
Also after a re-running the comment and performing an --update, it still worked as expected. Thank you.

**Comment by RhetTbull** [comment]
@finestream OK, I will close the issue. Glad it's working. If it happens again feel free to re-open. Is the target directory on a network drive by chance? It could be a network error caused the code which checks to see if a file is already in the export folder to fail.
