### ISSUE TITLE
Add --sidecar to import command

### ISSUE THREAD

**Issue by finestream** [RhetTbull/osxphotos#1322]
**Is your feature request related to a problem? Please describe.**
I am experimenting with using osxphotos to make a backup of my photo library and the key feature is a restore procedure that would be based on the import command. I would have a preference for not using exiftool for two reasons: 1) I do not like changing the original files and 2) not all file formats support all metadata

**Describe the solution you'd like**
support for -sidecar in the import command, the options should work symmetrically to the -sidecar for export

**Describe alternatives you've considered**
use the already implemented -exiftool

**Additional context**
Super tool! Thank you

**Comment by RhetTbull** [comment]
As an alternative I've already thought about doing a "restore" tool that would read all the metadata from the export database (everything needed to reconstruct the sidecars is steady stored). I'm also working on some code that would allow osxphotos to create a new Photos library and directly populate it without using the Photos import feature. This is a longer term effort but would be useful for repairing a corrupted library.

**Comment by RhetTbull** [comment]
Doing this with a JSON sidecar as osxphotos can generate would be easy. Reading the XMP sidecar is more difficult. I've not found an XMP library that is compatible with the osxphotos license. The sidecars are written with a template but reading XMP is more challenging.

**Comment by RhetTbull** [comment]
Did some experimenting and exiftool could be used to convert XMP files to JSON by way of an intermediate temporary EXV file:

```bash
exiftool -tagsfromfile IMG_4547.jpg.xmp  -all:all temp.exv
exiftool -G -j temp.exv > IMG_4547.jpg.json
```

**Comment by RhetTbull** [comment]
Actually, this can be done in one command!

`exiftool -G -j IMG_4547.jpg.xmp > IMG_4547.jpg.json`

**Comment by RhetTbull** [comment]
And the `osxphotos.exiftool.ExifTool` class will read these just fine!

```pycon
>>> exif = ExifTool("IMG_4547.jpg.xmp")
>>> exif.asdict()
{'SourceFile': 'IMG_4547.jpg.xmp', 'ExifTool:ExifToolVersion': 12.67, 'File:FileName': 'IMG_4547.jpg.xmp', 'File:Directory': '.', 'File:FileSize': 3814, 'File:FileModifyDate': '2023:12:09 15:57:22-08:00', 'File:FileAccessDate': '2023:12:09 15:59:43-08:00', 'File:FileInodeChangeDate': '2023:12:09 15:57:22-08:00', 'File:FilePermissions': 100644, 'File:FileType': 'XMP', 'File:FileTypeExtension': 'XMP', 'File:MIMEType': 'application/rdf+xml', 'XMP:XMPToolkit': 'osxphotos', 'XMP:SidecarForExtension': 'jpg', 'XMP:Description': '\u2068Elder Park\u2069, \u2068Adelaide\u2069, \u2068Australia\u2069', 'XMP:Title': 'Elder Park', 'XMP:Subject': ['Frühstück', 'Museum', 'Römermuseum', 'album:2018-10 - Sponsion', 'album:2019-10/11 Paris Clermont', 'album:Folder1/SubFolder2/AlbumInFolder'], 'XMP:DateCreated': '2017:06:20 17:18:56.518000+09:30', 'XMP:TagsList': ['Frühstück', 'Museum', 'Römermuseum', 'album:2018-10 - Sponsion', 'album:2019-10/11 Paris Clermont', 'album:Folder1/SubFolder2/AlbumInFolder'], 'XMP:CreateDate': '2017:06:20 17:18:56', 'XMP:ModifyDate': '2017:06:20 17:18:56', 'XMP:GPSLongitude': 138.59686167, 'XMP:GPSLatitude': -34.91889167, 'XMP:RegionAppliedToDimensionsH': 2754, 'XMP:RegionAppliedToDimensionsW': 2754, 'XMP:RegionAppliedToDimensionsUnit': 'pixel', 'XMP:RegionAreaH': 0.0, 'XMP:RegionAreaW': 0.0, 'XMP:RegionAreaX': 0.0, 'XMP:RegionAreaY': 1.0, 'XMP:RegionAreaUnit': 'normalized', 'XMP:RegionName': '', 'XMP:RegionRotation': 0.0, 'XMP:RegionType': 'Face', 'XMP:RegionPersonDisplayName': '', 'XMP:RegionRectangle': '0.000000, 1.000000, 0.000000, 0.000000', 'Composite:GPSLatitudeRef': 'S', 'Composite:GPSLongitudeRef': 'E', 'Composite:GPSPosition': '-34.91889167 138.59686167'}

```

**Comment by RhetTbull** [comment]
This should work as `--sidecar SIDECAR_TEMPLATE` so you could do this:

`osxphotos import --sidecar "{filepath}.xmp"` or if you didn't have the image extension as part of the sidecar name, `osxphotos import --sidecar "{filepath.stem}.xmp"`

Sidecar type would be inferred from the file extension.

**Comment by RhetTbull** [comment]
Another use case for this is "downgrading" a library. If you've upgraded macOS versions (and aren't using iCloud) and your library gets migrated to the new version, you cannot go back without losing access to your photos. This would allow users to do a full export then re-import once they downgraded the OS.

**Comment by RhetTbull** [comment]
@finestream  this has been implemented in a feature branch and will be included in the next release. The next release will have two new options for `osxphotos import`

`--sidecar`: automatically find the associated sidecar file and if it is present, import metadata from the sidecar.
`--sidecar-template`: use the osxphotos template system to specify the name of the sidecar file, for example:
`--sidecar-template "{filepath}.xmp"`

JSON and XMP sidecars are supported. If using XMP, exiftool must be installed as it is used to read the XMP files.

**Comment by finestream** [comment]
Thank you looking forward to the next release

**Comment by finestream** [comment]
Thank you very much for the feature. 

It generally works well a few comments:

- the limitation on live photos is in fact not there (see #1345) - I have not tested yet how it works for Raw-Jpeg pairs (I do not have any, will test when I get a moment with the DSLR)

- for the back-up use case there is a bug and json files for edited images are not generated (see #1346)

- There is a strange behaviour that I do not understand, I exported 251 Live Photos and imported them with the import command. 2 Pictures were edited hence I got 249 JSON files and 251 pairs JPEG / MOV. During import osxphoto tracked 502 files (i.e. 2x251). I get the following result "Done: imported 381 files, 121 errors", all 251 Live Photos show up correctly in photos. So I get the expected behaviour AND an error message. The errors are all on the mov part of the pair and the message reads "Error importing file <FILEPATH AND NAME>. If I test any of the imported Live Photos that triggered an error, I get the expected result and the video works. Will explore further and if I find a reproducible but I will file it.

**Comment by finestream** [comment]
One more minor point:

The option --sidecar-template has a different syntax and semantics in import vs. export. In particular it is not possible to skip the mako template argument in the export version.

**Comment by RhetTbull** [comment]
Thanks. Will look into this. As for --sidecar-template, yes I'm aware of this. They mean two different things between export and import. I couldn't think of a better name for the import version. For export, the option allows you to specify your own template for a custom sidecar format.

**Comment by finestream** [comment]
Hoping to help here a few ideas for the --sidecar-template:

1. **Use --filename and --directory options:** the --filename and --directory options already control the sidecar filename on export. Add a new conditional keyword {sidecar? :} to do specific manipulations for the sidecar files. On import it would also be possible to deprecate the --parse-date and --parse-folder-date options and extract all sorts of metadata from directory/filenames structures using the templating system. On export reduce the --sidecar-template only to be used for the sidecar format (i.e. in 2 argument variant). 

1. **Use two arguments:** --sidecar-template and --sidecar-filename where --sidecar-template is used for the format and --sidecar-filename is used for the name both on import and export. For export I would leave the three arguments variant of --sidecar-template to preserve backwards compatibility (in which case it would over-ride --sidecar-filename if present).

I find the former Option somehow "cleaner" but it would break backwards compatibility. The latter Option would break a recent change introduced with 0.67.0 for which I am probably the only user :-) 

Finally, in both options a --sidecar-template option might be added to import to use custom templates. I do not see a compelling use-cases for this.

**Comment by RhetTbull** [comment]
Thanks for the suggestions. What is the desired outcome for control over naming the exported sidecar? I'm not aware of a single program that makes use of sidecars that aren't named either IMG_1234.jpg.json or IMG_1234.json. The latter case is already covered by `--sidecar-drop-ext` and can be controlled via sidecar filename template when using `--sidecar-template`. Is there an app you want to use that uses a different naming scheme?

The only deviation I'm aware of to this scheme is Google Takeout and it appears to be a bug that images named IMG_1234(1).jpg get a sidecar named IMG_1234.jpg(1).json but the other cases follow conventions.

> Finally, in both options a --sidecar-template option might be added to import to use custom templates. I do not see a compelling use-cases for this.

I agree I can't think of a compelling use case. 

This can be accomplished on import using the `--post-function`. You can have a custom python function that gets called after each import with the part of the imported file and a reference to the imported photo. From there you could process the sidecar and apply the metadata to the image. Providing a means to handle custom sidecars means having to supply a mapping of every sidecar field to the correct metadata, perform date conversions, etc. This is as complex or more so than writing a post function to do this.

**Comment by RhetTbull** [comment]
To avoid confusion between export and import I could rename the newly created `--sidecar-template` for import to `--sidecar-filename` then could add the same to export. In the export case though as I said I don't understand the use case for creating sidecars that don't match convention. (Though for import the existence of this implies that maybe there are such cases?)

**Comment by finestream** [comment]
Thank you for your answers!

> To avoid confusion between export and import I could rename the newly created --sidecar-template for import to --sidecar-filename then could add the same to export. In the export case though as I said I don't understand the use case for creating sidecars that don't match convention. (Though for import the existence of this implies that maybe there are such cases?)

--sidecar-filename would be also my 2nd option suggestion.

As for the use case for creating sidecars with custom filenames, I also do not see a use case. While I was trying to workaround bug #1346, I noticed that current export --sidecar-template option includes a parameter "SIDECAR_FILENAME_TEMPLATE", hence I assumed that there is a use case for custom sidecar filenames.

**Comment by RhetTbull** [comment]
--sidecar-template on export is provided for a case where a user wants to create custom sidecars and can support any custom format via template. While it is possible to create a custom naming scheme here the filename template is needed to specify the extension (Eg .xmp). The user could create a custom naming scheme for some custom use case but this isn't something import should necessarily support. 

But I do think I'll rename the import option to make it less confusing.

**Comment by RhetTbull** [comment]
@finestream release v0.67.1 changed `--sidecar-template` to `--sidecar-filename` for the import command.

**Comment by finestream** [comment]
thank you - in the mean time I could test the restore function it works with the limitations mentioned in the documentation of the import command. Happy new year!
