### ISSUE TITLE
osxphotos does not install via pipx on 12.7.1

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#1324]
```
➜  ~ pipx install osxphotos
Fatal error from pip prevented installation. Full pip output in file:
    /Users/rhet/Library/Logs/pipx/cmd_2023-12-10_14.08.10_pip_errors.log

pip seemed to fail to build package:
    wrapt<1.14.0,>=1.13.3

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ValueError: malformed node or string on line 2: <ast.Call object at 0x108433990>
    AttributeError: wrapt has no attribute __version__
    ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py). Did you mean: 'formatargvalues'?
    error: metadata-generation-failed

Error installing osxphotos.
➜  ~
```

Looks like wrapt is using formatargspec deprecated in python 3.11. Not sure why this even works on Ventura but not on Monterey.

**Comment by RhetTbull** [comment]
See [this post on reddit](https://www.reddit.com/r/osxphotos/comments/18f9kgw/pipx_install_osxphotos_fails/)

**Comment by RhetTbull** [comment]
Weird, the spec for wrapt in osxphotos is  `wrapt>=1.14.1,<2.0.0` which I updated a year ago in #825 so why is pipx trying to install < 1.1.14?

```
pip seemed to fail to build package:
    wrapt<1.14.0,>=1.13.3
```

**Comment by RhetTbull** [comment]
<details><summary>Full log here:</summary>
PIP STDOUT
----------
Collecting osxphotos
  Downloading osxphotos-0.64.0-py3-none-any.whl.metadata (15 kB)
Collecting bitmath<1.4.0.0,>=1.3.3.1 (from osxphotos)
  Downloading bitmath-1.3.3.1.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 509.4 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting bpylist2<5.0.0,>=4.1.1 (from osxphotos)
  Downloading bpylist2-4.1.1-py3-none-any.whl.metadata (5.5 kB)
Collecting Click<9.0,>=8.1.3 (from osxphotos)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting Mako<1.3.0,>=1.2.2 (from osxphotos)
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 412.0 kB/s eta 0:00:00
Collecting more-itertools<9.0.0,>=8.8.0 (from osxphotos)
  Downloading more_itertools-8.14.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 298.2 kB/s eta 0:00:00
Collecting objexplore<2.0.0,>=1.6.3 (from osxphotos)
  Downloading objexplore-1.6.3-py3-none-any.whl (22 kB)
Collecting packaging>=21.3 (from osxphotos)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pathvalidate<4.0.0,>=2.4.1 (from osxphotos)
  Downloading pathvalidate-3.2.0-py3-none-any.whl.metadata (11 kB)
Collecting ptpython<4.0.0,>=3.0.20 (from osxphotos)
  Downloading ptpython-3.0.23-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.0/64.0 kB 517.0 kB/s eta 0:00:00
Collecting pytimeparse2<2.0.0,>=1.4.0 (from osxphotos)
  Downloading pytimeparse2-1.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting PyYAML<7.0.0,>=6.0.0 (from osxphotos)
  Downloading PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting requests<3.0.0,>=2.27.1 (from osxphotos)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting rich-theme-manager>=0.11.0 (from osxphotos)
  Downloading rich_theme_manager-0.11.0-py3-none-any.whl (14 kB)
Collecting rich<14.0.0,>=13.5.2 (from osxphotos)
  Downloading rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting shortuuid<2.0.0,>=1.0.9 (from osxphotos)
  Downloading shortuuid-1.0.11-py3-none-any.whl (10 kB)
Collecting strpdatetime>=0.2.0 (from osxphotos)
  Downloading strpdatetime-0.3.0-py3-none-any.whl.metadata (4.7 kB)
Collecting tenacity<9.0.0,>=8.0.1 (from osxphotos)
  Downloading tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Collecting textx<4.0.0,>=3.1.1 (from osxphotos)
  Downloading textX-3.1.1-py2.py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 498.3 kB/s eta 0:00:00
Collecting toml<0.11.0,>=0.10.2 (from osxphotos)
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting wrapt<2.0.0,>=1.14.1 (from osxphotos)
  Downloading wrapt-1.16.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (6.6 kB)
Collecting wurlitzer<4.0.0,>=3.0.2 (from osxphotos)
  Downloading wurlitzer-3.0.3-py3-none-any.whl (7.3 kB)
Collecting xdg-base-dirs>=6.0.0 (from osxphotos)
  Downloading xdg_base_dirs-6.0.1-py3-none-any.whl.metadata (4.6 kB)
INFO: pip is looking at multiple versions of osxphotos to determine which version is compatible with other requirements. This could take a while.
Collecting osxphotos
  Downloading osxphotos-0.63.5-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.63.4-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.63.3-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.63.2-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.63.1-py3-none-any.whl.metadata (15 kB)
Collecting bpylist2==4.0.1 (from osxphotos)
  Downloading bpylist2-4.0.1-py3-none-any.whl (30 kB)
Collecting osxphotos
  Downloading osxphotos-0.63.0-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.62.3-py3-none-any.whl.metadata (15 kB)
INFO: pip is still looking at multiple versions of osxphotos to determine which version is compatible with other requirements. This could take a while.
  Downloading osxphotos-0.62.2-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.62.1-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.62.0-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.61.0-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.10-py3-none-any.whl.metadata (15 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading osxphotos-0.60.9-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.8-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.7-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.6-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.5-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.4-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.3-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.2-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.1-py3-none-any.whl.metadata (15 kB)
  Downloading osxphotos-0.60.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.6 MB/s eta 0:00:00
  Downloading osxphotos-0.59.3-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
  Downloading osxphotos-0.59.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
  Downloading osxphotos-0.59.1-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
  Downloading osxphotos-0.59.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
  Downloading osxphotos-0.58.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
  Downloading osxphotos-0.58.1-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.3 MB/s eta 0:00:00
  Downloading osxphotos-0.58.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.3 MB/s eta 0:00:00
  Downloading osxphotos-0.57.3-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.1 MB/s eta 0:00:00
  Downloading osxphotos-0.57.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.2 MB/s eta 0:00:00
  Downloading osxphotos-0.57.1-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.1 MB/s eta 0:00:00
  Downloading osxphotos-0.57.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.3 MB/s eta 0:00:00
  Downloading osxphotos-0.56.7-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.2 MB/s eta 0:00:00
  Downloading osxphotos-0.56.6-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.2 MB/s eta 0:00:00
  Downloading osxphotos-0.56.5-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.56.4-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.2 MB/s eta 0:00:00
  Downloading osxphotos-0.56.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.1 MB/s eta 0:00:00
  Downloading osxphotos-0.56.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.1 MB/s eta 0:00:00
  Downloading osxphotos-0.56.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.56.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.55.7-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.55.6-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.55.5-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.1 MB/s eta 0:00:00
  Downloading osxphotos-0.55.4-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.55.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.0 MB/s eta 0:00:00
  Downloading osxphotos-0.55.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.7 MB/s eta 0:00:00
  Downloading osxphotos-0.55.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.4 MB/s eta 0:00:00
  Downloading osxphotos-0.55.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 703.4 kB/s eta 0:00:00
  Downloading osxphotos-0.54.4-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 534.9 kB/s eta 0:00:00
  Downloading osxphotos-0.54.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 761.5 kB/s eta 0:00:00
  Downloading osxphotos-0.54.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.0 MB/s eta 0:00:00
  Downloading osxphotos-0.54.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.0 MB/s eta 0:00:00
  Downloading osxphotos-0.54.0-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.0 MB/s eta 0:00:00
  Downloading osxphotos-0.53.0-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 544.4 kB/s eta 0:00:00
  Downloading osxphotos-0.52.0-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.2 MB/s eta 0:00:00
  Downloading osxphotos-0.51.8-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.3 MB/s eta 0:00:00
Collecting osxmetadata<1.0.0,>=0.99.34 (from osxphotos)
  Downloading osxmetadata-0.99.38-py3-none-any.whl (39 kB)
Collecting pathvalidate<3.0.0,>=2.4.1 (from osxphotos)
  Downloading pathvalidate-2.5.2-py3-none-any.whl (20 kB)
Collecting photoscript<0.2.0,>=0.1.4 (from osxphotos)
  Downloading photoscript-0.1.6-py3-none-any.whl (20 kB)
Collecting pyobjc-core<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc-core-8.5.1.tar.gz (789 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 789.1/789.1 kB 1.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pyobjc-framework-AVFoundation<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc_framework_AVFoundation-8.5.1-cp36-abi3-macosx_11_0_universal2.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 388.4 kB/s eta 0:00:00
Collecting pyobjc-framework-AppleScriptKit<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc_framework_AppleScriptKit-8.5.1-py2.py3-none-any.whl (3.9 kB)
Collecting pyobjc-framework-AppleScriptObjC<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc_framework_AppleScriptObjC-8.5.1-py2.py3-none-any.whl (4.0 kB)
Collecting pyobjc-framework-Cocoa<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc-framework-Cocoa-8.5.1.tar.gz (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 3.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pyobjc-framework-CoreServices<9.0,>=7.2 (from osxphotos)
  Downloading pyobjc_framework_CoreServices-8.5.1-cp36-abi3-macosx_11_0_universal2.whl (29 kB)
Collecting pyobjc-framework-Metal<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc_framework_Metal-8.5.1-cp36-abi3-macosx_11_0_universal2.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.0/48.0 kB 284.1 kB/s eta 0:00:00
Collecting pyobjc-framework-Photos<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc_framework_Photos-8.5.1-cp36-abi3-macosx_11_0_universal2.whl (12 kB)
Collecting pyobjc-framework-Quartz<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc-framework-Quartz-8.5.1.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 3.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pyobjc-framework-Vision<9.0,>=7.3 (from osxphotos)
  Downloading pyobjc_framework_Vision-8.5.1-cp36-abi3-macosx_11_0_universal2.whl (13 kB)
Collecting pytimeparse2==1.4.0 (from osxphotos)
  Downloading pytimeparse2-1.4.0-py3-none-any.whl (5.2 kB)
Collecting rich<13.0.0,>=11.2.0 (from osxphotos)
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.5/237.5 kB 1.3 MB/s eta 0:00:00
Collecting shortuuid==1.0.9 (from osxphotos)
  Downloading shortuuid-1.0.9-py3-none-any.whl (9.4 kB)
Collecting textx<3.0.0,>=2.3.0 (from osxphotos)
  Downloading textX-2.3.0-py2.py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.8/72.8 kB 556.0 kB/s eta 0:00:00
Collecting wrapt<1.14.0,>=1.13.3 (from osxphotos)
  Downloading wrapt-1.13.3.tar.gz (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 320.4 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/expand.py", line 80, in __getattr__
          return next(
                 ^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/expand.py", line 81, in <genexpr>
          ast.literal_eval(value)
        File "/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py", line 112, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py", line 111, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py", line 85, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py", line 76, in _convert_num
          _raise_malformed_node(node)
        File "/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py", line 73, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x108433990>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/expand.py", line 192, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/expand.py", line 86, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/rhet/Library/Application Support/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/rhet/Library/Application Support/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/rhet/Library/Application Support/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 623, in parse_config_files
          setupcfg.parse_configuration(
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 475, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 592, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/expand.py", line 195, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-build-env-r_vhoztq/overlay/lib/python3.12/site-packages/setuptools/config/expand.py", line 215, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-install-cq59u0n_/wrapt_ecfc4d99732142ee9715e1e361c91ce9/src/wrapt/__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
        File "/private/var/folders/2h/89q0s6sd1y34cmp44_bmcf680000gn/T/pip-install-cq59u0n_/wrapt_ecfc4d99732142ee9715e1e361c91ce9/src/wrapt/decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py). Did you mean: 'formatargvalues'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</details>

**Comment by RhetTbull** [comment]
Why is pipx trying to install osxphotos-0.51.8-py3-none-any.whl (1.6 MB)

**Comment by RhetTbull** [comment]
Actually has nothing to do with wrapt. It's osxmetadata which was pinned to `python=">=3.8;<=3.12"` and for python > 3.12.0 this caused pip to find an old version of osxmetadata.

**Comment by nikravi** [comment]
hello

I have the same issue now in python3.13 on mac os Sequoia

```
Fatal error from pip prevented installation. Full pip output in file:
    /Users/nr/.local/pipx/logs/cmd_2024-10-11_11.43.57_pip_errors.log

pip seemed to fail to build package:
    wrapt<1.14.0,>=1.13.3

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ValueError: malformed node or string on line 2: <ast.Call object at 0x1046e3b90>
    AttributeError: wrapt has no attribute __version__
    ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py). Did you mean: 'formatargvalues'?
    error: metadata-generation-failed

Error installing osxphotos.
``` 

Please advice how this can be fixed, thank you!

**Comment by RhetTbull** [comment]
OSXPhotos has not been tested with 3.13 and does not claim to be compatible with 3.13. I will look at porting to 3.13 when time permits.
