### ISSUE TITLE
Catch malformed export database and instruct user how to fix it. (Or attempt repair in osxphotos)

### ISSUE THREAD

**Issue by mikekenyon99** [RhetTbull/osxphotos#1329]
** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

- If you installed with pipx: `pipx upgrade osxphotos`
- If you installed with pip: `pip install --upgrade osxphotos`
- If you installed the pre-built binary, download and install the latest [release](https://github.com/RhetTbull/osxphotos/releases)

**Describe the bug**
I run the software and it instantly crashes with the error log (attached).  

**To Reproduce**
1. What's the full command line you used with osxphotos?

osxphotos export /Users/mikekenyon/Library/CloudStorage/OneDrive-Personal/Pictures/"Camera Roll" --directory "{created.year}/{created.month}" --exiftool --keyword-template "{label}" --finder-tag-keywords --download-missing  --skip-original-if-edited --db /Volumes/"Extreme SSD"/"Photos Library.photoslibrary" --update --cleanup --skip-live

4. What was the error output?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Sonoma 14.1.2
 - osxphotos version: 0.66.0

**Additional context**

Please see the crash log here:
[osxphotos_crash.log](https://github.com/RhetTbull/osxphotos/files/13649274/osxphotos_crash.log)

**Comment by RhetTbull** [comment]
I don't know what happened but the export database which is used by osxphotos to maintain state between exports appears to be corrupt. Try deleting the file:

"/Users/mikekenyon/Library/CloudStorage/OneDrive-Personal/Pictures/Camera Roll/.osxphotos_export.db"

and trying again.

**Comment by mikekenyon99** [comment]
Ok - that will mean it will re upload etc..?  Guess there isn't much else I can do?

**Comment by RhetTbull** [comment]
Yeah, it's probably actually best to start over with a fresh export directory and let osxphotos re-export everything. I don't know what happened -- I've not seen that error before -- but it appears osxphotos is trying to open the export database which is malformed and causing the crash. Was this working before for you?

**Comment by RhetTbull** [comment]
Here's the actual error:

`sqlite3.DatabaseError: database disk image is malformed`

**Comment by mikekenyon99** [comment]
Yes, it's been working fine for many months actually - this is my first error.   Just seen that error message - not good.  I have quite a large export so it takes quite a while.  Oh well, it is what it is. 

Thanks for the quick response. 

Mike

**Comment by RhetTbull** [comment]
Before you do that, perhaps this is worth a try:

`sqlite3 "/Users/mikekenyon/Library/CloudStorage/OneDrive-Personal/Pictures/Camera Roll/.osxphotos_export.db" ".recover" | sqlite3 "/Users/mikekenyon/Library/CloudStorage/OneDrive-Personal/Pictures/Camera Roll/.osxphotos_export_new.db" `

If that works, then copy the new recovered database to the old database and start the export again.

**Comment by RhetTbull** [comment]
If the above command is successful, you would then run:

`cp "/Users/mikekenyon/Library/CloudStorage/OneDrive-Personal/Pictures/Camera Roll/.osxphotos_export_new.db"  "/Users/mikekenyon/Library/CloudStorage/OneDrive-Personal/Pictures/Camera Roll/.osxphotos_export.db" `

**Comment by mikekenyon99** [comment]
Now then good sir! That has worked :-) You need to put that in the Wiki as a possible fix for that error.  It did some "processing.." steps when I re-ran osxphotos but it's catching up now.  Will let you know if it completes successful. 

Mike

**Comment by RhetTbull** [comment]
Great! I'll catch that specific error and have osxphotos give a suggestion then also put in the docs.

**Comment by mikekenyon99** [comment]
All completed successfully :-) 

Cheers

Mike

**Comment by RhetTbull** [comment]
Add this to exportdb as `osxphotos exportdb --repair`

**Comment by RhetTbull** [comment]
Added `osxphotos exportdb --check` and `osxphotos exportdb --repeair` , will be released in v0.67.0

**Comment by RhetTbull** [comment]
@all-contributors please add @mikekenyon99 for ideas, bug
