### ISSUE TITLE
no such table: Z_METADATA

### ISSUE THREAD

**Issue by DeepYogurt** [RhetTbull/osxphotos#1343]
Am trying to work with a Photos library on a Mac Mini M2 Pro system that was updated on Ventura 13.6.3 version of Photos.app - the photos library is physically located on a Mac Pro 2013 system running High Sierra 13.6.1 on a HFS+ case sensitive volume that was originally created on a High Sierra version of Photos.app (version 3) and then remotely mounted on the Mac Mini Ventura system and then when Photos on Ventura tried to open it, it wanted to update it so that it became a version 8 photos library. The "update" process took 2-3 hours (the Photos library is about 900GB) and there were no errors during the update process. But when Photos.app tried to then open this "updated" photos library, it gets a -1 error and won't do anything with it now. Since the photos library has now been updated by Ventura, I can no longer use it on the High Sierra system, so am now trying to deal with a rather large photos library that can't be used either on High Sierra or on Ventura.

Apparently there is a problem with new versions of Photos on macOS that don't like photo libraries located on case-sensitive volumes, even though I've been using the High Sierra Photos.app with a case sensitive volume for years and years. I've contacted Apple and tried to confirm this fact but have not been seen where this is documented on any official Apple web page - does anyone know where this is documented, or is this really just a rumor?

So I came across osxphotos and am trying it out to see what I can find out about the updated photos library, and when I try, get the following when osxphotos tries to give me info about this photos library:

 ****### **_% ./osxphotos-arm info --library ./Bob\'s\ Photos.photoslibrary 
Loading library: ./Bob's Photos.photoslibrary
WARNING: Only tested on database versions [6000, 5001, 4025, 4016, 3301, 2622] You have database version=5002 which has not been tested
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:18                                                                                   │
│                                                                                                  │
│ in __call__:1157                                                                                 │
│                                                                                                  │
│ in main:1078                                                                                     │
│                                                                                                  │
│ in invoke:1688                                                                                   │
│                                                                                                  │
│ in invoke:1434                                                                                   │
│                                                                                                  │
│ in invoke:783                                                                                    │
│                                                                                                  │
│ in new_func:45                                                                                   │
│                                                                                                  │
│ in new_func:33                                                                                   │
│                                                                                                  │
│ in info:36                                                                                       │
│                                                                                                  │
│ in __init__:394                                                                                  │
│                                                                                                  │
│ in get_photos_version_from_model:107                                                             │
│                                                                                                  │
│ in get_model_version:88                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OperationalError: no such table: Z_METADATA
[2977] Failed to execute script 'cli' due to unhandled exception!
 %**_****

Anyone ever seen this Photos.app -1 error or know what it's really having a problem with?? I do have a TimeMachine backup of the original Photos library on the High Sierra system, so that's my fallback plan, but would really like to be able to use Photos.app on the Mac Mini system, as it's a lot faster than the High Sierra computer. Appreciate any suggestions, ideas, etc.

Here is the osxphotos version info (i tried both the arm and the x86 versions I downloaded this morning - both give the same error about missing Z_METADATA table):

**% ./osxphotos-x86 --version                                    
osxphotos, version 0.67.0
Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]
macOS 13.6.3, x86_64
% ./osxphotos-arm --version
osxphotos, version 0.67.0
Python 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]
macOS 13.6.3, arm64
 %**

Odd that the two different versions of the osxphotos program (I named them osxphotos-arm and osxphotos-x86) give different python version info - is that normal when using the ARM and X86 versions of the osxphotos program??

I was expecting to see a lot of info about the underlying photos library that had been updated by Photos.app on Ventura. By the way, got the same -1 error when this Mac Mini was running macOS version 13.6.1, and Apple asked me to update to the lastest 13.6.3, which I did and it made no difference.

Anyone have any idea why the missing "Z_METADATA" table happened or how to fix it or what the -1 really is all about? 

Thanks very much...

-bob

**Comment by RhetTbull** [comment]
It sounds like migration from the High Sierra to Ventura failed. `Z_METADATA` is a table that should be in the database for any Photos library from Catalina or newer. The osxphotos code found database version `5002` which indicates a Catalina+ database. It then needs to read `Z_METADATA` to find out which exact version of Photos created the library so it can use the correct schema. Yours is in a n "in between" state -- the migration updated the version to `5002` (High Sierra would have been most likely `3301` originally) -- but it did not create the Z_METADATA table. This is also why Photos cannot open the database. 

It is probably possible to patch the osxphotos code to get around this (but who knows what other inconsistencies we'd find if the database is in a partially migrated state. You said you had a Time Machine backup of the library -- is it current? If so, I recommend copying that library to an external drive formatted with APFS (and preferably an SSD drive) then attempting to do the conversion again with the 13.6.3  machine. That is far more likely to produce a good result than attempting to work around a corrupt database.

> Odd that the two different versions of the osxphotos program (I named them osxphotos-arm and osxphotos-x86) give different python version info - is that normal when using the ARM and X86 versions of the osxphotos program??

Yes. I build the images on 2 different machines that have different pythons installed. The preferred install approach is to use pipx per the instructions but the binaries are provided for those who don't want to do so.

**Comment by RhetTbull** [comment]
> Apparently there is a problem with new versions of Photos on macOS that don't like photo libraries located on case-sensitive volumes,...does anyone know where this is documented,

I don't know if this is documented but the Mac in general does not like case-sensitive file systems and I would avoid doing this in the future.

**Comment by DeepYogurt** [comment]
The reason for the case-sensitive file system is that the photos library was located on the same disk as a bunch of other stuff I use on many different systems. Like I mentioned, I've been using this case-sensitive setup on High Sierra version of Photos.app for years with absolutely no problems - and before that Sierra and Mountain Lion and Lion and even further back I think, as I've been taking digital photographs and keeping them on a Mac system since the early 2000's. This is not a bootable volume, just a place for a lot of misc stuff, from downloads collected over the years to various UNIX projects, to various media files (movies, music, etc) and many other things.

I've been a UNIX user since the 1970's, so case-sensitive filesystems are part of my "DNA" and I simply can't imagine life without them, even on my Mac systems. I understand some software will refuse to even install on case-sensitive volumes (like most/all of Adobe's programs) but for that case-insensitive stuff I use the boot disk usually or another case-insensitive disk for just those sorts of programs that need to live on case-insensitive volumes. 

In my opinion, I believe that the reason Adobe claims that their software doesn't work on case-sensitive volumes is because of sloppy programming practices on their part that would be a significant effort for them to repair and they "solve" the problem by simply forbidding people to install their software on case-sensitive volumes - many years ago I've seen crash reports from various Adobe software apps (e.g. Photoshop) that I've experimented with on case-sensitive volumes, that very clearly demonstrate programs that try to do things like compare a filename on the disk named "ABC.jpg" to a variable that contains the value "abc.jpg" and on a case-insensitve file system that sort of thing can work, but on a case-sensitive file system will, of course, fail. So, rather than fix the real problem by cleaning up their code, they have perpetuated the "myth' that case-sensitive volumes are the problem, but I'm afraid I couldn't disagree more. UNIX was born with case-sensitive files being no big deal and I couldn't agree more. Perhaps a few Adobe programmers now work at Apple on Photos and they've adopted this philosophy rather than be more careful when writing software?

Given your comments, I'm a bit puzzled why the original Ventura Photos.app invocation that updated the High Sierra photos library didn't do a better job at complaining that the update process failed in a rather significant way. I will try and talk to Apple support now being aware of this important information and see what they have to suggest as to what might have happened. If I find out, will update these notes to let folks know what they have to say/suggest.

Thanks very much for your insights, as this gives me a good reason to restore the original High Sierra photos library folder from Time Machine and get it working again rather than pursue what seems to have been a faulty conversion, and then try Ventura Photos.app on a separate photo library and leave my High Sierra photo library alone and untouched by newer macOS versions and avoid this whole mess in the future - hopefully ;-)

Couldn't have asked for a better Chrismas present that this great "osxphotos" program - thanks so much for all the work, you and everyone else has done for this project, and best wishes for the holidays and the coming year. Open Source software is, without question, one of the best ideas to have been happened to everyone who uses computers. Thanks to everyone who makes this a better world because of their efforts on this project and all the others!!!

-bob

**Comment by RhetTbull** [comment]
> UNIX was born with case-sensitive files being no big deal and I couldn't agree more. 

But macOS is not unix. It is based off BSD but has significantly diverged and Apple has made a bunch of macOS specific design choices (like defaulting to a case-insensitive file system). I really think you'll be much better off moving the library to an APFS disk and trying to convert again -- who knows what state the corrupt library is in and even if you could get it working, it would be hard to know if there was anything missing.  (Though osxphotos could be used to write a script to compare the two).

For what it's worth, when exporting from Photos, osxphotos will assume that files are case-insensitive as this is the default for most Mac users and targeting the expected use case is a better design choice that targeting an edge case. So if you had two photos that were getting exported to the same directory: `IMG_123.jpg` and `img_1234.JPG`, osxphotos will first normalize unicode then convert to lower case and compare. In this case, you'd end up with `IMG_1234.jpg` and `img_1234 (1).JPG` as the exported files even if exporting to a case-sensitive file system. Working around the case-sensitive edge case just complicates the code for very little benefit for most users. The original case will be preserved in the created file names but as they both compare to the same name when converted to lower case, one name will be incremented to deconflict with the other.

> Couldn't have asked for a better Chrismas present than this great "osxphotos" program 

Thanks! I hope it's useful to you!

Cheers and Merry Christmas!
Rhet

**Comment by DeepYogurt** [comment]
Well, I got osxphotos installed on High Sierra and Ventura so that I can dig into the innards of my Photos libraries and what a cool tool!! Thanks again for all your effort in creating and maintaining osxphotos. Definately on my list of favorites!!

-bob

**Comment by RhetTbull** [comment]
@DeepYogurt  thanks for the feedback! Glad you find it useful!
