### ISSUE TITLE
Star ratings from iPhoto should go to the XMP:Rating field

### ISSUE THREAD

**Issue by mlevin77** [RhetTbull/osxphotos#1353]
From our email discussion:

> given that there's a field called XMP:Rating, won't it work to convert the star ratings from iPhoto to the XMP:Rating field?
 
Yes that would work. The iPhoto code provides a rating property:
 
    @property
    def rating(self) -> int:
        """Rating of photo as int from 0 to 5"""
        return self._db._db_photos[self._uuid]["rating"]
 
Please open an issue on GitHub to add this. Will be a 2 line fix but need to add a test case, etc.

**Comment by RhetTbull** [comment]
- Will need to figure out how to handle rating for Photos. Current implementation of PhotoInfo.rating returns 5 if favorite else 0. But this would make `--favorite-rating ` actually do nothing as rating would always get written if favorite. Could change implementation of rating to return None for Photos or just get rid of `--favorite-rating`

```python
   @property
    def rating(self) -> int:
        """Star rating of photo as int from 0 to 5; for iPhoto, returns star rating; for Photos, returns 5 if favorite, else 0"""
        return 5 if self.favorite else 0
```

**Comment by RhetTbull** [comment]
@all-contributors please add @mlevin77 for ideas

**Comment by RhetTbull** [comment]
Fixed in current branch. Will be in next release.
