### ISSUE TITLE
ismissing not always correct for Photos 5

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#136]
Editing raw image can result in `'localAvailability': -32768` which causes ismissing to be reported as True even if image is not missing.

**Comment by mccarverone** [comment]
Having this issue with many .MOV. These files do not belong on iCloud Photo Library or any shared album. They result missing while being played locally with no issue. Photo 5.0 (151.19.150). Let me know if I can help with the debug. Regards

**Comment by RhetTbull** [comment]
@mccarverone some additional debug data would be helpful.  Try the following:

`osxphotos query --missing`

This will print out a list of all photos reported as missing.  Find one of the .MOV files you know is missing and locate it's UUID (unique identifier) which is a string of seemingly random characters that looks like `AAEF4330-9B36-4CB1-88F6-D68048B36D04`

If you know the name of one of these movies you can do this:
`osxphotos query --missing | grep -i name_of_file.MOV`

Then do the following:

`osxphotos debug-dump --dump photos --uuid AAEF4330-9B36-4CB1-88F6-D68048B36D04 > debug.txt`

(replace AAEF4330-9B... with the UUID you copied above)

Then either send [me](mailto:rturnbull+git@gmail.com) the file or post the contents here.

**Comment by RhetTbull** [comment]
v0.29.14 seems to fix this
