### ISSUE TITLE
Add option to export altered (rotated, etc.) versions of photos from iPhoto

### ISSUE THREAD

**Issue by mlevin77** [RhetTbull/osxphotos#1396]
Right now, it exports the original photos.  iPhoto offers ability to rotate (and otherwise edit, but rotation is the most important one) the photos. Apparently they are stored separately, and not actually over-writing the original files. I'd love there to be an option to export the rotated ones, instead of the originals.

**Comment by RhetTbull** [comment]
If a photo is rotated in iPhoto the following happens:

photo.hasadjustments is False (assuming no previous adjustments)
photo.width, photo.height are adjusted accordingly
photo.orientation does not change (is 0 for iPhoto)
photo._info["rotation"] is set to the degrees rotated (e.g. 90 deg counter clockwise = 270]

**Comment by RhetTbull** [comment]
Implemented as `--fix-orientation`. Need to add tests.

**Comment by RhetTbull** [comment]
This is included in release v0.67.4
