### ISSUE TITLE
Various issues in exporting fotos to network folder

### ISSUE THREAD

**Issue by Checole** [RhetTbull/osxphotos#1405]
Dear RheTbull, 

after being in contact a long time ago, I retried exporting fotos from apple databases.
Also I have looked at other components to exclude them.

I tag fotos in apple fotos on a MacBook M2. I create 2 folders and same name album in each
-one with my name (importing the stuff from my iPhone)
-one with the name of my wife (importing the stuff from her iPhone)

I managed today to export some 1000 photos from the second album. I needed around 7 attempts as the execution got stuck and I had to abort the run. Presumably this problem occurs when the MacBook's smb connectivity gets to sleep. But I can see that I need to reclick on a folder in order to reconnect in the finder. However, in the last run the outstaniding some 1000 fotos from a total of 13.000 fotos were exported on the drive.

After that using the exact same command for the first folder / album to a neighbored folder on the share does not run.

Update:
copied the apple fotos db, deleted around 13.000 fotos, and export worked

 

** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

- If you installed with pipx: `pipx upgrade osxphotos`
- If you installed with pip: `pip install --upgrade osxphotos`
- If you installed the pre-built binary, download and install the latest [release](https://github.com/RhetTbull/osxphotos/releases)

**Describe the bug**

**To Reproduce**
1. What' the full command line you used with osxphotos?
2. What was the error output?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS]
 - osxphotos version (`osxphotos --version`)

**Additional context**

**Comment by Checole** [comment]
copied the apple fotos db, deleted around 13.000 fotos, and export worked

**Comment by RhetTbull** [comment]
Glad you got it working. This sounds like an issue with the network drive and that's beyond the scope of osxphotos. osxphotos expects the drive to be connected and reliable. It does include options like `--ramdb` and `--retry 3` that are useful if using a flaky drive but beyond that, you need to ensure your network connection is reliable.
