### ISSUE TITLE
Photos imported to Photos app not seen by 0.67.7

### ISSUE THREAD

**Issue by markswanusa** [RhetTbull/osxphotos#1451]
**% osxphotos version**
...
You have the latest version of osxphotos: 0.67.7

**Describe the bug**
I took several photos on my iPhone and air-dropped them to my MacBook Air then imported to Photos.  I can see the photos in Photos and have placed them into albums.  When running osxphotos to query or export, these photos don't seem to exist.  I imported some other photos via the normal "plug in a cable" method and these are not seen by osxphotos either.

**To Reproduce**
Take pics on iPhone
Air drop them to a Mac and import to Photos or connect a cable and import to Photos
The pics show up in "Library" and in albums that I created.

osxphotos export --dry-run --verbose --update --cleanup --skip-edited --skip-live --directory '{folder_album}' --library '/Users/mark/Pictures/Photos Library.photoslibrary' /Users/mark/Pictures/digiKam/main

does not export any of the newly imported pics

or

osxphotos query --library ~/Pictures/Photos\ Library.photoslibrary

does not show that any of those newly imported pics exist.

**Desktop (please complete the following information):**
 - OS: Sonoma 14.2.1

**Comment by RhetTbull** [comment]
Very curious. I cannot think of anything that would cause this. Select one of the photos in Photos (in the main "Library" view) and try `osxphotos query --selected`.

Have you previously exported with osxphotos from this library? Are other photos correctly exported?

**Comment by markswanusa** [comment]
OMG!  User error.  I had made a copy of my main library when doing repairs and experimentation and I had one of those copies open.  

I am so sorry.  Once I pointed at the correct library, everything worked just fine.  

Mark
