### ISSUE TITLE
Edited photo is exported without the original

### ISSUE THREAD

**Issue by odedia** [RhetTbull/osxphotos#1500]
While exporting edited images, I see the _EDITED.jpeg file, its xmp file and the original file's XMP file - in my case it's a Nikon .NEF RAW file.
However, the RAW file itself is not present in the export.

```
osxphotos export /Users/odedia/Pictures/OSXPhotos  --directory "{created.year}/{created.year}-{created.mm}-{created.mm}" --retry 3 --sidecar XMP --sidecar-drop-ext --keyword-template "{label}"
```
I also verified without ` --sidecar-drop-ext`, same issue.

Expected: _edited JPEG and the original NEF should be in the same folder along with their XMP files.
Actual: _edited JPEG and both XMP files are shown, but without the NEF.

**Comment by odedia** [comment]
Thanks for the fast response!
```
macOS version: Sonoma.
> osxphotos --version
osxphotos, version 0.67.10
Python 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:39) [Clang 13.0.0 (clang-1300.0.29.30)]
macOS 14.4.1, x86_64
```
I think I may have realized what the issue is, I do use iCloud (for now) but I thought I had all originals downloaded. My library has ~80,000 images, but 4,000 seems to still try to download in the background. I may have noticed those in particular.

Here is an image that doesn't have the original NEF:

![image](https://github.com/RhetTbull/osxphotos/assets/2992180/e475d398-9ce5-43f5-84e8-db77dc7e3eaa)

After editing it in Apple Photos (forcing it to download, I guess), I now do see it after running again:

![image](https://github.com/RhetTbull/osxphotos/assets/2992180/d4e793c7-7ab6-4309-8de9-09bc866f621b)

Perhaps it would make sense to warn if an original is not available? I know there's a parameter to download from iCloud if it doesn't exist but I think that makes sense to be the default since it's a rather hidden error.

Thanks again for the excellent program, I plan to use it to migrate from iCloud PhotoPrism over time.

**Comment by RhetTbull** [comment]
> Perhaps it would make sense to warn if an original is not available? 

If you use the `--verbose` flag, then OSXPhotos will tell you if an item is missing:

```
Exporting IMG_0090.JPG (44972598-55DB-410C-94E6-B9928BB6BBF9.JPG) (130/39924)
Skipping missing original photo IMG_0090.JPG (44972598-55DB-410C-94E6-B9928BB6BBF9)
```

This message prints out the UUID (unique ID) for the photo which Photos (and OSXPhotos) use internally to track each item. This allows you to use additional debugging features. For example, `osxphotos show UUID` will display the item in Photos.  `osxphotos debug-dump --dump photos --uuid UUID` will output a bunch of debug info about the specific item. But for a large library, the verbose mode prints A LOT of information and some users don't like this so OSXPhotos is quiet unless told not to be.

Also, it prints a summary at the conclusion of export that looks like this:

`Processed: 39924 photos, exported: 105, missing: 50, error: 0, limit: 100/100 exported`

Which shows you the number of missing items and how many errors there were. 

Personally, I always use the `--report photos_export_{today}.csv` option to output a CSV report so I can see what was missing, what the errors were etc. The `{today}` in the name uses the OSXPhotos template system to print today's date as part of the report name, for example, `photos_export_2024-04-07.csv`. I also use `--verbose` to see the output in the Terminal. 

For your export, you can generate a report if you didn't use the `--report` option, using this command:

`osxphotos exportdb /Users/odedia/Pictures/OSXPhotos --report report.csv 0`

This creates a `report.csv` file for the last export. To get a report for the export before that, count backwards, so it would be `osxphotos exportdb /Users/odedia/Pictures/OSXPhotos --report report.csv -1` ; the one before that would be `-2`, and so on. The data is stored in the export database for the last 10 exports.

>  I know there's a parameter to download from iCloud if it doesn't exist but I think that makes sense to be the default since it's a rather hidden error.

Not everyone uses iCloud in which case this could cause an error if a photo was missing on disk (perhaps the user is using a referenced library and deleted the image, etc). OSXPhotos also runs on linux and this feature wouldn't work. (I think that's a strange use case but there are users that run the export from a linux system connected to their Mac).  Additionally, OSXPhotos can run against non-default libraries using the `--library` feature and many people use multiple libraries. This feature will only work on the default library. 

OSXPhotos is optimized for use with libraries that use the "store originals on this Mac" setting but provides `--download-missing` as an option for those that need it. Using this option also requires extra permissions from the user (which your Terminal will prompt for) so OSXPhotos doesn't ask for these if not needed (and if the option is not used). Selecting defaults is always a difficult design trade off. In this case, I've added the option to force a download if user needs it and alert the user (via the verbose message or the report or the export summary) that something was missing.

**Comment by odedia** [comment]
That's a great summary. Thanks again!
