### ISSUE TITLE
Editing with Photomator breaks query command JSON output

### ISSUE THREAD

**Issue by kitschpatrol** [RhetTbull/osxphotos#1518]
Thanks for this fantastic tool!

This is a bit of an edge case, and it's likely Photomator is doing something funky here, but I noticed that Photos libraries containing images edited in specific ways by Photomator can break `osxphotos query --json` output.

I've attached a [single-photo test library](https://github.com/RhetTbull/osxphotos/files/15018890/PhotomatorTest.photoslibrary.zip) that triggers the bug.

The error seems to come from parsing adjustments metadata added to the library when the "Super Resolution" feature is used in Photomator.

Sepcifically, [`adjustmentsinfo.py:115`](https://github.com/RhetTbull/osxphotos/blob/main/osxphotos/adjustmentsinfo.py#L115):

```py
return self._adjustments["adjustments"] if self._adjustments else []
```

Throws:

```
TypeError: list indices must be integers or slices, not str
```

Inspecting `self._adjustments` of the offending image shows the following:

```json
[
  1,
  {
    "s": {
      "v": 2,
      "c": {
        "o": "14.4.1",
        "v": "3.3.5",
        "h": "ea636c8",
        "u": "public.jpeg",
        "r": "Photomator",
        "d": "Mac15,10",
        "t": 735096853.71553
      }
    },
    "c": [
      3,
      {
        "c": "73DF27EA-0F00-4AB1-AEB1-407E802BFB3E",
        "super": [
          3,
          {
            "n": "404D022B-7D4C-45C5-977B-8B74E7E93E4D_4_5005_c",
            "i": "85C8AA14-8877-4C2C-8683-FDE7BF8B32B4",
            "u": "com.pixelmatorteam.pixelmator-photo-edit.document.binary",
            "e": true,
            "h": "85C8AA14",
            "v": 2,
            "w": [
              1,
              {
                "v": "3.3.5",
                "o": "14.4.1",
                "d": "Mac15,10",
                "a": "photomator",
                "b": "ea636c8",
                "r": 16230,
                "p": "macOS"
              }
            ],
            "l": "local"
          }
        ]
      }
    ]
  }
]
```

Seems like the expected `"adjustments"` key is missing.

**To Reproduce from scratch:**
1. Open your library with Photomator
2. Select an image
3. Tools → Open Edit Tools
4. Tools → Super Resolution
5. Tools → Close Edit Tools
6. Close Photomator
7. Run `osxphotos query --json`

**To Reproduce with the [attached sample library](https://github.com/RhetTbull/osxphotos/files/15018890/PhotomatorTest.photoslibrary.zip):**
1. `osxphotos query --library "Path/To/PhotomatorTest.photoslibrary" --json`

**Expected behavior:**
Normal JSON photo info output.

Running the same command _without_ the `--json` flag does not trigger the error and produces normal output.

**Desktop Mac:**
osxphotos, version 0.67.10
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
macOS 14.4.1, arm64

**Comment by RhetTbull** [comment]
Thanks for the detailed report and test library. This will be helpful for debugging this! I'll take a look as soon as I have chance.

@all-contributors please add @kitschpatrol for bug

**Comment by kitschpatrol** [comment]
Thank you.

As a work-around for now I've patched extra `TypeError` checks in `adjustmentsinfo.py`, so that the (currently) un-parsable Photomator adjustment metadata is ignored.

I can see how supporting every possible adjustment data format would be out of scope for this tool, so maybe this approach makes sense? Or maybe it would better to indicate that data was present but unparsable by some means other than empty values?

**Comment by RhetTbull** [comment]
> I can see how supporting every possible adjustment data format would be out of scope for this tool, so maybe this approach makes sense? Or maybe it would better to indicate that data was present but unparsable by some means other than empty values?

Yes, it's not possible to parse every format that an external editor might use. It might be best just to log a warning and return None or an empty dictionary. I'll take a look at the code and see what makes sense.

**Comment by RhetTbull** [comment]
This is fixed in main and will be included in next release
