### ISSUE TITLE
Add ability to export only original or edited

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#159]
CLI export command currently exports both original and edited version unless --skip-edited flag is enabled in which case only original is exported.  Some users want to export either the original (if no edited version) or edited (if edited version exists) but not both.  Add something like:
`--skip-original-if-edited` or `--latest` flag to enable this.

**Comment by ihsanturk** [comment]
I created a workaround script to remove originals if there are their edited versions: https://gist.github.com/ihsanturk/b5148e3107d8077a597cb7159b6c2ac2

**Comment by RhetTbull** [comment]
Added in v0.34.0

**Comment by garz75** [comment]
Thank you @RhetTbull for adding this option! Seems to work as advertised ;-)
