### ISSUE TITLE
Usability question: how do I get all photos and iterate over them? 

### ISSUE THREAD

**Issue by sg-s** [RhetTbull/osxphotos#1596]
Apologies for the noob question, but I've read the manual and played around with the CLI and I can't seem to figure this out.

What I want to do:

- get IDs of all photos
- iterate over all IDs, fetching each photos
- modify caption by ID

I'm basically stuck at the first step, and don't see a way to list all photos

**Comment by ljen** [comment]
Hey,

the Python API will help you. Take a look at the first example how to read all Photos.
https://github.com/RhetTbull/osxphotos/blob/main/API_README.md

**Comment by RhetTbull** [comment]
Hi @sg-s are you interested in writing python code to do this or using CLI tools? If the latter, what scripting skills do you have? 

From the CLI, you can get the ID of all assets using something like this which prints a CSV of uuid, filename:

`osxphotos query --field uuid "{uuid}" --field name "{photo.original_filename}"`

You can use the `osxphotos batch-edit` to edit the captions (descriptions) of selected photos. See `osxphotos help batch-edit`

If using a python script, see [this example](https://github.com/RhetTbull/osxphotos/blob/main/examples/cli_example_1.py) which creates a CLI that iterates over photos. See the full [API docs](https://github.com/RhetTbull/osxphotos/blob/main/API_README.md) for more info. To edit the photo, you'll need to use [photoscript](https://github.com/RhetTbull/PhotoScript). Reference this code in `batch-edit`:

https://github.com/RhetTbull/osxphotos/blob/39f16e40cedcfe5de98f28e414dd5ae7fa9136bd/osxphotos/cli/batch_edit.py#L293-L320

it's important to note that osxphotos alone cannot edit the Photos library or any assets in the library. osxphotos is primarily a tool for reading the library. To make changes you'll need to use [PhotoScript](https://github.com/RhetTbull/PhotoScript), a companion project that provides a Python interface to the Photos AppleScript interface. Alternatively you could just use AppleScript but that's left as a exercise for the reader. For example, the following will loop through all the photos in the library and adjust the description (caption) without using osxphotos, just photoscript:

```python
"""Loop through all photos in the Photos library and adjust the caption (description)"""

import photoscript

def main():
    photolibrary = photoscript.PhotosLibrary()
    print("Loading photos...")
    for photo in photolibrary.photos():
        uuid = photo.uuid
        old_description = photo.description
        print(f"Photo: {uuid} {photo.filename}: {old_description}")
        # set new description
        #photo.description = f"New description for {uuid}"


if __name__ == "__main__":
    main()

```

Also note that scripts using osxphotos (as in the CLI example above) or PhotoScript (as in the code directly above) can be run with osxphotos via `osxphotos run script.py`.  This may be more convenient than installing python and using pip to install the right libraries.

**Comment by sg-s** [comment]
thank you so much!

this is sufficient for my needs:

```python
for photo in photosdb.photos():
    print(photo.uuid)
```

i'm closing this for now
