### ISSUE TITLE
Comma in album name during import generates SyntaxError: None:1:15: Expected '{' or EOF

### ISSUE THREAD

**Issue by mpr90** [RhetTbull/osxphotos#1599]
osxphotos version 0.68.1

When importing photos using ```osxphotos import``` having a comma in the name of the album into which to import will cause an error as shown in the command line/output below:

```osxphotos import images/2014\ Vancouver,\ Summer/P1020237.JPG --album "2014 Vancouver, Summer" --check```

> Usage: osxphotos import [OPTIONS] [FILES_OR_DIRS]...
> Try 'osxphotos import -h' for help.
> Error: Invalid value for '--album' / '-a': SyntaxError: None:1:15: Expected '{' or EOF => ' Vancouver*, Summer'

If I remove the comma from the album name, then this command executes correctly as expected.

**Comment by RhetTbull** [comment]
The album name is an [OSXPhotos template](https://rhettbull.github.io/osxphotos/template_help.html) and in the OSXPhotos template language, comma is a reserved symbol. To include a comma in the album name (or any other template), use `{comma}`.  For example, `Vancouver{comma} Summer`.

**Comment by mpr90** [comment]
Thanks for the feedback. My bad for filing a bug - I did *try* looking through the docs before doing so... ;-)

**Comment by RhetTbull** [comment]
No worries. The error message isn't very helpful. Unfortunately it is generated by the parser I use for the template system and I don't have much control over it. I'll look into adding a more descriptive suggestion when the parsing error is generated.
