### ISSUE TITLE
macOS 15 timewarp --pull-exif: no such table: Z_31ASSETS

### ISSUE THREAD

**Issue by lasjoe** [RhetTbull/osxphotos#1613]
On the latest beta 3 of macOS 15 the following error appears when trying to execute 

`osxphotos timewarp --pull-exif`

```osxphotos crash log
Created: 2024-07-13 19:20:04.127053
osxphotos version: 0.68.2
Platform: macOS-15.0-arm64-arm-64bit
Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.argv: ['/Users//.local/bin/osxphotos', 'timewarp', '--pull-exif']
CRASH_DATA:
locals: {'date': None, 'date_delta': None, 'time': None, 'time_delta': None, 'timezone': None, 'date_added': None, 'date_added_from_photo': False, 'inspect': False, 'compare_exif': False, 'push_exif': False, 'pull_exif': True, 'function': None, 'match_time': False, 'use_file_time': False, 'add_to_album': None, 'exiftool_path': None, 'verbose_flag': 0, 'library': None, 'theme': None, 'parse_date': None, 'plain': False, 'timestamp': False, 'force': False}
osxphotos version: 0.68.2
Error: no such table: Z_31ASSETS
Traceback (most recent call last):
  File "/Users//.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/crash_reporter.py", line 79, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users//.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/timewarp.py", line 648, in timewarp
    exif_updater = ExifDateTimeUpdater(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users//.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/exif_datetime_updater.py", line 39, in __init__
    self.db = PhotosDB(self.library_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 419, in __init__
    self._process_database5()
  File "/Users//.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 1832, in _process_database5
    c.execute(
sqlite3.OperationalError: no such table: Z_31ASSETS
```

**Comment by RhetTbull** [comment]
macOS 15 is not officially supported yet. The first beta worked but Apple keeps changing things.

**Comment by mybizgeek** [comment]
@RhetTbull I'm getting a similar error on MacOS 14.6. Was working fine on 14.5.

```
osxphotos crash log
Created: 2024-08-01 15:43:26.501718
osxphotos version: 0.68.2
Platform: macOS-14.6-arm64-arm-64bit
Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.argv: ['/Users/user/.local/bin/osxphotos', 'export', '--album', 'Family Photos', '/Users/user/Backups/iCloud Photo Backups/Family Photos', '--directory', '{created.year}', '--filename', '{created.mm}_{created.dd}_{created.hour}{created.min}{created.sec}', '--update', '--cleanup']
CRASH_DATA:
locals: {'dest': '/Users/user/Backups/iCloud Photo Backups/Family Photos', 'db': None, 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': ('Family Photos',), 'album_keyword': False, 'alt_db': None, 'alt_copy': False, 'append': False, 'fix_orientation': False, 'beta': False, 'burst': False, 'checkpoint': None, 'cleanup': True, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'crash_after': None, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'directory': '{created.year}', 'download_missing': False, 'dry_run': False, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': False, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': '{created.mm}_{created.dd}_{created.hour}{created.min}{created.sec}', 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_exportdb': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': None, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_exportdb': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_edited': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': False, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_command_error': None, 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': None, 'save_config': None, 'screenshot': False, 'selfie': False, 'shared': False, 'export_aae': False, 'sidecar': (), 'sidecar_drop_ext': False, 'sidecar_template': (), 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid': (), 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': False, 'update': True, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose_flag': 0, 'xattr_template': (), 'year': (), 'syndicated': False, 'not_syndicated': False, 'saved_to_library': False, 'not_saved_to_library': False, 'shared_moment': False, 'not_shared_moment': False, 'shared_library': False, 'not_shared_library': False, 'selected': False, 'ctx': <click.core.Context object at 0x11113ce60>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x100942b70>}
osxphotos version: 0.68.2
Error: no such table: Z_28ASSETS
Traceback (most recent call last):
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/crash_reporter.py", line 79, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/export.py", line 1115, in export
    return_code = export_cli(**locals())
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/export.py", line 1866, in export_cli
    photosdb = osxphotos.PhotosDB(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 419, in __init__
    self._process_database5()
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 1832, in _process_database5
    c.execute(
sqlite3.OperationalError: no such table: Z_28ASSETS
```

**Comment by RhetTbull** [comment]
@mybizgeek yeah, Apple changed the schema again. Working on a fix that will address both 14.6 and 15.0

**Comment by mybizgeek** [comment]
> @mybizgeek yeah, Apple changed the schema again. Working on a fix that will address both 14.6 and 15.0

Thanks @RhetTbull, much appreciated!

**Comment by RhetTbull** [comment]
Release [v0.68.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.68.3) should restore functionality for Sequoia beta and macOS 14.6 however I don't have access to these to test. Please let me know if it works or if you encounter any issues.

**Comment by mybizgeek** [comment]
`osxphotos crash log
Created: 2024-08-04 10:29:46.786055
osxphotos version: 0.68.3
Platform: macOS-14.6-arm64-arm-64bit
Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.argv: ['/Users/user/.local/bin/osxphotos', 'export', '--not-in-album', '/Users/user/Backups/iCloud Photo Backups/Photo Library', '--directory', '{created.year}', '--filename', '{created.mm}_{created.dd}_{created.hour}{created.min}{created.sec}', '--update', '--cleanup']
CRASH_DATA:
locals: {'dest': '/Users/user/Backups/iCloud Photo Backups/Photo Library', 'db': None, 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': False, 'alt_db': None, 'alt_copy': False, 'append': False, 'fix_orientation': False, 'beta': False, 'burst': False, 'checkpoint': None, 'cleanup': True, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'crash_after': None, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'directory': '{created.year}', 'download_missing': False, 'dry_run': False, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': False, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': '{created.mm}_{created.dd}_{created.hour}{created.min}{created.sec}', 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_exportdb': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': None, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_exportdb': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_edited': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': True, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_screen_recording': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': False, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_command_error': None, 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': None, 'save_config': None, 'screenshot': False, 'screen_recording': False, 'selfie': False, 'shared': False, 'export_aae': False, 'sidecar': (), 'sidecar_drop_ext': False, 'sidecar_template': (), 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid': (), 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': False, 'update': True, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose_flag': 0, 'xattr_template': (), 'year': (), 'syndicated': False, 'not_syndicated': False, 'saved_to_library': False, 'not_saved_to_library': False, 'shared_moment': False, 'not_shared_moment': False, 'shared_library': False, 'not_shared_library': False, 'selected': False, 'ctx': <click.core.Context object at 0x10bba21b0>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x10bbfbd40>}
osxphotos version: 0.68.3
Error: no such column: Z_1KEYWORDS.Z_40KEYWORDS
Traceback (most recent call last):
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/crash_reporter.py", line 79, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/export.py", line 1119, in export
    return_code = export_cli(**locals())
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/export.py", line 1878, in export_cli
    photosdb = osxphotos.PhotosDB(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 419, in __init__
    self._process_database5()
  File "/Users/user/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 1951, in _process_database5
    c.execute(
sqlite3.OperationalError: no such column: Z_1KEYWORDS.Z_40KEYWORDS
`

@RhetTbull getting a different error now

**Comment by RhetTbull** [comment]
Ugh...Will take a look.

**Comment by oPromessa** [comment]
> Release v0.68.3 should restore functionality for Sequoia beta and macOS 14.6 however I don't have access to these to test. Please let me know if it works or if you encounter any issues.

Sorry. On Sonoma 14.6 osxphotos I get the same error on Z_40KEYWORDS

do you want me to pick a test library from tests/ folder and upgrade it and upload the library to a branch on either your or my fork of osxphotos ?

**Comment by RhetTbull** [comment]
Yes please that would be very helpful. Use the 14.0 library and upgrade to 14.6. You can send a link to osxphotos.py@gmail.com

**Comment by oPromessa** [comment]
Sorry for the delay. [Check this link with the updated 14.6 branch](https://github.com/oPromessa/osxphotos/tree/sonoma14-6)

**Comment by lasjoe** [comment]
Thanks for the update, on Sequoia I'm now getting

```sqlite3.OperationalError: no such column: Z_1KEYWORDS.Z_48KEYWORDS```

**Comment by RhetTbull** [comment]
@oPromessa sorry I wasn't clear. I'll still need the 14.0 library left as is for testing the older code. What I need is a *copy* of the 14.0 library (renamed to 14.6) and updated to 14.6 so I can modify the code and run tests against the modified library.

**Comment by oPromessa** [comment]
Got it. Let me work on it. 

Is over 100MB so there are some uploading restrictions on GitHub Desktop. Will work thru it.

**Comment by oPromessa** [comment]
> Yes please that would be very helpful. Use the 14.0 library and upgrade to 14.6. You can send a link to [osxphotos.py@gmail.com](mailto:osxphotos.py@gmail.com)

Dropped you a link to a zip file, via email. Hope it works!

**Comment by RhetTbull** [comment]
If someone with access to the latest macOS 15.0 beta could download [this test Photos library](https://www.dropbox.com/scl/fi/692pq9v8sgf817fwpgoxr/Test-15.0.0.photoslibrary.zip?rlkey=mqxs2yp9kvxyffqjrnt5a1b1b&st=hhbb0hhw&dl=0) and open it in Photos then compress it and send it back to me via osxphotos.py@gmail.com, that would be very helpful for testing.

**Comment by lasjoe** [comment]
@RhetTbull  I've sent library opened in 15.1 (already updated from 15.0 to 15.1) to osxphotos.py@gmail.com, hope that helps. Thanks.

**Comment by RhetTbull** [comment]
Thank you @lasjoe 

@all-contributors please add @lasjoe for data

**Comment by lasjoe** [comment]
Thanks @RhetTbull all good on macOS 15.1!
