### ISSUE TITLE
Album with unknown kind "1500" (Photos.app 5.0)

### ISSUE THREAD

**Issue by garz75** [RhetTbull/osxphotos#169]
Hello, 
Something weird happened while trying to export an album  created recently:
```
BarneyStinson:~/Desktop/out> ls -l
total 51216
-rw-r--r--    1 fgarzon  staff   9039354 Jun 19 15:32 debug.txt
-rw-r--r--    1 fgarzon  staff  16511987 Jun 19 15:31 osxphotos.dump
BarneyStinson:~/Desktop/out> osxphotos export .  --album "2000-07 Noces de diamant Pepe" --directory "{album}"  --person-keyword --keyword-template "{label}"   --exiftool  --filename "{created.strftime,%Y-%m-%d-%H%M%S}"
Using last opened Photos library: /Users/fgarzon/Pictures/Bibliothèque Photos.photoslibrary
Exporting 3 photos to ....
  [####################################]  100%
Exported: 6 photos
Elapsed time: 1.686 seconds
BarneyStinson:~/Desktop/out> ls -l
total 51216
drwxr-xr-x  5 fgarzon  staff       160 Jun 19 15:42 2000-07 Noces de diamant Pepe
drwxr-xr-x  5 fgarzon  staff       160 Jun 19 15:42 268565486
-rw-r--r--  1 fgarzon  staff   9039354 Jun 19 15:32 debug.txt
-rw-r--r--  1 fgarzon  staff  16511987 Jun 19 15:31 osxphotos.dump
```
I was surprised to have 2 directories created instead of 1 (the 3 photos in this album are in only one album): there was this weird 268565486 directory created. this album is not visible in the Photos app but "exists" in the Photos db, here it is as seen in the `osxphotos debug-dump --dump albums` output:
```
 'AC825C13-4DD4-4D54-B509-1FF1F4201B0E': {'_uuid': 'AC825C13-4DD4-4D54-B509-1FF1F4201B0E',
                                          'cloudidentifier': None,
                                          'cloudlibrarystate': None,
                                          'cloudlocalstate': 0,
                                          'cloudownderlastname': None,
                                          'cloudownerfirstname': None,
                                          'cloudownerhashedpersonid': None,
                                          'intrash': False,
                                          'kind': 1500,
                                          'parentfolder': 4,
                                          'pk': 4344,
                                          'title': '268565486'},
``` 
Its parent folder 4 is the root folder. the 1500 kind is not listed in the _constants.py module.

I did an export of this album (`osxphotos export .  --album "268565486" --directory "{album}" ETC.` it contains 109 photos, which correspond to the last two photos imports I did recently ... It is the only album/folder with this kind in the osxphotos dump... 
It is a minor annoyance, but I guess this is something you would like to know about. Rhett, the full debug of my my DB is available on demand...

**Comment by RhetTbull** [comment]
Thanks @garz75 ! I'll take a look this weekend and see what I can figure out. Since Apple doesn't document the Photos database everything I've done is figured out by trial & error and reverse engineering -- there's still many things like these different album kinds I haven't sorted out.  

If you run `osxphotos albums` does this album show up in the list?

**Comment by RhetTbull** [comment]
@garz75 I think I've fixed this in [v0.29.23](https://github.com/RhetTbull/osxphotos/releases/tag/v0.29.23).  Give it a try and let me know if you still have the problem with the mystery album.  I have seen these album with `'kind': 1500` before but have not been able to reverse engineer what it is.  For the fix, I filter out only albums with known kinds (regular album, shared album).

**Comment by garz75** [comment]
Yes, well done. The `export` command above does not create this 268565486 directory anymore. But the album is still reported wit the command `osxphotos albums`
```
....
  2014-02-13 Florida: 109
  '268565486': 109
  2005-02-12_Claude: 107
...
```

**Comment by RhetTbull** [comment]
Thanks.  I think it should not show up in `osxphotos albums` either as it's not a "real" album.  I'll work on a fix for that too.

**Comment by garz75** [comment]
> Thanks. I think it should not show up in `osxphotos albums` either as it's not a "real" album. 

I agree. Thanks again for the quick fix

**Comment by RhetTbull** [comment]
I've refactored all the album code and believe this should now be fixed (e.g. you won't see the mystery album in `osxphotos albums` nor when exporting).  See [v0.29.24](https://github.com/RhetTbull/osxphotos/releases/tag/v0.29.24).  In doing so, I discovered (and fixed) another bug in that empty albums wouldn't show up in `osxphotos albums`.

**Comment by garz75** [comment]
Confirmed. my 1500 album does not show up anymore in albums listing. Thank you again.
