### ISSUE TITLE
fresh install with pipx gives error

### ISSUE THREAD

**Issue by Juggler00** [RhetTbull/osxphotos#1710]
macOS Sequoia 15.0.1
Fresh install of Homebrew and pipx with no errors.

```
XXX@MacBook-Air ~ % pipx install osxphotos
Fatal error from pip prevented installation. Full pip output in file:
    /Users/shamus/.local/pipx/logs/cmd_2024-10-14_10.11.32_pip_errors.log

pip seemed to fail to build package:
    wrapt<1.14.0,>=1.13.3

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ValueError: malformed node or string on line 2: <ast.Call object at 0x1068c7e50>
    AttributeError: wrapt has no attribute __version__
    ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py). Did you mean: 'formatargvalues'?
    error: metadata-generation-failed

Error installing osxphotos.
```

**Comment by RhetTbull** [comment]
> /opt/homebrew/Cellar/python@3.13

OSXPhotos has not been tested with Python 3.13 and needs to be ported. I'll get to this as soon as I'm able but rather busy at the moment.

I'm surprised pipx even tried to install it as the `setup.py` states `python_requires=">=3.9,<3.13",`

Unfortunately `brew install pipx` now insists on installing Python 3.13.  You should be able to get around this by:

`brew install python@3.12`
`pipx install osxphotos --python /usr/local/opt/python@3.12/bin/python3`

(verify the path to the python 3.12 installed by homebrew).

**Comment by Juggler00** [comment]
My apologies... thank you for your quick response and all of your work!

**Comment by RhetTbull** [comment]
No apologies needed! It's frustrating that brew + pipx behaves this way!
