### ISSUE TITLE
Question: Exporting raw live photos without associated video while exporting other videos

### ISSUE THREAD

**Issue by jeremy-collette** [RhetTbull/osxphotos#1726]
Is it possible to export live photos as originals (HEIC) and videos recorded in video mode (.mov) without also exporting the videos associated with live photos (also in .mov format)?

I took a look at the `export` command and I couldn't find options for this scenario.

Please let me know if it's possible or not supported today.

Cheers,

Jeremy

**Comment by RhetTbull** [comment]
Yes, `--skip-live`:

```
--skip-live  Do not export the associated live video component of a live photo.
```

The built in help has a search feature. To find this, I typed, `osxphotos help export live` which searches for any option in the export command that mentions the word `live`.

**Comment by jeremy-collette** [comment]
Oops.. I saw that option but thought it would skip the actual photo too. Thanks for clarifying!
