### ISSUE TITLE
Favorite iOS to macOS sync crashes with DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by mauticom** [RhetTbull/osxphotos#1743]
Hi, 

first thank you for the great and very sophisticated tool. However I'm running into an issue I can't seem to fix. I hope you can help. Thank you very much.

**Describe the bug**
Trying to sync favourites from my iPhone with my Photos library

**To Reproduce**

I'm running Photos 8.0 (macOS Ventura) and iPhone iOS 18.1.1

1. I imported my iPhone.sqlite, ..sqlite-shm, ..sqlite-wal files from my iPhone
2. Run osxphotos sync --import /Users/cmm/Downloads/Photos.sqlite --set favorite --verbose
3. osxphotos detects and processes my Photos libraries but when it starts processing my iPhone.sqlite it crashes after "Processing detected faces in photos" with a "DatabaseError: database disk image is malformed" error.

**Expected behavior**
Syncing my favorites from all my iPhone photos to the imported photos in Photos.app.

**Terminal Log**

```
osxphotos sync --import /Users/cmm/Downloads/Photos.sqlite --set favorite --verbose

Processing database /Volumes/Silo 10TB/Bilder/Fotos Library.photoslibrary/database/photos.db

Processing database /Volumes/Silo 10TB/Bilder/Fotos Library.photoslibrary/database/Photos.sqlite

Photos database version: 6000, 8.

Processing persons in photos.

Processing detected faces in photos.

Processing albums.

Processing keywords.

Processing photo details.

Processing import sessions.

Processing additional photo details.

Processing face details.

Processing photo labels.

Processing EXIF details.

Processing computed aesthetic scores.

Processing comments and likes for shared photos.

Processing moments.

Processing syndication info.

Processing shared iCloud library info

Done processing details from Photos library.

Importing metadata for 39198 photos from /Users/cmm/Downloads/Photos.sqlite

Processing database /Users/cmm/Downloads/Photos.sqlite

Processing database /Users/cmm/Downloads/Photos.sqlite

Photos database version: 5001, 10.

Processing persons in photos.

Processing detected faces in photos.

DatabaseError: database disk image is malformed
```

![Bildschirmfoto 2024-11-28 um 23 50 53](https://github.com/user-attachments/assets/f6026bc2-5e63-4793-8d54-62024ab24d2d)
![Bildschirmfoto 2024-11-28 um 23 51 06](https://github.com/user-attachments/assets/dffad416-62b5-4a1a-89ce-668979389bf7)

**Desktop (please complete the following information):**
osxphotos, version 0.68.6
Python 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS 13.6.7, x86_64
iOS 18.1.1

**Comment by RhetTbull** [comment]
Sync requires you to first export the metadata to a sync database then import from that sync database. I'm on mobile so can't test at moment but it's something like:

osxphotos sync --export sync.db --library /path/to/photos.sqlite

Then

osxphotos sync --import sync.db

**Comment by mauticom** [comment]
Hi @RhetTbull,

thank you very much. I see this part was missing in your 8 months old Reddit post how to sync favorites from your iPhone to your Mac. -> https://www.reddit.com/r/ApplePhotos/comments/1brt4eg/is_it_possible_to_sync_favorites_and_albums_from/?rdt=36865

However it seems osxphotos has troubles to read the iOS 18.1.1 Photos.sqlite or the free version of iMazing tinkers with it and makes it unusable.

I tried your suggestion just out of curiousity with the local macOS Photos.app Photos.sqlite and also used the sync import function and everything works fine but of course no new data was set since it was the same. 

So the culprit is definitaley my iOS Photos.sqlite with iOS 18.1.1. No clue how to fix that yet. I'll try to find another app  to import the data from my phone.

**Comment by mauticom** [comment]
Indeed I can confirm with the demo version of iExplorer everything was working as expected. So the trial period of imazing really screwed something up.

I'm super happy with the result. Thank you so much @RhetTbull. 

Finally syncing favourites from iOS to macOS without the artifical and greedy requirement to pay for iCloud. So this issue can be closed now.

**Comment by RhetTbull** [comment]
You're right about the example -- I had forgotten that `osxphotos sync --import` can actually read a Photos database *or* a sync database previously created with `osxphotos sync --export`. This was put in exactly for the use case you have. Glad it's working. I have previously used iMazing with no problem.
