### ISSUE TITLE
PhotoInfo.export should default to original filename, not current filename

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#176]
This would mirror the behavior of Photos and, with Photos 5 name mangling, likely be what the user expects

**Comment by AaronVanGeffen** [comment]
What would be required to add support for this? I was looking to use this in my own backup script; perhaps I can contribute.

**Comment by RhetTbull** [comment]
I think all that's needed is just to replace `self.filename` with `self.original_filename` in these lines.  The test suite will likely need to be updated too --  running pytest will identify which tests, if any, are testing for the default exported file name.  This is a really easy fix, just haven't gotten to it as I already work around in the osxphotos command line and have been busy on other fixes.

https://github.com/RhetTbull/osxphotos/blob/595307a003c8ae5d3bee3ad161bb880d884b3cc3/osxphotos/photoinfo/_photoinfo_export.py#L616-L618

**Comment by RhetTbull** [comment]
Thanks @AaronVanGeffen for implementing this!
