### ISSUE TITLE
applescript.ScriptError: Application isn’t running. (-600) when run from cron job

### ISSUE THREAD

**Issue by gabeklavans** [RhetTbull/osxphotos#1764]
**Describe the bug**
I had a simple set up using cron to export to a mounted SMB share working for months with no issue:

```
0 4 * * 4 /Users/gabe/.local/bin/osxphotos export --load-config /volumes/Pictures/photos-backup/osxphotos_config.toml /volumes/Pictures/photos-backup/data
```
with this config file:
```toml
[export]
cleanup = true
directory = "{created.year}/{created.mm}"
download_missing = true
exiftool_merge_keywords = true
favorite_rating = true
filename_template = "{id}_{original_name}"
keyword_template = [ "album:{album}", "{label}",]
ramdb = true
retry = 3
sidecar = [ "xmp",]
skip_original_if_edited = true
update = true
update_errors = true
use_photokit = true
```

I had since updated to macOS 15.1, still it was working, but it soon started failing to write the db file, so I decided to move the backup to my local machine instead of over an SMB share. I also updated osxphotos to 0.69.2 from whatever version I had installed back when I was running macOS 14.x (and switched to using `uv` to manage it). Now my cron and config are as follows:
```
0 4 * * 4 /Users/gabe/.local/bin/osxphotos export --load-config /Users/gabe/Pictures/photos-backup/osxphotos_config.toml /Users/gabe/Pictures/photos-backup/data
```
```toml
[export]
cleanup = true
directory = "{created.year}/{created.mm}"
download_missing = true
exiftool_merge_keywords = true
favorite_rating = true
filename_template = "{id}_{original_name}"
keyword_template = [ "album:{album}", "{label}",]
retry = 3
sidecar = [ "xmp",]
skip_original_if_edited = true
update = true
update_errors = true
use_photokit = true
```
(I just removed `ramdb` from the config and changed the destination to my local machine)

Now, I can run the export fine when I run from my interactive shell, but the cron job ALWAYS fails with this error:
```
Traceback (most recent call last):
  File "/Users/gabe/.local/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli_main
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/osxphotos/__init__.py", line 17, in <module>
    from .iphoto import (
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/osxphotos/iphoto.py", line 62, in <module>
    from .photoexporter import PhotoExporter
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/osxphotos/photoexporter.py", line 39, in <module>
    import photoscript
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/photoscript/__init__.py", line 18, in <module>
    from .script_loader import run_script
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/photoscript/script_loader.py", line 15, in <module>
    SCRIPT_OBJ = load_applescript("photoscript") 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/photoscript/script_loader.py", line 13, in load_applescript
    return AppleScript(script)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/gabe/.local/share/uv/tools/osxphotos/lib/python3.12/site-packages/applescript/__init__.py", line 49, in __init__
    raise ScriptError(errorinfo)
applescript.ScriptError: Application isn’t running. (-600) range=40102-40324
```

**To Reproduce**
1. Open Photos app
2. Run `/Users/gabe/.local/bin/osxphotos export --load-config /Users/gabe/Pictures/photos-backup/osxphotos_config.toml /Users/gabe/Pictures/photos-backup/data` with no issue
3. Paste the above command into crontab via `crontab -e` from logged in user (gabe)
4. See above error in `mail` (easiest way to get cron job outputs on macOS that I've found)

**Expected behavior**
A successful backup, just like if the command was run manually.

**Desktop (please complete the following information):**
osxphotos, version 0.69.2
Python 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
Python executable: /Users/gabe/.local/share/uv/tools/osxphotos/bin/python
macOS 15.1.0, arm64

**Additional context**
I notice that the error traceback shows an AppleScript function, even though I specified `use_photokit = true` in my config file. I tried also adding `use_photos_export = true` to the config, tried removing both, and putting `--use-photokit` directly into the command, but the result was the same.

**Comment by gabeklavans** [comment]
Downgrading to 0.67.10 yields the same error when run from cron, so I'm honestly not sure what has caused my set up to break.

**Comment by RhetTbull** [comment]
Permissions with unattended jobs are tricky. This is a macOS issue not an osxphotos issue. My guess is that upgrade (as well as subsequent downgrade) caused executable to change and only the first executable you ran this with had the permissions. See #1080 which may offer some tips on how to fix the permissions.

**Comment by gabeklavans** [comment]
> My guess is that upgrade (as well as subsequent downgrade) caused executable to change and only the first executable you ran this with had the permissions.

Ah this is reminding me of a lot of messing around with adding allows and exceptions into Apple's privacy functions that get stricter with each macOS upgrade. You might be right on that point, and I'll try messing with those.

**Comment by gabeklavans** [comment]
And on the first try, adding the new `osxphotos` binary to "Accessibility" allowed everything to work. Apple must have an interesting definition of "Accessibility"...
