### ISSUE TITLE
Feature: add access to shared iCloud libraries

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#18]
A few notes:
ZGENERICASSET.ZCLOUDLOCALSTATE
ZCLOUDISMYASSET = 0 (not NULL) appears to be shared Photos not owned by me
photos appear to be /resources/cloudsharing/ when downloaded
directory is /resources/cloudsharing/data/
within folder for each shared album, there's an Info.plist with cloudOwnerEmail, CloudOwnerName, etc
e.g. /Users/rhet/Pictures/Photos Library.photoslibrary/resources/cloudsharing/data/146768460/8021C2B2-4D83-4A5D-924E-861071AB604A/Info.plist
ZCLOUDOWNERHASHEDPERSONID is not NULL if shared  <-- seems to be the most reliable indicator of shared photo
ZCLOUDPLACEHOLDERKIND = 2 if shared album, 5 if not? or could be 4?
ZLOCALRESOURCESSTATE = -1 if shared album?
ZSAVEDASSETTYPE = 4 if shared?
ZCLOUDFEEDASSETSENTRY = not NULL if shared?
Z_FOK_CLOUDFEEDASSETSENTRY = not NULL if shared? 
ZCLOUDBATCHPUBLISHDATE not NULL if shared
ZMASTER = NULL if cloud

Have not been able to determine how to tell if file is downloaded without actually looking for the photo

**Comment by RhetTbull** [comment]
Create test db for shared: create a test iCloud account with a test library then share it (need two accounts to share to each other).

**Comment by RhetTbull** [comment]
v0.18.0 adds support for shared albums but only for Photos 5. I've not been able to figure out how to access shared albums in Photos <= 4

**Comment by RhetTbull** [comment]
Need to add shared to PhotoInfo.json()

**Comment by mwort** [comment]
Hi RhetTbull, great enhancement, thanks. I was wondering if it would it be possible to not only support export of shared iCloud items but also those that are not shared but only residing on iCloud? Currently, a "Skipping missing photo" warning is given and when I download the photo (i.e. open it), the export succeeds.

**Comment by RhetTbull** [comment]
@mwort — yes, I think this is possible. Issue #13 to add PhotoKit support would enable this. I’m stuck on one of the implementation details but will work as time permits. Currently, osxphotos reads the Photos library and can copy files already present on disk but doesn’t directly interact with Photos or PhotoKit (Apple’s approved programmatic interface to Photos).  Using PyObjC, I should be able to directly interact with Photos and request a copy of the original image which will force download. Another way to do this is call an AppleScript to force the export. That’s more clunky so I’d prefer to get a PhotoKit interface implemented.

**Comment by mwort** [comment]
Sounds good, I'm happy run tests.

**Comment by RhetTbull** [comment]
@mwort I've added a "--download-missing" option to the command line export tool. Give it a try and see if this does what you need. I've not down a lot of testing yet but in initial testing, seems to work.  Note: current implementation uses applescript to interact with Photos so it will ask for permission to interact with Photos first time you run it  then Photos will stay in foreground while the script is running as it's constantly being hit by applescript to do the export.  Kind of klunky but until I can get a native PhotosKit version working this might do the trick.

**Comment by mwort** [comment]
Thanks @RhetTbull, that works for me. I encountered two smaller issues after upgrading to get this to work (apologies for not opening separate issues for that, just for you to consider):
- got a `TypeError: __init__() got an unexpected keyword argument 'hidden'` error with click 6.7 installed, i.e. you might want to stipulate `click>=7.0` in setup.py
- for some reason none of the CLI commands worked before I had started Photos once, gave me a can't find library error, worked once it was started and even after I had closed it again (file access/permissions problem?)

**Comment by RhetTbull** [comment]
@mwort Thanks for the feedback.  I updated setup.py to specify min required version of Click.

On the second point, I opened issue #54 as a new bug.  osxphotos reads the file ~/Library/Containers/com.apple.Photos/Data/Library/Preferences/com.apple.Photos.plist to find the last opened Photos library but this must have failed in your case. 

Which OS are you running?  Also, had you previously opened Photos from that account or was this on a new machine? If you've got any other details to add, please add a comment on issue #54.  Thanks!
