### ISSUE TITLE
Documenting Photos Library Structure?

### ISSUE THREAD

**Issue by neilpa** [RhetTbull/osxphotos#182]
Hi @RhetTbull. I noticed you stumbled onto my [phace](github.com/neilpa/phace) repo from a few years ago. I've recently started hacking on it again post-Catalina. Wish I had known about your project earlier before I spent several evenings re-reverse-engineering the new DB structure.

I've been planning on writing up my raw notes in a more palatable format and figured `osxphotos` could be a good landing spot for that info. Especially given the maturity of this project compared to what I was working on.

I noticed you have some of the basics on the wiki but there's a lot more details that could be useful to flush out. Interest/thoughts?

**Comment by RhetTbull** [comment]
Hi @neilpa -- yes, I think that's a great idea! Not much in the wiki at the moment but I would like to create a definitive repository of information about Photos so we could help others avoid having to reverse engineer things all over again!  I welcome any contributions you'd like to make to the wiki.  I think I've fixed the wiki permissions so you can collaborate -- let me know if it doesn't work.  I'm definitely interested in your work on [phace](https://github.com/neilpa/phace) as I'd like to add face support to osxphotos.

**Comment by neilpa** [comment]
You probably already know all of the details I outline, but I wrote up a [getting started blog post about this sort of reverse engineering focused on getting at the face tag data](https://neilpa.me/2018-12-07-mac-photos-library/). If you scroll to the bottom it has a bit of the info you might be interested in (although it's for pre-Catalina).

I had intended to write a couple of follow-ups with more of the gory details that would likely be more interesting for you but life got in the way. I've had a renewed interest in this lately as I've been getting back into photography. I might have some time over the next week or so to compile what I've got to share.

**Comment by neilpa** [comment]
I made a few some updates to the [Photos v5 page](https://github.com/RhetTbull/osxphotos/wiki/Photos-version-5-database) and stubbed out some more things that would be useful to write about. Hopefully I'll find some more time to follow up on that.

**Comment by RhetTbull** [comment]
Thanks!  I added some details on Album sort order that I worked out over the weekend and will keep updating.  My next big push will be to provide an interface to face details.  I did some refactoring this weekend to make it easier to add in faces and link them to persons.

**Comment by neilpa** [comment]
>  I added some details on Album sort order that I worked out over the weekend and will keep updating

I noticed that and much appreciate it. That was actually one of the items I had on my list to figure out next since I wanted the same feature that was requested in #184
