### ISSUE TITLE
PhotosDB.photos from_date and to_date give incorrect results

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#193]
from_date and to_date don't account for timezone.  Code treats `imageDate` as if it's local timezone when in fact it might be in a different timezone.  

Look at here:
https://github.com/RhetTbull/osxphotos/blob/65b84ad345a7a6dceea784766217990086c9bc09/osxphotos/photosdb/photosdb.py#L954-L962

And implement something like `PhotoInfo.date`:
https://github.com/RhetTbull/osxphotos/blob/65b84ad345a7a6dceea784766217990086c9bc09/osxphotos/photoinfo/photoinfo.py#L87-L94

Correct behavior is to probably convert `imageDate` to timezone aware date.  If `from_date` or `to_date` is TZ aware, use timezone, if not, assume local timezone.

Thanks to @PabloKohan for finding and reporting this.  

The following test case will cause this issue to be noticed:
`TZ=Asia/Jerusalem python3 -m pytest -v tests/test_cli.py::test_query_date`

**Comment by PabloKohan** [comment]
I'd leave the `imageDate` as UTC, but make the `from_date`/`to_date` TZ aware (or TZ neutral).

**Comment by RhetTbull** [comment]
Need to do this for `lastmodifieddate` as well

**Comment by RhetTbull** [comment]
At least one user reports from_date, to_date working incorrectly since [fc416ea](https://github.com/RhetTbull/osxphotos/commit/fc416ea0b746413d2ac2f1dd2f1bc200227013ed)
