### ISSUE TITLE
Issue when starting and opening DB

### ISSUE THREAD

**Issue by bevadey** [RhetTbull/osxphotos#195]
With this simple code I have this issue.
import osxphotos
photosdb = osxphotos.PhotosDB(dbfile="/Users/.../Pictures/2020.photoslibrary/database/photos.db")

Error copying /Users/.../Pictures/2020.photoslibrary/database/photos.db to /var/folders/vf/3t083h9j1jx9mhxwwvzmpvhc0000gn/T/osxphotos_7v_3k1tb/photos.db
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/osxphotos/photosdb/photosdb.py", line 516, in _copy_db_file
    copyfile(fname, dest_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/Users/.../Pictures/2020.photoslibrary/database/photos.db'

and in /T/ the  folder osxphotos_7v_3k1tb/photos.db is not created
and 
drwx------@ 432 bvde  staff  13824 26 jul 12:30 T

nb: osxphotos work fine from the terminal (CLI)

**Comment by RhetTbull** [comment]
1. What version of MacOS are you using?
2. What version of python are you using?
3. Is the Photos library you're opening in your home directory or is it in another users?
4. Do you still get the error if you call `PhotosDB` with no arguments (e.g. open the default database)? 
```python
photosdb = osxphotos.PhotosDB()
```
5. Have you tried running the script with sudo? `sudo python3 your_script.py`
6. Check `System Preferences | Security & Privacy | Photos` and `System Preferences | Security & Privacy | Full Disk Access` -- do you see the Terminal listed (or whichever terminal app you're using)?

**Comment by bevadey** [comment]
Thank you for your answer.

> Le 26 juil. 2020 à 15:31, Rhet Turnbull <notifications@github.com> a écrit :
> 
> 
> What version of MacOS are you using?
10.16.6 
> What version of python are you using?
3.8
> Is the Photos library you're opening in your home directory or is it in another users?
Yes


BUT
I ‘ve tried running the script from ‘terminal’: python3 your_script.py and it’s WORKING !

I was using the terminal window in VScode where I have always the same error.

**Comment by RhetTbull** [comment]
Ah...that makes sense.  You may need to add VSCode to "Full Disk Access" and "Developer Tools" in Security & Privacy.

**Comment by bevadey** [comment]
Yes, you’re right.
Working in VScode now.
Thank you very much
