### ISSUE TITLE
Portrait mode is not tagged correctly

### ISSUE THREAD

**Issue by mccarverone** [RhetTbull/osxphotos#203]
Osxphotos 0.32.0 - When I get photos details from a python script I have pictures taken in portrait mode not correctly tagged as such: portrait property of PhotoDB.photos stays False. Instead they are reported as edited even if no adjustments were made.

Thanks for your continuous work on this project.

**Comment by RhetTbull** [comment]
@mccarverone  If you're able to do try the following and send the data to me or post here, that'll be helpful for debugging. 

First, get the UUID of one of the images in question.  In your script, you can do that via the `.uuid` property of the PhotoInfo object.  It should look something like: `03AD4703-ED12-4682-978D-B784E8AB8E9A` 

Then, run this command substituting the UUID from step 1 for the UUID in the command below:

`python3 -m osxphotos debug-dump --dump photos --uuid '03AD4703-ED12-4682-978D-B784E8AB8E9A' >  debug.out`

Finally, run this command:

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite ".headers on" "select * from ZGENERICASSET where zuuid = '03AD4703-ED12-4682-978D-B784E8AB8E9A'" > debug2.out`

**Comment by RhetTbull** [comment]
I think I may have found it -- all portrait photos and only portrait photos (at least as far as I can see in my library) appear to have a "depth state" value.  I should be able to use this to identify portrait photos--however, the schema for depth state in the database changed in the new MacOS Big Sur beta so I'll have to engineer a solution that works for both database versions.  

In Photos 5 / Catalina:
`ZGENERICASSET.ZDEPTHSTATE`

In Photos 5 / Big Sur this is replaced with
`ZASSET.DEPTHTYPE`

But I need to do further investigation to see if these are identical in value.  My guess is this feeds the "blur background" filter.  Also, all portraits appear to show `ZHASADJUSTMENTS = 1` presumably because the background blur happens after the original is taken.

**Comment by RhetTbull** [comment]
I was using `ZGENERICASSET.ZCUSTOMRENDEREDVALUE` to identify Portrait photos and have seen values of 7, 8, and 9 for this and in one case 2.  Though not all photos with value of 2 are portraits.

**Comment by RhetTbull** [comment]
@mccarverone I think this is fixed for Catalina / Big Sur in [v0.33.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.33.3).  Let me know if you have any more issues.  I still need to do some testing for Mojave and below.

**Comment by RhetTbull** [comment]
Confirmed behavior as expected on Mojave

**Comment by mccarverone** [comment]
I'll leave a maybe useful note for future reference: `ZGENERICASSET.ZHASADJUSTMENTS` is often flagged even if no actual adjustments were made (e.g. all portrait photos). I traced back real changes to photos such as free rotations, brightness, b&w to table `ACHANGE` which I think can hardly be reverse engineered. However fields `ACHANGE.ZTOMBSTONE*` (yeah, "tombstone") contains the UUID of photos that gets adjusted.
This could in theory help discriminating. Only problem is that this table is incremental and so reversing all changes to the original photo doesn't delete any row, so you would still find the UUID.

**Comment by RhetTbull** [comment]
Thanks.  I've not been able to figure out exactly what's going on with ACHANGE.  As far as detecting "real" adjustments, I could change `PhotoInfo.hasadjustments` to look at both `ZGENERICASSET.ZHASADJUSTMENTS` **and** look for presence of an edited image.  However, I think it's possible for the edited image to be in iCloud and not on the local disk if the user doesn't have Photos configured to store all images on the local machine so this check would sometimes fail. 

Besides Portrait photos have you seen other cases where this happens regularly?

**Comment by mccarverone** [comment]
Hello sorry for the delay. I have been actually investigating this for a while and my conclusions are that the `hasadjustment` flag works in a consistent way. I was thrown out by a couple picture that were reported as modified, but were not actually modified. However they spontaneously changed back to 'not modified' just after opening them in Apple Photos. So an inconsistent database from my part it seems.
One note: changing photo location doesn't trigger the `hasadjustment` property. I guess this is Apple decision.
Thanks
