### ISSUE TITLE
Encoding issues with non-english characters in album titles

### ISSUE THREAD

**Issue by jotzet79** [RhetTbull/osxphotos#208]
When having Album titles with "strange" (non-english, e.g. german umlaut / diaretics) characters in it, queries with that album title result in empty resultsets, and therefore exports yield to no output as well.

E.g.
"2018-10 - Sponsion, Museum, Fru\u0308hstu\u0308ck, Ro\u0308mermuseum" instead of 
"2018-10 - Sponsion, Museum, Frühstück, Römermuseum"

**Comment by RhetTbull** [comment]
@jotzet79 Thanks for reporting this -- I'll look into it.

**Comment by jotzet79** [comment]
If you need help in testing / debugging, just reach out to me...
BTW: JSON Output seems to be correct (e.g. piping to `„jq“`, only output in the normal operation mode seems to be broken!

**Comment by RhetTbull** [comment]
Still looking into this.  Photos is encoding text differently than python -- e.g. the diacriticals are encoded as separate characters (see `len()` below) whereas python will internally handle the unicode string just fine. 

```python
osxphotos version: 0.33.6
Using last opened Photos library: /Users/rhet/Pictures/Test-10.14.6.photoslibrary
loading database
done: took 0.2252544299999999 seconds
database version: 4025
getting photos
found 7 photos in 0.0014893330000000926 seconds
>>> photosdb.albums
['2018-10 - Sponsion, Museum, Frühstück, Römermuseum', 'Pumpkin Farm', 'AlbumInFolder', 'Test Album (1)', 'Test Album']
>>> photosdb.album_info
[<osxphotos.albuminfo.AlbumInfo object at 0x113983b80>, <osxphotos.albuminfo.AlbumInfo object at 0x113983be0>, <osxphotos.albuminfo.AlbumInfo object at 0x113983df0>, <osxphotos.albuminfo.AlbumInfo object at 0x113983e50>, <osxphotos.albuminfo.AlbumInfo object at 0x113983eb0>]
>>> photosdb.album_info[4].title
'2018-10 - Sponsion, Museum, Frühstück, Römermuseum'
>>> photosdb.album_info[4].title == "2018-10 - Sponsion, Museum, Frühstück, Römermuseum"
False
>>> photosdb.album_info[4].title[31]
'̈'
>>> photosdb.album_info[4].title[35]
'u'
>>> photosdb.album_info[4].title[36]
'̈'
>>> len(photosdb.album_info[4].title)
53
>>> len("2018-10 - Sponsion, Museum, Frühstück, Römermuseum")
50
>>>
```

**Comment by RhetTbull** [comment]
@jotzet79 What's your use case?  Are you running the `osxphotos` command line utility or using the package in your own code?  If using the command line, you might try [iTerm](https://www.iterm2.com/) as a temporary fix -- it seemed to handle the encoding automatically in my initial tests. Either way, I'll still need to fix this but it might help you get work done now while waiting for a fix.

**Comment by RhetTbull** [comment]
I think the solution is to normalize all text from both the Photos database and as passed in from the command line.

```python
>>> unicodedata.is_normalized('NFC',photosdb.album_info[4].title)
False
>>> unicodedata.is_normalized('NFD',photosdb.album_info[4].title)
True
>>> unicodedata.is_normalized('NFD',"2018-10 - Sponsion, Museum, Frühstück, Römermuseum")
False
>>> unicodedata.is_normalized('NFC',"2018-10 - Sponsion, Museum, Frühstück, Römermuseum")
True
>>> unicodedata.is_normalized('NFC',"2018-10 - Sponsion, Museum, Fru\u0308hstu\u0308ck, Ro\u0308mermuseum")
False
>>> unicodedata.is_normalized('NFD',"2018-10 - Sponsion, Museum, Fru\u0308hstu\u0308ck, Ro\u0308mermuseum")
True
>>> print("2018-10 - Sponsion, Museum, Fru\u0308hstu\u0308ck, Ro\u0308mermuseum")
2018-10 - Sponsion, Museum, Frühstück, Römermuseum
>>> photosdb.album_info[4].title == "2018-10 - Sponsion, Museum, Frühstück, Römermuseum"
False
>>> unicodedata.normalize('NFC',photosdb.album_info[4].title) == unicodedata.normalize('NFC',"2018-10 - Sponsion, Museum, Frühstück, Römermuseum")
True
>>>
```

**Comment by RhetTbull** [comment]
@jotzet79 I think this is fixed in v0.33.7.  Take a look and let me know if it solves the problem.  I now normalize all unicode text when reading from the Photos database and again when reading input from the command line.

**Comment by jotzet79** [comment]
Hi @RhetTbull, 

It has gotten a bit better, nonetheless I still have strange (unicode entity) characters on bash:
`"2018-10 - Sponsion, Museum, Fr\xFChst\xFCck, R\xF6mermuseum"`
So I think we are definitely getting closer... Do you need additional debugging info?

Thank you,
Joachim

PS: I cannot say how grateful I am to having found this neat piece of sw-lib! I definitely will use it in my Export-Photos-to-BackupDrive/GDrive-Sync-Workflow! So thanks a bunch for putting your time and efforts into this...

**Comment by RhetTbull** [comment]
Can you post or send me the exact command line (or code snippet if you're writing your own export method) you are using?  Also, are the unicode character codes appearing in the output of osxphotos command or are the actual export folders misnamed?

**Comment by jotzet79** [comment]
At the moment I'm simply running it from command line: 
`osxphotos albums
Using last opened Photos library: /Users/.../Pictures/Fotos-Mediathek.photoslibrary
albums:
.
.
.
  2018-05 - Hochzeit Name1 & Name2: 35
  "2018-10 - Sponsion, Museum, Fr\xFChst\xFCck, R\xF6mermuseum": 34
.
.
.
`

**Comment by RhetTbull** [comment]
Which version of MacOS are you using?
Which shell are you using? (you referenced bash above but just want to confirm)
Which terminal are you using (Terminal.app, iTerm.app, other?)

I've not been able to reproduce this. I created an album called `2018-10 - Sponsion, Museum, Frühstück, Römermuseum` and ran export with the same options you were using and both the verbose output on screen and the resulting folder name in Finder were correct.  I tried using both bash and zsh on both iTerm and Terminal.app on MacOS 10.15.6.

<img width="920" alt="Screen Shot 2020-09-04 at 11 13 36 AM" src="https://user-images.githubusercontent.com/41546558/92273646-99c19480-eea0-11ea-9dc9-298d5d7c16d5.png">

**Comment by jotzet79** [comment]
Dear @RhetTbull, So now (corona lockdown / winter) I got time to look into this again, and for me this is working now. I don't know if there has been issues with Shell back then. Maybe a restart of Terminal.app did the trick. But overall output in shell on STDOUT, and especially in the file system works reliably. 
Again: Thank you very much!
Joachim
