### ISSUE TITLE
Feature: provide interface to the detailed faces information in database

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#21]
The database contains much detailed info about the people/faces in the photo

**Comment by AaronVanGeffen** [comment]
I would love an export option for this information as well. Perhaps they could be added as EXIF keywords in the photos themselves?

**Comment by RhetTbull** [comment]
@AaronVanGeffen the names of the people in the images are already included in the export for both JSON and XMP (stored in XMP:Subject and IPTC:PersonInImage).  I am also working on an ExifTool interface to directly write this and other metadata to the image upon export.  This issue (though written very vaguely!) is referring to the detailed information such as the actual face regions and characteristics (e.g. left eye closed, right eye closed, has smile, etc.) that Photos stores about the faces. (In Photos 5, much of this information is in ZDETECTEDFACE table) It would be useful to have access to this info, for example, for experimenting with face detection or machine learning.

**Comment by RhetTbull** [comment]
Need to add height, width, orientation to PhotoInfo.  (Should add size while I'm at it)

**Comment by RhetTbull** [comment]
See this note on [orientation](http://sylvana.net/jpegcrop/exif_orientation.html)

**Comment by RhetTbull** [comment]
Photos 4
```sql
CREATE TABLE RKFace (modelId integer primary key autoincrement, uuid varchar, isInTrash integer, personId integer, 
hasBeenSynced integer, adjustmentUuid varchar, imageModelId integer, sourceWidth integer, sourceHeight integer, centerX 
decimal, centerY decimal, size decimal, leftEyeX decimal, leftEyeY decimal, rightEyeX decimal, rightEyeY decimal, mouthX 
decimal, mouthY decimal, hidden integer, manual integer, hasSmile integer, blurScore decimal, isLeftEyeClosed integer, 
isRightEyeClosed integer, nameSource integer, poseRoll decimal, poseYaw decimal, posePitch decimal, faceAlgorithmVersion 
integer, expressionConfidence decimal, expressionType1 integer, expressionType2 integer, expressionType3 integer, 
expressionScore1 decimal, expressionScore2 decimal, expressionScore3 decimal, qualityMeasure integer, 
clusterSequenceNumber integer, syncPropertyModifiedDate timestamp, faceGroupId integer, 
confirmedFaceCropGenerationState integer, faceType integer, trainingType integer, cloudNameSource integer, personUuid 
varchar);
```

Photos 5
```sql
CREATE TABLE ZDETECTEDFACE (
  Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, 
  Z_OPT INTEGER, ZAGETYPE INTEGER, ZASSETVISIBLE INTEGER, 
  ZBALDTYPE INTEGER, ZCLOUDLOCALSTATE INTEGER, 
  ZCLOUDNAMESOURCE INTEGER, ZCLUSTERSEQUENCENUMBER INTEGER, 
  ZCONFIRMEDFACECROPGENERATIONSTATE INTEGER, 
  ZEYEMAKEUPTYPE INTEGER, ZEYESSTATE INTEGER, 
  ZFACEALGORITHMVERSION INTEGER, ZFACIALHAIRTYPE INTEGER, 
  ZGENDERTYPE INTEGER, ZGLASSESTYPE INTEGER, 
  ZHAIRCOLORTYPE INTEGER, ZHASSMILE INTEGER, 
  ZHIDDEN INTEGER, ZISINTRASH INTEGER, 
  ZISLEFTEYECLOSED INTEGER, ZISRIGHTEYECLOSED INTEGER, 
  ZLIPMAKEUPTYPE INTEGER, ZMANUAL INTEGER, 
  ZNAMESOURCE INTEGER, ZQUALITYMEASURE INTEGER, 
  ZSMILETYPE INTEGER, ZSOURCEHEIGHT INTEGER, 
  ZSOURCEWIDTH INTEGER, ZTRAININGTYPE INTEGER, 
  ZASSET INTEGER, Z34_ASSET INTEGER, 
  ZFACECROP INTEGER, ZFACEGROUP INTEGER, 
  ZFACEGROUPBEINGKEYFACE INTEGER, 
  ZFACEPRINT INTEGER, ZPERSON INTEGER, 
  ZPERSONBEINGKEYFACE INTEGER, ZADJUSTMENTVERSION TIMESTAMP, 
  ZBLURSCORE FLOAT, ZCENTERX FLOAT, 
  ZCENTERY FLOAT, ZLEFTEYEX FLOAT, ZLEFTEYEY FLOAT, 
  ZMOUTHX FLOAT, ZMOUTHY FLOAT, ZPOSEYAW FLOAT, 
  ZQUALITY FLOAT, ZRIGHTEYEX FLOAT, 
  ZRIGHTEYEY FLOAT, ZROLL FLOAT, ZSIZE FLOAT, 
  ZYAW FLOAT, ZGROUPINGIDENTIFIER VARCHAR, 
  ZMASTERIDENTIFIER VARCHAR, ZUUID VARCHAR
);
```

**Comment by RhetTbull** [comment]
Working with this query on Photos 5

```sql
SELECT
ZGENERICASSET.ZUUID,
ZDETECTEDFACE.ZUUID,
ZDETECTEDFACE.ZPERSON,
ZPERSON.ZFULLNAME,
ZDETECTEDFACE.ZAGETYPE,
ZDETECTEDFACE.ZBALDTYPE,
ZDETECTEDFACE.ZEYEMAKEUPTYPE,
ZDETECTEDFACE.ZEYESSTATE,
ZDETECTEDFACE.ZFACIALHAIRTYPE,
ZDETECTEDFACE.ZGENDERTYPE,
ZDETECTEDFACE.ZGLASSESTYPE,
ZDETECTEDFACE.ZHAIRCOLORTYPE,
ZDETECTEDFACE.ZHASSMILE,
ZDETECTEDFACE.ZHIDDEN,
ZDETECTEDFACE.ZISINTRASH,
ZDETECTEDFACE.ZISLEFTEYECLOSED,
ZDETECTEDFACE.ZISRIGHTEYECLOSED,
ZDETECTEDFACE.ZLIPMAKEUPTYPE,
ZDETECTEDFACE.ZMANUAL,
ZDETECTEDFACE.ZQUALITYMEASURE,
ZDETECTEDFACE.ZSMILETYPE,
ZDETECTEDFACE.ZSOURCEHEIGHT,
ZDETECTEDFACE.ZSOURCEWIDTH,
ZDETECTEDFACE.ZBLURSCORE,
ZDETECTEDFACE.ZCENTERX,
ZDETECTEDFACE.ZCENTERY,
ZDETECTEDFACE.ZLEFTEYEX,
ZDETECTEDFACE.ZLEFTEYEY,
ZDETECTEDFACE.ZMOUTHX,
ZDETECTEDFACE.ZMOUTHY,
ZDETECTEDFACE.ZPOSEYAW,
ZDETECTEDFACE.ZQUALITY,
ZDETECTEDFACE.ZRIGHTEYEX,
ZDETECTEDFACE.ZRIGHTEYEY,
ZDETECTEDFACE.ZROLL,
ZDETECTEDFACE.ZSIZE,
ZDETECTEDFACE.ZYAW,
ZDETECTEDFACE.ZMASTERIDENTIFIER
FROM ZDETECTEDFACE
JOIN ZGENERICASSET ON ZGENERICASSET.Z_PK = ZDETECTEDFACE.ZASSET
JOIN ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSON
ORDER BY ZGENERICASSET.ZUUID
```

**Comment by RhetTbull** [comment]
`ZAGETYPE`:
0 =  ?? (have seen children and adults; perhaps "unknown" or "not yet processed")?
1 = infant
2 = child
3 = older child
4 = ??
5 = adult

`ZBALDTYPE`:
0 = ??
1 = not seen in database
2 = not much hair
3 = has hair

**Comment by RhetTbull** [comment]
For Photos 4:

```sql
SELECT
RKFace.modelId,
RKFace.uuid,
RKVersion.uuid, 
RKPerson.name,
RKFace.isInTrash,
RKFace.personId,
RKFace.imageModelId, 
RKFace.sourceWidth,
RKFace.sourceHeight, 
RKFace.centerX,
RKFace.centerY,
RKFace.size,
RKFace.leftEyeX, 
RKFace.leftEyeY,
RKFace.rightEyeX, 
RKFace.rightEyeY, 
RKFace.mouthX,
RKFace.mouthY, 
RKFace.hidden, 
RKFace.manual, 
RKFace.hasSmile, 
RKFace.isLeftEyeClosed, 
RKFace.isRightEyeClosed, 
RKFace.poseRoll, 
RKFace.poseYaw, 
RKFace.posePitch, 
RKFace.faceType,
RKFace.personUuid
FROM
RKFace
JOIN RKPerson on RKPerson.modelId = RKFace.personId
JOIN RKVersion on RKVersion.modelId = RKFace.imageModelId
```

**Comment by neilpa** [comment]
> See also [phace](https://github.com/neilpa/phace)

The ["drawing" code](https://github.com/neilpa/phace/blob/7594776480505d0c389688a42099c94ac5d34f3f/cmd/phace/draw.go#L34-L57) that handles this for Photos 4. And the [orientation adjustments](https://github.com/neilpa/phace/blob/7594776480505d0c389688a42099c94ac5d34f3f/cmd/phace/draw.go#L79-L94) that I validated against my personal photos lib at the time.

**Comment by RhetTbull** [comment]
@neilpa perfect--thanks!  I did a lot of work on this over the weekend and have added a `FaceInfo` object with all the relevant details (not yet committed to GitHub).  I was able the bounding box correct for all exif cases but hadn't yet figured out the transforms for the other points. (I ended up with upside down faces for example on photos that had been rotated).

**Comment by RhetTbull** [comment]
Thanks to @neilpa I've got the bounding boxes and face points working for all EXIF orientations....except for pictures rotated inside Photos.  Photos rotated using `Image | Rotate` don't change the value for `ZORIENTATION` and I've not yet been able to decipher how Photos is storing the orientation for these.

**Comment by neilpa** [comment]
>  Photos rotated using Image | Rotate don't change the value for `ZORIENTATION`

I was going to guess that this would end up in `ZADJUSTMENT` or `ZUNMANAGEDADJUSTMENT` but that doesn't appear to be the case from looking at the records I have for my photos lib.

I've got a few different hacks which can partially "diff" two different snapshots of the photos DB. It's come in handy for reverse engineering stuff but I mostly use it to detect and backup newly imported assets. I'll see if I can use this trick to figure out how that rotation is represented.

**Comment by neilpa** [comment]
Also, if you haven't already, you should look at the `ACHANGE`, `ATRANSACTION`, and `ATRANSACTIONSTRING` tables. Those have helped me decipher how things fit together. Especially when trying to trace the meanings of numeric identifiers across tables. (In that case I usually just create a SQL dump and `grep` the output text file).

**Comment by RhetTbull** [comment]
Thanks. I've been using [sqldiff](https://www.sqlite.org/sqldiff.html) a lot to compare the database between changes.  It looks like the Photos adjustments, including rotation, are in a `.plist` file in the same file as the edited images (`resources/renders/X/` where X is first character of UUID) but the adjustment data is stored in a binary format I've not yet tried to decipher.   All adjustments produce an entry in `ZINTERNALRESOURCE` and there's a `ZDATASTOREKEYDATA` column that I suspect may map to data in the .plist file which has a DataStore field.

**Comment by neilpa** [comment]
Thanks for the pointers, especially `sqldiff`. Can't believe I haven't seen that before.

**Comment by neilpa** [comment]
I spent some time poking at this but haven't deciphired the format of the embedded blobs in the `:adjustmentData` field of the `.plist` files you mention. I did a little hex dump slicing, dicing, and diffing but nothing obvious jumped out. Will likely need a more methodical approach that I didn't have time for at the moment.

Also, In my limited testing though it doesn't look like `ZDATASTOREKEYDATA` can be used to detect/differentiate those rotations. It's always the same small binary value for all three rotations (90, 180, 270). I was hoping to maybe find some other clues with `sqldiff` for a non-plist option but no luck so far.

**Comment by RhetTbull** [comment]
The `.plist` file in the renders folder is a serialized [PHAdjustmentData](https://developer.apple.com/documentation/photokit/phadjustmentdata) object.  Unfortunately, the specification for the `adjustmentData` property is not specified -- it's free form data that any application that edits photos via `PhotoKit` can set.  So in this case, we need to look at the Photos specific format which Apple doesn't document.  This also means though that if user edited photo in some other app or plugin that used `PhotoKit` the rotation data might be stored in a different format (not sure how Photos would then know how to apply face regions...)   

I've spent a lot of time with a hex editor trying to identify how the rotation data is stored by Photos and so far have come up empty handed.  The `data` field appears to be a series of binary records of variable length delimited by `0x0A09` but I've not yet found any common bytes across these for different sequences of edits and rotations that would identify the rotation.

For now, I think I'll push the initial `FaceInfo` implementation with a caveat that it'll be wrong for images rotated in Photos.

**Comment by RhetTbull** [comment]
I think I found it!  Was looking in the wrong place.  The rotation information for images edited in Photos doesn't appear to be stored in the database but the rotation of the face itself is stored in `ZDETECTEDFACE.ZROLL` and `ZDETECTEDFACE.ZYAW`.  These appear to be angles in radians so I should be able to rotate the face points accordingly.  It appears that `ZROLL` is the angle in radians the face is rotated about an axis perpendicular to the screen where clockwise is negative.

**Comment by neilpa** [comment]
> I've spent a lot of time with a hex editor trying to identify how the rotation data is stored by Photos and so far have come up empty handed. The data field appears to be a series of binary records of variable length delimited by 0x0A09 but I've not yet found any common bytes across these for different sequences of edits and rotations that would identify the rotation.

Same for me. I spent a couple hours with [Hex Fiend](https://github.com/ridiculousfish/HexFiend) yesterday evening looking at various diffs and have yet to make any real progress. Surprising since it's only ~150 bytes of data.

> I think I found it!

Awesome that you figured this out for photos with detected faces at least.

**Comment by RhetTbull** [comment]
[v0.31.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.31.0) has initial support for face regions. See [docs](https://github.com/RhetTbull/osxphotos#faceinfo).  Note: The bounding box for the face region appears to be correct for all possible rotations and flips of the image but for the `left_eye`, `right_eye`, and `mouth` properties which return coordinates (in the image coordinate frame) for the eyes and mouth are not always correct if the face is tilted off normal.  The angles to describe the necessary rotation are stored in `roll`, `pitch`, and `yaw` but I've not yet figured out how to apply the transformation (except for `roll` which is updated when an image is itself rotated).  See issue #196.

**Comment by RhetTbull** [comment]
Now need to add face regions to XMP sidecars.  See [iphoto2xmp](https://github.com/jensb/iphoto2xmp):

https://github.com/jensb/iphoto2xmp/blob/2e47eacb45f385f9447fa674ef0bbd5a362c14d8/iphoto2xmp_template.xmp.erb#L141-L160

**Comment by RhetTbull** [comment]
I think the XMP sidecar is now properly encoding the face regions...however, I've not been able to find a way to test this.  I've tried both Digikam and Lightroom, both of which I'm unfamiliar with, and can't figure out how to get them to import face regions from an XMP file despite hours of googling.  I'm going to put this issue on hold until I can find an app or some code that will show me the face regions in an exported image so I can verify they're being encoded properly.

**Comment by neilpa** [comment]
> I've not been able to find a way to test this. I've tried both Digikam and Lightroom, both of which I'm unfamiliar with, and can't figure out how to get them to import face regions from an XMP file despite hours of googling

I hit this exact same issue when working on this in phace. I could not find an app that actually used the encoded face regions. IIRC the docs for DigiKam claimed to but in all my experimenting I couldn't find an example of it working. Best I did was find some sample images with the XMP face regions already encoded and made sure I could round-trip the data based on my understanding of the format.

**Comment by RhetTbull** [comment]
@neilpa I've figured out how to make DigiKam at least write the XMP files with embedded face regions.  My plan is to mark face regions in DigiKam then export the XMP files for a bunch of photos in every possible EXIF orientation then write a program that reads the XMP files and draws the face regions with Pillow.  Assuming DigiKam is properly encoding the face regions and I can visually verify that I can interpret the encodings correctly, that will be give me a way to then verify the regions I'm encoding are correct.  But it does lead to the question of what the value is in face regions if apps don't actually read this information.  I like the idea of exporting it to future proof the export but it is frustrating the state of this so bad given how much effort it takes to properly tag a library with thousands of photos!  In researching this I learned that even though there's a Metadata Working Group standard for face regions, Microsoft developed their own which is completely different (but best as I can tell, encodes no additional information).  DigiKam does encode the Microsoft format as well so perhaps I can add that to osxphotos too.

**Comment by d0m1n1qu3** [comment]
Hi,
for example pigallery2 use the metadata of the image files to show the persons/faces
so it will be cool to keep the faces, store them in the metadata and a presentation tool like pigallery2 can use them instead of refined all faces again ..

`from pigallery2 website ...
Faces (persons) support
reads Adobe's XMP Face region metadata. (It is defined by the Metadata Working Group (MWG).)`

https://github.com/bpatrik/pigallery2

best regards Dominique

**Comment by RhetTbull** [comment]
Thanks @d0m1n1qu3 I'll take a look at pigallery2.  Currently, the face information is written to the XMP sidecar if you use `osxphotos export /path/to/export --sidecar xmp` option but I've not been able to properly test this as I can't find an app that actually uses this information.  If pigallery2 will read the sidecars, that would help confirm I'm exporting the data correctly.

**Comment by martinhrpi** [comment]
Would love to See xmp faceregion support. Supported by Digikam, Lightroom and others like Photostation on a Synology NAS. Tell me, if I could help.

I exported the data with the PersonInImage Tag but I see no way to convert it to Faceregion via Exiftool.

**Comment by RhetTbull** [comment]
osxphotos currently exports the personInImage info (name of person) but not the face region. It does have access to the face regions info but I've not found a way to validate the XMP nor found any program that will actually read this info. Lightroom writes it but I couldn't figure out how to make Lightroom read it. Happy for some help here: 1) an example of a valid XMP with Face Regions so I can copy the format, 2) ability to test the creature against some app that will actually read it from XMP.

**Comment by martinhrpi** [comment]
Sorry for the delay. So here is a true xmp, generated from Digikam. The first is normal orientation with People named left to right (LTR1, LTR 2, etc) and the second Data is the same picture and naming only rotated left. Had to change the type from amp to txt. Does this help? do you need anything else? Will be happy to test the new creature :-)


[digikam_test_normal.txt](https://github.com/RhetTbull/osxphotos/files/5813683/digikam_test_normal.txt)
[digikam_test_rotate.txt](https://github.com/RhetTbull/osxphotos/files/5813684/digikam_test_rotate.txt)

**Comment by RhetTbull** [comment]
That's helpful -- thanks! I'll be working on XMP this weekend -- #349, #350 -- so will take a look at this as well.

**Comment by martinhrpi** [comment]
Than thank you very much in advance!

**Comment by RhetTbull** [comment]
The DigiKam XMP files contain face regions in two formats:

The Metadata Working Group Regions (mwg-rs), see after page 51 [here](https://s3.amazonaws.com/software.tagthatphoto.com/docs/mwg_guidance.pdf).

Microsoft [MPRI format](https://docs.microsoft.com/en-us/windows/win32/wic/-wic-people-tagging) ("Microsoft Photo Region Info"?) 

>People Rectangles
>People's names however, are only part of the people-tagging feature. In addition to storing people's names in the metadata, the schema also supports region information that identifies the specific area (a rectangle) the person is shown in the image.
>The rectangle information is represented by four comma-delimited decimal values, such as "0.25, 0.25, 0.25, 0.25". The first two values specify the top-left coordinate; the final two specify the height and width of the rectangle. The dimensions of the image for the purposes of defining people rectangles are normalized to 1, which means that in the "0.25, 0.25, 0.25, 0.25" example, the rectangle starts 1/4 of the distance from the top and 1/4 of the distance from the left of the image. Both the height and width of the rectangle are 1/4 of the size of their respective image dimensions.

**Comment by martinhrpi** [comment]
Yes I think for broad compatability. But I think mwg is the best way

**Comment by RhetTbull** [comment]
@martinhrpi do you know how to make Digikam actually read the face tags from XMP? I've tried and not been able to make Digikam display the tagged faces in an XMP file. I worked on this issue several months ago and gave up because I could not find a way to test that the output is correct.  E.g. I need a way to write an XMP file then have some program read the XMP file and display the tagged regions to see if they're correct.   Without that, I'm shooting in the dark.

**Comment by RhetTbull** [comment]
exiftool region tags:

https://exiftool.org/TagNames/MWG.html#Regions

`exiftool -xmp-mwg-rs:RegionAppliedToDimensionsH=4000 -xmp-mwg-rs:RegionAppliedToDimensionsUnit="pixel" -xmp-mwg-rs:RegionAppliedToDimensionsW=6000 -xmp-mwg-rs:RegionAreaX=0.319270833 -xmp-mwg-rs:RegionAreaY=0.21015625 -xmp-mwg-rs:RegionAreaW=0.165104167 -xmp-mwg-rs:RegionAreaH=0.30390625 -xmp-mwg-rs:RegionName=John -xmp-mwg-rs:RegionRotation=0 -xmp-mwg-rs:RegionType="Face" myfile.xmp`

**Comment by martinhrpi** [comment]
So Digikam reads the mwg in xmp I provided to you. I copied the image and XMP, deleted the original and re-imported it and it worked.

Did you tell Digikam to read/write xmp in the settings?

**Comment by martinhrpi** [comment]
Btw I use the Beta. So Digikam 7.2 Beta 2.

and concerning exiftool: there is no way to convert your exported Data to mwg via exiftool as far as I found.

**Comment by RhetTbull** [comment]
> Did you tell Digikam to read/write xmp in the settings?
I did.  But I can't figure out how to make Digikam actually show the face regions.  (I don't use Digikam so not familiar with it -- just need something for testing)

**Comment by martinhrpi** [comment]
So let me make something for you :)

**Comment by martinhrpi** [comment]
So here is a Test-Picture from Google (Creative Commons). I imported the picture to Digikam, named the man "Test Man". Then I copied the picture away from Digitkam and delete it in Digikam. No data left in Digikam.

Then, with the help of exiftool

`exiftool -overwrite_original -all= `

I wiped the data from the picture file (so only the data from sidecar xmp) are left.

Then I re-Imported the picture and voila: after reading from the Sidecar: there was the face again with the same rectangle (I think) and the correct name.

![test](https://user-images.githubusercontent.com/19407684/104818356-62d49580-5827-11eb-892e-be0708b46d90.jpg)
![Bildschirmfoto 2021-01-16 um 18 11 54](https://user-images.githubusercontent.com/19407684/104818378-85ff4500-5827-11eb-8362-d8cac72b3e8a.png)
[test.txt](https://github.com/RhetTbull/osxphotos/files/5824816/test.txt)

**Comment by RhetTbull** [comment]
Thanks!

**Comment by RhetTbull** [comment]
After wasting many hours in following loop: 1) modify XMP, 2) load it in digikam, 3) curse, 4) delete digikam database 5) repeat, I've figured out that Digikam is reading the Microsoft MPRI region info and not the standard mwg region info.  

Given this knowledge, I think I can write this info to the XMP. I would still like to include mwg regions and I think osxphotos is correctly writing these but I have no way to test.  Lack of ability to test this feature is why I abandoned it months ago.  I wish a simple app existed that would read an XMP, validate it, and then draw/label face regions on the jpeg which I could use for testing.  I've searched Google and Github to no avail.  I'd write it except of course, it would only validate that I'm interpreting the spec correctly, not that I actually got it right.  While the standard case is fairly easy, handling all the different rotations / orientations for an image is tricky and that's what I need to test.

**Comment by martinhrpi** [comment]
I would love to use what you have built so far. As a Workaround, since Digikam seems to use microsoft but also writes mwg I could use osxphotos to write the face and get it out of Photos, and then use Digikam to make it "more available" aka transform it to the other Face-Standards.

**Comment by martinhrpi** [comment]
So XnView can read mwg. But not in the sidecar it seems, only in the Image-File. Tested with this file (delete the Microsoft Tags first).
![test](https://user-images.githubusercontent.com/19407684/104849320-4c8f0e00-58e9-11eb-9ccd-d64275c388ae.jpg)

**Comment by RhetTbull** [comment]
Thanks -- I had previous found & tried xnview but as you noted, I couldn't get it to read the sidecar.   I'll post a beta release as soon as I can get digikam to read the xmp generated by osxphotos.  Currently, exiftool says the XMP is valid but I cannot get digikam to read any XMP file it did not actually generate.

**Comment by martinhrpi** [comment]
So thank you very very much for the beta - happy to test it. As for sidecar-support on XnView: in the current Version it supports Sidecar files as I found out minutes ago. Testet it with the emptied image file and amp sidecar where I changed a view things via a text-editor. It worked so I think you could test the data with XnView!

![Bildschirmfoto 2021-01-17 um 18 04 49](https://user-images.githubusercontent.com/19407684/104850333-ce356a80-58ee-11eb-8e06-ae3a5a7db5e8.png)

**Comment by RhetTbull** [comment]
>edit: But it seems like XnView doesn't draw the face if the data is in the sidecar only.
This is the main issue.  I know the sidecar is valid because exiftool accepts it (and I consider exiftool the gold standard) but because I need to apply coordinate transformations for the face region I really need to see what some other app thinks the bounding box is.  I will try to apply the XMP, via exiftool, to the image file then see if XnView will show it.

**Comment by martinhrpi** [comment]
> I will try to apply the XMP, via exiftool, to the image file then see if XnView will show it.

I tried that with Test Man and it worked.

**Comment by RhetTbull** [comment]
I think mwg regions are correct now.  First photo is face region in Photos (stored by Photos as circle) and second is in XnView (XMP stores region as rectangle).  Still can't get Digikam to read the XMP though.  Now I'll work on confirming the MPRI regions are correct as that seems to be what Digikam uses.  These use a different coordinate system.

<img width="628" alt="Screen Shot 2021-01-17 at 4 30 42 PM" src="https://user-images.githubusercontent.com/41546558/104860806-cfac6600-58e1-11eb-851c-95eae1ce5bf8.png">

<img width="841" alt="Screen Shot 2021-01-17 at 4 31 38 PM" src="https://user-images.githubusercontent.com/41546558/104860816-d63add80-58e1-11eb-83fc-f58d4abc63e4.png">

**Comment by RhetTbull** [comment]
I think I now have the Microsoft Photo Regions working.  Identical results for both MWG regions and MPRI regions.  (Photo is creative commons from Flickr--one of the photos in the osxphotos test library).  First is MPRI region and second is MWG-RS region.

<img width="438" alt="Screen Shot 2021-01-17 at 6 22 19 PM" src="https://user-images.githubusercontent.com/41546558/104865713-924fd480-58f1-11eb-9be0-d3bb6be290cb.png">

<img width="433" alt="Screen Shot 2021-01-17 at 6 23 21 PM" src="https://user-images.githubusercontent.com/41546558/104865723-967bf200-58f1-11eb-9a56-abe1936a61d5.png">

**Comment by RhetTbull** [comment]
If both MWG-RS and MPRI face regions are in the XMP data, both XnView and Digikam

**Comment by RhetTbull** [comment]
@martinhrpi  I've added beta support for face regions in XMP in [v0.39.21](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.21).  Note, to use this you'll need to use the undocumented "--beta" flag when exporting.  e.g.

`osxphotos export /path/to/export --sidecar xmp --beta --sidecar-drop-ext`

I'd be happy for any feedback you have on whether this is working.  There may be issues with different photo orientations though the ones I've tested do work.  I still need to figure out why Digikam won't read the XMP sidecar.

**Comment by RhetTbull** [comment]
One known issue: the face region info in Photos is stored relative to the most recent version of the photo (e.g. if photo has adjustments/edits, face region applies to the edited photo, not the original).  osxphotos currently exports the same XMP data for both edited and original version so if you resized or cropped the photo, face regions for the original will be incorrect.  I still need to think about how to handle this as it will complicate the XMP sidecar logic to deal with this properly.  Happy for any thoughts on how to deal with this case.

**Comment by martinhrpi** [comment]
Uff! You are a genius! Testes ist with a test-database of about 60 photos, works perfect! I can‘t thank you enough!

Will test it now with a 16.000 picture data-base and will think about the edited ones, too. I scanned a lot of old pictures (yet another photos database) and edited them - so I have quite a good testing ground.

thank you so much so far - you saved me months of work!

**Comment by martinhrpi** [comment]
Oh wow so Digikam even uses the not yet named faces for their "unknown" category. So you get the ones you already named in MacOS Photos AND you get the ones that you didn't name in Photos. That is even more convenient.

To give you some perspective of your impact (at least on me):
- Mac User for over 15 years, first with iPhoto now with Photos.
- I also have a Synology NAS with their "Synology Moments" App (which could detect Faces but stores them in their own database) and Photostation (which is bad in detection but reads xmp faces).
- So I moved my photos from MacOS to the NAS and named about 40.000 pictures again in "Moments".
- Now Synology introduced a new App as part of their new OS as a beta (https://community.synology.com/enu/forum/20/post/139108) which is the badest part of both old apps (Moments/Photostation), since their is no migration of their database and no more Tag-Reading....
- So I had enough and switched to Digikam for naming pictures and "archiving" them in the picture by a well-known open standard (even though it seems with faces their are a 1000 standards).
- So with your help I can now export a rest of about 16.000 pictures with ALL of the data from MacOS in the matter of minutes and not months or weeks, not counting about 3.000 scanned Dias, negatives and so on.

Thank you again for that great help - and I will look into the edit thing :-)

**Comment by RhetTbull** [comment]
Success!  New version [v0.39.22](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.22) generates XMP sidecars that Digikam will read! Must still be used with --beta to enable this.  As soon as I get a little more testing I'll enable this by default.

**Comment by martinhrpi** [comment]
And I have found (I think) that it‘s not a only problem with pictures edited by OS Photo but also with selfies or pictures rotated outside of photos by exif info. So I don‘t think there is a fix - but this small percentage of wrongly drawn faces is nothing against the big advantages!

**Comment by RhetTbull** [comment]
@martinhrpi if you have one of the "incorrect" images you're willing to share, send me the image and XMP file to rturnbull+git@gmail.com and I'll see if I can figure it out.  I think I have an idea how to fix this (though there are some photos for which I cannot easily get the correct orientation due to how Photos stores this data).

**Comment by RhetTbull** [comment]
I think I've fixed the incorrect face regions for most photos -- tested with several different exif orientations.  See release [v0.39.23](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.23).  Photos rotated within Apple Photos app may still be incorrect as these photos do not change the orientation data in the database.  I think I can extract the correct orientation using the native PhotoKit interface but this will take more work.

**Comment by martinhrpi** [comment]
Ahhh saw your comment to late. I have just now collected 35 MB of problematic pictures. Would just Need to Upload those.

I will test the new Version and give feedback.

**Comment by martinhrpi** [comment]
YES! I can confirm the images that were incorrect because the camera set the rotation or iOS switched it because of selfie are now correct!

**Comment by RhetTbull** [comment]
Great! Thanks much for the testing and feedback.  I'll promote this new XMP format to "non-beta" in the next release.  Now I'll need to work on --no-person (#284) option because some people want to export XMP without details on people.

**Comment by martinhrpi** [comment]
Thank you for your great work! I will now export 24.000 pictures! Hooray :-)

**Comment by RhetTbull** [comment]
One more [update](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.24) --  I found the face regions weren't correct for a couple of EXIF orientations.  I've tested this with photos of every orientation I had in my library (only EXIF 1, 3, 6, 8) and they were all correct with this latest fix.

**Comment by RhetTbull** [comment]
Here's a quick script to get the "best" 3 photos of each possible orientation that also contain faces and print out the UUIDs in a form useable by --uuid-from-file for testing:

```python
import osxphotos

photos = osxphotos.PhotosDB().photos()
for orientation in range(1,9):
    # valid EXIF orientations are 1-8
    face_photos = sorted([p for p in photos if p.orientation == orientation and p.face_info], key=lambda p: p.score.overall, reverse=True)
    if face_photos:
        num_photos = 3 if len(face_photos) >= 3 else len(face_photos)
        for x in range(num_photos):
            photo = face_photos[x]
            print(f"#{photo.orientation}")
            print(photo.uuid)
```

**Comment by RhetTbull** [comment]
Fixed face regions for mirrored exif orientations in [v0.39.25](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.25).  All exif orientations have now been tested.

**Comment by RhetTbull** [comment]
[v0.40.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.00) now includes face regions by default in the XMP file (no need for --beta flag). All exif orientations seem to be working.  Some photos rotated in Photos.app may still be incorrect.

**Comment by wasauce** [comment]
@RhetTbull this is really impressive. Thanks for creating this functionality.

Is there a way to get this functionality working on the iphone -- I'm not familiar enough (yet) with differences between how the photos library on macosx exists vs photos on mobile.

**Comment by RhetTbull** [comment]
@wasauce osxphotos itself is a command line tool written in python and will not run on the iPhone. You can however connect an iPhone to  a Mac and copy the Photos database to the Mac (using something like [iMazing](https://imazing.com/)) then use osxphotos to read the database and output information about your photos. This is not very practical.

What specifically are you trying to do on the iPhone?

**Comment by wasauce** [comment]
@RhetTbull - my hope is to be apply to apply some of the same approach as what you have done here in an iOS app. Obviously not in python. Goal is to be able to in an app, with permissions granted, show the photos that have names/people identified -- and then help users create profiles with those photos for those people.

Are you aware of any projects that has made this work in swift / on an iOS device?

Thank you again!

**Comment by RhetTbull** [comment]
@wasauce I don't believe this will be possible on iOS due to sandboxing. On iOS, the only way to access Photos and associated metadata is via the PhotoKit API and Apple does not provide a way to access information about persons in the photos via the public API.  OSXPhotos works by directly reading the Photos.sqlite database in the Photos library.  The database exists on iOS but it is not possible (AFAIK) to read the database from an iOS app.

There is a Mac app, [Face Explorer](https://github.com/TimFelixBeyer/FaceExplorer) that uses the same techniques as OSXPhotos to read face data from the Photos library but again, this requires full access to the underlying database.

It would be great if Apple provided better APIs for working with Photos but so far they've not shown any interest in doing so.

**Comment by wasauce** [comment]
@RhetTbull - Thanks very much for your detailed reply. I greatly appreciate it. 

Yes, I read the PhotoKit documentation and via everything I see, I don't see Apple providing a way to access information about people in the photos.

Thank you for the link to Face Explorer -- interesting.

What you have built here is quite impressive. Thank you again for your replies!
