### ISSUE TITLE
XMP sidecar collisions

### ISSUE THREAD

**Issue by mccarverone** [RhetTbull/osxphotos#210]
I noticed that in case a live photo is exported with a sidecar, both .HEIC and .MOV share the same .XMP file. This is confusing for other software as it is treated as a sidecar for both medias at the same time.
I suggest a couple of solutions:

- using the standard photoshop:SidecarForExtension to specify which media the sidecar is actually pointing at (https://www.exiv2.org/tags-xmp-photoshop.html)
- duplicating the sidecar files keeping the original file extension so as to have both .HEIC.XMP and .MOV.XMP which is a widespread solution adopted by many DAM solutions

Didn't try other sidecar formats.

Thanks, regards

**Comment by RhetTbull** [comment]
@mccarverone Any reason not do to both of these?  E.g. add the `photoshop:SidecarForExtension` and also change the name to include original file extension?

**Comment by mccarverone** [comment]
Definitely not an expert here. Personally I'd keep sidecar files as lightweight as possible, but it is more a matter of personal taste. I also have a hard time finding references at all on the matter. Probably having both solutions can't hurt.

**Comment by neilpa** [comment]
Both seems like the right approach to me. I know that darktable defaults to appending `.xmp` while keeping the original file extension.
