### ISSUE TITLE
Export: / character in album name not handled properly when album name used as directory

### ISSUE THREAD

**Issue by garz75** [RhetTbull/osxphotos#213]
When exporting with these options : 
`$ osxphotos export . --update --folder "2019" --directory "{album,NoAlbum}"  --person-keyword --keyword-template "{label}" --skip-original-if-edited --exiftool  --filename "{created.strftime,%Y-%m-%d-%H%M%S}"`

I have an album in the 2019 folder called "2019-10/11 Paris Clermont" 
The export succeeds but this album content gets exported in the following directory:
./2019-10/11 Paris Clermont
Notice the extra directory created because of the / in the middle of the name.
I guess the proper way to handle this would be to issue a warning and to replace the "/" character, for example by ":", as the finder does when you create a file with a / in it from the finder... It is not perfect as it would still appear as a ":" in the shell via ls...

**Comment by RhetTbull** [comment]
@garz75 yep, definitely a bug.  I do check for valid filepaths:
https://github.com/RhetTbull/osxphotos/blob/eb00ffd73737ef4832229e4e6fd8dc4ccb0b8539/osxphotos/__main__.py#L2417-L2424

but didn't anticipate this issue.  Because I use `os.makedirs` to make the output directory, it happily creates the "extra" folder.  I think your suggestion of replacing the `/` with another character is likely the best bet.  This may require changes to the --update code as well...I'll investigate.

**Comment by RhetTbull** [comment]
In Catalina, Finder does show the "/" in place of the ":"

Finder:
<img width="569" alt="Screen Shot 2020-09-13 at 5 48 11 PM" src="https://user-images.githubusercontent.com/41546558/93033066-71950c80-f5e9-11ea-92c7-79a2670846ee.png">

Terminal:
<img width="723" alt="Screen Shot 2020-09-13 at 5 50 15 PM" src="https://user-images.githubusercontent.com/41546558/93033102-9d17f700-f5e9-11ea-8ea2-a5b9afc55c2a.png">

**Comment by RhetTbull** [comment]
@garz75 I've released a quick fix in [v0.34.2](https://github.com/RhetTbull/osxphotos/releases/tag/v0.34.2).  This fix changes "/" to ":" in album names.  However, a more complete fix will take additional time as I'll have to refactor the template code.  Currently the code that generates the template doesn't know if the template is for a directory (--directory) or to be used in a keyword, etc.  To do this right, the template code will have to replace "/" and any other "illegal" path characters only for directory templates and not for others.  It will have to do this for all possible template substitutions, not just albums. For example, Photos lets you use "/" in Folder names, keywords, etc. that could be used in --directory.

**Comment by neilpa** [comment]
> In Catalina, Finder does show the "/" in place of the ":"

Woah, crazy that Finder blindly replaces `:` in a directory name with `/` for display. Guess this [originates from the pre-OSX days](https://stackoverflow.com/a/13298479/1999152) which was before I switched to macs.

**Comment by RhetTbull** [comment]
I've refactored the template code to fix this, not only for album names, but also for other substitutions such as keywords and description.
