### ISSUE TITLE
Add --cleanup option to export (was: Possibility to delete missing on update?)

### ISSUE THREAD

**Issue by wormiedk** [RhetTbull/osxphotos#262]
I use OSXphotos to create a local copy of my images ordered by folder / album that I then use in Plex and other places. O

ne thing that I have been unable to find out is if I can make OSXphotos delete photos which are no longer in an album.

E.g. 
1) I use osxphoto export --update ... one day when my album contains 120 photos
2) I tidy up my album so it now onlu contains 60 photos in apple photos
3) I would like for osxphotos export --update to delete the 60 photos that I removed from the album in apple photos

**Comment by RhetTbull** [comment]
This is currently not possible with osxphotos.  It would be possible to implement this by having osxphotos keep a list of all files exported then go back and do a "clean up" pass comparing files in the directory against that list.

**Comment by narensankar0529** [comment]
+1 for this feature. This would be awesome!

**Comment by narensankar0529** [comment]
Regarding this feature - if I export without using --update and use --overwrite, would osxphotos essentially write out files that are currently in the database overwriting the existing files on disk (or hard links) and hence changing their modified time and leave the deleted files in the database untouched - is this correct? Then I could outside of osxphotos run a pass with find and delete files that are unmodified. Would this essentially work as a replacement till this feature is implemented within osxphotos?

**Comment by RhetTbull** [comment]
@narensankar0529 Yes, if you use --overwrite, osxphotos should overwrite the exported files but I don't think it necessarily change the modification time as osxphotos preserves the timestamps of the files in the Photos library (unless you use --touch-file which updates the files to use Photo creation date).  I think you'd have to do a recursive touch (e.g. `find . -type f -exec touch {} +`) on all files in the export folder, run osxphotos with --overwrite, then remove all untouched files.

There may be an easier solution: the new --report option generates a CSV report which includes the path to all files generated during the export.  You could parse that with `cut` to get the filenames and delete any file that's not in the list.

That's basically how I'll implement this feature -- while adding the code for --report, I created the ability to track every file (including sidecar files) that were generated during the export.  Given that ground work is done, this feature won't be difficult to implement (though I tend to only work on this on the weekends so it may be a week or two till I can get to it)

If you try this, be careful not to also delete the `.osxphotos_export.db` file if you want to be able to run --update again.

**Comment by RhetTbull** [comment]
Also, if you use the --report option, you don't need to run osxphotos with --overwrite because the report includes every file that was evaluated whether it was exported or skipped because it was up to date.

**Comment by narensankar0529** [comment]
Looking at the report file I notice something - why are the extensions not consistent in their case? I see jpg and JPG and mov and MOV, DNG and dng.

Also edited photos - I think almost all Portraits are like this - have jpeg instead of jpg

**Comment by RhetTbull** [comment]
osxphotos uses whatever extension Photos uses which is usually the original extension but there are certain cases where Photos changes the extension 

1. For photos that have been imported to Photos and are present in the local library (not missing), osxphotos copies those directly out of the library and those photos will have the original extension they were imported with.  
2. For photos that have been edited, Photos uses the .jpeg extension or .mov if it's a movie.
3. If you use --download-missing, Photos will sometimes rename the file with .jpeg instead of .JPG.
4. If you use --use-photokit, the PhotoKit API doesn't specify an extension -- in certain cases, it only provides the binary data for the image not an actual file.  In those cases, osxphotos uses an Apple [API](https://developer.apple.com/documentation/coreservices/1442744-uttypecopypreferredtagwithclass) to get the correct extension. In this case, it will often be .jpeg, .mov, etc.

**Comment by narensankar0529** [comment]
ok then - if I rename the extensions outside of osxphotos - would that still work? or will that break the export --update function ? This is just cosmetic of course but just curious

**Comment by RhetTbull** [comment]
Yes, it would break the ability to use --update.  osxphotos stores state information about the export in a `.osxphotos_export.db` file in the export folder.  It keeps track of each exported file by the relative path (to the export folder) of each exported file and stores this information in the export database.  Changing the file name would cause osxphotos to treat the file as missing when running --update.

However, osxphotos normalizes the filenames by converting to lowercase before checking so if you changed `.jpg` to `.JPG`, update would still work.  Changing `.jpeg` to `.JPG` though would break the update.

**Comment by narensankar0529** [comment]
Understood -

Here is the script I wrote to cleanup. Hopefully it is useful to others before you add the functionality -

/usr/local/bin/osxphotos export --update --not-hidden --not-shared \
  --export-as-hardlink --skip-original-if-edited --skip-raw --skip-bursts --sidecar xmp \
  --directory '{media_type}/{created.year}/{created.month}' --filename "{media_type}_${loggedInUser}_{exiftool:EXIF:DateTimeOriginal}" \
  --report $logFileName.csv \
  ${libraryExportDir} >> $logFileName 2>&1

EXITCODE=$?

if [ $EXITCODE=0 ]; then
  # Remove files removed from the photos library
  sed 1d $logFileName.csv | cut -f1 -d, > $logFileName.csv.1
  mv $logFileName.csv.1 $logFileName.csv
  mkdir -p ${libraryExportDir}/../to_delete.${loggedInUser}
  rsync -r --remove-source-files \
        --exclude-from=$logFileName.csv ${libraryExportDir} ${libraryExportDir}/../to_delete.${loggedInUser}
  find ${libraryExportDir} -type d -empty -delete
  NUMTODELETE=0
  NUMTODELETE=find ${libraryExportDir}/../to_delete.${loggedInUser} -type f | wc -l
  echo "Deleting $NUMTODELETE old files no longer in iCloud"
  rm -rf ${libraryExportDir}/../to_delete.${loggedInUser}/*
  rmdir -f ${libraryExportDir}/../to_delete.${loggedInUser}

  # fix up permissions
  echo "Fixing up permissions" >> $logFileName 2>&1
  chmod -R g+rw,o+r,+X ${libraryExportDir} >> $logFileName 2>&1
  chmod -RN ${libraryExportDir} >> $logFileName 2>&1
  chgrp -Rh staff ${libraryExportDir} >> $logFileName 2>&1
fi

**Comment by RhetTbull** [comment]
@narensankar0529 I added a --cleanup option in [v0.37.6](https://github.com/RhetTbull/osxphotos/releases/tag/v0.37.6) that should do what you want when used with --update.

**Comment by narensankar0529** [comment]
I am using the following command -

/usr/local/bin/osxphotos export --update --cleanup --not-hidden --not-shared \
  --export-as-hardlink --skip-original-if-edited --skip-raw --skip-bursts --sidecar xmp \

And I get an error - Incompatible export options

**Comment by RhetTbull** [comment]
I had made --clean-up incompatible with --export-as-hardlink thinking I didn't want cleanup to accidently delete the files in the Photos library that were linked to.  I realize now that's incorrect and cleanup would only remove the linked file in the export directory.  I'll fix that and push a new update.

**Comment by RhetTbull** [comment]
OK, I think this is fixed.  I've tested --cleanup with --export-as-hardlink and it seems to be working correctly now.

**Comment by narensankar0529** [comment]
Great! Looks good and works well for now!
