### ISSUE TITLE
XMP sidecar is written to on each export update even if no actual source files changed

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#265]
It appears that sidecar XMP files are touched or updated on each export even if no photo is changed or updated. Is this expected? This means that sync/backup has to update these files even if nothing actually changed in the Photos database

**Comment by RhetTbull** [comment]
That was the original design because it made the export logic easier when I added the the --update feature.  I can see the issue with synching or backup up the files though.  I took a look at the code and it won't be terribly difficult to avoid writing the XMP files if nothing has changed.

**Comment by narensankar0529** [comment]
It would be great if there is a flag for controlling this behavior if the original behavior is still desired.

The issue is if I want to backup a copy of photos to something like aws glacier or deep archive which have a minimum storage time requirement then updating the xmp on every export will cause the xmp to be uploaded again and increase the storage costs.

Thanks!
—————

Naren Sankar

**Comment by RhetTbull** [comment]
I've fixed this in [v0.36.24](https://github.com/RhetTbull/osxphotos/releases/tag/v0.36.24).  sidecar files will only be written if the sidecar file has changed (e.g. modification time is different) or the photo's metadata has changed.
