### ISSUE TITLE
GPS info in XMP doesn't use GPSCoordinate format

### ISSUE THREAD

**Issue by jstrine** [RhetTbull/osxphotos#269]
Exiv2 and exiftool incorrectly report the GPS information in the XMP sidecar.  In my testing they would ignore the GPSLatitudeRef and GPSLongitudeRef such that all coordinates were E and N.

It seems to be related to the format of the EXIF GPS data when in the XMP sidecar.  The spec seems to indicate that the GPSLatitude and GPSLongitude should be in GPSCoordinate format:  https://www.exiv2.org/tags-xmp-exif.html

The best explaination I found of the GPSCoordinate format is at:  www.cipa.jp/std/documents/e/DC-X010-2017.pdf.  This doc also indicates that the GPSLongitudeRef an GPSLatitudeRef are no longer used.

A photo tagged at Niagara Falls, Canada...

**The incorrect format:**
```
<exif:GPSLongitudeRef>W</exif:GPSLongitudeRef>
<exif:GPSLongitude>79.0770034790039</exif:GPSLongitude>
<exif:GPSLatitude>43.07640075683594</exif:GPSLatitude>
<exif:GPSLatitudeRef>N</exif:GPSLatitudeRef>
```
```
% exiftool DSCF0034.JPG.xmp | grep GPS
GPS Longitude                   : 79 deg 4' 37.21" E
GPS Latitude                    : 43 deg 4' 35.04" N
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Position                    : 43 deg 4' 35.04" N, 79 deg 4' 37.21" E
```

**The correct format:**
```
<exif:GPSLongitude>79,4.620208740234375W</exif:GPSLongitude>
<exif:GPSLatitude>43,4.58404541015625N</exif:GPSLatitude>
```
```
% exiftool DSCF0034.JPG.xmp | grep GPS
GPS Longitude                   : 79 deg 4' 37.21" W
GPS Latitude                    : 43 deg 4' 35.04" N
GPS Latitude Ref                : North
GPS Longitude Ref               : West
GPS Position                    : 43 deg 4' 35.04" N, 79 deg 4' 37.21" W
```

**Comment by tuomassa** [comment]
<exif:GPSLongitude>79,4.620208740234375W</exif:GPSLongitude>
<exif:GPSLatitude>43,4.58404541015625N</exif:GPSLatitude>

can this be correct? Does it mean 79 degrees, 4 minutes, 620208740234375 seconds? Seconds should have decimal point somewhere?

**Comment by jstrine** [comment]
It's expressed in DDD,MMM.mmm where
DDD = number of degress
MMM = number of minutes
mmm = fractions of minutes

So in this case, it's 79 degress and 4.620208740234375 minutes.
To get seconds, it would be 0.620208740234375 x 60 = 37.212.. seconds

**Comment by tuomassa** [comment]
Ahh right it was DDM and not DMS, which I thought was more common. Thanks for fast answer and sorry for bothering!
