### ISSUE TITLE
Add "--sync-existing" option 

### ISSUE THREAD

**Issue by jotzet79** [RhetTbull/osxphotos#273]
I have the following use case: I have currently ~30k of (legacy) pictures on my drive outside of Photos.app management. I have curated them by syncing every timestamp, adding location data, syncing timezones, converted / muxed / deinterlaced every non-h264 Video to mp4, added proper DTS / Lat/Lon also to Video, tags for certain events / people etc... I manage them in the same way on file sys as in Photos (i.e. YYYY/YYYY-MM - Albumname).

Now I'm going to import all these media assets to Photos, and would like to SYNC the ones existing on the file system with the ones imported and then exported again to the Exports folder. This would mean that the database file should be created prior to export and consider the files which are already there. This would further mean that there should be a diff by hash (there are two options to accomplish this: the file itself or the image information WITHOUT any metadata).

Currently this is not done and would possibly break existing functionality / database files, referencing osxphotos help

> To determine which files need to be updated, osxphotos
> stores file signature information in the '.osxphotos_export.db' database. The
> signature includes size, modification time, and filename.  In order to
> minimize run time, _**--update does not do a full comparison (diff) of the files
> nor does it compare hashes of the files**_.  In normal usage, this is sufficient
> for updating the library. You can always run export without the --update
> option to re-export the entire library thus rebuilding the
> '.osxphotos_export.db' database.

Thank you,
Joachim

**Comment by RhetTbull** [comment]
Hi Joachim.  I don't quite understand the use case.  Let me restate what I think you're asking:

1. Files exist outside Photos (for example /path/to/photos)
2. You are going to import all those files into Photos
3. You are then going to export all photos from Photos back to /path/to/photos but don't want the 30K photos that already exist there to be re-exported.

If this is the case, I think that running osxphotos with the `--update` flag will do what you want.  As long as the export directory structure is identical, osxphotos will see the photo is there and skip exporting it as it's signature will match the one imported to Photos.  This works even if the export database doesn't exist (as it won't in your case).  You'll need to use the `--directory` option to ensure the files are exported to the same directory and they'll have to be in the same folder/album structure in Photos.  For example:

`osxphotos export /path/to/Exports --update --directory "{created.year}/{created.year}-{created.mm} - {album}"`

I recommend you copy a small subset of these photos to a separate path then do a test to verify.  You can create an alternate Photos library for testing also by holding down the "option" key while launching Photos.

**Comment by RhetTbull** [comment]
Did you find a way to resolve this?
