### ISSUE TITLE
add a command line option to export labels as keywords 

### ISSUE THREAD

**Issue by finestream** [RhetTbull/osxphotos#293]
Add an option

  --label-keyword                 Use label names as keyword/tag when exporting metadata.

Enhancement seems easy as similar code as what is currently used for albums un person could be re-used for labels.

A workaround is also possible with the option --keyword-template

**Comment by RhetTbull** [comment]
`--keyword-template "{label}"` does this.  The `--person-keyword` and `--album-keyword` were added before I added the template system. The template system is much more versatile and in general, I prefer flexible options over lots of single-use options.

**Comment by finestream** [comment]
Thank you for your quick answer. Agree the template system is a good and clean solution. 

I still have to learn how to properly use it, for instance I am not able to add all keywords and all labels by solely using the template options. It seems that whenever I combine tags in the template I get unexpected behaviours:
* {keyword}{label} generates all permutations ("keyword1label1", "keyword1label2", ... , "keyword2label1", "keyword2label2", ...}
* {, +keword},{, label} generates a single long label containing comma-separated keywords / label

If you point me in the right direction, I would be pleased to contribute a relevant proposal for a documentation improvement.

**Comment by RhetTbull** [comment]
Each time you use the `--keyword-template` option, it generates a new keyword or list of keywords from the template.  The key is you can use the option multiple times as in:

`--keyword-template "{label}" --keyword-template "{keyword}"

Agree the docs need some clarification there.

The `--keyword-template` option itself is documented here:
https://github.com/RhetTbull/osxphotos/blob/3c14ace8264abd6dbada326bf4ec4caff948b1da/osxphotos/__main__.py#L1360-L1372

and the longer text about the template system is documented here (this part of the code is a bit messy and on my to-do list is to refactor all the help text)

https://github.com/RhetTbull/osxphotos/blob/3c14ace8264abd6dbada326bf4ec4caff948b1da/osxphotos/__main__.py#L168-L180

**Comment by finestream** [comment]
Thank you for pointing in this. direction, I missed totally the help line on multiple templates, that in fact is the key. 

I have suggested an incremental edit to README.md in the examples section (this is where I looked for help) and the Templating System help. See [https://github.com/finestream/osxphotos](url)

**Comment by RhetTbull** [comment]
@finestream I don't see any PRs (pull requests).  If you made the changes in your fork, see here for how to open a PR:

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by RhetTbull** [comment]
Thanks for the PR! I merged your fix.
