### ISSUE TITLE
remove duplicate keywords

### ISSUE THREAD

**Issue by finestream** [RhetTbull/osxphotos#294]
before adding the keywords to the sidecar or the image, sort and remove possible duplicate keywords. Duplicate keywords might have originated from pre-existing keywords in the original, --album-keyword and --person-keyword.

(issue is minor)

**Comment by RhetTbull** [comment]
Good catch -- thanks.  Easy fix.  

something like `keyword_list = list(set(keyword_list))` after this line should do the trick:

https://github.com/RhetTbull/osxphotos/blob/3c14ace8264abd6dbada326bf4ec4caff948b1da/osxphotos/photoinfo/_photoinfo_export.py#L1266

**Comment by finestream** [comment]
While you are at it, it could also be a good idea to move the sort from

[https://github.com/RhetTbull/osxphotos/blob/3c14ace8264abd6dbada326bf4ec4caff948b1da/osxphotos/photoinfo/_photoinfo_export.py#L1231](url)

to the new line (or remove it altogether)

**Comment by RhetTbull** [comment]
Yes, the sorted there is completely unnecessary as person_list is already sorted earlier in the code.  But if I eliminate duplicates (using `set()`) there's no preservation of order so I don't need any of the sorts that occur in this method.
