### ISSUE TITLE
Possibile to expose SearchInfo labels and other items to XMP?

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#302]
Is it possible to output the ML labels and other items exposed in the SearchInfo to either XMP or EXIF?

**Comment by RhetTbull** [comment]
You can use `--keyword-template` to output the labels from SearchInfo to XMP and exif like this:

`--keyword-template "{label}"`  or `--keyword-template "{label_normalized}"` if you'd rather have the normalized (all lower case) versions

I don't currently have plans to expose the other SearchInfo doing so would not be difficult if there was a good use case.  Which of the other SearchInfo would you want and which field in the XMP/exif would you put it in?

**Comment by narensankar0529** [comment]
Great! So that works, but curious as to why it is written to the Digikam portion of XMP - digiKam:TagsList v/s the core dc:Subject as per - https://www.exiv2.org/metadata.html

Also appears that while items like Holidays and Seasons might be valuable, Photos does not seem to do a great job of actually dealing with these tags in terms of having only a few Holidays supported. And Seasons covers only the 4 basic ones. So only Labels are good enough. Thanks!

**Comment by RhetTbull** [comment]
The XMP fields were a best guess at the time. I think I used a DigiKam XMP file as an example for the template.  I'm happy to update the XMP template to output all the keywords to dc:Subject if that's more correct.  I'm not an expert on XMP so happy for any suggestions on how to improve the output.

**Comment by narensankar0529** [comment]
dc:Subject is supported by all readers since that is in the standard namespace. Look at description from exiftool - 

https://exiftool.org/TagNames/XMP.html

Here is a Lightroom example -

<dc:subject>
            <rdf:Bag>
               <rdf:li>Flower C3</rdf:li>
               <rdf:li>Flower</rdf:li>
               <rdf:li>Flowers</rdf:li>
               <rdf:li>Flower C3 DS40402</rdf:li>
               <rdf:li>Delicate</rdf:li>
               <rdf:li>Flower Petal C3</rdf:li>
               <rdf:li>Flower Petal</rdf:li>
               <rdf:li>Flower Petals</rdf:li>
               <rdf:li>Flower Petal C3 DS40402</rdf:li>
               <rdf:li>Case YYYYYY</rdf:li>
               <rdf:li>Standardised Naming Convention</rdf:li>
            </rdf:Bag>
         </dc:subject>

**Comment by RhetTbull** [comment]
Release [v0.38.13](https://github.com/RhetTbull/osxphotos/releases/tag/v0.38.13) fixes XMP:Subject to match IPTC:Keywords for both json and XMP sidecars and --exiftool.  Whatever keywords is set to: e.g. if you use --person-keyword or --keyword-template, XMP:Subject (dc:Subject) will be set accordingly.

**Comment by RhetTbull** [comment]
@narensankar0529 I added the following searchinfo values to the template system in [v0.38.16](https://github.com/RhetTbull/osxphotos/releases/tag/v0.38.16):
- `{searchinfo.season}`
- `{searchinfo.holiday}`
- `{searchinfo.activity}`
- `{searchinfo.venue}`
- `{searchinfo.venue_type}`

**Comment by narensankar0529** [comment]
Is it possible to do the following - 

--keyword-template "{label_normalized},{searchinfo.venue_type}"

**Comment by RhetTbull** [comment]
Yes, but not as you wrote it.  You can specify multiple `--keyword-template` options as in:
`--keyword-template "{label_normalized}" --keyword-template "{searchinfo.venue_type}"`

**Comment by narensankar0529** [comment]
ok. Great! Thanks. I assume if there is no venue_type - then the output would be ""?

**Comment by RhetTbull** [comment]
Yes, in `--keyword-template` evaluates to nothing, then no keyword is output for that template.  This behavior is different templates used for --directory and --filename as those will evaluate to a default value; default is "_" but can be specified using the template syntax -- see Templating System in the README for details.

**Comment by narensankar0529** [comment]
Great! Thanks a lot. this is perfect
