### ISSUE TITLE
--exiftool-path broken

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#308]
Getting error - Incompatible export options: --exiftool-path must be used with at least one of: --exiftool, --exiftool-merge-keywords, --exiftool-merge-persons.

And this is because I need to use --filename "{exiftool:EXIF:Make}

So when exiftool keywords are used - then path to exiftool should be allowed.

**Comment by RhetTbull** [comment]
Thanks -- good catch.  I removed the constraint in [v0.38.22](https://github.com/RhetTbull/osxphotos/releases/tag/v0.38.22)
