### ISSUE TITLE
Add --json option to export report

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#309]
When using --report in the CLI, which outputs a CSV report of all files exported, the --json option should output a json report instead.  This would be consistent with how `osxphotos --json query` works.

**Comment by oPromessa** [comment]
# Suggestion for an alternative: 
* use [mlr: Miller which is like awk, sed, cut, join, and sort for data formats such as CSV, TSV, JSON, JSON Lines, and positionally-indexed.](https://github.com/johnkerl/miller)
# Example 1:
```sh
$ osxphotos query  --person "Someone" > person.csv
$ mlr --icsv --ojson cat person.csv | more
[
{
  "uuid": "20693557-4B84-4EE6-B0A6-CCC2F2FCE24F",
  "filename": "IMG_8690.JPG",
  "original_filename": "IMG_8690.JPG",
  "date": "2016-07-03T18:53:56+01:00",
  "description": "                               ",
  "title": "",
  "keywords": "(...)",
  "albums": "(...)",
  "persons": "Someone, Other",
(...)
$  mlr --icsv --ojson cut -f persons person.csv 
[
{
 "persons": "Someone, Other",
},
{
  "persons": "YetAnother"
},
(...)
```

# Example 2: working on the CSV report:
```sh
$ mlr  --icsv --ojson cut -f filename,skipped   report.csv
(...)
{
  "filename": "/Volumes/photo-1/(...)/IMG_20210703_210206_1.JPG",
  "skipped": 1
}
]

$ mlr --icsv --ojson filter '$skipped == 1'  report.csv
(...)
{
  "filename": "/Volumes/photo-1/(...)/_79A9942APB.jpg",
  "exported": 0,
  "new": 0,
  "updated": 0,
  "skipped": 1,
(...)
```

**Comment by RhetTbull** [comment]
Thanks! mlr looks like a great utility -- I wasn't aware of this. I do have a design for a new report writer that will improve the CSV reporting and also make it easy to implement a json option so I may still implement this.  The current report writer doesn't write the report until the entire export is finished. That means that if osxphotos crashes or the export is terminated, no report is written, even for the files already exported. The new design will write the results to the report during the export (and I've got a design to use a queue so this works with the multiprocessing option eventually).

**Comment by RhetTbull** [comment]
Done in v0.49.0 which also adds support for SQLite reports and adds the `osxphotos exportdb --report` command to re-create a report file after the export is completed (in case you forgot to use the `--report` option.
