### ISSUE TITLE
{modified.sec} seems to not be working in filename template

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#312]
I am trying to use {modified.sec} in the output file name template.

--filename "{exiftool:EXIF:Make}_{media_type}_{created.yy}{created.mm}{created.dd}_{modified.sec}"

But osxphotos is outputting _ instead.

photo/2014/October/24/__photo_141024__ (30).json:[{"SourceFile": "__photo_141024__ (30).JPG", "ExifToolVersion": "12.00", "FileName": "__photo_141024__ (30).JPG", "Keywords": ["Fall", "adult cat", "animal", "cat", "feline", "mammal"], "Subject": ["Fall", "adult cat", "animal", "cat", "feline", "mammal"], "TagsList": ["Fall", "adult cat", "animal", "cat", "feline", "mammal"], "DateTimeOriginal": "2014:10:24 15:03:50", "CreateDate": "2014:10:24 15:03:50", "OffsetTimeOriginal": "+00:00", "DateCreated": "2014:10:24", "TimeCreated": "15:03:50+00:00", "ModifyDate": "2014:10:24 15:03:50"}]

**Comment by RhetTbull** [comment]
Not all files have a modified time.  If the file is edited, modified time is null.

**Comment by RhetTbull** [comment]
In your example json, you'll see that CreateDate and ModifyDate are the same.  When exporting, Photos sets ModifyDate to CreateDate if the photo has not been modified though internally, Photos stores a null modification date if there are no edits (see issue #247 for the details).  I emulate this behavior in the json export but not in the template.  I suppose the best behavior is to emulate this behavior in the {modified} template so that if there's modification date, it uses the create date.  

Does this fit your use case?

**Comment by narensankar0529** [comment]
Do you mean if there is no modification date then use create date right?

If so then yes that is ok. I am just trying to use the modified second as a way to prevent file name collision.

Actually wondering if it is possible to add a sequence number to the template. Something similar to what Lightroom does. You can specific a starting number and then the sequence updates by one for every file exported. So this way collisions in file names are avoided globally rather than on a per folder basis.

Thanks!
—————

Naren Sankar

**Comment by RhetTbull** [comment]
> Do you mean if there is no modification date then use create date right?

Yes.  That's what the json export does but the template doesn't currently do that.

I've considered doing a global sequence number or even a per folder sequence number but given the current implementation of the template system and the --update code, it would require some significant work.  The update system in particular would have to be able to map the sequence number to a photo in a deterministic way for every export.

**Comment by narensankar0529** [comment]
Ok. Yes I understand that. Did not think of the update. It will be very problematic to make it work reliably I guess. Can only work for full export.

For now I will just use the modified or created seconds to disambiguate. That should take care of everything except for bursts.

Thanks!
—————

Naren Sankar

**Comment by RhetTbull** [comment]
When I get a chance I'll update the {modified} template to use created time if modified time is null.

If your primary need is to avoid collisions, osxphotos will add (1), (2), etc. to the end of the filename if it detects a file with the same name already exists.  (This is what Photos does as well).  This works with --update which searches for the correct file when updating.

Each photo also has a universally unique identifier (UUID) which is how Photos (and osxphotos) manages photos internally.  I could expose that to the template system (issue #314) to allow a guaranteed unique identifier to be added to each file name.  The UUID has format of:

`44107FE0-AA2E-4E25-A5F3-60CA63109141`

**Comment by narensankar0529** [comment]
The primary need is to avoid collisions but globally amongst many libraries. So that is why I am trying to use the seconds - so that way it is highly unlikely that everyone in my family took a picture at the exact same second. The current system that osxphotos uses still causes collisions across libraries.

UUID would be good. Maybe the lowest 12 digits or something.

Thanks!
—————

Naren Sankar

**Comment by RhetTbull** [comment]
In [v0.39.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.3) modified date templates will use creation date if photo has not been modified.

**Comment by RhetTbull** [comment]
I added `{uuid}` template in release [v0.39.5](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.5).  Will work on a short uuid at some future point (#314).
