### ISSUE TITLE
Provide access to visibility state in PhotoInfo

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#334]
From @Rott-Apple

>Since only one frame of a burst photo is visible and the rest are hidden, all the hidden frames can be found with `ZGENERICASSET.ZVISIBILITYSTATE = 2` (Visible items have value 0)

PhotoInfo currently provides access to hidden state via `ZGENERICASSET.ZHIDDEN` but might be useful (especially for bursts) to also have access to `ZVISIBILITYSTATE`

**Comment by Rott-Apple** [comment]
I meant to point out that there is a difference between hidden and not visible: A file can be hidden (as in Image > Hide) with ZHIDDEN = 1, but have ZVISIBILITYSTATE = 0 (Visible).
![Screen Shot 2021-01-05 at 19 49 18](https://user-images.githubusercontent.com/67875570/103657394-deb12100-4f8f-11eb-9dd1-f426700ebd7a.png)

**Comment by RhetTbull** [comment]
@all-contributors please add @Rott-Apple for research
