### ISSUE TITLE
Warning on M1 

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#347]
2021-01-11 16:44:47,940 - WARNING - photosdb.py - 90 - WARNING: This module has only been tested with MacOS 10.[12, 13, 14, 15, 16]: you have Darwin, OS version: 1

How can I help to test on a Apple M1 system?

**Comment by RhetTbull** [comment]
> How can I help to test on a Apple M1 system?

Yes!  Would appreciate any feedback on M1.  

Looks like you're running 11.1 and a native python which is reporting 11.1 instead of 10.16.  I'll need to add some code to check for this.

If you're willing to clone the github repository and run the tests suite, any feedback would be very useful.  Probably better if I fix the version check first.

`git clone git@github.com:RhetTbull/osxphotos.git`
`cd osxphotos`
`python3 -m venv .venv`
`source .venv/bin/activate`
`python3 setup.py develop`
`python3 -m pip install pytest`
`python3 -m pip install pytest-mock`
`pytest`

**Comment by narensankar0529** [comment]
No problem. Cloning takes forever :-( but it is going through the process now. So when you fix the warning I will run the tests. So far it seems to work without issues. But of course I am not using it for exporting jpegs etc so there might be corner cases on a M1 so it would be good to run the test cases.

**Comment by RhetTbull** [comment]
> Cloning takes forever 

Yeah...unfortunately the repo is huge because it contains test libraries for every version of macOS since 10.12 and each is different and needs many different types of media (live photos, slowmo, etc)

**Comment by narensankar0529** [comment]
I am guessing I need to wait for your version check fix -

_________________________________________________________________________________________ test_from_to_date __________________________________________________________________________________________

    def test_from_to_date():
        import osxphotos
        import datetime as dt

        photosdb = osxphotos.PhotosDB(PHOTOS_DB)

        photos = photosdb.photos(from_date=dt.datetime(2018, 10, 28))
        assert len(photos) == 6

        photos = photosdb.photos(to_date=dt.datetime(2018, 10, 28))
        assert len(photos) == 7

        photos = photosdb.photos(
            from_date=dt.datetime(2018, 9, 28), to_date=dt.datetime(2018, 9, 29)
        )
>       assert len(photos) == 4
E       assert 0 == 4
E        +  where 0 = len([])

tests/test_catalina_10_15_5.py:1043: AssertionError
---------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------
2021-01-12 11:08:32,097 - WARNING - photosdb.py - 90 - WARNING: This module has only been tested with MacOS 10.[12, 13, 14, 15, 16]: you have Darwin, OS version: 1
----------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------
WARNING  root:photosdb.py:90 WARNING: This module has only been tested with MacOS 10.[12, 13, 14, 15, 16]: you have Darwin, OS version: 1
========================================================================================== warnings summary ==========================================================================================
tests/test_cli.py::test_osxphotos
tests/test_cli.py::test_osxphotos
  /Users/nsankar/projects/osxphotos/.venv/lib/python3.9/site-packages/bitstring-3.1.7-py3.9.egg/bitstring.py:2: DeprecationWarning: invalid escape sequence \

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================================================== short test summary info =======================================================================================
FAILED tests/test_bigsur_10_16_0.py::test_from_to_date - assert 0 == 4
FAILED tests/test_bigsur_10_16_0_1.py::test_from_to_date - assert 0 == 4
FAILED tests/test_catalina_10_15_1.py::test_from_to_date - assert 0 == 4
FAILED tests/test_catalina_10_15_4.py::test_from_to_date - assert 0 == 4
FAILED tests/test_catalina_10_15_5.py::test_from_to_date - assert 0 == 4
====================================================================== 5 failed, 1090 passed, 52 skipped, 2 warnings in 26.82s =======================================================================

**Comment by RhetTbull** [comment]
I fixed the version check in [v0.39.16](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.16).  You can do a `git pull` to get the latest changes into your clone.  With the new fix you shouldn't see the warning when running osxphotos on 11.0 or 11.1.

Then, we you re-test, use this command:

`OSXPHOTOS_TEST_CONVERT=1 pytest`

This will tell the test suite to test the `convert_to_jpeg` code (some of the 52 tests that were skipped in your results above).  You'll still get some skipped tests since some of the tests are dependent on my personal library and those won't run. 

The 5 failed tests are a real mystery -- that same tests exists in other test files that didn't fail and I can't think of why it would fail on M1.  Perhaps something to do with time epoch as they're all calculating date ranges.  I'll have to dig into this.

**Comment by RhetTbull** [comment]
I think I figured it out -- those tests all had dependencies on time (query photos from a certain date range) and you must be in a different timezone than I am so the query failed to find the right number of photos. I added the timezone to the tests so hopefully they should pass now.  Please do a `git pull` and re-run the tests. Thanks!

**Comment by narensankar0529** [comment]
Have a failure and some skipped tests
[testrun.log.txt](https://github.com/RhetTbull/osxphotos/files/5800420/testrun.log.txt)

**Comment by RhetTbull** [comment]
Thanks -- very helpful!  Much better than I expected.  Could you try the following command, from inside the osxphotos source code directory:

`osxphotos export --db tests/Test-10.15.6.photoslibrary --convert-to-jpeg --uuid D05A5FE3-15FB-49A1-A15D-AB3DA6F8B068 --verbose ~/Desktop`

(The last argument is export part -- of course you could substitute the path of your choice)

Then tell me the size of the resulting `DSC03584.jpeg` file and open it in preview to see if it appears to be a valid file.

**Comment by narensankar0529** [comment]
Size is 7792709

Valid file - 4000 × 6000 pixels. Inspector seems to show everything good

**Comment by RhetTbull** [comment]
Interesting -- thanks! I'll update the test for M1.  This is a RAW file that on x86 Mac compresses to 14MB with "best quality" setting.  Your M1 Mac compresses it to about half that size with the same setting.

**Comment by RhetTbull** [comment]
`git pull` should fix that last failing test.

**Comment by narensankar0529** [comment]
That is completely weird! I would have assumed that the algorithms they used would be the same. Not sure why there is such a huge difference between x64 and arm64

**Comment by RhetTbull** [comment]
>That is completely weird! I would have assumed that the algorithms they used would be the same. Not sure why there is such a huge difference between x64 and arm64

Agree! This is something worth exploring as I'll want to make sure the convert-to-jpeg code is respecting the user's quality preference.  It may be that the M1 is so much better optimized for these types of algorithms that they can achieve better compression. But that much of a change is unexpected.

**Comment by narensankar0529** [comment]
1110 passed, 38 skipped, 2 warnings

Log attached
[testrun.log.txt](https://github.com/RhetTbull/osxphotos/files/5802960/testrun.log.txt)

**Comment by narensankar0529** [comment]
Is this good to say M1 can be supported?

**Comment by RhetTbull** [comment]
Yes, with all tests passing I think we can say osxphotos is working as expected on M1!  The two warnings have to do with one of the external libraries I'm using [bitstring](https://github.com/scott-griffiths/bitstring/issues/207) and don't affect performance.  The skipped tests are tests that will run only on my personal library because they need photos in the library to run.  Thanks very much for your help!

**Comment by narensankar0529** [comment]
Great! I will keep the environment available. So if there is any feature you want to test on the M1, let me know and I can run the tests again.

**Comment by narensankar0529** [comment]
I think there is a bug in the conversion algorithm in osxphotos perhaps or in the API it calls - 

I exported the DNG and used preview to output a "best: quality output jpeg on the m1 and it produces a file with size 14671087 which is just a minor difference from my x64 MacBook Pro - 14674006.

So perhaps your call is not generating "best quality" some how on the M1.

**Comment by narensankar0529** [comment]
Using identify - it shows both files are at 100% so it does seem export at best quality.

**Comment by RhetTbull** [comment]
That's very odd.  I'm quite surprised that two jpegs could be so different in size with the same settings.  It's possible the M1 optimized algorithm is just much better at the compression but it's also possible there's a bug in the code osxphotos calls.  osxphotos uses [Core Image CIContext.writeJPEGRepresentationOfImage](https://developer.apple.com/documentation/coreimage/cicontext/1642218-writejpegrepresentationofimage?changes=l_1&language=objc) to do the compression.  I've not been able to find any clues in the Apple documentation that would indicate a difference.
