### ISSUE TITLE
Documentation typo for --jpeg-ext EXTENSION 

### ISSUE THREAD

**Issue by davidjroos** [RhetTbull/osxphotos#359]
Minor one - the description for the jpeg-ext command uses **jpg-ext** instead of **jpeg-ext**

**--jpeg-ext** EXTENSION
Specify file extension for JPEG files. Photos uses .jpeg for edited images but many images are imported with .jpg or .JPG which can result in multiple different extensions used for JPEG files upon export.  Use **--jpg-ext** to specify a single extension to use for all exported JPEG images. Valid values are jpeg, jpg, JPEG, JPG; e.g. '**--jpg-ext jpg'** to use '.jpg' for all JPEGs.

**Comment by RhetTbull** [comment]
Thanks!  I've fixed this in [v0.40.6](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.6). I went back & forth on what to call this feature and settled on jpeg-ext as Photos defaults to jpeg but never fixed the docs.
