### ISSUE TITLE
Test Update on MacOS 11.2 and Apple Silicon M1

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#360]
=============================================================================================== warnings summary ================================================================================================
tests/test_cli.py::test_osxphotos
tests/test_cli.py::test_osxphotos
  /Users/nsankar/projects/osxphotos/.venv/lib/python3.9/site-packages/bitstring-3.1.7-py3.9.egg/bitstring.py:2: DeprecationWarning: invalid escape sequence \

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================= 1119 passed, 52 skipped, 2 warnings in 28.80s =================================================================================

osxphotos version 0.40.5

**Comment by RhetTbull** [comment]
Thank-you!  I've added 11.2 to the tested versions list so osxphotos won't throw a warning.
