### ISSUE TITLE
--convert-to-jpeg outputs wrong file extension (was --convert-to-jpeg messes up videos)

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#366]
--convert-to-jpeg seems to output videos with .jpg file extension. All of the original extensions are broken.

 /Volumes/PhotoSync/FotosOutput/Fotos.nsankar/video/2021/January/01/ exiftool video_n_210101_CA5042B4-C3B8-41D8-8831-2C10C561D0BE_edited.jpg
ExifTool Version Number         : 12.16
File Name                       : video_n_210101_CA5042B4-C3B8-41D8-8831-2C10C561D0BE_edited.jpg
Directory                       : .
File Size                       : 477 MiB
File Modification Date/Time     : 2021:01:01 00:02:06+08:00
File Access Date/Time           : 2021:01:01 00:02:06+08:00
File Inode Change Date/Time     : 2021:02:06 23:49:31+08:00
File Permissions                : rw-rw-r--
File Type                       : MOV
File Type Extension             : mov
MIME Type                       : video/quicktime
Major Brand                     : Apple QuickTime (.MOV/QT)
Minor Version                   : 0.0.0
Compatible Brands               : qt
Media Data Size                 : 499782013
Media Data Offset               : 36
Movie Header Version            : 0
Create Date                     : 2020:12:31 16:16:45
Modify Date                     : 2020:12:31 16:17:02
Time Scale                      : 600
Duration                        : 0:03:16
Preferred Rate                  : 1
Preferred Volume                : 100.00%

**Comment by narensankar0529** [comment]
I am using the following command line options -

    --jpeg-ext jpg \
    --convert-to-jpeg \
    --jpeg-quality 0.85 \

**Comment by RhetTbull** [comment]
Thanks for bug report!  The videos weren't actually getting converted but the extension was wrong as you noted.  This was introduced accidently when I added --jpeg-ext.  I think it's fixed now in [v0.40.10](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.10).

**Comment by narensankar0529** [comment]
Great! Fixed now

**Comment by narensankar0529** [comment]
So it seems that videos that are edited are still output with jpg extension. So - video_n_210101_CA5042B4-C3B8-41D8-8831-2C10C561D0BE_edited

**Comment by RhetTbull** [comment]
Are you using the most recent version [v0.40.13](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.13)?  I made recent changes to the --jpeg-ext code for issue #374 This particular part of the code has proven very difficult to get right!

**Comment by RhetTbull** [comment]
I found the problem --working on a fix.

**Comment by RhetTbull** [comment]
I *think* I've finally fixed this once and for all. I also added a couple of tests for this specific bug should it get re-introduced.  Let me know if you still see any issues with [v0.40.14](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.14)
