### ISSUE TITLE
Explicitly write Description to Caption-Abstract field?

### ISSUE THREAD

**Issue by neilpa** [RhetTbull/osxphotos#380]
When doing some export and re-imports I noticed issues with stale descriptions showing back up in Photos. Specifically, this seems to be an issue with Photos preferring IPTC:Caption-Abstract over the XMP-dc:Description to populate the "description" box in the photo info. In my case here's what I think happened

1. Import photo into Photos app
2. Change description in photos info dialog
3. Export via `osxphotos`
4. Delete the exported photo
5. Re-import the exported photo. It will have the description from 2.
6. Edit the photo (e.g. crop). Photos creates derivative JPEG[s] with both Description and Caption-Abstract fields set.
7. Update the description to something new.
8. Export the photo again. Both the original RAW and edited JPEG have the XMP-dc:Description from 7. The edited JPEG still has the IPTC:Caption-Abstract from 2.
9. Delete and re-import the edited JPEG. It will surprisingly have the description from 2.

So, should `osxphotos` update additional fields that are effectively the same as the XMP-dc:Description? I also found this [exiftool forum thread](https://exiftool.org/forum/index.php?topic=6589.0) which mentions a few other fields in the context of Windows Explorer that all could generically be considered the "description".

**Comment by neilpa** [comment]
I also noticed that there's the IFD0:ImageDescription field which is updated alongside the XMP-dc:Description

**Comment by RhetTbull** [comment]
It make sense to do this and won't be hard to implement.  The metadata stuff is so frustrating...wish there was a single standard everyone used! 

I'll need to update both the --exiftool options and the XMP template.

**Comment by RhetTbull** [comment]
The `--exiftool` option currently sets both `Exif:ImageDescription` (which is the same as `IFD0:ImageDescription`) and `XMP:Description` but `--sidecar xmp` only sets `XMP:Description` (I originally matched the fields that Photos set when exporting).  I'll update both to set both of these as well as `IPTC:Caption-Abstract`.

**Comment by RhetTbull** [comment]
It seems that none of this will play well with Windows though which mixes both Title and Description, which in Photos are different fields.

re: https://exiftool.org/forum/index.php?topic=6589.msg32862#msg32862

```txt
When you set the Title from Windows Properties, the following tags are set:

    EXIF:ImageDescription
    EXIF:XPTitle
    IPTC:Caption-Abstract
    XMP:Description
    XMP:Title


Windows Properties will populate the Title with the same tags, in this order of priority:

    XMP:Title
    EXIF:ImageDescription
    IPTC:Caption-Abstract
    XMP:Description
    EXIF:XPTitle
```

**Comment by RhetTbull** [comment]
While I'm in this part of the code I'm also going to set IPTC:ObjectName = XMP:Title = title.  Code currently only sets XMP:Title.  

See page 29 of this document for mapping of IPTC to XMP:
https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata-201610_1.pdf

While I'm at it may also set City/Province/Country in the XMP if these are set in the reverse geolocation data.

- City=photoshop:City
- Province/State=photoshop:State
- Country/Primary Location Name=photoshop:Country

**Comment by RhetTbull** [comment]
I added Caption-Abstract in [v0.40.16](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.16)
