### ISSUE TITLE
Bug: path_edited does not check ismissing

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#39]
path_edited checks to see if file exists and warns if not but it shouldn't do this if we know the file is missing

**Comment by cjs226** [comment]
I believe I'm running into this issue:

> Exporting IMG_2863.MOV (0017BE2A-FD9F-4CBC-9C90-30CD7718637C.mov) as IMG_2863.MOV
> Skipped up to date file /Volumes/cjs226-mpb-3-scratch/backup/photos/_/2015-08-13/IMG_2863.MOV
> Exporting edited version of IMG_2863.MOV as IMG_2863_edited.mov
> Traceback (most recent call last):
>   File "/Users/clif/.local/pipx/venvs/osxphotos/bin/osxphotos", line 8, in <module>
>     sys.exit(cli())
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
>     return f(get_current_context().obj, *args, **kwargs)
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/__main__.py", line 1635, in export
>     results = export_photo(
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/__main__.py", line 2381, in export_photo
>     export_results_edited = photo.export2(
>   File "/Users/clif/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/photoinfo/_photoinfo_export.py", line 470, in export2
>     raise FileNotFoundError(
> FileNotFoundError: Cannot export edited photo if path_edited is None

**Comment by RhetTbull** [comment]
@cjs226 thanks for the bug report.  What version of MacOS are you running?  Also, could you post or email the output of the following command:

`osxphotos debug-dump --dump photos --uuid "0017BE2A-FD9F-4CBC-9C90-30CD7718637C"`

You may be right that it's this issue you're running into.  The code should check to see if the photo is missing and not try to export it if it is.  It's possible the original photo isn't missing but the edited version is which could lead to this error.

**Comment by cjs226** [comment]
wow, @RhetTbull thanks for responding so quickly!

I'm running 10.15.7.

I've emailed you the result of the command.

**Comment by RhetTbull** [comment]
@cjs226 I think I found the issue and fixed in release [v0.36.6](https://github.com/RhetTbull/osxphotos/releases/tag/v0.36.6).  Try this one and let me know if the problem was fixed.

**Comment by cjs226** [comment]
@RhetTbull, yes sir, I'm up and running.  Thank you!
