### ISSUE TITLE
Possible to log files removed with --cleanup

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#395]
Would it be possible to add the list of files removed with --cleanup either within the current report or in a separate report generated? This would be good to see if there are accidental deletes or also for syncing deleted across outputs.

**Comment by RhetTbull** [comment]
Yes, this wouldn't be too hard.  The cleanest is probably to add the deleted files to the existing report.  In the mean time you can run --cleanup with --verbose and look for the lines beginning with "Deleting".  For example:

`osxphotos export ~/Desktop/export --verbose  --exiftool --cleanup | grep Deleting`

**Comment by narensankar0529** [comment]
Yeah - Adding to the existing report would be great!

**Comment by RhetTbull** [comment]
Fixed in [v0.41.3](https://github.com/RhetTbull/osxphotos/releases/tag/v0.41.3)
