### ISSUE TITLE
Error exporting with --exiftool: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by ubrandes** [RhetTbull/osxphotos#414]
Thank you for this wonderful app. Testing with >30k imported photos from iOS and a few other sources, I came across this error message for 32 of these 32k photos:
`Error exporting photo (...) as ...: 'NoneType' object has no attribute 'replace'`

I could not determine what causes the error message, other than that it appears only for these 32pics and with option `--exiftool` as in
`UB@Mac ~ % osxphotos export --folder work --name 20181112 --exiftool /Volumes/photo/test`
The affected files are being exported fine, however with original file creation date. The other files have creation date = now instead.

When I omit the `--exiftool` option, the error does not appear.  Happy to send the photos over for debugging if necessary.

ExifTool is on the most recent version, 12.23. Previously I was on an older version, 11.10, but the error was the same.

**Comment by RhetTbull** [comment]
Thanks for the bug report -- this should be enough to get me pointed to the right spot: `'NoneType' object has no attribute 'replace'`

I'll post back here if I need any additional info.

**Comment by RhetTbull** [comment]
Try version [v0.41.9](https://github.com/RhetTbull/osxphotos/releases/tag/v0.41.9) and let me know if you are still having problems.  You can download from the github [release](https://github.com/RhetTbull/osxphotos/releases/tag/v0.41.9) page or `python3 -m pip install --upgrade osxphotos` if you installed with pip originally.

**Comment by ubrandes** [comment]
Thank you for the quick response, Rhet.

I had originally installed osxphotos with pipx, so I ran pipx upgrade osxphotos now.
=> upgraded package osxphotos from 0.41.8 to 0.41.9
=> re-ran osxphotos export --dry-run --folder work --name 20181112 --exiftool /Volumes/photo/test

The problem seems fixed.  No more of these errors.  Thank you!  This was very quick :)
