### ISSUE TITLE
Error when using with --exiftool option

### ISSUE THREAD

**Issue by kaduskj** [RhetTbull/osxphotos#452]
Thank you for creating this wonderful tool. I am using this tool to export my photo library on Big Sur and getting the following error when using exiftool option.

Error exporting photo (BE6A10E6-7569-4E1E-B954-4D647AA99555: IMG_4380.JPG) as IMG_4380.JPG: '<' not supported between instances of 'str' and 'NoneType'

Let me know if you need any additional information about the error. I think the error does not occur if I don't use exiftool option

**Comment by RhetTbull** [comment]
Please post the entire command line you're using for osxphotos export.

**Comment by kaduskj** [comment]
osxphotos export --exiftool --export-by-date <photolibraryfile>  <destinationdir>

**Comment by RhetTbull** [comment]
I've searched through the code and can't find an obvious culprit.  Please run the following command and post the content here (or email to me at rturnbull+git@gmail.com).  Note: this will produce a debug dump of data that might contain private information such as location. So if that's important to you, look at it and sanitize the information first (all the fields are labeled should be self-explanatory).

`osxphotos debug-dump --dump photos --uuid BE6A10E6-7569-4E1E-B954-4D647AA99555 > debug.txt`

**Comment by kaduskj** [comment]
[debug.txt](https://github.com/RhetTbull/osxphotos/files/6528494/debug.txt)
Please find attached the output. Thanks again for you support.

**Comment by RhetTbull** [comment]
Thanks for the additional debug info. One more command to run.  Still trying to sort this out as it's not obvious so far what's causing the data. The error is almost certainly from a `sorted` call which only occurs a few places in the code but it's not clear from the example you sent what could be causing it.

`osxphotos debug-dump --dump keywords --dump persons > debug.txt`

**Comment by kaduskj** [comment]
[debug.txt](https://github.com/RhetTbull/osxphotos/files/6528538/debug.txt)

**Comment by RhetTbull** [comment]
Thanks -- that did it! I see the problem.  Now I need to figure out how to fix it as it's a condition I've never seen before and not sure if the issue is in Photos database or in my code.

**Comment by RhetTbull** [comment]
The error almost certainly occurs in this section of code:

https://github.com/RhetTbull/osxphotos/blob/bd6656107b18d0bcec67540411b85180f6bec372/osxphotos/photoinfo/_photoinfo_export.py#L1596-L1598

The expected behavior when osxphotos encounters a face with no person name attached, is that osxphotos uses a sentinel value of "_UNKNOWN_" as the person name then filters these out when exporting persons with --exiftool.  In this database there are some persons that show a name of `None` instead of the sentinel value which is causing the error.  See below where person 14 has name of `None` but person 3265 has name of `_UNKNONW_` as expected.

```
 14: {'displayname': None,
      'facecount': 166,
      'fullname': None,
      'keyface': 136,
      'keyface_uuid': '56F9638A-EBE3-4628-BD58-41513AB8E90F',
      'photo_uuid': 'C272EE75-FD6C-4819-9788-F60E8AA17DA3',
      'pk': 14,
      'uuid': '16AD2D0E-57DC-4E38-9E2B-E92D126A40FB'},
 3265: {'displayname': None,
        'facecount': 2,
        'fullname': '_UNKNOWN_',
        'keyface': 14760,
        'keyface_uuid': 'CEE75C95-9509-4945-8D7E-3EA60D4F0766',
        'photo_uuid': '42A43625-D9FD-41AC-8FFC-C639395384F2',
        'pk': 3265,
        'uuid': '2CB1B77C-7CF6-4BDB-8736-D7BFE599EBE1'},
```

**Comment by kaduskj** [comment]
Thanks. Like I said its a great tool you have built and I am glad I was able to help you remove a defect from it :). This is a regular Apple PhotoLibrary. I have not really played with it at all. I will still look at the pictures with None and see if I can recollect anything which may useful.
Also I did scroll down the file but failed to notice that there are actual names in there. Will appreciate if you can remove the file . Thanks

**Comment by RhetTbull** [comment]
I deleted the debug data I'd downloaded.  I'm testing a fix now.

**Comment by RhetTbull** [comment]
This should be fixed in [v0.42.24](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.24).  Please give it a try and let me know if you still get an error.

**Comment by RhetTbull** [comment]
@all-contributors add @kaduskj for bug

**Comment by kaduskj** [comment]
Thanks. Updated the version and error no longer occurs.
