### ISSUE TITLE
Errors running test on 11.3

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#454]
2021-05-24 12:30:07,228 - WARNING - photosdb.py - 97 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2]: you have Darwin, OS version: 11.3

I updated and ran the tests on my M1 mini. Some errors seen. Log attached
[testrun.txt](https://github.com/RhetTbull/osxphotos/files/6533025/testrun.txt)

**Comment by RhetTbull** [comment]
Thanks!  I'll take a look and see what I can figure out.  My machine running Big Sur has died so I don't have a way to test...will see if I can figure out what's going on then send you an update.

**Comment by RhetTbull** [comment]
Looks like the exiftool process closed while osxphotos was trying to use it.  Can you try this to see if the test fails every time or if something weird happened on this particular run:

`python3 -m pytest tests/test_template.py::test_exiftool_template`

**Comment by narensankar0529** [comment]
Running the individual test works and does not return any errors. However running all of the tests via "pytest" still results in error -

        command_str += (
            b"\n".join([c.encode("utf-8") for c in commands])
            + b"\n"
            + filename
            + b"\n"
            + b"-execute\n"
        )

        # send the command
>       self._process.stdin.write(command_str)
E       ValueError: write to closed file

osxphotos/exiftool.py:288: ValueError
============================================================== warnings summary ==============================================================
tests/test_cli.py::test_osxphotos
tests/test_cli.py::test_osxphotos
  /Users/nsankar/projects/osxphotos/.venv/lib/python3.9/site-packages/bitstring-3.1.7-py3.9.egg/bitstring.py:2: DeprecationWarning: invalid escape sequence \

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================== short test summary info ===========================================================
FAILED tests/test_template.py::test_exiftool_template - ValueError: write to closed file

**Comment by RhetTbull** [comment]
I've managed to reproduce this but not sure yet why it's happening. I believe it's related to the fix for #449 and is a problem with test setup, not an actual problem with osxphotos. But still need to do more testing.

**Comment by RhetTbull** [comment]
I've confirmed the functionality this test is testing actually works as expected.  The problem also seems to only occur when the following tests are run in order:

- tests/test_cli.py 
- tests/test_exiftool.py 
- tests/test_template.py

The `ExifTool` module uses a singleton pattern and a module-level global variable to track state so I suspect one of these tests is somehow affecting the state.  All theses tests run fine if run in different order or individually.

**Comment by narensankar0529** [comment]
So I think it would be ok to mark as 11.3 is supported as well and perhaps change the order of the tests might be ok.

**Comment by RhetTbull** [comment]
I think I found & fixed the problem. I updated supported versions for 11.3 in release [v0.42.26](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.26)
