### ISSUE TITLE
RAW+JPEG files not converted with `--convert-to-jpeg`

### ISSUE THREAD

**Issue by neilpa** [RhetTbull/osxphotos#469]
Noticed that some (all?) of my photos that are RAW+JPEG aren't converted when exported with `--convert-to-jpeg`. I've seen this for both Sony `.arw` and Nikon `.nef` files I have. Here's the full command that I'm running

```
osxphotos export \
  --update \
  --db $DB \
  --directory '{created.year}/{created.mm}.{created.mon|lower}/{created.dd}' \
  --filename '{function:templates.py::filename_prefix}.{original_name}.{uuid}' \
  --convert-to-jpeg \
  --jpeg-ext jpeg \
  --skip-original-if-edited \
  --edited-suffix '' \
  --exiftool \
  --sidecar xmp \
  --sidecar json \
  --strip \
  --verbose \
  --report $LOGS/$TS.report.csv \
  $EXPORT
```

If you need it I can also put together a test db with a few of the problematic files.

**Comment by RhetTbull** [comment]
A small test db would be great! You can email it or a link to me at Rturnbull+git@gmail.com I'm traveling and won't be able to take a look until this weekend.

**Comment by RhetTbull** [comment]
Just looked at the code in _photoinfo_export.py and I think I see the issue. RAW+JPEG have a UTI of 'public.jpeg' in Photos even if the RAW is selected as the original so the conversion never gets triggered. Will need to think about the best way to bands this. Not sure everyone will want the raw converted if there's already a jpeg. Also need to avoid name collisions when the jpeg is also exported.

```python 
uti = self.uti if edited else self.uti_original
    if convert_to_jpeg and self.isphoto and uti != "public.jpeg":
        # not a jpeg but will convert to jpeg upon export so fix file extension
        fname_new = pathlib.Path(fname)
        ext = "." + jpeg_ext if jpeg_ext else ".jpeg"
        fname = str(fname_new.parent / f"{fname_new.stem}{ext}")
    else:
        # nothing to convert
        convert_to_jpeg = False
```

**Comment by RhetTbull** [comment]
See also https://github.com/RhetTbull/osxphotos#raw-related-attributes

**Comment by RhetTbull** [comment]
PS -- you get the osxphotos Power User badge!  Love to see some of the newer features like template filters and functions "in the wild"!

**Comment by neilpa** [comment]
> PS -- you get the osxphotos Power User badge! Love to see some of the newer features like template filters and functions "in the wild"!

Yea, I was experimenting with it yesterday and it worked out great for customizing export names just how I want them.

**Comment by neilpa** [comment]
> RAW+JPEG have a UTI of 'public.jpeg' in Photos even if the RAW is selected as the original so the conversion never gets triggered. Will need to think about the best way to bands this. Not sure everyone will want the raw converted if there's already a jpeg.

Ahh, I didn't realize that they both got exported. In that case, seems like if `--convert-to-jpeg` is specified it should just skip the RAW entirely since the associated JPEG is already getting exported.

**Comment by RhetTbull** [comment]
You could use `--skip-raw` to skip the RAW component of the RAW+JPEG pair

**Comment by neilpa** [comment]
> You could use `--skip-raw` to skip the RAW component of the RAW+JPEG pair and this may eliminate the need to have separate logic in the export code to deal with RAW+JPEG and conversion.

The majority of my photos are plain RAW files. Wouldn't that also skip those rather than convert them to JPEG?

**Comment by neilpa** [comment]
> > You could use `--skip-raw` to skip the RAW component of the RAW+JPEG pair and this may eliminate the need to have separate logic in the export code to deal with RAW+JPEG and conversion.
> 
> The majority of my photos are plain RAW files. Wouldn't that also skip those rather than convert them to JPEG?

Just re-read the docs. That's definitely what I want. Thanks!

```
  --skip-raw                      Do not export associated raw images of a
                                  RAW+JPEG pair.  Note: this does not skip raw
                                  photos if the raw photo does not have an
                                  associated jpeg image (e.g. the raw file was
                                  imported to Photos without a jpeg preview).
```

**Comment by RhetTbull** [comment]
> The majority of my photos are plain RAW files. Wouldn't that also skip those rather than convert them to JPEG?

No. It only skips the RAW component of the RAW+JPEG pair.  (And thus, perhaps the `--skip-raw` flag is not the best name, though the help text for the flag does try to clarify.  The other --skip-X flags all behave similarly,e.g. `--skip-live` skips the associated live movie for a live image but still exports the actual image, `--skip-edited` skips the edited version but still exports the original,etc.)

Here's the actual code: it looks at [photo.has_raw](https://github.com/RhetTbull/osxphotos#has_raw) which is True if the photo has an associated RAW image but False if the photo is itself a RAW image without a JPEG pair as yours are.  Setting `--skip-raw` toggles `raw_photo` to False in the snippet below.
  
https://github.com/RhetTbull/osxphotos/blob/5143b165b59a0814ed090dd022937c3c878a6fce/osxphotos/photoinfo/_photoinfo_export.py#L810-L830

**Comment by neilpa** [comment]
> `--skip-live` skips the associated live movie for a live image but still exports the actual image

Another flag I probably want since I've got a few of those imported.

**Comment by RhetTbull** [comment]
I updated the help text in [v0.42.39](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.39) to try to make it more clear what --convert-to-jpeg actually does with RAW+JPEG pairs.
