### ISSUE TITLE
Cleanup won't delete recently deleted files

### ISSUE THREAD

**Issue by mkirkland4874** [RhetTbull/osxphotos#481]
The --cleanup function does not run when --deleted-only is used while Recently Deleted is empty in the photo library. Instead, "Did not find any photos to export" is printed to console and no cleanup occurs.

You can produce the bug as follows:

1. Delete 1 photo so Recently Deleted has one file in it
2. Run the following command to export Recently Deleted to an empty folder. This will result in one image downloaded to the Deleted folder.
`osxphotos export --db ~/Pictures/Photos\ Library.photoslibrary --export-by-date --update --cleanup --deleted-only /Users/Username/Documents/Photos/Deleted`
3. Restore the deleted photo in Photos back to the library (and Recently Deleted now has no files in it)
4. Run the same command to export Recently Deleted to a specific folder
`osxphotos export --db ~/Pictures/Photos\ Library.photoslibrary --export-by-date --update --cleanup --deleted-only /Users/Username/Documents/Photos/Deleted`
5. osxphotos will not delete/cleanup the previously downloaded image from the Deleted folder even though you moved the image back to the library and it will simply print "Did not find any photos to export" to the console.

As a result, one cannot use the --update --cleanup --deleted-only commands to maintain a synced copy of the Recently Deleted album in Photos.

Edit: Same thing occurs if you run --update --cleanup and --album on an empty album but the local directory has files in it. So if I delete the last image in an album on Photos, osxphotos will not cleanup the folder on the local filesystem.

**Comment by RhetTbull** [comment]
Thanks for the report. I took a look at the code and the cleanup code does not run if no files were exported which matches what you reported. Should be an easy fix.

**Comment by RhetTbull** [comment]
@mkirkland4874  I think this is fixed in [v0.41.51](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.51).  Let me know if it fixes your issue.

**Comment by RhetTbull** [comment]
@all-contributors please add @mkirkland4874  for bug

**Comment by mkirkland4874** [comment]
> @mkirkland4874 I think this is fixed in [v0.41.51](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.51). Let me know if it fixes your issue.

Looks like it's fixed in v0.42.51. Thanks!
