### ISSUE TITLE
Broken caching for {detected_text}

### ISSUE THREAD

**Issue by hyfen** [RhetTbull/osxphotos#499]
When exporting new images with `{detect_text}`, I noticed that {detected text} is being populated inconsistently. 

Here's what I was doing: 
1. `$ osxphotos export . --exiftool --download-missing --from-date "2021-07-27" --touch-file --not-shared --overwrite --description-template "{detected_text}" --update`
2. `$ exiftool -s -description *` to check the results

Only one of the images had this field set even though I have a few more images and screenshots that have very legible text.

Then, I deleted `.osxphotos_export.db` and ran the command again. This time, all the descriptions were set properly on the images with legible text.

Perhaps there's a race condition or timeout issue when interacting with the Vision API? 

If it's helpful, I'm still on macOS 10.15.

(I'm creating a new issue that's following up on this [this comment](https://github.com/RhetTbull/osxphotos/issues/498#issuecomment-888314377).)

**Comment by RhetTbull** [comment]
Thanks @hyfen I think you win the prize for shortest time between release and bug report. I think the problem is actually in the database code--I'll take a look soon.  I'm also working on a more robust way to cache the information using extended attributes that would work even if the export database was deleted.

**Comment by RhetTbull** [comment]
So far I've found no smoking gun for this.  

- I've verified the database caching code is working (and added tests to confirm this).  
- I then thought maybe it was a problem with database migration (the caching code adds a table to the database) but in my testing the migration was working fine.  
- It's possible there's an error condition raised by the Vision API -- previously, if Vision raised an error, I ignored it and set the detected text to an empty list.  Now I catch the error and log it to stderr so the user will see the error.

Try version [0.42.70](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.70) which adds additional error logging and let me know if you experience any errors when using {detected_text}.  I'll keep looking for what else it could be.

**Comment by RhetTbull** [comment]
I've redesigned the caching code for {detected_text}.  Results are now cached as an extended metadata attribute on the actual image file so this is independent of the export database.  This also paves the way for me to add a `osxphotos detect-text` command which can be run ahead of time to pre-cache all the detected text.  New changes in [v0.42.72](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.72).
