### ISSUE TITLE
Feature: add path_rendered, path_thumbnail

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#50]
It would be useful to be able to access thumbnails as well as the rendered images (e.g. for screenshots where original PNG is not typically stored by Photos on the Mac but a high resolution rendered JPEG is).   This would also give user an option to export rendered JPEG (add to PhotoKit.export?) if the original was missing.

**Comment by RhetTbull** [comment]
Movies also include a jpeg frame grab (or heic) preview and follow same conventions as edited images for the edited preview frame.

**Comment by RhetTbull** [comment]
On Photos 5:

Original, 3088x2316:
`./originals/F/F88C2797-D829-495D-8FAE-517D2A00DD12.jpeg`

Thumbnail, 480x360, ends in `_4_5005_c.jpeg`:
`./resources/derivatives/masters/F/F88C2797-D829-495D-8FAE-517D2A00DD12_4_5005_c.jpeg`

Small preview, 1024x768 (always present if photo is downloaded), 1024x768, ends in `_1_105_c.jpeg`:
`./resources/derivatives/F/F88C2797-D829-495D-8FAE-517D2A00DD12_1_105_c.jpeg`

Large preview: sometimes available, 2048x1536, ends in `_1_102_o.jpeg`:
`./resources/derivatives/F/F88C2797-D829-495D-8FAE-517D2A00DD12_1_102_o.jpeg`

**Comment by RhetTbull** [comment]
For Photos 4:

There's a thumbnail and mini preview and sometimes a larger preview:
```
./resources/proxies/derivatives/00/00/c/UNADJUSTEDRAW_mini_c.jpg
./resources/proxies/derivatives/00/00/c/UNADJUSTEDRAW_thumb_c.jpg
./resources/proxies/derivatives/00/00/c/UNADJUSTEDRAW_largepv_c.jpg
```

There's also sometimes a full-size render:
```
./resources/media/master/00/00/fullsizeoutput_f.jpeg
```

**Comment by Rott-Apple** [comment]
"Large preview: sometimes available, 2048x1536, ends in _1_102_o.jpeg". In my library, some photos have more than one such preview files, with incrementing suffixes. Screenshot attached. There is also a .THM (thumbnail file) that's generated by many cameras to present on-screen previews.
![Catalina](https://user-images.githubusercontent.com/67875570/103455834-92a77780-4d16-11eb-9d35-1cb521b48bf3.png)

**Comment by RhetTbull** [comment]
Thanks.  Are they all they same size?  Photos also maintains .THM files but I've not found a way to read these.  I'd like to be able to export previews from .THM files.  The most likely use case for exporting previews is to preserve images for someone who's lost access to the iCloud account but doesn't have all the photos synched.  For most other cases, I imagine people would just want the original and edited images (which osxphotos supports).

**Comment by Rott-Apple** [comment]
These are for a video file that's in Originals > F. (F19E06B8-A712-4B5C-907A-C007D37BDA16.M4V, 7.4MB, 6 Feb 2020)

Resources > Derivatives > F has:

F19E06B8-A712-4B5C-907A-C007D37BDA16_1_101_o.jpeg (270,153 bytes, 15 Feb 2020)
F19E06B8-A712-4B5C-907A-C007D37BDA16_1_102_o.jpeg (58,917 bytes, 14 March 2020)
F19E06B8-A712-4B5C-907A-C007D37BDA16_1_105_c.jpeg (177,514 bytes, 15 Feb 2020)
F19E06B8-A712-4B5C-907A-C007D37BDA16.thm

(Note that the 3rd file listed ends in _c, not _o)

The .THM file is a **square** 4kb thumbnail created from the center slice of the video's first frame. Use any image viewer (e.g. File > Open in a web browser) – or change .THM to .JPG (it is encoded as JPG.) So you can easily export previews.

In addition, Resources > Derivatives > Masters > F has another, smaller thumbnail than the _1_10X_o ones.

F19E06B8-A712-4B5C-907A-C007D37BDA16_4_5005_c.jpeg (73,592 bytes, 14 March 2020)

**Comment by RhetTbull** [comment]
Edited preview appears to be here:
`./resources/derivatives/masters/2/263E3C26-2300-4D42-BA19-1A4CAE2FC2FB_4_5005_c.jpeg`

**Comment by RhetTbull** [comment]
Implemented by path_derivatives.  path_derivatives does not provide access to the .THM files but not sure if those are really useful.

**Comment by RhetTbull** [comment]
In `Photos Library.photoslibrary/resources/derivatives/thumbs/thumbnailConfiguration` there's this hint about the _5005 files:

```
$ cat thumbnailConfiguration
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PLThumbnailManagerThumbnailFormatKey</key>
	<integer>5005</integer>
	<key>PLThumbnailManagerVersionKey</key>
	<integer>28</integer>
</dict>
</plist>
```

**Comment by RhetTbull** [comment]
Shared cloud photos have a preview here:

`/resources/cloudsharing/resources/derivatives/masters/6/6DF9B23E-E169-42C2-BDA2-5245587539B4_4_5005_c.jpeg`
