### ISSUE TITLE
Export by date timezone issue

### ISSUE THREAD

**Issue by sirnacnud** [RhetTbull/osxphotos#504]
I used the export-by-date option and I noticed an image has a different date and time compared to what is in the Photos library.

In the Photos library the image shows as October 9th, 2016 1:13AM. When it is exported via osxphotos it has October 8th, 2016 11:13PM.

When I do a query of the image through osxphotos, I see the date is `2016-10-08T23:13:59+00:00`. 

Is this a bug or is Photos doing a conversion from this timezone to my current, as I'm not in +00:00 (UTC timezone)?

**Comment by RhetTbull** [comment]
@sirnacnud what's the full osxphotos command line you're using?

When you say the exported file's date is wrong, do you mean that the timestamp of the file on disk (e.g. the time that shows up in Finder or Terminal) or do you mean the file was exported into the wrong directory (e.g. 2016-10-08 instead of 2016-10-09)?

Are you using the `--touch-file` option?  By default, osxphotos does not modify the time stamp of any file that's exported -- it merely copies the file out of the library.  If you use `--touch-file`, osxphotos will touch the time stamp of the exported file so it matches the date the photos was created.

**Comment by sirnacnud** [comment]
I did `$ osxphotos export --export-by-date <PhotosDB Path> <Export Path> --exiftool`

The photo is exported in 2016/10/8, which Photos actually has it in Masters/2016/10/8, so I guess that is alright. The issue is the Creation Date and Time in the EXIF data is 23:13:59, so it seems like the timezone was dropped or wasn't considered?

**Comment by RhetTbull** [comment]
When used with --exiftool, osxphotos sets "IPTC:DateCreated" and "IPTC:TimeCreated" as well as "OffsetTimeOriginal".  For the time, it does include the timezone offset in form "+hh:mm".  For example:

```
exiftool -G exported_photo.jpeg:
...
[IPTC]          Date Created                    : 2017:06:20
[IPTC]          Time Created                    : 17:18:56+09:30
...
[EXIF]          Offset Time Original            : +09:30
```

Is your export time offset not getting set correctly? From the sample data you provided, it looks like your photo was actually recorded with a zero offset (e.g. UTC).  If it was taken with a phone while you were in your current timezone, I would expect it to show whatever your UTC offset is but in this case Photos thinks the photo was taken in UTC timezone (0 offset).  Was this taken with a camera that may have had the wrong time or was it created in UTC timezone?  

Is your current timezone UTC+02:00?  

Try the following to see if we can get some more details about this photo.  Select the photo in question in Photos then at your shell, run `osxphotos repl` then try these commands:

```
$ osxphotos repl
python version: 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02)
....rest of startup output truncated
>>> from photoscript import PhotosLibrary
>>> photos = PhotosLibrary().selection
>>> photo = get_photo(photos[0].uuid)
>>> photo.date
datetime.datetime(2017, 6, 20, 17, 18, 56, 518000, tzinfo=datetime.timezone(datetime.timedelta(seconds=34200)))
>>> photo._info["imageTimeZoneOffsetSeconds"]
34200
>>>
```

**Comment by sirnacnud** [comment]
Actually I just checked the EXIF data of the photo with `exiftool` and it does have the correct timezone set. I think this must be an issue with Digikam not displaying/handling the timezone for the photo.

Thank you for helping me investigate this, I think you can close the issue since it's not related to osxphotos.
