### ISSUE TITLE
bug: get_last_library_path does not always return last library

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#54]
In some cases, get_last_library_path will fail if Photos hasn't already been opened.  I don't know if this is an issue with permissions or if /Library/Containers/com.apple.Photos/Data/Library/Preferences/com.apple.Photos.plist is missing.  

Also, it will always fail on a "clean install" account where Photos has never been opened.  

In these cases, should it return ~/Pictures/Photos Library.photoslibrary?

**Comment by mwort** [comment]
I can't actually reproduce my initial error with this but my first thought was it expects the `~/Pictures/Photos Library.photoslibrary` to exist, which did exist already when the error first occurred. IMHO I actually think the use of the last opened library is somewhat inconsistent because the result of osxphotos depends on the use of the app. I would suggest to always default to the user standard library (as does OSX and access to iCloud is only possible in this lib) and non-standard locations need to be parsed with the --db argument on the CLI.

**Comment by mwort** [comment]
Another example where this going to fail if you trash the last opened lib btw. I just think this behaviour is more hassle than it is useful.

**Comment by RhetTbull** [comment]
I agree the behavior of opening last library could be ambiguous and lead to unexpected behavior.  I'll change the code to require the library be explicitly specified.  Ideally, I'd use the system library as the default as you suggest but I've not been able to find a way to reliably do this.  On Catalina, the system library seems to be specified in ~/Library/Containers/com.apple.photolibraryd/Data/Library/Preferences/com.apple.photolibraryd.plist (used by osxphotos.utils.get_system_library_path) but this doesn't work on older OS versions.  I could default to ~/Pictures/Photos Library.photoslibrary but the user can change/rename the system library and I don't know if this naming convention holds across different languages.

**Comment by RhetTbull** [comment]
Another option is to have the CLI print a list of all available libraries (e.g. as is done by `osxphotos list`) if the user does not specify one explicitly on the command line.

**Comment by mwort** [comment]
Sounds good to me. If `--db` not parsed, why not do:
1. try to determine system lib. If that fails, ...
2. try to list used libs (with a blocking prompt?). If that fails, ...
3. require `--db` to be parsed.

I am using Catalina too (and High Sierra on my old machine) and I thought the `~/Pictures/Photos Library.photoslibrary` was universal.

**Comment by RhetTbull** [comment]
I've been playing with this.  I've got the following behavior prototyped:
1. --db can be passed before or after the command e.g. `osxphotos --db ~/Pictures/Foo.photoslibrary info` or `osxphotos info --db ~Pictures/Foo.photoslibrary`
2. The path to the photos library can be specified as an argument after the command without using --db: `osxphotos info ~/Pictures/Foo.photoslibrary`  This seems more natural than using an option, which by definition should be optional.
3. If neither 1 or 2 is specified, osxphotos will:
    1. first try to get the last library opened in Photos
    2. failing 1, will try to get system photos library
    3. failing 2, will look for "~/Pictures/Photos Library.photoslibrary" (need to understand if this works under non-English installs)
    4. failing 3, will list all available libraries and prompt user to select one

Rationale is that this will likely "just work" for the average user and "do what I mean".  Downside is that it could lead to non-deterministic behavior.

**Comment by RhetTbull** [comment]
Version 0.22.0 implements this new behavior with one exception to above -- if a database path isn't passed either as argument or --db option, osxphotos will list available databases but does not block with a prompt

**Comment by mwort** [comment]
Cool, works well. How come you ditched the search for a "default" library? The behaviour listed in 3) make sense except for 3.i to keep it deterministic.

**Comment by RhetTbull** [comment]
@mwort Mainly just to make it more clear which library is being operated on.  I can't reliably find the system library and you found at least one case where default library didn't work. If you think it makes sense to keep search for default library I'm happy to put it back in.  Another option might be to add a "--system-lib" and "--last-lib" options so you could explicitly say "look for the last library I opened".  For 99% of users, they probably have only one library but I expect people using this module might be more likely to be in the 1% with more than one library.  I'm open to suggestions on how to make this easier to use/more intuitive!

**Comment by RhetTbull** [comment]
What about if --db or photo_library not specified, attempt to find default library then print a prompt saying something like: "Found Photos library at ~/Pictures/Photos Library.photoslibrary -- use this one (Y/n)?" If user says Y, use it, if N, then list the other libraries?  What I'd like to avoid is user operating on the wrong library by accident.

**Comment by mwort** [comment]
Yes I agree that would be useful although I would think that if a system library can be found, it should still operate on it without prompt (with a warning to stderr maybe). That would make it easier for the 90% of (Catalina) users.

**Comment by RhetTbull** [comment]
I just pushed a new update that implements # 3 above: looks for last library, then system library, then ~/Pictures/Photos Library.photosdb. As you suggested, it will print out a statement to stderr listing the library being used

**Comment by RhetTbull** [comment]
osxphotos now works around this issue as described above.
