### ISSUE TITLE
Export Crash on - OperationalError: no such column: ZDETECTEDFACE.ZBALDTYPE

### ISSUE THREAD

**Issue by neebah** [RhetTbull/osxphotos#544]
Got a crash while exporting today 

Lots of details here

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /Library/Frameworks/Python.framework/Versions/3.9/bin/osxphotos:8 in         │
│ <module>                                                                     │
│                                                                              │
│   5 from osxphotos.__main__ import cli                                       │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(cli())                                                      │
│   9                                                                          │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/core.py:1137 in __call__                                             │
│                                                                              │
│   1134 │                                                                     │
│   1135 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:       │
│   1136 │   │   """Alias for :meth:`main`."""                                 │
│ ❱ 1137 │   │   return self.main(*args, **kwargs)                             │
│   1138                                                                       │
│   1139                                                                       │
│   1140 class Command(BaseCommand):                                           │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/core.py:1062 in main                                                 │
│                                                                              │
│   1059 │   │   try:                                                          │
│   1060 │   │   │   try:                                                      │
│   1061 │   │   │   │   with self.make_context(prog_name, args, **extra) as c │
│ ❱ 1062 │   │   │   │   │   rv = self.invoke(ctx)                             │
│   1063 │   │   │   │   │   if not standalone_mode:                           │
│   1064 │   │   │   │   │   │   return rv                                     │
│   1065 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!           │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/core.py:1668 in invoke                                               │
│                                                                              │
│   1665 │   │   │   │   super().invoke(ctx)                                   │
│   1666 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx │
│   1667 │   │   │   │   with sub_ctx:                                         │
│ ❱ 1668 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub │
│   1669 │   │                                                                 │
│   1670 │   │   # In chain mode we create the contexts step by step, but afte │
│   1671 │   │   # base command has been invoked.  Because at that point we do │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/core.py:1404 in invoke                                               │
│                                                                              │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                  │
│   1402 │   │                                                                 │
│   1403 │   │   if self.callback is not None:                                 │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)            │
│   1405 │                                                                     │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List │
│   1407 │   │   """Return a list of completions for the incomplete value. Loo │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/core.py:763 in invoke                                                │
│                                                                              │
│    760 │   │                                                                 │
│    761 │   │   with augment_usage_errors(__self):                            │
│    762 │   │   │   with ctx:                                                 │
│ ❱  763 │   │   │   │   return __callback(*args, **kwargs)                    │
│    764 │                                                                     │
│    765 │   def forward(                                                      │
│    766 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # no │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/decorators.py:38 in new_func                                         │
│                                                                              │
│    35 │   """                                                                │
│    36 │                                                                      │
│    37 │   def new_func(*args, **kwargs):  # type: ignore                     │
│ ❱  38 │   │   return f(get_current_context().obj, *args, **kwargs)           │
│    39 │                                                                      │
│    40 │   return update_wrapper(t.cast(F, new_func), f)                      │
│    41                                                                        │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/click/decorators.py:26 in new_func                                         │
│                                                                              │
│    23 │   """                                                                │
│    24 │                                                                      │
│    25 │   def new_func(*args, **kwargs):  # type: ignore                     │
│ ❱  26 │   │   return f(get_current_context(), *args, **kwargs)               │
│    27 │                                                                      │
│    28 │   return update_wrapper(t.cast(F, new_func), f)                      │
│    29                                                                        │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/osxphotos/cli.py:1596 in export                                            │
│                                                                              │
│   1593 │   │   │   │   f"Upgraded export database {export_db_path} from vers │
│   1594 │   │   │   )                                                         │
│   1595 │                                                                     │
│ ❱ 1596 │   photosdb = osxphotos.PhotosDB(dbfile=db, verbose=verbose_, exifto │
│   1597 │                                                                     │
│   1598 │   # enable beta features if requested                               │
│   1599 │   photosdb._beta = beta                                             │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/osxphotos/photosdb/photosdb.py:331 in __init__                             │
│                                                                              │
│    328 │   │   if int(self._db_version) <= int(_PHOTOS_4_VERSION):           │
│    329 │   │   │   self._process_database4()                                 │
│    330 │   │   else:                                                         │
│ ❱  331 │   │   │   self._process_database5()                                 │
│    332 │                                                                     │
│    333 │   @property                                                         │
│    334 │   def keywords_as_dict(self):                                       │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/osxphotos/photosdb/photosdb.py:2466 in _process_database5                  │
│                                                                              │
│   2463 │   │                                                                 │
│   2464 │   │   # process face info                                           │
│   2465 │   │   verbose("Processing face details.")                           │
│ ❱ 2466 │   │   self._process_faceinfo()                                      │
│   2467 │   │                                                                 │
│   2468 │   │   # process search info                                         │
│   2469 │   │   verbose("Processing photo labels.")                           │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/osxphotos/photosdb/_photosdb_process_faceinfo.py:35 in _process_faceinfo   │
│                                                                              │
│    32 │   if self._db_version <= _PHOTOS_4_VERSION:                          │
│    33 │   │   _process_faceinfo_4(self)                                      │
│    34 │   else:                                                              │
│ ❱  35 │   │   _process_faceinfo_5(self)                                      │
│    36                                                                        │
│    37                                                                        │
│    38 def _process_faceinfo_4(photosdb):                                     │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-package │
│ s/osxphotos/photosdb/_photosdb_process_faceinfo.py:188 in                    │
│ _process_faceinfo_5                                                          │
│                                                                              │
│   185 │                                                                      │
│   186 │   (conn, cursor) = _open_sql_file(db)                                │
│   187 │                                                                      │
│ ❱ 188 │   result = cursor.execute(                                           │
│   189 │   │   f"""                                                           │
│   190 │   │   SELECT                                                         │
│   191 │   │   ZDETECTEDFACE.Z_PK,                                            │
╰──────────────────────────────────────────────────────────────────────────────╯
OperationalError: no such column: ZDETECTEDFACE.ZBALDTYPE

**Comment by RhetTbull** [comment]
You must be running on Monterey?  I think this is fixed in the most recent version of osxphotos. Try upgrading (either `python3 -m pip install --upgrade osxphotos` or `pipx install --upgrade osxphotos` if installed with pipx.

**Comment by neebah** [comment]
I'm at the most recent version.  I upgraded just the same.  Seems that the issue has vanished.  Running the export now.

**Comment by neebah** [comment]
And yes I am running Monterey
