### ISSUE TITLE
Missing photo error when using --download-missing

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#558]
Having an issue with one video which looks like somehow is in the DB but missing on disk. I think this is a deleted video but not sure where the corruption in the DB is. How do I look for this? Error I get when using --download-missing

Processing database /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary/database/photos.db
Processing database /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary/database/Photos.sqlite
Database locked, creating temporary copy.
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Exporting 1 photo to /opt/tmp/downloads_n...
Exporting RPReplay_Final1638350532.mp4 (BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.mp4) as video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.mp4
Writing XMP sidecar /opt/tmp/downloads_n/video/2021/December/01/video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.xmp
Error exporting photo (BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92: RPReplay_Final1638350532.mp4) as /opt/tmp/downloads_n/video/2021/December/01/video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.mp4: Invalid photo id: BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92 (_photoinfo_export.py: 1343)
Processed: 1 photo, exported: 0, missing: 0, error: 1, touched date: 0
Elapsed time: 0.346 seconds

**Comment by RhetTbull** [comment]
Try `osxphotos debug-dump --dump photos --uuid BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92` and post output here and I'll see if there are any clues.  You might also retry with `--use-photokit` with `--download-missing` to see if that can download it. I think the error you're getting is that Photos doesn't think this is a valid photo UUID but it's in the database.

**Comment by narensankar0529** [comment]
/opt/tmp/ osxphotos debug-dump --dump photos --uuid BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92
Using last opened Photos library: /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary
Opening database: /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary
2021-12-27 19:00:07,511 - WARNING - photosdb.py - 102 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6]: you have Darwin, OS version: 12.0
Done; took 77.52 seconds
_dbphotos['BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92']:
{'UTI': 'public.mpeg-4',
 'UTI_original': None,
 'UTI_raw': None,
 '_uuid': 'BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92',
 'added_date': datetime.datetime(2021, 12, 1, 17, 23, 37, 444464),
 'adjustmentFormatID': None,
 'adjustmentUuid': None,
 'albums': [],
 'alt_master_uuid': None,
 'burst': False,
 'burstPickType': 0,
 'burstUUID': None,
 'cloudAssetGUID': '666E7B54-38D6-4384-9E2A-3B2A38F9B1A7',
 'cloudAvailable': None,
 'cloudLibraryState': None,
 'cloudLocalState': 3,
 'cloudStatus': None,
 'cloudbatchpublishdate': None,
 'cloudownerhashedpersonid': None,
 'countryCode': None,
 'customRenderedValue': 0,
 'datastore_subtype': None,
 'depth_state': 0,
 'directory': 'B',
 'extendedDescription': None,
 'favorite': 0,
 'filename': 'BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.mp4',
 'fok_import_session': None,
 'hasAdjustments': 0,
 'hasAlbums': 0,
 'hasKeywords': 0,
 'hasPersons': 0,
 'has_raw': False,
 'hdr': False,
 'height': 1920,
 'hidden': 0,
 'imageDate': datetime.datetime(2021, 12, 1, 17, 22, 12, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))),
 'imageDate_timestamp': 660043332,
 'imageTimeZoneOffsetSeconds': 28800,
 'import_session': None,
 'import_uuid': None,
 'incloud': True,
 'intrash': False,
 'isMissing': 0,
 'isreference': False,
 'keywords': [],
 'lastmodifieddate': None,
 'lastmodifieddate_timestamp': None,
 'latitude': None,
 'live_photo': False,
 'localAvailability': 1,
 'longitude': None,
 'masterFingerprint': 'AZRPPzEeqIlt6TEzG6I3LgfrViLV',
 'masterUuid': None,
 'modelID': None,
 'momentID': None,
 'name': None,
 'non_raw_master_uuid': None,
 'orientation': 1,
 'originalFilename': 'RPReplay_Final1638350532.mp4',
 'original_filesize': 37976245,
 'original_height': 1920,
 'original_orientation': 1,
 'original_resource_choice': 0,
 'original_width': 888,
 'panorama': False,
 'persons': [],
 'pk': 60568,
 'placeIDs': None,
 'placeNames': None,
 'portrait': False,
 'raw_data_length': None,
 'raw_info': None,
 'raw_is_original': False,
 'raw_master_uuid': None,
 'remoteAvailability': 1,
 'resource_type': None,
 'reverse_geolocation': None,
 'saved_asset_type': 8,
 'screenshot': False,
 'selfie': False,
 'shared': False,
 'slow_mo': False,
 'subtype': 103,
 'time_lapse': False,
 'trasheddate': None,
 'trasheddate_timestamp': None,
 'type': 1,
 'visibility_state': 0,
 'visible': True,
 'width': 888}

**Comment by narensankar0529** [comment]
With --use-photokit - I claims to have downloaded/exported but actually in the directory there are two xmp files and no mp4

ls video/2021/December/01/video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92*
video/2021/December/01/video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92 (1).xmp
video/2021/December/01/video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.xmp

Run with the command line - 

osxphotos export --verbose --missing --download-missing --not-hidden --not-shared --not-screenshot --use-photokit\
    --touch-file \
    --sidecar xmp \
    --sidecar-drop-ext \
    --jpeg-ext jpg \
    --keyword-template "{place.name.country}" \
    --keyword-template "{place.name.city}" \
    --keyword-template "{place.name.state_province}" \
    --keyword-template "{place.name.area_of_interest}" \
    --keyword-template "{label_normalized}" \
    --keyword-template "{searchinfo.venue_type}" \
    --keyword-template "{searchinfo.season}" \
    --keyword-template "{searchinfo.holiday}" \
    --keyword-template "{searchinfo.activity}" \
    --keyword-template "{searchinfo.venue}" \
    --keyword-template "{searchinfo.venue_type}" \
    --directory '{photo_or_video}/{created.year}/{created.month}/{created.dd}' \
    --filename "{media_type}_n_{created.yy}{created.mm}{created.dd}_{uuid}" \
    /opt/tmp/
osxphotos version 0.43.8
Using last opened Photos library: /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary
Using export database /opt/tmp/.osxphotos_export.db
2021-12-27 19:21:52,024 - WARNING - photosdb.py - 102 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6]: you have Darwin, OS version: 12.0
Processing database /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary/database/photos.db
Processing database /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary/database/Photos.sqlite
Database locked, creating temporary copy.
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Exporting 1 photo to /opt/tmp...
Exporting RPReplay_Final1638350532.mp4 (BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.mp4) as video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92.mp4
Writing XMP sidecar /opt/tmp/video/2021/December/01/video_n_211201_BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92 (1).xmp
Processed: 1 photo, exported: 0, missing: 0, error: 0, touched date: 0
Elapsed time: 0.408 seconds

**Comment by RhetTbull** [comment]
Thanks for the debug data. It's doubly weird that `--use-photokit` fails to download the file but doesn't log an error.  That may be an unrelated bug I'll have to look into.  According to the debug data this file should be present on the local machine.  

Try searching for the original filename in Photos:`RPReplay_Final1638350532.mp4` and let me know if Photos finds the photos and is able to open it. 

This appears to be a screencast recording video.  It's subtype (`103`) is one I've never seen before but not sure if that is relevant.

**Comment by narensankar0529** [comment]
Video does not exist in the library since I deleted it before and I can't find it via search as well. So looks like only in the DB for some reason. I rebuilt my photos library as well and it still shows up

**Comment by RhetTbull** [comment]
> Video does not exist in the library since I deleted it before and I can't find it via search as well. So looks like only in the DB for some reason. I rebuilt my photos library as well and it still shows up

In that case, this does appear to be a corrupt Photos database that somehow didn't get marked as deleted. (The debug data shows the database says the photo is available locally and is not in the trash). I'm not sure this is a case osxphotos can/should handle other than reporting the error of a missing photo.  It does appear to be a bug though that `--use-photokit` didn't report the error so I'll look into that.

**Comment by RhetTbull** [comment]
I just looked at the code and don't see how the error could have not been reported with `--use-photokit`.  If you don't mind, please try the following and let me know if you get an errors.

`osxphotos repl`

which opens an interactive debug session with osxphotos, then type the following:

```
photo = get_photo('BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92')
photo.export2(dest="/tmp",use_photos_export=True)
```

**Comment by narensankar0529** [comment]
>>> photo = get_photo('BBCF2AB6-E7AC-43E9-9960-B6CDF9CEEC92')
>>> photo.export2(dest="/tmp",use_photos_export=True)
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'export2'

'NoneType' object has no attribute 'export2'
>>>

**Comment by narensankar0529** [comment]
Sorry it looks like the photo ID changed when I repaired the Photos Library

Now it is 

photo = get_photo('16E9B125-AF8A-4604-B1BE-81EA760A423D')

And 
photo.export2(dest="/tmp",use_photos_export=True)
returns - 

>>> photo.export2(dest="/tmp",use_photos_export=True)
<osxphotos.photoinfo._photoinfo_export.ExportResults object at 0x159d0df70>

But nothing is written at /tmp

**Comment by RhetTbull** [comment]
Try 

```
results = photo.export2(dest="/tmp",use_photos_export=True)
print(str(results))
```

**Comment by narensankar0529** [comment]
print(str(results))
ExportResults(exported=[],new=[],updated=[],skipped=[],exif_updated=[],touched=[],converted_to_jpeg=[],sidecar_json_written=[],sidecar_json_skipped=[],sidecar_exiftool_written=[],sidecar_exiftool_skipped=[],sidecar_xmp_written=[],sidecar_xmp_skipped=[],missing=[],error=[('/tmp/RPReplay_Final1638350532.mp4', 'Invalid photo id: 16E9B125-AF8A-4604-B1BE-81EA760A423D (_photoinfo_export.py: 1343)')],exiftool_warning=[],exiftool_error=[],deleted_files=[],deleted_directories=[],exported_album=[],skipped_album=[],missing_album=[])

**Comment by narensankar0529** [comment]
inspect(photo)
╭───────────────────────────────────── <class 'osxphotos.photoinfo.photoinfo.PhotoInfo'> ──────────────────────────────────────╮
│ Info about a specific photo, contains all the details about the photo                                                        │
│ including keywords, persons, albums, uuid, path, etc.                                                                        │
│                                                                                                                              │
│ ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ osxphotos.PhotoInfo(db=osxphotos.PhotosDB(dbfile='/Volumes/PhotoSync/nsankar/Photos                                      │ │
│ │ Library.photoslibrary/database/photos.db'), uuid='16E9B125-AF8A-4604-B1BE-81EA760A423D', info={'_uuid':                  │ │
│ │ '16E9B125-AF8A-4604-B1BE-81EA760A423D', 'modelID': None, 'masterUuid': None, 'masterFingerprint':                        │ │
│ │ 'AZRPPzEeqIlt6TEzG6I3LgfrViLV', 'name': None, 'lastmodifieddate_timestamp': None, 'lastmodifieddate': None,              │ │
│ │ 'imageTimeZoneOffsetSeconds': 28800, 'imageDate_timestamp': 660043332, 'imageDate': datetime.datetime(2021, 12, 1, 17,   │ │
│ │ 22, 12, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'hidden': 0, 'favorite': 0, 'originalFilename':    │ │
│ │ 'RPReplay_Final1638350532.mp4', 'filename': '16E9B125-AF8A-4604-B1BE-81EA760A423D.mp4', 'directory': '1', 'latitude':    │ │
│ │ None, 'longitude': None, 'hasAdjustments': 0, 'cloudbatchpublishdate': None, 'shared': False, 'extendedDescription':     │ │
│ │ None, 'localAvailability': 1, 'remoteAvailability': 1, 'isMissing': 0, 'adjustmentUuid': None, 'adjustmentFormatID':     │ │
│ │ None, 'type': 1, 'UTI': 'public.mpeg-4', 'UTI_original': None, 'burstUUID': None, 'burstPickType': 0, 'burst': False,    │ │
│ │ 'subtype': 103, 'live_photo': False, 'screenshot': False, 'slow_mo': False, 'time_lapse': False, 'customRenderedValue':  │ │
│ │ 0, 'hdr': False, 'depth_state': 0, 'portrait': False, 'panorama': False, 'selfie': False, 'cloudAssetGUID':              │ │
│ │ '666E7B54-38D6-4384-9E2A-3B2A38F9B1A7', 'cloudLocalState': 3, 'incloud': True, 'cloudLibraryState': None, 'cloudStatus': │ │
│ │ None, 'cloudAvailable': None, 'reverse_geolocation': None, 'placeIDs': None, 'placeNames': None, 'countryCode': None,    │ │
│ │ 'momentID': None, 'original_resource_choice': 0, 'raw_is_original': False, 'intrash': False, 'trasheddate_timestamp':    │ │
│ │ None, 'trasheddate': None, 'height': 1920, 'width': 888, 'orientation': 1, 'original_height': 1920, 'original_width':    │ │
│ │ 888, 'original_orientation': 1, 'original_filesize': 37976245, 'visibility_state': 0, 'visible': True,                   │ │
│ │ 'saved_asset_type': 8, 'isreference': False, 'added_date': datetime.datetime(2021, 12, 1, 17, 23, 37, 444464), 'pk':     │ │
│ │ 60474, 'cloudownerhashedpersonid': None, 'import_session': None, 'fok_import_session': None, 'import_uuid': None,        │ │
│ │ 'has_raw': False, 'raw_data_length': None, 'UTI_raw': None, 'datastore_subtype': None, 'resource_type': None,            │ │
│ │ 'raw_master_uuid': None, 'non_raw_master_uuid': None, 'alt_master_uuid': None, 'raw_info': None, 'hasKeywords': 0,       │ │
│ │ 'keywords': [], 'hasPersons': 0, 'persons': [], 'albums': [], 'hasAlbums': 0})

**Comment by RhetTbull** [comment]
Thanks for the additional data. Nothing jumps out about the Photo as to why Photos would think this an invalid photo ID other than the fact you deleted it but it still shows `'intrash': False`.  It is unexpected that the export2 command did log an error (`Invalid photo ID`) but this wasn't reported by osxphotos.  I'll look into this.

**Comment by narensankar0529** [comment]
I just checked on my MacBook Pro which doesn't download the originals from iCloud and it looks like the actual image (mp4) is recorded as being in iCloud so it does propagate to my MacBook as well as my M1 Mini which stores the originals

osxphotos query --name RPReplay_Final16
Using last opened Photos library: /Users/nsankar/Pictures/Photos Library.photoslibrary
2021-12-28 22:16:00,996 - WARNING - photosdb.py - 102 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6]: you have Darwin, OS version: 12.0
uuid,filename,original_filename,date,description,title,keywords,albums,persons,path,ismissing,hasadjustments,external_edit,favorite,hidden,shared,latitude,longitude,path_edited,isphoto,ismovie,uti,burst,live_photo,path_live_photo,iscloudasset,incloud,date_modified,portrait,screenshot,slow_mo,time_lapse,hdr,selfie,panorama,has_raw,uti_raw,path_raw,intrash
F9D5C634-F6D9-4C98-BEC7-B259E2FA95C5,F9D5C634-F6D9-4C98-BEC7-B259E2FA95C5.mp4,RPReplay_Final1638350532.mp4,2021-12-01T17:22:12+08:00,,,,,,,True,False,False,False,False,False,,,,False,True,public.mpeg-4,False,False,,True,True,,False,False,False,False,False,False,False,False,,,False

Not sure how to get rid of this entry from iCloud since there is no path for the file and it is marked ismissing according to osxphotos, but seems that an entry is present in the actual database in Photos. And repairing the Photos database makes no difference. So wondering if somehow this stale entry is being ignored by Photos but osxphotos doesn't know why it is being ignored.

**Comment by RhetTbull** [comment]
> So wondering if somehow this stale entry is being ignored by Photos but osxphotos doesn't know why it is being ignored.

This is likely what's happening but I don't have any way to determine how Photos is doing this based on what I've been able to learn by reverse engineering the Photos database so far.  Without access to the actual library I'm not even sure I'd be able to determine what to look for.  

One possible work around would be the addition of a `--skip-uuid` option that would allow you to specify one or more photos to skip during the export process.  This would be an easy addition and could be used thusly:

`osxphotos export /path/to/export --skip-uuid F9D5C634-F6D9-4C98-BEC7-B259E2FA95C5`

**Comment by narensankar0529** [comment]
Yeah. Skipping would be the best option. But wondering if the UUIDs can be specified from a file instead to be read if that works since that would be easier for scripting

**Comment by RhetTbull** [comment]
> But wondering if the UUIDs can be specified from a file instead to be read if that works since that would be easier for scripting

Yeah, it would be easy to add a `--skip-uuid-from-file` that works just like `--uuid-from-file`

**Comment by narensankar0529** [comment]
Great! That would be perfect then

Thanks!
—————

Naren Sankar

**Comment by RhetTbull** [comment]
I've added `--skip-uuid`, `--skip-uuid-from-file` to [v0.44.1](https://github.com/RhetTbull/osxphotos/releases/tag/v0.44.1).  These work just like `--uuid` and `--uuid-from-file`.

**Comment by narensankar0529** [comment]
Great! Thanks

Thanks!
—————

Naren Sankar
