### ISSUE TITLE
--preview does not export preview for missing files with --download-missing

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#564]
@spencerc99 I finally got some time to take a look at this issue.  I have not been able to reproduce the "preview_preview" issue but I did discover a bug associated with `--preview` and `--download-missing`.  Namely, if the original file is missing and thus the `--download-missing` code runs, the code that exports the preview will not be run and thus previews aren't exported for missing photos.  If the export is run again with --update, chances are good the originals will now be in the library (they were downloaded in the previous run) and now the preview code is reached, exporting the previews.  I'll open a new issue for this.  Still looking into the duplicate preview and the --overwrite issue.

_Originally posted by @RhetTbull in https://github.com/RhetTbull/osxphotos/issues/526#issuecomment-1003593631_

**Comment by spencerc99** [comment]
great thank you!
