### ISSUE TITLE
Question: Can I export image thumbnails with their exif data using osxphotos?

### ISSUE THREAD

**Issue by Cybrosys** [RhetTbull/osxphotos#566]
Hello!

I've been given a corrupt(?) Photos library where some of the images no longer have their original image file available (not in iCloud either). I can't export any of the images using the build in features, because they all try to use the "original" data. What I can do is select the images I am interrested in and do a copy & paste to an empty folder. Doing so gives me the "thumbnail" version of the images, which for these old images are close to the original in visual quality. The only issue with the copy & paste-aproach is that the exif data is not extracted. 

Can I use osxphotos to extract the image thumbnails and have the exif data as well?

What I'm mostly after is having the correct date, currently the date written is when the thumbnail was initially created or when the image was originally added to the library. So photos from e.g. May & June 2014 will get 18 July 2014 as the file creation date because that was when the user synced/added the images. The date in Photos is the correct one, e.g. 4 June 2014.

**Comment by RhetTbull** [comment]
Yes.  In osxphotos, these are referred to as "preview" images.  You can export them using the `--preview` flag.  For example:

`osxphotos export /path/to/export --directory "{folder_album}" --preview --exiftool`

The `--directory "{folder_album}"` tells osxphotos to use the same folder/album structure in Photos to export the photos to.  You can specify many other options depending on how you'd like the photos organized.  If you don't specify a `--directory` option, all the photos will be dumped into a single folder (specified by /path/to/export argument)

You'll need [exiftool](https://exiftool.org/) installed to use the `--exiftool` option.

By default, the preview files will be named `filename_preview.jpeg` You can use the `--preview-suffix` option to change the preview suffix to something else.

Note: Photos stores something called thumbnails too but these are *very* small images used for the small thumbnail image shown in the "All Photos" view -- these use a special file format that osxphotos does not support.

**Comment by Cybrosys** [comment]
> 

Thank you so much! Just tried it and it works like a charm!
