### ISSUE TITLE
query --name does not find a specific pic/filename 

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#571]
**osxphotos, version 0.44.4**

**Describe the bug**
- While trying to dump into a `csv` file the full contents of the Photos database with command `osxphotos query --in-album > RKMaster.csv`
- I later found a particular filename was missing: `IMG_20190805_154316.JPG`
- I've then went in with `sqlite3` on the `Photos.sqlite` file and compared with result of `osxphotos query --name IMG_20190805_154316` (see below)
- Either:
   - I'm doing something wrong
   - or there is some particular _status_ on this asset which prevents the **query** to find that pic
   - or something else is preventing the query to find the file?
- let me know how I can add more _debug_ into it.

```
$ sqlite3 /Users/Shared/Pictures/iPhoto\ Shared\ Library.photoslibrary/database/Photos.sqlite
SQLite version 3.36.0 2021-06-18 18:58:49
Enter ".help" for usage hints.
sqlite> select * from zasset where zfilename like "%IMG_20190805_154316%";
88668|3|8|0|0|0|0|0||||||0|0|1|0|0|1|9570462743920721|0|0|0|2316|0|0|0|0|3|8163062088925207|0|5911215031779371|1|0|10|0|88468|0|0|0|0|0|0|0|3088|88669||83666||||||88666|3834|3834||3834|2692||||83574|3772||||||663089676.296619||663096491.984218||||0.5|586708996.3|0.0||0.0|0.0||40.4994466666667|-3.881295|663096520.119894|0.400390625|0.0|586708996.3||3E27CC3C-2362-436F-B2B6-6AD6E421980D|||||/Users/Shared/Pictures/Pictures/iPhoto/2019-08-31-0007-00/JSP|IMG_20190805_154316.JPG||Display P3|public.jpeg|6DD669E7-176C-4109-9922-50CC8D8A1ED5|?n	|??M???D@??d?
                                                                                                                                     ??("???@??1ىz"@|0
sqlite> .exit
$ osxphotos query --name IMG_20190805_154316
Using last opened Photos library: /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary
uuid,filename,original_filename,date,description,title,keywords,albums,persons,path,ismissing,hasadjustments,external_edit,favorite,hidden,shared,latitude,longitude,path_edited,isphoto,ismovie,uti,burst,live_photo,path_live_photo,iscloudasset,incloud,date_modified,portrait,screenshot,slow_mo,time_lapse,hdr,selfie,panorama,has_raw,uti_raw,path_raw,intrash
(venv) 
$ 
```

**To Reproduce**
1. What' the full command line you used with osxphotos? A: `osxphotos query --name IMG_20190805_154316`
2. What was the error output? A: see above.

**Expected behavior**
Would expect the row pointing to that file to be listed.

**Screenshots**
See log above.

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS]> Mac OS 12.1(Monterey)
 - osxphotos version (`osxphotos --version`): osxphotos, version 0.44.4

**Additional context**
N/A

**Comment by RhetTbull** [comment]
I'm not sure what would cause this.  Every photo in ZASSET is loaded by osxphotos and should be searched.

What happens if you select the photo in Photos and do a `osxphotos query --selected`?

**Comment by oPromessa** [comment]
Curiously enough MAC OS prompted with the following message when running `osxphotos query --selected`
<img width="259" alt="image" src="https://user-images.githubusercontent.com/21261491/148366886-0a804ae8-d52a-4fb4-b32f-964c9350d73d.png">

- I said OK. 
- Output is still empty for this particular pic.
- Tried selecting another pic on Photos and ran `osxphotos query --selected` again, and this time around it did produce an output.
- So there is something _fishy_ with this pic

**Comment by RhetTbull** [comment]
Very strange.  From the SQL output you included, it appears the UUID of this photo is `6DD669E7-176C-4109-9922-50CC8D8A1ED5`.  Try this to see if osxphotos is even loading the data associated with this photo:

`osxphotos debug-dump --dump photos --uuid 6DD669E7-176C-4109-9922-50CC8D8A1ED5`

**Comment by oPromessa** [comment]
Here's the output. IT seems it found it.
- Simply removed filed  'reverse_geolocation': <<REMOVED FOR PRIVACY REASONS>>
```
osxphotos debug-dump --dump photos --uuid 6DD669E7-176C-4109-9922-50CC8D8A1ED5
Using last opened Photos library: /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary
Opening database: /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary
Done; took 28.88 seconds
_dbphotos['6DD669E7-176C-4109-9922-50CC8D8A1ED5']:
{'UTI': 'public.jpeg',
 'UTI_original': None,
 'UTI_raw': None,
 '_uuid': '6DD669E7-176C-4109-9922-50CC8D8A1ED5',
 'added_date': datetime.datetime(2022, 1, 5, 15, 34, 36, 296619),
 'adjustmentFormatID': None,
 'adjustmentUuid': None,
 'albums': ['29584506-2147-44CC-85FC-336930074BB1'],
 'alt_master_uuid': None,
 'burst': True,
 'burstPickType': 0,
 'burstUUID': '3E27CC3C-2362-436F-B2B6-6AD6E421980D',
 'cloudAssetGUID': None,
 'cloudAvailable': None,
 'cloudLibraryState': None,
 'cloudLocalState': None,
 'cloudStatus': None,
 'cloudbatchpublishdate': None,
 'cloudownerhashedpersonid': None,
 'countryCode': None,
 'customRenderedValue': 0,
 'datastore_subtype': None,
 'depth_state': 0,
 'directory': '/Users/Shared/Pictures/Pictures/iPhoto/2019-08-31-0007-00/JSP',
 'extendedDescription': None,
 'favorite': 0,
 'filename': 'IMG_20190805_154316.JPG',
 'fok_import_session': None,
 'hasAdjustments': 0,
 'hasAlbums': 1,
 'hasKeywords': 0,
 'hasPersons': 1,
 'has_raw': False,
 'hdr': False,
 'height': 2316,
 'hidden': 0,
 'imageDate': datetime.datetime(2019, 8, 5, 16, 43, 16, 300000, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))),
 'imageDate_timestamp': 586708996.3,
 'imageTimeZoneOffsetSeconds': 7200,
 'import_session': 2692,
 'import_uuid': 'BC75C1A7-2199-40FA-A160-5F6A53FC9674',
 'incloud': None,
 'intrash': False,
 'isMissing': 0,
 'isreference': True,
 'keywords': [],
 'lastmodifieddate': None,
 'lastmodifieddate_timestamp': None,
 'latitude': 40.499446666666664,
 'live_photo': False,
 'localAvailability': 1,
 'longitude': -3.8812949999999997,
 'masterFingerprint': 'AVZPqiSWqcpbTGnKXqgVdKbfi1oQ',
 'masterUuid': None,
 'modelID': None,
 'momentID': 3772,
 'name': None,
 'non_raw_master_uuid': None,
 'orientation': 3,
 'originalFilename': 'IMG_20190805_154316.JPG',
 'original_filesize': 1413404,
 'original_height': 2316,
 'original_orientation': 3,
 'original_resource_choice': 0,
 'original_width': 3088,
 'panorama': False,
 'persons': [445, 461],
 'pk': 88668,
 'placeIDs': None,
 'placeNames': None,
 'portrait': False,
 'raw_data_length': None,
 'raw_info': None,
 'raw_is_original': False,
 'raw_master_uuid': None,
 'remoteAvailability': 0,
 'resource_type': None,
 'reverse_geolocation': 
<<REMOVED FOR PRIVACY REASONS>>
 'saved_asset_type': 10,
 'screenshot': False,
 'selfie': True,
 'shared': False,
 'slow_mo': False,
 'subtype': 0,
 'time_lapse': False,
 'trasheddate': None,
 'trasheddate_timestamp': None,
 'type': 0,
 'visibility_state': 0,
 'visible': True,
 'width': 3088}
```

**Comment by RhetTbull** [comment]
>    Simply removed filed 'reverse_geolocation':

Yeah, I've got plan to add a `--privacy` flag to the debug-dump command that would hash any private info like location, names, etc. just haven't gotten to it.  

The only thing that seems strange I see is that this photo appears to be a burst image (a group of photos taken in rapid succession by holding down the button on your phone).  In burst images, Photos selects a "key image" that is the one that's shown in the library then allows you to select other images.  osxphotos doesn't export or query non-selected burst images nor does Photos -- they're treated as if they don't exist until you select them. For example, in Photos, if you search for the filename of a non-selected burst image, it won't be shown.  The photo in question has a 'burstPickType' of 0 which I've never seen in testing.  'burstPickType' is a bit flag that can hold multiple values but I've never seen 0.  For example, "not selected" has a value of 2.  

```
 'burst': True,
 'burstPickType': 0,
 'burstUUID': '3E27CC3C-2362-436F-B2B6-6AD6E421980D',
```

osxphotos is acting as designed by filtering out this image:

```python
        if self._dbphotos[p]["burst"] and not (
                self._dbphotos[p]["burstPickType"] & BURST_SELECTED
                or self._dbphotos[p]["burstPickType"] & BURST_KEY
         ):
                # not a key/selected burst photo, don't include in returned results
                continue
```

So some questions are "is this photo somehow corrupted in the database?" and "is 'burstPickType' 0 valid and how should osxphotos handle this?"  

I guess another question is "is the current osxphotos behavior, which ignores non-selected burst-images, correct (and what users would expect) or should osxphotos query/export all burst images?" Or maybe should osxphotos add a --non-selected-bursts flag that also queries/exports non-selected-bursts?

Can you export this photo from Photos using the `File | Export` command?

This photo appears to be a reference (not copied to Photos library): `'isreference': True,`  Is the original file on disk? (e.g. if you search your photos directory for the filename do you find the image?)

**Comment by oPromessa** [comment]
Thanks for the prompt reply!

**Comment by oPromessa** [comment]
- So further to this, I found the explanation to have:I've looked around and these pics were possibly part of a **burst** sequence from an iPhone.
- Given that `exiftool` reports a `Burst UUID` field, 
```
# exiftool IMG_20190805_154316.JPG | grep -i uuid
Burst UUID                      : 3E27CC3C-2362-436F-B2B6-6AD6E421980D
```
- But my workflow of importing iPhotos

**Comment by RhetTbull** [comment]
It should be easy to include 'ZAVALANCHEPICKTYPE=0' photos in the results returned by osxphotos as this appears to the only use case of this. (non-seleected = 2).  I think I'll also add a `--non-selected-bursts` filter that filters *only* the non-selected bursts and a `--all-bursts` filter that includes the non-selects in other search results.

**Comment by RhetTbull** [comment]
I think [v0.44.6](https://github.com/RhetTbull/osxphotos/releases/tag/v0.44.6) will allow you to query/export this photo now as I fixed it to include burst images with pick type == 0. (Normal images have ZAVALANCHEPICKTYPE=0 but the code was filtering out burst images with this same pick type).  I've opened a new issue (#574) to add the `--non-selected-bursts` and `--all-burst` filters.  Let me know if you're able to now query/export the photo(s) in question.

**Comment by oPromessa** [comment]
Worked like a charm.
- `osxphotos --name` finds the pic
- `osxphotos query --in-album` includes such pics in the resulting file.
   - And the counts add up: photo_count + movie count = 89646 (total lines exported).

item|count|total (photo+movie)
--|--|--
photo_count| 87777|
movie_count| 1869|89646
hidden_photo_count| 4904|


Thanks again! Super Work!
