### ISSUE TITLE
"Wrong database format" error with Photos.app 7.0 and latest osxphotos

### ISSUE THREAD

**Issue by ahti123** [RhetTbull/osxphotos#575]
osxphotos installed from git repository (but the same is with pip and binary, too)
maxOS Monterey 12.1
Photos.app 7.0
osxphotos, version 0.44.6

Running osxphotos export exits with an error:
"RuntimeError: Wrong database format!"

Complete commandline for the export:
osxphotos export ./photos --dry-run

There is a warning, too:
WARNING: Only tested on database versions [6000, 4025, 4016, 3301, 2622] You have database version=5001 which has not been tested

osxphotos is able to display db info, though, with command info

**Comment by RhetTbull** [comment]
This is a database version I've not seen before so the code doesn't know which schema to use.  Please run the following commands and attach the output here:

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/photos.db ".schema" > db_schema.txt`

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/photos.sqlite ".schema" > sqlite_schema.txt`

Should be an easy fix once I get the schemas. These commands assume the the library is in the default location so adjust the path accordingly.

**Comment by RhetTbull** [comment]
See also #102, #459

**Comment by ahti123** [comment]
Aha, I thought I did search the issue history. Anyway, as the #459 seems not to have schemas attached, I will add them here
[db_schema.txt](https://github.com/RhetTbull/osxphotos/files/7834740/db_schema.txt)
[sqlite_schema.txt](https://github.com/RhetTbull/osxphotos/files/7834741/sqlite_schema.txt)

**Comment by ahti123** [comment]
Funnly enough, changing db version value from 6000 to 5000, to bluntly satisfy the condition, it works :)
[osxphotos_db_version.patch.txt](https://github.com/RhetTbull/osxphotos/files/7834775/osxphotos_db_version.patch.txt)

**Comment by RhetTbull** [comment]
Thanks for the schema info -- I've been trying to get those for this DB version for a long time.  Thanks also for the PR. I'll implement it but it won't be entirely sufficient as this DB version "5001" has also shown up on Catalina which has a different schema than Monterey.  I'll have to detect which one to switch schemas.  

When you run osxphotos do you get a warning about "Unknown model version:"?  If so, could you post the whole warning here.  There are several pieces of version information needed to determine which schema to use and this is one of them.

**Comment by RhetTbull** [comment]
Actually, this would also be helpful:

At terminal type `osxphotos repl` which launches osxphotos into an interactive mode.  Then type at the prompt:

`osxphotos.photosdb.get_model_version(photosdb._dbfile_actual)`

and post the result.  Should be an integer number.

**Comment by RhetTbull** [comment]
I'd still like the check the model version for your database but looking through the code again, I *think* it'll do the right thing regarding different schemas for Catalina and BigSur/Monterey with your change. I've released [v0.44.8](https://github.com/RhetTbull/osxphotos/releases/tag/v0.44.8) that includes your fix. Thanks!

**Comment by ahti123** [comment]
> `osxphotos.photosdb.get_model_version(photosdb._dbfile_actual)`
> and post the result. Should be an integer number.

Model version reported:
15331

**Comment by RhetTbull** [comment]
Thanks!  That's in the range I'd guessed for Monterey so all the schema logic should work fine.
