### ISSUE TITLE
CLI to list all photos with original filenames by camera type and file format

### ISSUE THREAD

**Issue by tbelcher** [RhetTbull/osxphotos#595]
**Is your feature request related to a problem? Please describe.**
My Photos library recently blew up and my latest backup is from a year ago.  I'd like to make sure that I've accounted for all new photos because Photos seems to be buggy about importing large amounts of pictures.  In any event, I'd like to get a list of all photos with original filenames based on camera type.  This will allow me to look for gaps in the sequences due to missing photos.  It doesn't appear that I can do this via the CLI.

**Describe the solution you'd like**
I'd like to be able to run the CLI and get a CSV that contains original filename, UUID/current filename, camera type, and file type (Raw, Joe, etc)

**Describe alternatives you've considered**
No alternate solution that I've been able to find

**Additional context**

**Comment by RhetTbull** [comment]
This is too niche to create an actual CLI feature out of but fortunately, what you're asking is super easy using the osxphotos python interface.  osxphotos has an interactive mode called `osxphotos repl` (repl = read-evaluate-print loop).  If you run `osxphotos repl` then type the following commands, it will generate the file you want.  You should be able to copy and paste directly into the repl interface.

```
import csv
with open("photos.csv", "w", newline="") as csvfile:
     csvwriter = csv.writer(csvfile, delimiter=",", quotechar='|', quoting=csv.QUOTE_MINIMAL)
     # write the header row
     csvwriter.writerow(["original_filename", "uuid", "current_filename", "camera_type", "file_type"])
     for photo in photos:
         csvwriter.writerow([photo.original_filename, photo.uuid, photo.filename, photo.exif_info.camera_make, photo.uti_original])
```

When you paste, it'll look like this.  You may need to hit `return` again after pasting.
```pycon
>>> import csv
>>> with open("photos.csv", "w", newline="") as csvfile:
...     csvwriter = csv.writer(csvfile, delimiter=",", quotechar='|', quoting=csv.QUOTE_MINIMAL)
...     # write the header row
...     csvwriter.writerow(["original_filename", "uuid", "current_filename", "camera_type", "file_type"])
...     for photo in photos:
...         csvwriter.writerow([photo.original_filename, photo.uuid, photo.filename, photo.exif_info.camera_make, photo.uti_original])
>>>
```

You'll be left with a CSV file called `photos.csv` containing the desired info.

**Comment by tbelcher** [comment]
Thank you for the quick reply!  I'll give it a shot this weekend.

**Comment by tbelcher** [comment]
So it seems to have run, although I'm not sure if it's completed or not.  

It gave the following when I initially ran it:
import csv
with open("photos.csv", "w", newline="") as csvfile:
     csvwriter = csv.writer(csvfile, delimiter=",", quotechar='|', quoting=csv.QUOTE_MINIMAL)
     # write the header row
     csvwriter.writerow(["original_filename", "uuid", "current_filename", "camera_type", "file_type"])
     for photo in photos:
         csvwriter.writerow([photo.original_filename, photo.uuid, photo.filename, photo.exif_info.camera_make, photo.uti_original])
python version: 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)]
osxphotos version: 0.44.9
Using last opened Photos library: /Users/belchet/Pictures/Photo library test.photoslibrary
Loading database
Processing database /Users/belchet/Pictures/Photo library test.photoslibrary/database/photos.db
Processing database /Users/belchet/Pictures/Photo library test.photoslibrary/database/Photos.sqlite
Database locked, creating temporary copy.
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Done: took 1.43 seconds
Getting photos
Found 10683 photos in 1.08 seconds

The following classes have been imported from osxphotos:
- AlbumInfo, ExifTool, PhotoInfo, PhotoExporter, ExportResults, PhotosDB, PlaceInfo, QueryOptions, MomentInfo, ScoreInfo, SearchInfo

The following variables are defined:
- photosdb: PhotosDB() instance for /Users/belchet/Pictures/Photo library test.photoslibrary
- photos: list of PhotoInfo objects for all photos in photosdb, including those in the trash (len=10683)
- selected: list of PhotoInfo objects for any photos selected in Photos (len=0)

The following functions may be helpful:
- get_photo(uuid): return a PhotoInfo object for photo with uuid; e.g. get_photo('B13F4485-94E0-41CD-AF71-913095D62E31')
- get_selected(); return list of PhotoInfo objects for photos selected in Photos
- show(photo): open a photo object in the default viewer; e.g. show(selected[0])
- show(path): open a file at path in the default viewer; e.g. show('/path/to/photo.jpg')
- spotlight(photo): open a photo and spotlight it in Photos
- inspect(object): print information about an object; e.g. inspect(PhotoInfo)
- explore(object): interactively explore an object with objexplore; e.g. explore(PhotoInfo)
- q, quit, quit(), exit, exit(): exit this interactive shell

>>> import csv
>>> with open("photos.csv", "w", newline="") as csvfile:
...          csvwriter = csv.writer(csvfile, delimiter=",", quotechar='|', quoting=csv.QUOTE_MINIMAL)
...               # write the header row
...          csvwriter.writerow(["original_filename", "uuid", "current_filename", "camera_type", "file_type"])
...          for photo in photos:
...              csvwriter.writerow([photo.original_filename, photo.uuid, photo.filename, photo.exif_info.camera_make, photo.uti_original])

and then sat waiting for me to figure out what the Meta key was (It wanted me to hit Meta plus enter).

Then it created the csv file, but spit out the following and is just sitting at a "[" prompt:
>>> with open("photos.csv", "w", newline="") as csvfile:
...          csvwriter = csv.writer(csvfile, delimiter=",", quotechar='|', quoting=csv.QUOTE_MINIMAL)
...               # write the header row
...          csvwriter.writerow(["original_filename", "uuid", "current_filename", "camera_type", "file_type"])
...          for photo in photos:
...              csvwriter.writerow([photo.original_filename, photo.uuid, photo.filename, photo.exif_info.camera_make, photo.uti_original])

How will I know when it's done?
Thanks,

Tim

**Comment by RhetTbull** [comment]
> and then sat waiting for me to figure out what the Meta key was (It wanted me to hit Meta plus enter).

I have no idea what this means. You should just enter the python code then press Enter

>Then it created the csv file, but spit out the following and is just sitting at a "[" prompt:

There's an error in the code that got transcribed.

Hit Ctrl+C to cancel then type `quit` to quit the REPL.  Relaunch `osxphotos repl` then copy the code using the copy button:

<img width="823" alt="Screen Shot 2022-01-22 at 4 55 46 PM" src="https://user-images.githubusercontent.com/41546558/150660473-9079cb60-9694-4021-917a-0af53a7e4b45.png">

Then paste the code into the REPL and hit Enter 2 times

It'll be done when you see the `>>>` prompt appear as below:

<img width="1264" alt="Screen Shot 2022-01-22 at 4 56 09 PM" src="https://user-images.githubusercontent.com/41546558/150660463-07a2e211-02ea-476c-ae6f-0b931a05910d.png">

**Comment by RhetTbull** [comment]
I also updated the code above to print "Done!" when done :-)

**Comment by RhetTbull** [comment]
Hi @tbelcher were you able to get this to work?

**Comment by tbelcher** [comment]
Hi @RhetTbull,

Yes, thank you, it seems to be working but I have a question:
I have only 1500 photos in my test library, but when I run this I get the information for more than double that number.  Is it possible that this is also including photos from Shared Albums?  If so, is there a way that I can exclude those? If not, any idea what the extra photos may be?  They all seem to have UUID's as their filenames and I've rebuilt the library but still get the same result.

Also, I added "photo.date" to the output to get the original date the photo was taken.  This seems to be correct, but please let me know if I'm overlooking something.

Thank you again,

Tim

**Comment by RhetTbull** [comment]
>  Is it possible that this is also including photos from Shared Albums? 

Yes, it does. Also includes photos in the trash (recently deleted).  Add this line right below `import csv`
`photos = [photo for photo in photos if not photo.shared and not photo.intrash]`

So your code should look like this.

```pycon
>>> import csv
... photos = [photo for photo in photos if not photo.shared and not photo.intrash]
... with open("photos.csv", "w", newline="") as csvfile:
...      csvwriter = csv.writer(csvfile, delimiter=",", quotechar='|', quoting=csv.QUOTE_MINIMAL)
...      # write the header row
...      csvwriter.writerow(["original_filename", "uuid", "current_filename", "camera_type", "file_type"])
...      for photo in photos:
...          csvwriter.writerow([photo.original_filename, photo.uuid, photo.filename, photo.exif_info.camera_make, photo.uti_original])
...      print("Done!")
```

Try this: 
> Also, I added "photo.date" to the output to

Yes, that's the creation date of the photo

**Comment by RhetTbull** [comment]
In case you haven't figured it out, you can use the arrow keys to cycle through previous commands in the repl and then edit the commands so you don't have to retype everything. If you're not familiar with vim keybindings, launching the repl with the --emacs option might be easier.
