### ISSUE TITLE
Do you need help testing Darwin 12.2

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#636]
**Is your feature request related to a problem? Please describe.**
Related with warning message:
```
WARNING - photosdb.py - 110 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.0, 12.1]: you have Darwin, OS version: 12.2
```

**Describe the solution you'd like**
Testing with this MacOS 12.2 version may be required. 

**Describe alternatives you've considered**
So far no errors detected. 

**Additional context**
Using osxphotos with Darwin 12.1 for some time. OS was now upgraded.

**Comment by RhetTbull** [comment]
That would be great.  If you wait until I release 0.46.0 (to fix #630) then run the test suite that would be helpful.

There are still some issues with shared photos on 12.x I haven't been able to track down but as far as I know, most everything else is working (sporadic issues with `--use-photokit` too).

1. clone the repo
2. create and activate a virtual environment (using whatever method you normally use)
3. `pip install -r dev_requirements.txt`
4. `pip install -r requirements.txt`
5. `pytest`

**Comment by oPromessa** [comment]
* @RhetTbull tested with `0.46.1` with `Darwin 12.2` and `python 3.9.10`. Hope not helps!!!

* Running `pytest` gave me the following error:
```
ImportError while loading conftest '/Users/MSP/Documents/GitHub/osxphotos/tests/conftest.py'.
tests/conftest.py:8: in <module>
    import osxphotos
E   ModuleNotFoundError: No module named 'osxphotos'
```
* Running `python3 -m bytes`
    * Generated `osxphotos_crash.log` half way through. Pressed "y" to continue.
```
$ cat osxphotos_crash.log
osxphotos crash log
Created: 2022-02-21 13:45:50.444888
Python version: 3.9.10 (main, Jan 15 2022, 11:48:04) 
[Clang 13.0.0 (clang-1300.0.29.3)]
Platform: macOS-12.2-x86_64-i386-64bit
sys.argv: ['/Users/MSP/Documents/GitHub/osxphotos/venv/lib/python3.9/site-packages/pytest/__main__.py']
osxphotos version: 0.46.1
Error: 
Traceback (most recent call last):
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/crash_reporter.py", line 26, in wrapped
    return func(*args, **kwargs)
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/cli.py", line 1835, in export
    click.confirm("Do you want to continue?", abort=True)
  File "/Users/MSP/Documents/GitHub/osxphotos/venv/lib/python3.9/site-packages/click/termui.py", line 248, in confirm
    raise Abort()
click.exceptions.Abort
```
* It seems several instances of `osxphotos_crash.log` are created as errors occur and the file is overwritten.
* Final result was
```
=========================================== 62 failed, 1070 passed, 77 skipped in 354.72s (0:05:54) ===========================================
```
* The full output log is [osxphotos.0.46.1_darwin.12.2.txt](https://github.com/RhetTbull/osxphotos/files/8112232/osxphotos.0.46.1_darwin.12.2.txt)

**Comment by RhetTbull** [comment]
Sorry, missed a step above. Before running pytest you need to install osxphotos:

from in the osxphotos directory:
`pip install .`

or
`pip install -e .` if you want an editable install (e.g. you'll be developing on this clone)

**Comment by oPromessa** [comment]
ok. Thanks!. Looking at the failures is because of the **WARNING** message which is not expected?
```
------------------------------------------------------------ Captured stderr call -------------------------------------------------------------
2022-02-21 13:13:24,435 - WARNING - photosdb.py - 110 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.0, 12.1]: you have Darwin, OS version: 12.2
```

**Comment by RhetTbull** [comment]
Thanks -- I'll take a look at the crash log to see if I can figure out what's going on.

**Comment by RhetTbull** [comment]
All of the failed tests relate to exiftool.  These tests should be skipped automatically if exiftool isn't in your path but since they're getting run, I'm guessing exiftool is in the path but something is still going wrong.   What's the output of these two commands?

`which exiftool`
`exiftool -ver`

**Comment by RhetTbull** [comment]
Putting this here for future reference:

To set up a dev environment to work on osxphotos code or run tests follow these steps.  This assumes you have python 3.7 or later installed.  If you need to install python, you can do so with the XCode command lines tools (`xcode-select --install`) or from [python.org](https://www.python.org/downloads/macos/).

- `git clone git@github.com:RhetTbull/osxphotos.git`
- `cd osxphotos`
- `python3 -m venv venv`
- `source venv/bin/activate`
- `python3 -m pip install -r dev_requirements.txt`
- `python3 -m pip install -e .`
- `python3 -m pytest -vv`

**Comment by RhetTbull** [comment]
I just did a clean clone / install / test and everything worked fine on 10.15.7.  I wanted to make sure it wasn't a "works on my machine" kind of thing.  This could be an issue with how I'm launching the exiftool subprocess that 12.2 doesn't like (maybe it's a new "security feature").

**Comment by oPromessa** [comment]
> All of the failed tests relate to exiftool. These tests should be skipped automatically if exiftool isn't in your path but since they're getting run, I'm guessing exiftool is in the path but something is still going wrong. What's the output of these two commands?
> 
> `which exiftool` `exiftool -ver`

```
$ which exiftool
/usr/local/bin/exiftool
$ exiftool -ver
12.37
```
* Note: Downloaded and installed from [https://exiftool.org/]( https://exiftool.org/)

**Comment by oPromessa** [comment]
> I just did a clean clone / install / test and everything worked fine on 10.15.7. I wanted to make sure it wasn't a "works on my machine" kind of thing. This could be an issue with how I'm launching the exiftool subprocess that 12.2 doesn't like (maybe it's a new "security feature").

* Maybe if you provide me a small snippet code on how you call `exiftool` I can run it for you.
* Of course with Monterey version I add to provide additional access permissions to Terminal, etc.

**Comment by RhetTbull** [comment]
That's exactly what I'm running.  Have you tried the `--exiftool` feature of osxphotos and if so, doesn't work for you?  Maybe select a photo in your library then try `osxphotos export /private/tmp --selected --verbose --exiftool` and see what the output is.

**Comment by oPromessa** [comment]
> That's exactly what I'm running. Have you tried the `--exiftool` feature of osxphotos and if so, doesn't work for you? Maybe select a photo in your library then try `osxphotos export /private/tmp --selected --verbose --exiftool` and see what the output is.

With 0.45.12 the exiftool is running fine on some small tests I was doing (working with keywords and persons) Will test with 0.46.1

Thanks, MSP

**Comment by RhetTbull** [comment]
Thanks...so it's something with the test setup as osxphotos appears to be working.  I'll take another look at the test cases.

**Comment by oPromessa** [comment]
Hold on a second. Just got a permission error `ssd`-- yes I was running the tests remotely from the ssh commend line. Possibly that prevented the test from running.

Just gave the ok and will try again...

**Comment by oPromessa** [comment]
Meanwhile just got an indication to upgrade to:
* Monterey 12.2.1
* and Command Line Tools for Xcode 13.12

(willl probably run it in a little while)

**Comment by oPromessa** [comment]
(Update)
* So I have re-ran the test from the Terminal on the main MAC directly.
* Result is similar. 
```
=========== 62 failed, 1070 passed, 77 skipped in 124.77s (0:02:04) ============
```
* Full Log file. [so.txt](https://github.com/RhetTbull/osxphotos/files/8112759/so.txt)
* the last **crash** file is here. [osxphotos_crash.txt](https://github.com/RhetTbull/osxphotos/files/8112762/osxphotos_crash.txt)

**Comment by RhetTbull** [comment]
Maybe I should add a time stamp to the crash log file name? 

The last crash log appears to be from one of your runs not a test?  It looks like there's an error in `smalltest.toml`

This is weird...it appears every test that uses exiftool is failing as if the exiftool process is barfing but I can't figure out why.  Will keep digging.

**Comment by oPromessa** [comment]
> Maybe I should add a time stamp to the crash log file name? 
> 
> 
> 
> The last crash log appears to be from one of your runs not a test?  It looks like there's an error in `smalltest.toml`
> 
> 
> 
> This is weird...it appears every test that uses exiftool is failing as if the exiftool process is barfing but I can't figure out why.  Will keep digging. 

- Yes. Time stamping it might be good. Just wondering with too t crashes on the failed tests we may reach a large number of crash files. 
- incorrect crash file. Update it above with correct one.

**Comment by RhetTbull** [comment]
The crash log above is a "valid" crash as the test in question (`tests/test_cli.py::test_bad_query_eval`) is intended to crash -- e.g. to verify an invalid query criteria causes osxphotos to exit with error. I didn't realize the test suite would create these in the source folder as most of the tests should run in an isolated temp directory. I'm still not sure what the issue is with the exiftool tests.

**Comment by RhetTbull** [comment]
Can you try this command (it's the same as one of the tests that failed) from the osxphotos directory where you cloned the repo:

`osxphotos query --db tests/Test-10.15.7.photoslibrary --json --exif 'EXIF:Make' 'FUJIFILM'`

**Comment by oPromessa** [comment]
Output is:
```
$ osxphotos query --db tests/Test-10.15.7.photoslibrary --json --exif 'EXIF:Make' 'FUJIFILM'
2022-02-22 07:28:18,419 - WARNING - photosdb.py - 110 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.0, 12.1]: you have Darwin, OS version: 12.2
[]
```

- Oddly enough if I add --verbose to that very same command line it does recognize it as an option:

```
$ osxphotos query --db tests/Test-10.15.7.photoslibrary --json --exif 'EXIF:Make' 'FUJIFILM' --verbose
Usage: osxphotos query [OPTIONS] [PHOTOS_LIBRARY]...
Try 'osxphotos query -h' for help.

Error: No such option: --verbose
```

**Comment by RhetTbull** [comment]
Try a `git pull` then the following:

`python3 -m osxphotos query --db tests/Test-10.15.7.photoslibrary --json --exif 'EXIF:Make' 'FUJIFILM' --debug > exiftool.txt`

**Comment by oPromessa** [comment]
`query` command does not seem to recognize `--debug` option :(
```
$  python3 -m osxphotos query --db tests/Test-10.15.7.photoslibrary --json --exif 'EXIF:Make' 'FUJIFILM' --debug
Usage: python -m osxphotos query [OPTIONS] [PHOTOS_LIBRARY]...
Try 'python -m osxphotos query -h' for help.

Error: No such option: --debug Did you mean --db?
$
```

**Comment by RhetTbull** [comment]
Did you do a `git pull`? I added the debug option today to the version on GitHub.

**Comment by RhetTbull** [comment]
Thanks, that was helpful...getting closer. I added more debugging logic. Please try the same command again when you get chance (after doing a `git pull`).  I'm not at my computer so made the changes directly in GitHub without testing...living dangerously!


> It does generate the XATTR warning. With -q -q it can be removed!

Does it print a warning to screen?  

exiftool is calling `xattr` command to read extended attributes. I'm guessing Monterey has done something to lock down reading extended attributes.  On Big Sur, xattr was broken so it wouldn't write extended attributes.  I know why Apple is making these changes ("security" & "privacy") but MacOS is becoming increasingly less useful for the power user that wants to use command line.  Very frustrating!  

> With -q -q it can be removed!

Not implemented for query but with `osxphotos export` you can use `--exiftool-option '-q'` `--exiftool-option '-q'` to add these flags.  I'll take a look at implications of adding `-q -q` to the osxphotos exiftool interface to make sure making this the default doesn't break anything.

**Comment by oPromessa** [comment]
> living dangerously!

Ah ah ah!

Here's the new 
[exiftool.txt](https://github.com/RhetTbull/osxphotos/files/8119189/exiftool.txt)

1. Use of `-q -q`... quite mode... of course it may have unwanted side effects :(
```
$ exiftool /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg  
ExifTool Version Number         : 12.37
Now                             : 2022:02:22 18:27:08+00:00
New GUID                        : 20220222-1827-0800-5E71-068565516238
File Sequence                   : 0
File Name                       : 3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg
(...)
MD Item FS Owner User ID        : 501
MD Item FS Size                 : 1477654
MD Item FS Type Code            : 
Warning                         : Error running "xattr" to extract XAttr tags
File Type                       : JPEG
File Type Extension             : jpg
(...)
Lens ID                         : iPhone 6s back camera 4.15mm f/2.2
Processing Time                 : 0.165 s
$ exiftool -MajorBrand /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg  
Warning: Error running "xattr" to extract XAttr tags - /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg
(venv) 


$ exiftool -q -MajorBrand /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg  
Warning: Error running "xattr" to extract XAttr tags - /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg


$ exiftool -q -q -MajorBrand /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg  
```

**Comment by oPromessa** [comment]
1. Looked at Exiftool source code for this error
   * https://github.com/exiftool/exiftool/blob/00e4fdc52ea3780e25b0371e9817ecb39329518c/lib/Image/ExifTool/MacOS.pm#L568-L571
``` 

2. One can see xattr is called with `-lx` parameters from exiftool!

3. Which xattr?
```
$ which xattr
/Users/MSP/Documents/GitHub/osxphotos/venv/bin/xattr

$ ls -la venv/bin/xattr
16449314 8 -rwxr-xr-x  1 MSP  staff   246B 21 Feb 21:02 venv/bin/xattr
```

4.Does not seem to accept `-lx` option 
```
$ xattr -lx /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg
option -x not recognized

usage: xattr [-slz] file [file ...]
       xattr -p [-slz] attr_name file [file ...]
       xattr -w [-sz] attr_name attr_value file [file ...]
       xattr -d [-s] attr_name file [file ...]
       xattr -c [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -s: act on symbolic links themselves rather than their targets
  -l: print long format (attr_name: attr_value)
  -z: compress or decompress (if compressed) attribute value in zip format
(venv) 
```
5. whereas the `/usr/bin/xattr`does... although with no output! ;)
```
$ /usr/bin/xattr -lx /Users/MSP/Documents/GitHub/osxphotos/tests/Test-10.15.7.photoslibrary/originals/3/3DD2C897-F19E-4CA6-8C22-B027D5A71907.jpeg

```

**Comment by RhetTbull** [comment]
Good sleuthing! I believe that xattr is coming from the [python xattr](https://pypi.org/project/xattr/) package which is used by [osxmetadata](https://github.com/RhetTbull/osxmetadata) which osxphotos uses for the --xattr and finder tags options.  Will need to think about how to fix this...it might be possible for osxphotos to manipulate the path so exiftool finds the right xattr.  It would be best for exiftool to use full path to xattr -- I'll post a note on [exiftool forum](https://exiftool.org/forum/index.php) -- the author is pretty responsive.

**Comment by RhetTbull** [comment]
> Ahah!

`json.loads error Expecting ',' delimiter: line 1 column 339 (char 338)`

There's an error loading the JSON response back from exiftool (exiftool is working but osxphoto's was silently catching the exception). The exception is caused by the `&quot` character in: `"ExifTool:Warning": "Error running &quot;xattr&quot; to extract XAttr tags"` (related to the same `xattr` problem).  I'll have to make sure this being properly escaped before processing.

**Comment by RhetTbull** [comment]
The relevant bit of code is:

https://github.com/RhetTbull/osxphotos/blob/6cb7dedd9be53d2c62489125fc44b9f4dccfb7ae/osxphotos/exiftool.py#L404-L442

**Comment by RhetTbull** [comment]
Something like this should work for helping exiftool find the right path:

```python 
import subprocess, os
my_env = os.environ.copy()
my_env["PATH"] = "/usr/sbin:/sbin:" + my_env["PATH"]
subprocess.Popen(my_command, env=my_env)
```

**Comment by RhetTbull** [comment]
I implemented what I think will be a fix.  Try a `git pull` and re-run the test suite.  You can run just the exiftool tests with `python3 -m pytest -k exiftool`

**Comment by oPromessa** [comment]
1. Will do.

2. Meanwhile opened [issue 101 at the xattr project](https://github.com/xattr/xattr/issues/101#issue-1147476616) and got the following response...

> I'm not sure when I would have time to look at this, but if someone else is interested it looks like this is where Apple keeps their fork and patches: https://opensource.apple.com/source/python_modules/python_modules-61.140.1/Modules/xattr-0.6.4/

**Comment by RhetTbull** [comment]
I think the real problem isn't with xattr package but with exiftool calling xattr without path.  I opened an [exiftool issue](https://github.com/exiftool/exiftool/issues/122). In the meantime, I *think* the workaround I implemented will work.

**Comment by oPromessa** [comment]
* Hurrah!!! Successful test with `0.46.3` on `Darwin 12.2.1`
```
$ osxphotos --version
osxphotos, version 0.46.3

$ python3 -m pytest -vv 
(...)
================= 1132 passed, 78 skipped in 125.06s (0:02:05) =================
```

**Comment by RhetTbull** [comment]
Updated the version check in [0.46.5](https://github.com/RhetTbull/osxphotos/releases/tag/v0.46.5) (forgot to do it in 0.46.4 which I'd just released!)

**Comment by oPromessa** [comment]
Tested with success!
```
(...)
====== 1133 passed, 78 skipped in 124.55s (0:02:04) ======
$  osxphotos --version
osxphotos, version 0.46.5
```

**Comment by RhetTbull** [comment]
@oPromessa if you could run one more test, this would be helpful.  There are a number of tests that are skipped when not running on my machine because they either need access to my personal library or direct user intervention.  Some of those relate to the use of AppleScript and PhotoKit to download missing photos.  I've had reports of some trouble with those on Monterrey (but working for other people) so I'd like to get more data. Could you try the following...select a photo in Photos from your library then run this command:

`osxphotos export /private/tmp --use-photos-export --selected --verbose`

That will exercise both the AppleScript interface (to grab the selected photo's UUID) then the PhotoKit interface to do the actual export (instead of copying the file out of the library which is what osxphotos does)

If it crashes, it'll produce a crash log you can post here.  Your terminal (Terminal.app, iTerm, etc) should prompt you for permission to access the Photos library which it'll need for this to work.

**Comment by oPromessa** [comment]
## 1. coming back a bit... the `pytest -vv` did produce a crashlog...
### crash_log
* The crash_file was generated although no error message was displayed. The date referenced on the file is possibly on another time zone as it does not match (see below).
```sh
$ ls -l osxphotos_crash.log 
-rw-r--r--  1 MSP  staff  1689 24 Feb 15:53 osxphotos_crash.log
$ cat osxphotos_crash.log
osxphotos crash log
Created: 2022-02-24 07:53:34.408799
Python version: 3.9.10 (main, Jan 15 2022, 11:48:04) 
[Clang 13.0.0 (clang-1300.0.29.3)]
Platform: macOS-12.2.1-x86_64-i386-64bit
sys.argv: ['/Users/MSP/Documents/GitHub/osxphotos/venv/lib/python3.9/site-packages/pytest/__main__.py', '-vv']
osxphotos version: 0.46.5
Error: Invalid query-eval CRITERIA:  'PhotoInfo' object has no attribute 'originalfilename'
Traceback (most recent call last):
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/photosdb/photosdb.py", line 3353, in query
    photos = eval(query_string)
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
AttributeError: 'PhotoInfo' object has no attribute 'originalfilename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/cli.py", line 1947, in export
    photos = photosdb.query(query_options)
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/photosdb/photosdb.py", line 3355, in query
    raise ValueError(f"Invalid query_eval CRITERIA: {e}")
ValueError: Invalid query_eval CRITERIA: 'PhotoInfo' object has no attribute 'originalfilename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/crash_reporter.py", line 26, in wrapped
    return func(*args, **kwargs)
  File "/Users/MSP/Documents/GitHub/osxphotos/osxphotos/cli.py", line 1951, in export
    raise click.BadOptionUsage(
click.exceptions.BadOptionUsage: Invalid query-eval CRITERIA:  'PhotoInfo' object has no attribute 'originalfilename'
```

## 2. Test`selected`export. No crash from `osxphotos` but from Photos itself !!!
* the file was not exported.
* please note all my pics are referenced pics.
* and the file was actually missing -- when I migrated from iPhoto to Photos all the pics show up but when you try to export  them or edit them it always comes with an option to "find the original" and once I tell it where it is all works well.
* also I was running a parallel osxphotos `0.46.1`

```sh
$ mkdir tmp;  osxphotos export tmp --use-photos-export --selected --verbose
osxphotos version 0.46.5
Using last opened Photos library: /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary
Created export database /Users/MSP/Documents/GitHub/osxphotos/tmp/.osxphotos_export.db
Processing database /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary/database/photos.db
Processing database /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary/database/Photos.sqlite
Database locked, creating temporary copy.
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Exporting 1 photo to /Users/MSP/Documents/GitHub/osxphotos/tmp...
Exporting IMG_20210725_202544.JPG (IMG_20210725_202544.JPG) as IMG_20210725_202544.JPG (1/1)
Skipping missing original photo IMG_20210725_202544.JPG (26E2CE2C-ED7C-4D92-B79B-F3676ED25DEF)
Processed: 1 photo, exported: 0, missing: 1, error: 0
Elapsed time: 0:00:00
```
## 3. Test `selected`export. So I ran the test again, on its own, pic is now not missing, and not other competing osxphotos ;)
* no crash log file.
* Photos also did not crash.
```sh
$ mkdir tmp;  osxphotos export tmp --use-photos-export --selected --verbose
osxphotos version 0.46.5
Using last opened Photos library: /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary
Created export database /Users/MSP/Documents/GitHub/osxphotos/tmp/.osxphotos_export.db
Processing database /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary/database/photos.db
Processing database /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary/database/Photos.sqlite
Database locked, creating temporary copy.
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Exporting 1 photo to /Users/MSP/Documents/GitHub/osxphotos/tmp...
Exporting IMG_20210725_202544.JPG (IMG_20210725_202544.JPG) as IMG_20210725_202544.JPG (1/1)
Exported /Users/MSP/Documents/GitHub/osxphotos/tmp/IMG_20210725_202544.JPG
Processed: 1 photo, exported: 1, missing: 0, error: 0
Elapsed time: 0:00:00
```

**Comment by RhetTbull** [comment]
Great -- thanks!  So it looks like AppleScript and PhotoKit working fine on your Mac, that's good.

The one crash log produced by the test is from a test that's supposed to crash -- it tests an invalid query parameter.  I may need to add something to the test suite to clean up the crash logs produced.
