### ISSUE TITLE
Export photos without a defined Keyword (`--not-keyword`)

### ISSUE THREAD

**Issue by lewisthompson** [RhetTbull/osxphotos#637]
I have exported a large number of albums from Lightroom to Photos.  All of these photos have a Keyword `icpl_is_not_source_of_truth`.

I'd like to make a backup of Photos with `osxphotos` however I do not want a second copy of these re-exported images.

Being able to specify `osxphotos export --not-keyword icpl_is_not_source_of_truth ...` would help here.

**Comment by RhetTbull** [comment]
Until I get around to implementing this, you can achieve the same thing very easily using the following option:

`--query-eval "not photo.keywords"`

e.g. 

`osxphotos export /path/to/export --query-eval "not photo.keywords"`

`--query-eval` evaluates a python expression that is passed the `PhotoInfo` object (`photo`) and you can then inspect any of the [attributes](https://github.com/RhetTbull/osxphotos#photoinfo) of this object.

**Comment by lewisthompson** [comment]
Perfect!  I had just made a simple query-function that did this but:

```
--query-eval '"icpl_is_not_source_of_truth" not in photo.keywords'
```

is far nicer.  Thanks for the quick reply.

**Comment by RhetTbull** [comment]
I've added a `--no-keyword` option which finds photos with no keywords.  This will appear in the next release.  For your use case of finding photos that do not contain a specific keyword, `--query-eval` will continue to be the best way to do this.
