### ISSUE TITLE
Feature: allow specifying export directory format

### ISSUE THREAD

**Issue by AaronVanGeffen** [RhetTbull/osxphotos#65]
The `export` command already provides the option `--export-by-date` to export photos to directories based on the photo's date created, e.g. `DEST/2019/12/20/photoname.jpg`.

I would like to request this directory format be customisable to allow for formats like `DEST/2019/2019-12-20/photoname.jpg`. Ideally, the formatter would allow for locations (city, country?) as well, to allow for exporting straight into e.g. `DEST/2019/2019-12-20 Tokyo/photoname.jpg`.

**Comment by RhetTbull** [comment]
@AaronVanGeffen I like this idea and I've been thinking about how to allow some sort of templating system for exporting not only directory names but also the image name.   As for location, osxphotos does not currently provide access to the location name.  I see your script does get location data for older databases but Photos 5 stores location data in binary blobs and I haven't had time to reverse engineer this:

https://github.com/AaronVanGeffen/ExportPhotosLibrary/blob/0fa41d75ea115614792cc0526acf1646c9df69dd/export_photos.py#L149-L169

**Comment by RhetTbull** [comment]
Thinking about this... I already use [mako](https://docs.makotemplates.org/en/latest/usage.html#using-file-based-templates) templating system for writing the XMP sidecars.  It would be possible to use this to allow the user to specify filename or directory using something like:

`osxphotos export ~/Desktop/export --filename="${photo.original_filename}_${photo.date}" --directory="${photo.date.year}/${photo.date.date().isoformat()}"`

Demo code showing this would work (`p` is a single PhotoInfo object):
```python
>>> template = "${photo.original_filename}_${photo.date}"
>>> from mako.template import Template
>>> template = "${photo.original_filename}_${photo.date}"
>>> mytemplate = Template(template)
>>> mytemplate.render(photo=p)
'IMG_7922.JPG_2011-07-16 21:37:58-07:00'
>>> template = "${photo.date.year}/${photo.date.date().isoformat()}"
>>> mytemplate = Template(template)
>>> mytemplate.render(photo=p)
'2019/2019-07-19'
```

This implementation would be very powerful and give the user full control over the naming of exported images.  The downside of this implementation is that it also allows the user to enter arbitrary python code that would be executed by osxphotos.  Probably not a big deal as the user already has full access to the terminal but it still provides a vector to inject code, for example, if the user relied on a shell script to run osxphotos and didn't realize what they were feeding in.

This would also require the user to have a basic understanding of simple python syntax.  An alternative would be to roll my own templating system that does simple substitutions e.g. `--filename="{original_name}_{yyyy}_{mm}"` and substitute for values in the {} but that doesn't sound fun and would definitely be less flexible than a full templating system.

**Comment by RhetTbull** [comment]
I’m working on an implementation using a simple roll-my-own template system.  I experimented with both and decided that using a full template engine like Mako was overkill and would be overly complicated for users who weren’t programmers but just wanted to use the CLI.  Current thoughts on implementation are something like this:

--directory = “{yyyy}_{yy}-{mm}-{did}”
--filename = “{original_name}_{yyyy}”

Would produce something like:
Directory = 2020_20-03-13
Filename = photoname_2020.jpg

Will include other options like {month} for full month name in locale appropriate name, etc.

**Comment by AaronVanGeffen** [comment]
That sounds like it would certainly suffice for most purposes. I agree such formatting codes would be less intimidating, too. Having some description in addition to dates would be nice, but probably best left for a future extension.

**Comment by RhetTbull** [comment]
@AaronVanGeffen I’m planning on providing access to photo title, description, as well.  I’m also torching with the idea of allowing multi-valued attributes like keywords and albums to allow a photo to be exported to multiple locations or with multiple names (but use hard links to avoid duplicate files).  E.g. you could do something like this to export to albums:
--directory “{album}” and if photo was in albums “Vacation 2019” and “Ski Trip” it would result in:
Vacation 2019/photoname.jpg 
Ski Trip/photoname.jpg

I’ll play with this but will defer implementation to future version.  Let me know if you have thoughts on this or would find it useful.

**Comment by AaronVanGeffen** [comment]
Sounds like a good feature; I'm sure some would appreciate that. However, personally, I don't make a lot of use of albums. Instead, I'd really like to use the dominant location or 'moment name' for exported folders.

**Comment by RhetTbull** [comment]
@AaronVanGeffen initial version of this feature is implemented in 0.23.3.  command line export command has a new option --directory that allows you to specify the output directory name based on a templating system: e.g.
`osxphotos export ~/Pictures/export --directory "{created.year}/{place.name}"`

See `osxphotos help export` for full details on the templating system. I've not yet extended this to the output filename but plan to do so in the future.

**Comment by RhetTbull** [comment]
I've re-written the very basic MVP template engine that is in 0.23.3 to allow per-item substitution in case of None value. E.g. if item doesn't have reverse geolocation data, you could do this:

`--directory "{created.year}/{place.name,NoLocation}"`

Anything after the , gets used if the value is None.  This can be specified for each template replacement value.  

Still working on the code so it's not on github yet.  I am thinking about adding a PhotoInfo.render_template() method so the rendering can be done directly by the PhotoInfo object.

**Comment by AaronVanGeffen** [comment]
Interesting. In the case of `{place.name}`, what level of geographical detail would be used? Country, state, city, street? Would this be finetunable?

**Comment by RhetTbull** [comment]
Yes, currently, the following are available: 
| Substitution | Description |
|--------------|-------------|
|{name}|Filename of the photo|
|{original_name}|Photo's original filename when imported to Photos|
|{title}|Title of the photo|
|{descr}|Description of the photo|
|{created.date}|Photo's creation date in ISO format, e.g. '2020-03-22'|
|{created.year}|4-digit year of file creation time|
|{created.yy}|2-digit year of file creation time|
|{created.mm}|2-digit month of the file creation time (zero padded)|
|{created.month}|Month name in user's locale of the file creation time|
|{created.mon}|Month abbreviation in the user's locale of the file creation time|
|{created.doy}|3-digit day of year (e.g Julian day) of file creation time, starting from 1 (zero padded)|
|{modified.date}|Photo's modification date in ISO format, e.g. '2020-03-22'|
|{modified.year}|4-digit year of file modification time|
|{modified.yy}|2-digit year of file modification time|
|{modified.mm}|2-digit month of the file modification time (zero padded)|
|{modified.month}|Month name in user's locale of the file modification time|
|{modified.mon}|Month abbreviation in the user's locale of the file modification time|
|{modified.doy}|3-digit day of year (e.g Julian day) of file modification time, starting from 1 (zero padded)|
|{place.name}|Place name from the photo's reverse geolocation data|
|{place.names}|list of place names from the photo's reverse geolocation data, joined with '_', for example, '18th St NW_Washington_DC_United States'|
|{place.address}|Postal address from the photo's reverse geolocation data, e.g. '2007 18th St NW, Washington, DC 20009, United States'|
|{place.street}|Street part of the postal address, e.g. '2007 18th St NW'|
|{place.city}|City part of the postal address, e.g. 'Washington'|
|{place.state}|State part of the postal address, e.g. 'DC'|
|{place.postal_code}|Postal code part of the postal address, e.g. '20009'|
|{place.country}|Country name of the postal code, e.g. 'United States'|
|{place.country_code}|ISO country code of the postal address, e.g. 'US'|

**Comment by AaronVanGeffen** [comment]
That looks very detailed! Great work. I take this to mean `{place.name}` from the example is basically the string Photos.app uses, then?

**Comment by RhetTbull** [comment]
The only place information not directly available in current implementation is the list of names (which are sorted by area) because there are sometimes duplicates and often a different number of these depending on location.    Here's examples of the place.names from my photos:

> 
> ['Japanese American National Museum', 'Japanese American National Museum', 'Little Tokyo', 'Los Angeles', 'Downtown', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'California', 'United States']
> ['Adventure City', 'Adventure City', 'Stanton', 'Anaheim', 'West Anaheim', 'Anaheim', 'Orange', 'California', 'United States']
> ['White Point Nature Preserve & Education Center', 'White Point Nature Preserve & Education Center', 'San Pedro', 'San Pedro', 'San Pedro', 'Los Angeles', 'Los Angeles', 'California', 'United States']
> ['Santa Catalina Island', 'Santa Catalina Island', 'Santa Catalina Island', 'Los Angeles', 'California', 'United States']

If you use place.names in the template, it joins all together.  It would take some additional work to give you access to individual elements of the place list in the template.

**Comment by RhetTbull** [comment]
> That looks very detailed! Great work. I take this to mean `{place.name}` from the example is basically the string Photos.app uses, then?

No, it's the most detailed (local) name in the names list.  E.g. in the names list:
>['Japanese American National Museum', 'Japanese American National Museum', 'Little Tokyo', 'Los Angeles', 'Downtown', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'California', 'United States']

place.name would be 'Japanese American National Museum'.  In Photos, the map info shows '‎⁨Japanese American National Museum⁩, ⁨Los Angeles⁩, ⁨California⁩, ⁨United States⁩' which is a subset. I've not figured out what algorithm Photos uses to build the string it displays.

**Comment by AaronVanGeffen** [comment]
I see, that makes sense. Thank you for the clarification!

**Comment by RhetTbull** [comment]
Note to self: This might be helpful in decoding the various place names in Photos:

https://developer.apple.com/documentation/corelocation/clplacemark

**Comment by RhetTbull** [comment]
Making progress.  I think I've reverse-engineered how Photos constructs the reverse geolocation name it displays in the info dialog so I should be able to provide that (perhaps by changing place.name to return this).  I have also mapped each of the place types in place.names to their meaning so I'll be able to provide direct access to the following (which seem to correspond to the attributes of a Core Location CLPlacemark object).  The number is the corresponding `placeType` value in `sortedPlaceInfos`

- 1 country
- 14 postalCode
- 2 administrativeArea (The state or province associated with the placemark.)
- 3 subAdministrativeArea (Additional administrative area information for the placemark.)
- 4 locality (The city associated with the placemark.)
- 6 subLocality (Additional city-level information for the placemark.)
- 17 thoroughfare (The street address associated with the placemark.)
- 12 subThoroughfare (Additional street-level information for the placemark.)
- 11 region (The geographic region associated with the placemark) -- seems to be used for island name
- 9 inlandWater (The name of the inland water body associated with the placemark.) 
- 7 ocean (The name of the ocean associated with the placemark.)
- 8 areasOfInterest (The relevant areas of interest associated with the placemark.)

**Comment by RhetTbull** [comment]
For Photos <= 4, the type associated with place name is different and there is less information available.  In my database, I've figured out the following for `RKPlace.type`:

- 45: areasOfInterest (The relevant areas of interest associated with the placemark.)
- 44: body of water (includes both inlandWater and ocean)
- 43: subLocality (Additional city-level information for the placemark.
- 16: locality (The city associated with the placemark.)
- 4: subAdministrativeArea (Additional administrative area information for the placemark.)
- 2: administrativeArea (The state or province associated with the placemark.)
- 1: country

The name displayed in Photos is a maximum of three of these, in the following order:
- If areasOfInterest defined: 45, 16, 1
- Else if locality defined: 16, 2, 1
- Else if administrativeArea defined: 2, 1

**Comment by RhetTbull** [comment]
@AaronVanGeffen I've updated the template system in v0.24.1 to provide access to the detailed place name information. The following fields are all available to specify in the `--directory` option for `osxphotos export`.  Note, some of these changed from what I previously posted here.  You can also now specify a default value in case the substitution value is None.  For example, 
`osxphotos export ~/Desktop/export --directory "{created.year}/{place.name.city,NO_CITY}"`


| Substitution | Description |
|--------------|-------------|
|{name}|Filename of the photo|
|{original_name}|Photo's original filename when imported to Photos|
|{title}|Title of the photo|
|{descr}|Description of the photo|
|{created.date}|Photo's creation date in ISO format, e.g. '2020-03-22'|
|{created.year}|4-digit year of file creation time|
|{created.yy}|2-digit year of file creation time|
|{created.mm}|2-digit month of the file creation time (zero padded)|
|{created.month}|Month name in user's locale of the file creation time|
|{created.mon}|Month abbreviation in the user's locale of the file creation time|
|{created.doy}|3-digit day of year (e.g Julian day) of file creation time, starting from 1 (zero padded)|
|{modified.date}|Photo's modification date in ISO format, e.g. '2020-03-22'|
|{modified.year}|4-digit year of file modification time|
|{modified.yy}|2-digit year of file modification time|
|{modified.mm}|2-digit month of the file modification time (zero padded)|
|{modified.month}|Month name in user's locale of the file modification time|
|{modified.mon}|Month abbreviation in the user's locale of the file modification time|
|{modified.doy}|3-digit day of year (e.g Julian day) of file modification time, starting from 1 (zero padded)|
|{place.name}|Place name from the photo's reverse geolocation data, as displayed in Photos|
|{place.name.country}|Country name from the photo's reverse geolocation data|
|{place.name.state_province}|State or province name from the photo's reverse geolocation data|
|{place.name.city}|City or locality name from the photo's reverse geolocation data|
|{place.name.area_of_interest}|Area of interest name (e.g. landmark or public place) from the photo's reverse geolocation data|
|{place.address}|Postal address from the photo's reverse geolocation data, e.g. '2007 18th St NW, Washington, DC 20009, United States'|
|{place.address.street}|Street part of the postal address, e.g. '2007 18th St NW'|
|{place.address.city}|City part of the postal address, e.g. 'Washington'|
|{place.address.state_province}|State/province part of the postal address, e.g. 'DC'|
|{place.address.postal_code}|Postal code part of the postal address, e.g. '20009'|
|{place.address.country}|Country name of the postal address, e.g. 'United States'|
|{place.address.country_code}|ISO country code of the postal address, e.g. 'US'|

**Comment by RhetTbull** [comment]
I've update the template system to allow multi-valued template substitutions so the following now work as substitutions for `--directory`: `{album}, {keyword}, {person}`.  This means you can export by album using the following:
`osxphotos export /path/to/export/folder --directory "{album}"`  

**Note**: This could result in duplicate copies of photos being exported if a photo belongs to more than one album.

You can specify a default value for photos not in an album thusly:
`osxphotos export /path/to/export/folder --directory "{album,DEFAULT_ALBUM_NAME}"`
