### ISSUE TITLE
smart albums?

### ISSUE THREAD

**Issue by stogs** [RhetTbull/osxphotos#66]
Just curious if there is any way to extract images tied to a smart album.

**Comment by RhetTbull** [comment]
@stogs currently it’s not possible to access smart albums. Two possible work arounds:
1. In Photos, copy the photos from the smart album to a regular album. You could then export just those photos using  -- album
2. You can use the various export options to match the search criteria in the smart album to just export those

**Comment by stogs** [comment]
@RhetTbull  thanks for the ideas and the quick reply.  I will try those options.
