### ISSUE TITLE
Store .mov part of livephoto in subdir

### ISSUE THREAD

**Issue by wormiedk** [RhetTbull/osxphotos#662]
Is it possible to store the .mov part of a livephoto in a subdir e.g. livephotos?

**Comment by RhetTbull** [comment]
It is not currently possible to do this.  The .mov part of the live photo is always given the same path and name as the image part.  You can use `--skip-live` option to skip exporting the .mov part.

**Comment by RhetTbull** [comment]
@wormiedk It occurred to me that the `--post-function` option could be used to approximate this behavior. `--post-function` allows you to execute a python function immediately after each file is exported.  The function gets passed information about the exported file including the file paths.  Using this information, you can detect if a photo is a live photo, and if so, move the file to a sub-directory.

If you save the following in a file named `process_livephotos.py` you can run it as follows:

`osxphotos export /path/to/export  --post-function process_livephotos.py::process_livephotos`

One caveat: this won't work well with `--update` as the update code will detect the .mov files as missing and re-export them.

```python
""" Move the .mov component of a live photo to livephotos subdirectory in the same folder as the photo"""

import pathlib
from typing import Callable

from osxphotos import ExportResults, PhotoInfo


def process_livephotos(
    photo: PhotoInfo, results: ExportResults, verbose: Callable, **kwargs
):
    """Call this with osxphotos export /path/to/export --post-function process_livephotos.py::process_livephotos
        This will get called immediately after the photo has been exported

    Args:
        photo: PhotoInfo instance for the photo that's just been exported
        results: ExportResults instance with information about the files associated with the exported photo
        verbose: A function to print verbose output if --verbose is set; if --verbose is not set, acts as a no-op (nothing gets printed)
        **kwargs: reserved for future use; recommend you include **kwargs so your function still works if additional arguments are added in future versions

    Notes:
        Use verbose(str) instead of print if you want your function to conditionally output text depending on --verbose flag
        Any string printed with verbose that contains "warning" or "error" (case-insensitive) will be printed with the appropriate warning or error color
        Will not be called if --dry-run flag is enabled
        Will be called immediately after export and before any --post-command commands are executed
    """

    # only process live photos
    if not photo.live_photo:
        return

    for filename in results.exported:
        filename = pathlib.Path(filename)
        if filename.suffix != ".mov":
            continue
        # move the .mov file to the livephotos subdirectory
        livephotos_dir = filename.parent / "livephotos"
        if not livephotos_dir.is_dir():
            livephotos_dir.mkdir()
        new_filename = livephotos_dir / filename.name
        if new_filename.exists():
            # delete any existing file with the same name
            new_filename.unlink()
        filename.rename(new_filename)
        verbose(f"Moved {filename} to {livephotos_dir}")
```

**Comment by wormiedk** [comment]
Great! Thanks a lot. 
Is there a way to give live photos a different name e.g

Photo 1.jpg
Photo 2_live.jpg
Photo 2_live.mov

The objective is to be able to exclude Live Photos in Plex to avoid a lot of duplicate photos. With the above I could add a .plexignore with *live.mov to exclude the video part

**Comment by RhetTbull** [comment]
>  Is there a way to give live photos a different name e.g

Yes. You can use the `--filename` option with a template to do this. For example:

`osxphotos export /path/to/export --filename "{photo.live_photo?{original_name}_live,{original_name}}"`

This checks to see if the photo is a live photo:
`{photo.live_photo?`
and if it is, appends `_live` to the original filename:
`{original_name}_live`
otherwise uses the original filename:
`,{original_name}`

**Comment by wormiedk** [comment]
Can you see why this does not append _live to Live Photos?

`osxphotos export -V --folder "- nyere -" --update --cleanup --convert-to-jpeg --original-suffix "{edited?_original,}" --edited-suffix "" --exiftool --directory '{folder_album,Fotos ikke i album}' --album-keyword --filename '{created.date} {created.hour}.{created.min}.{created.sec}{photo.live_photo?_live,}' /Volumes/Photos/Export
`

**Comment by RhetTbull** [comment]
> Can you see why this does not append _live to Live Photos?

The --filename template you're using should append `_live` to live photos.  I've tested it and indeed it does on my system:

```
Exporting IMG_0728.JPG (51F2BEF7-431A-4D31-8AC1-3284A57826AE.jpeg) as 2019-12-29 19.01.15_live.JPG (23/29)
Exported /Users/rhet/Desktop/export/2019-12-29 19.01.15_live.JPG
Exported /Users/rhet/Desktop/export/2019-12-29 19.01.15_live.mov
```

Can you paste output from -V showing results for a live photo?  What does the photo actually get named?
