### ISSUE TITLE
unable to open database file (Monterey)

### ISSUE THREAD

**Issue by chrloew** [RhetTbull/osxphotos#663]
** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

- If you installed with pipx: `pipx upgrade osxphotos`
- If you installed with pip: `pip install --upgrade osxphotos`
- If you installed the pre-built binary, download and install the latest [release](https://github.com/RhetTbull/osxphotos/releases)

**- done, I'm running 0.47.6**

**Describe the bug**

**I tried to export my Photos, fist time on OS X Monterey, and ran into the error "unable to open database file". I gave the terminal application full HD access in security/privacy settings, but this did not help.**

**To Reproduce**
1. What' the full command line you used with osxphotos?
2. What was the error output?

**osxphotos export --export-by-date /Volumes/Archive/Fotos/iCloud-Backup --download-missing --update**

**Expected behavior**

Successful photo export (which already worked on Big Sur. This is the first time i tried on Monterey)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS]
 - osxphotos version (`osxphotos --version`)

**Additional context**
[osxphotos_crash.log](https://github.com/RhetTbull/osxphotos/files/8404238/osxphotos_crash.log)

**Comment by oPromessa** [comment]
Hello @chrloew . Hope you're doing well.

If I can try to help, from the error, I believe `osxphotos` is trying to open the export control database `.osxphotos_export.db` file; which is normally created on your export folder `/Volumes/Archive/Fotos/iCloud-Backup/.osxphotos_export.db`

Can you check a terminal if the file exists (it should as you mention you've ran osxphotos sometime in the past) and if the Terminal has ready/write permissions to it?

Regards, oPromessa

**Comment by chrloew** [comment]
Hello @oPromessa, thanks for your reply! The file exists, terminal return is:

`-rwx------  1 cloew  staff  15663104 20 Mär 11:19 /Volumes/Archive/Fotos/iCloud-Backup/.osxphotos_export.db`

**Comment by RhetTbull** [comment]
Hi @chrloew, I think @oPromessa is right that this is an error with the export database created by osxphotos to store state information related to the export.  It appears the export database was created but not properly initialized.  Try deleting the file: `rm   /Volumes/Archive/Fotos/iCloud-Backup/.osxphotos_export.db` and running the export command again.  

> Curiously, I just ran chmod 777 on it, but that did not change that output. Also tried sudo.

Did the file have rw permissions before you ran chmod?

What permissions does `/Volumes/Archive/Fotos/iCloud-Backup` have?

**Comment by chrloew** [comment]
Removing the .db file solved the error. Thank you, @RhetTbull and @oPromessa!

(The folder has drwx------ permissions.)

**Comment by RhetTbull** [comment]
Great -- glad the issue is resolved.  I'm perplexed about how the issue occurred in the first place though. I've tried to replicate this and haven't been able to.  If the export path is not readable, osxphotos will give you an error before it even runs. If the export path isn't writeable you'd get a different error. It appears that there was an error in initializing the export database between the time it was created and the time the database tables were initialized and this could occur if the volume is on a network and the network was flaky but it's very unlikely.

**Comment by chrloew** [comment]
It is a network-mounted volume (Synology NAS mounted via SMB). Network connection is fast and I have not witnessed any instabilities. I suspected that it might have something to do with that a different Mac did the initial backup (on Big Sur), I didn't mention that before.

> Did the file have rw permissions before you ran chmod?

It had rwx------ initially, before I ran chmod.

**Comment by cukal** [comment]
I ran osxphotos on my Photos library and exported to a local SSD. I rsync'ed the contents to a network drive (QNAP / AFPS) and tried to run an update. It returned this error:

```
osxphotos crash log
Created: 2024-04-08 08:06:32.905224
osxphotos version: 0.67.10
Platform: macOS-13.6.3-x86_64-i386-64bit
Python version: 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:39) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.argv: ['./osxphotos', 'export', '--verbose', '--export-by-date', '--skip-edited', '--update', '--only-new', '--library', '/Users/username/Pictures/Photos Library.photoslibrary', '/Volumes/Pictures/Cukal-Photos']
CRASH_DATA:
locals: {'dest': '/Volumes/Pictures/username-Photos', 'db': '/Users/username/Pictures/Photos Library.photoslibrary', 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': False, 'alt_db': None, 'alt_copy': False, 'append': False, 'fix_orientation': False, 'beta': False, 'burst': False, 'checkpoint': None, 'cleanup': False, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'crash_after': None, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'directory': None, 'download_missing': False, 'dry_run': False, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': False, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': True, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': None, 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_exportdb': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': None, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_exportdb': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_edited': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': True, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_command_error': None, 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': None, 'save_config': None, 'screenshot': False, 'selfie': False, 'shared': False, 'export_aae': False, 'sidecar': (), 'sidecar_drop_ext': False, 'sidecar_template': (), 'skip_bursts': False, 'skip_edited': True, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid': (), 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': False, 'update': True, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose_flag': 1, 'xattr_template': (), 'year': (), 'syndicated': False, 'not_syndicated': False, 'saved_to_library': False, 'not_saved_to_library': False, 'shared_moment': False, 'not_shared_moment': False, 'shared_library': False, 'not_shared_library': False, 'selected': False, 'ctx': <click.core.Context object at 0x10d76b470>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x10e440e30>}
osxphotos version: 0.67.10
Error: RetryError[<Future at 0x10e461340 state=finished raised OperationalError>]
Traceback (most recent call last):
  File "tenacity/__init__.py", line 382, in __call__
  File "osxphotos/export_db.py", line 556, in _get_database_version
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "osxphotos/crash_reporter.py", line 79, in wrapped
  File "osxphotos/cli/export.py", line 1115, in export
  File "osxphotos/cli/export.py", line 1792, in export_cli
  File "osxphotos/export_db.py", line 128, in __init__
  File "osxphotos/export_db.py", line 529, in _open_export_db
  File "tenacity/__init__.py", line 289, in wrapped_f
  File "tenacity/__init__.py", line 379, in __call__
  File "tenacity/__init__.py", line 326, in iter
tenacity.RetryError: RetryError[<Future at 0x10e461340 state=finished raised OperationalError>]
```

Not sure what is the actual root cause is but it seems it has to do with the .osxphotos_export.db being on a network drive?
A quick python SQLite test shows it can't open the database. Surprisingly running a new export, with the target folder on the same network drive, does create the .osxphotos_export.db and the export happily starts. 
But it's a 500GB Photos archive, it's gonna take _time_... 
My cunning plan was to run the first export locally on an SSD drive & copy that to a network drive and run subsequent updates against the network folder.

Why does a newly created SQLite db on a network drive work and why does a copied SQLite db on the same network drive not work? Baffled!

**Comment by cukal** [comment]
What seems to have done the trick:

1) run a new export with the target folder on the network drive
2) break off the export once it starts exporting images
3) in Python, copy everything from the initial locally created `.osxphotos_export.db` to the new-on-the-network created `.osxphotos_export.db` (drop table, create table, insert * from)
4) copy the new `.osxphotos_export.db` to the network location where the previously exported archive is
5) run osxphotos with update

It does report:
_WARNING: found other export database files in this destination directory branch. This likely means you are
attempting to export files into a directory that is either the parent or a child directory of a previous export.
Proceeding may cause your exported files to be overwritten._

But it detects what's already exported and it exports new images, so I don't have to recreate the 500GB archive again.
It seems there is something different with the initial creation of the database file on a local volume vs a network volume, or perhaps filesystem, that breaks when moving the local file to a network location.

**Comment by RhetTbull** [comment]
It sounds like the export database was corrupted when you copied it. There's nothing OSXPhotos is doing that should cause this.  The export database is purposefully kept with the exported files so the whole directory can be moved.  OSXPhotos maintains the path of the exported files relative to the parent directory of the export.  For example, if you export to `/Volumes/NetworkDrive/Photos` then the path is maintained relative to `Photos` so if you move the directory somewhere else, everything still works.

> WARNING: found other export database files in this destination directory branch. 

This means you have another `.osxhotos_export.db` lurking in either the parent or a child directory of your export destination.

**Comment by cukal** [comment]
It's not a OSXPhotos issue, I think it has to do where the initial SQLite db is created, local filesystem or on network. 
The md5sum of the local `.osxphotos_export.db` versus the one copied to the network is the same.
If SQLite initially creates on the network, it works. When initially created on a local fs and copied to the network, SQLite fails to open/lock the db. My solution was to create on the network and migrate all the tables from the local db.

There is a single `.osxphotos_export.db` file present in `/Volumes/Pictures/Cukal-Photos/`. I verified this with find. 
It warns about a `.osxphotos_export.db` one directory level higher. That's the one I copied from local to the network but just kept around in case of trouble. The one in the directory is the one I created on the network, and copied over the contents, through python, from the local one. 
Regarding the warning, I would have presumed OSXPhotos would confine its search to the given path and not one level higher. 

```
/Volumes/Pictures/Cukal-Photos$ find . -name .osxphotos_export.db
./.osxphotos_export.db

/Volumes/Pictures/Cukal-Photos$ ../OSXPhotos/osxphotos export  \
  --verbose \
  --export-by-date \
  --skip-edited \
  --update \
  --only-new \
  --library ~/Pictures/Photos\ Library.photoslibrary  \
  /Volumes/Pictures/Cukal-Photos/
  
osxphotos version: 0.67.10
Python version: 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:39) [Clang 13.0.0 (clang-1300.0.29.30)]
Platform: macOS-13.6.3-x86_64-i386-64bit, 13.6.3
Verbose level: 1
WARNING: found other export database files in this destination directory branch. This likely means you are
attempting to export files into a directory that is either the parent or a child directory of a previous export.
Proceeding may cause your exported files to be overwritten.
You are exporting to /Volumes/Pictures/Cukal-Photos, found .osxphotos_export.db files in:
/Volumes/Pictures/.osxphotos_export.db
```

The file it found is at `/Volumes/Pictures/` while the given export location in the args is `/Volumes/Pictures/Cukal-Photos/`
Removing the file at `/Volumes/Pictures/` cleared the warning.

**Comment by RhetTbull** [comment]
> Regarding the warning, I would have presumed OSXPhotos would confine its search to the given path and not one level higher.

The warning is there because I messed up my own export by using the wrong path. Because the export folder structure could be multiple levels deep, depending your `--directory` template, I can't think of a "normal" use case where you'd export into a subdirectory of an existing export and hence the path search up and down the tree. 

Regarding the SQLite error I can't think of any reason for this to fail in this manner. I'll do some experimenting with rsync to a network volume to see if I can replicate this.
