### ISSUE TITLE
Check for osxphotos upgrade from launchd

### ISSUE THREAD

**Issue by petebocken** [RhetTbull/osxphotos#671]
I am wanting to upgrade osxphotos automatically with a launchd job (with Lingon).

I've added the following command to my bash script:
`/opt/homebrew/bin/pipx upgrade osxphotos`

When I run this script in Terminal, it works and upgrades osxphotos just fine. However, when I run with launchd job, it does not.
I've had issues with launchd jobs and file paths, that is why I put the full path to pipx. I also tried adding the full path to osxphotos, but when run in the Terminal, that gives:
```
peter@Peters-MacBook-Pro osxphotos % /opt/homebrew/bin/pipx upgrade /Users/peter/.local/pipx/venvs/osxphotos
Package is not installed. Expected to find /users/peter/-local/pipx/venvs/osxphotos, but it does not exist.
```

**Comment by RhetTbull** [comment]
> Expected to find /users/peter/-local/pipx/venvs/osxphotos, but it does not exist.

This happens even if not running from launchd and you specify the whole path. Not sure why but I'm guessing pipx thinks the source for the package you're trying to install is located where it normally stores it's virtual environments so it uses `-local` instead of `.local`.  

> However, when I run with launchd job, it does not.

My guess is it's running as the wrong user.  Have you tried adding the `UserName` key to your launchd plist?

```
<key>UserName</key>
<string>peter</string>
```

**Comment by petebocken** [comment]
> My guess is it's running as the wrong user. Have you tried adding the `UserName` key to your launchd plist?
> 
> ```
> <key>UserName</key>
> <string>peter</string>
> ```

I'm using the Lingon app (https://www.peterborgapps.com/lingon/) and it automatically generates the plist file for me. I checked it and it does not contain the UserName key, nor does any other plist file Lingon has created or any other apps in ~/Library/LaunchAgents.

I went ahead and tried adding it, but it made no difference.

FYI - I can run osxphotos itself just fine through my bash script and launchd. It's just upgrading osxphotos through pipx that doesn't work.

**Comment by RhetTbull** [comment]
Have you tried using sudo?

`sudo -u peter pipx upgrade osxphotos`

**Comment by RhetTbull** [comment]
> Since I run osxphotos automatically daily, I could see adding a flag to automatically check for updates on every run. 

I'm working on this (as soon as I finish updating docs for the new `osxphotos docs` command).  My intent at the moment is to have this be the default behavior (always check for updates) but to have a flag to disable the check.

**Comment by petebocken** [comment]
> My intent at the moment is to have this be the default behavior (always check for updates) but to have a flag to disable the check.

So the flag would automatically upgrade or just notify? Since I run this automatically (in the background), notify won't help me much since I won't ever see it.

**Comment by RhetTbull** [comment]
> So the flag would automatically upgrade or just notify? 

Just notify.  I don't think it's possible to automate the update with pipx.

**Comment by oPromessa** [comment]
@petebocken i run osxphotos from inside a script launched via crontab instead of launchd. I do have to wake up the Mac a minute before via power settings to ensure crontab will run it. 

I bring this up because I believe you'd have more control over the script launched by crontab to ensure all the environment variables are set so that maybe you could run pipx upgrade.

**Comment by RhetTbull** [comment]
@petebocken I have implemented a new `osxphotos version` command that checks for new version and I think I've figured out a way to get it to auto-update osxphotos with pipx if there's a new version.  I need to finish testing then will push a new version this weekend.

**Comment by RhetTbull** [comment]
Got it working! You can now use the new `osxphotos version` command in [v0.47.12](https://github.com/RhetTbull/osxphotos/releases/tag/v0.47.12) to check for updates.  You can use the following command to force an update if there is a new update:

`osxphotos version --run 'pipx upgrade osxphotos'`

The --run option will run an optional command only if there is a new version of osxphotos available.

**Comment by petebocken** [comment]
> @petebocken i run osxphotos from inside a script launched via crontab instead of launchd. I do have to wake up the Mac a minute before via power settings to ensure crontab will run it.

@oPromessa Thanks! I tried running my script (with the pipx upgrade command) via crontab and it didn't seem to work before, but now that I tested it again today, it appears to be working. I'll wait for the next osxphotos version to confirm to automatically updates.

**Comment by petebocken** [comment]
> Got it working! You can now use the new `osxphotos version` command in [v0.47.12]

@RhetTbull Awesome! From my initial testing, it looks to work just fine from launchd! I'll wait for the next version and confirm it auto-updates with my script.

My script command is pretty crazy with the full paths, but it works.
`/Users/peter/.local/pipx/venvs/osxphotos/bin/osxphotos version --run '/opt/homebrew/bin/pipx upgrade /Users/peter/.local/pipx/venvs/osxphotos/bin/osxphotos'`

**Comment by RhetTbull** [comment]
I don't think the pipx command does what you think it does. I think you'll get an error of form:

`Package is not installed. Expected to find /users/Peter/-local/pipx/venvs/osxphotos/bin/osxphotos, but it does not exist.`

pipx needs to be told the package name not the location of the installed package.  I think what this might work but you'll need to test:

`sudo -u Peter /opt/homebrew/bin/pipx upgrade osxphotos`

Keep in mind that the `--run` doesn't run unless there's a new version available so the fact that the command is running from launchd now only means the version check is running.  Once a new version is published, you'll know if the `--run` command actually worked.

You can test this without waiting for a new version as I had to create a test version of osxphotos to test the capability. There's a version 0.47.11 that's identical to 0.47.12 for testing so you could do this:

`pipx uninstall osxphotos`
`pipx install osxphotos==0.47.11`
`osxphotos version --run '/opt/homebrew/bin/pipx upgrade /Users/peter/.local/pipx/venvs/osxphotos/bin/osxphotos`

**Comment by petebocken** [comment]
> pipx needs to be told the package name not the location of the installed package. I think what this might work but you'll need to test:
> 
> `sudo -u Peter /opt/homebrew/bin/pipx upgrade osxphotos`

That makes sense. I downgraded to .11 and my script (executed by launchd) updated it to .12. Thanks!

**Comment by petebocken** [comment]
Installed on a new Mac recently and trying to upgrade to 0.51.7 and I get this madness. This issue looks familiar and I thought I had this happen before, but I cannot remember how I got around it. I also tried uninstalled osxphotos and reinstalling.

```
peter@PETEFLIX osxphotos % osxphotos --version
osxphotos, version 0.51.6
peter@PETEFLIX osxphotos % osxphotos version
A new version of osxphotos is available: 0.51.7 (you have 0.51.6)
Run `pipx upgrade osxphotos` to upgrade (assuming you installed osxphotos with pipx).
See https://github.com/RhetTbull/osxphotos for more information.
peter@PETEFLIX osxphotos % pipx upgrade osxphotos
osxphotos is already at latest version 0.51.7 (location:
/Users/peter/.local/pipx/venvs/osxphotos)
peter@PETEFLIX osxphotos % osxphotos --version
osxphotos, version 0.51.6
peter@PETEFLIX osxphotos % osxphotos version --run 'pipx upgrade osxphotos'
A new version of osxphotos is available: 0.51.7 (you have 0.51.6)
Run `pipx upgrade osxphotos` to upgrade (assuming you installed osxphotos with pipx).
See https://github.com/RhetTbull/osxphotos for more information.
Running command: 'pipx upgrade osxphotos'
osxphotos is already at latest version 0.51.7 (location:
/Users/peter/.local/pipx/venvs/osxphotos)
peter@PETEFLIX osxphotos % osxphotos --version
osxphotos, version 0.51.6
peter@PETEFLIX osxphotos % osxphotos version
A new version of osxphotos is available: 0.51.7 (you have 0.51.6)
Run `pipx upgrade osxphotos` to upgrade (assuming you installed osxphotos with pipx).
See https://github.com/RhetTbull/osxphotos for more information.
```

**Comment by petebocken** [comment]
ah, right you are.

```
peter@PETEFLIX bin % which osxphotos
/opt/homebrew/bin/osxphotos
peter@PETEFLIX bin % cd ~/.local/bin/
peter@PETEFLIX bin % ls
osxphotos
```

How would I go about changing the path for `osxphotos` to `~/.local/bin/osxphotos` so `osxphotos version` functions correctly?

**Comment by RhetTbull** [comment]
I would just delete the homebrew version (or use `brew uninstall osxphotos` assuming it was installed with homebrew). Having two versions of something laying around is bound to cause issues as you discovered. Alternatively, you could ensure the pipx path is first in your path.  Edit your `~/.zshrc` and make sure that that `export PATH="/Users/yourusername/.local/bin:$PATH"` is the last path export statement in the file.

**Comment by petebocken** [comment]
I just had to delete the directory. Not even sure how that got there cause I thought osxphotos wasn't available in homebrew anyway??  Now `which osxphotos` shows the correct path and the upgrade command works. Thanks as always!

**Comment by petebocken** [comment]
Hi @RhetTbull , me again. I feel like my update script seems to break after so long. The script runs fine when run directly, but won't run when automated with cron. Maybe you can point me in the right direction again. 😄 

Here's my script:
```
#!/bin/bash

pipx upgrade osxphotos
```

I have the script piping to a log file (i've left this out above) and I can see that the script is indeed running, however osxphotos does not get updated.

I'm pretty confident that it has to do with cron just not knowing where osxphotos is and possibly even pipx??

**Comment by RhetTbull** [comment]
Hi @petebocken I don't use osxphotos this way so don't have many ideas. I would include the full path to pipx (`/opt/homebrew/bin/pipx`) in the script.  If you run the upgrade command in the Terminal directly does it work? I've noticed sometimes that the python version gets updated by homebrew which causes everything installed with pipx to break. The solution is `pipx reinstall-all`.

**Comment by petebocken** [comment]
@RhetTbull Ya, I needed the full path. Thanks!

`/opt/homebrew/bin/pipx upgrade osxphotos`
