### ISSUE TITLE
v0.47.12 "--skip-original-if-edited" No such option

### ISSUE THREAD

**Issue by petebocken** [RhetTbull/osxphotos#673]
**Describe the bug**
Updated to v0.47.12 and "--skip-original-if-edited" option isn't working.

```
% osxphotos --skip-original-if-edited
Usage: osxphotos [OPTIONS] COMMAND [ARGS]...
Try 'osxphotos -h' for help.

Error: No such option: --skip-original-if-edited
```

**To Reproduce**
1. Run command with option
`osxphotos --skip-original-if-edited`

**Expected behavior**
Command should run and skip originals if they are edited.

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - pipx
 - osxphotos version 0.47.12

**Comment by petebocken** [comment]
Disregard, I think I have something wrong with the new `osxphotos version --run 'pipx upgrade osxphotos'`

**Comment by RhetTbull** [comment]
The `--skip-original-if-edited` option only works with the export command.  That is:

`osxphotos export /path/to/export --skip-original-if-edited`

**Comment by petebocken** [comment]
> The `--skip-original-if-edited` option only works with the export command.

@RhetTbull Ya, I'm a dork and realized it is a separate command. ;-) thanks.
