### ISSUE TITLE
I/O error message after exporting to a NAS using --ramdb

### ISSUE THREAD

**Issue by sparselogic** [RhetTbull/osxphotos#674]
** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

Encountered and reproduced on 0.47.6

**Describe the bug**
After completing an osxphotos export using --ramdb, receive a disk I/O error message while trying to write export database changes back to .osxphotos_export.db. 

NOTE: this message only happens while using --ramdb. Without this flag, no I/O errors are reported.
NOTE 2: The destination .osxphotos_export.db timestamp is from that minute, though, so it seems like the write was successful.

**To Reproduce**
1. What' the full command line you used with osxphotos?
osxphotos export /Volumes/NAS/Photos_Backup --update --export-by-date --download-missing --retry 5 --exiftool --exiftool-merge-keywords --exiftool-merge-persons --keyword-template "{folder_album(>)}" --finder-tag-keywords --touch-file --verbose --use-photokit --ramdb

2. What was the error output?
Processed: 57447 photos, exported: 801, updated: 2, skipped: 71831, updated EXIF data: 803, missing: 300, error: 0, touched date: 803
Elapsed time: 1:41:54
Writing export database changes back to /Volumes/NAS/Photos_Backup/.osxphotos_export.db
Something went wrong and osxphotos encountered an error:
disk I/O error

─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/crash_rep │
│ orter.py:36 in wrapped                                                                           │
│                                                                                                  │
│   33 │   │   @functools.wraps(func)                                                              │
│   34 │   │   def wrapped(*args, **kwargs):                                                       │
│   35 │   │   │   try:                                                                            │
│ ❱ 36 │   │   │   │   return func(*args, **kwargs)                                                │
│   37 │   │   │   except Exception as e:                                                          │
│   38 │   │   │   │   print(message, file=sys.stderr)                                             │
│   39 │   │   │   │   print(f"[red]{e}[/red]", file=sys.stderr)                                   │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/cli/expor │
│ t.py:1632 in export                                                                              │
│                                                                                                  │
│   1629 │   # close export_db and write changes if needed                                         │
│   1630 │   if ramdb and not dry_run:                                                             │
│   1631 │   │   verbose_(f"Writing export database changes back to [filepath]{export_db.path}")   │
│ ❱ 1632 │   │   export_db.write_to_disk()                                                         │
│   1633 │   export_db.close()                                                                     │
│   1634                                                                                           │
│   1635                                                                                           │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/export_db │
│ .py:617 in write_to_disk                                                                         │
│                                                                                                  │
│   614 │   │   │   shm.unlink()                                                                   │
│   615 │   │                                                                                      │
│   616 │   │   conn_on_disk = sqlite3.connect(str(dbfile))                                        │
│ ❱ 617 │   │   conn_on_disk.cursor().executescript(dbdump.read())                                 │
│   618 │   │   conn_on_disk.commit()                                                              │
│   619 │   │   conn_on_disk.close()                                                               │
│   620                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/eugenefriesen/.local/bin/osxphotos:8 in <module>                                          │
│                                                                                                  │
│   5 from osxphotos.__main__ import cli_main                                                      │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli_main())                                                                     │
│   9                                                                                              │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py:1128  │
│ in __call__                                                                                      │
│                                                                                                  │
│   1125 │                                                                                         │
│   1126 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1127 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1128 │   │   return self.main(*args, **kwargs)                                                 │
│   1129                                                                                           │
│   1130                                                                                           │
│   1131 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py:1053  │
│ in main                                                                                          │
│                                                                                                  │
│   1050 │   │   try:                                                                              │
│   1051 │   │   │   try:                                                                          │
│   1052 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1053 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1054 │   │   │   │   │   if not standalone_mode:                                               │
│   1055 │   │   │   │   │   │   return rv                                                         │
│   1056 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py:1659  │
│ in invoke                                                                                        │
│                                                                                                  │
│   1656 │   │   │   │   super().invoke(ctx)                                                       │
│   1657 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1658 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1659 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1660 │   │                                                                                     │
│   1661 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1662 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py:1395  │
│ in invoke                                                                                        │
│                                                                                                  │
│   1392 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1393 │   │                                                                                     │
│   1394 │   │   if self.callback is not None:                                                     │
│ ❱ 1395 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1396 │                                                                                         │
│   1397 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1398 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/core.py:754   │
│ in invoke                                                                                        │
│                                                                                                  │
│    751 │   │                                                                                     │
│    752 │   │   with augment_usage_errors(__self):                                                │
│    753 │   │   │   with ctx:                                                                     │
│ ❱  754 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    755 │                                                                                         │
│    756 │   def forward(                                                                          │
│    757 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/decorators.py │
│ :38 in new_func                                                                                  │
│                                                                                                  │
│    35 │   """                                                                                    │
│    36 │                                                                                          │
│    37 │   def new_func(*args, **kwargs):  # type: ignore                                         │
│ ❱  38 │   │   return f(get_current_context().obj, *args, **kwargs)                               │
│    39 │                                                                                          │
│    40 │   return update_wrapper(t.cast(F, new_func), f)                                          │
│    41                                                                                            │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/click/decorators.py │
│ :26 in new_func                                                                                  │
│                                                                                                  │
│    23 │   """                                                                                    │
│    24 │                                                                                          │
│    25 │   def new_func(*args, **kwargs):  # type: ignore                                         │
│ ❱  26 │   │   return f(get_current_context(), *args, **kwargs)                                   │
│    27 │                                                                                          │
│    28 │   return update_wrapper(t.cast(F, new_func), f)                                          │
│    29                                                                                            │
│                                                                                                  │
│ /Users/eugenefriesen/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/crash_rep │
│ orter.py:40 in wrapped                                                                           │
│                                                                                                  │
│   37 │   │   │   except Exception as e:                                                          │
│   38 │   │   │   │   print(message, file=sys.stderr)                                             │
│   39 │   │   │   │   print(f"[red]{e}[/red]", file=sys.stderr)                                   │
│ ❱ 40 │   │   │   │   with open(filename, "w") as f:                                              │
│   41 │   │   │   │   │   f.write(f"{title}\n")                                                   │
│   42 │   │   │   │   │   f.write(f"Created: {datetime.datetime.now()}\n")                        │
│   43 │   │   │   │   │   f.write(f"osxphotos version: {__version__}\n")                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 1] Operation not permitted: '/Volumes/osxphotos_crash.log'

**Expected behavior**
Export db write should complete without errors.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Montery 12.3.1
 - osxphotos version 0.47.6

**Additional context**
--ramdb *massively* speeds up the process of backing up to a NAS! We're talking a change from days to hours for a full osxphotos --update run, even when very little is actually being written.

**Comment by oPromessa** [comment]
Hello @sparselogic , I'm also a user of `osxphotos` running similar conditions copying files to a Synology NAS Server.

Besides using `--ramdb` I've opted to also use the `--exportdb` option to keep the control database of osxphotos locally on the a local folder of the Mac. Eg: `--exportdb /Users/eugenefriesen/Logs/.osxphotos_export.db`

Although I'm sure @RhetTbull will want to squash that `bug` of the I/O Error this alternative method can simply avoid the problem.

Hope it helps.

**Comment by RhetTbull** [comment]
I'll see about adding a retry to the `write_to_disk` method that's causing this error.  The error is indicative of a problem with either the NAS itself or the network connection.  Something is flaky as the error isn't caused by a bug in osxphotos but by the fact that osxphotos tries to write a file to the NAS which then fails. 

> --ramdb massively speeds up the process of backing up to a NAS! We're talking a change from days to hours

The purpose of `--ramdb` is precisely this to speed up export but if the difference is that massive, this is also indicative that the NAS isn't healthy or the network connection is flaky.  Independent of the fix in osxphotos, it might be worth looking into your NAS setup.

As @oPromessa noted, you can avoid this for the time being by storing the osxphotos export database on your local Mac that's running the export with the `--exportdb` option.

**Comment by RhetTbull** [comment]
I think this is fixed in [v0.47.13](https://pypi.org/project/osxphotos/0.47.13/).  I've added an auto-retry to the code that writes the ramdb back out to disk.  I can't properly test this easily so give it a try and let me know if you still have problems.

**Comment by sparselogic** [comment]
@oPromessa - hey, fellow Synology user. :) Thanks for the `--exportdb` suggestion - that did allow the process to complete successfully.

@RhetTbull - I'll give 0.47.13 a try. Point taken re: possible issues with NAS and network. For a little bit of perspective, my Photos library has ~57k photos, so any latency introduced by round trips to the network will compound.

**Comment by sparselogic** [comment]
Following up: in 0.47.13, the ramdb successfully writes back to disk.
Thanks again!
