### ISSUE TITLE
How can i get labels associated with photos in a particular album

### ISSUE THREAD

**Issue by hanchangdong** [RhetTbull/osxphotos#717]
Hi, can i get my photo labels in album, forexample:
1.heic, cat
2.png, dog
thx

**Comment by RhetTbull** [comment]
I'm sorry I don't quite understand the question.  I think you may be asking if you can get the labels associated with photos in a particular album.  If so, here are some possible solutions.

1. Use [jq](https://github.com/stedolan/jq) which can be installed via `brew install jq` to parse the json output of `osxphotos query`:

`osxphotos query --album "Album Name" --json | jq '.[] | .original_filename, .labels'`

gives output similar to this:

```
"41578245374_61d718bd40_o.jpg"
[
  "Boat",
  "Dock",
  "Harbor",
  "Machine",
  "Mast",
  "Outdoor",
  "Pole",
  "Sky",
  "Vehicle",
  "Water",
  "Watercraft"
]
"Pumkins1.jpg"
[]
"[2020-08-29] AAF035.jpg"
[
  "Blue Sky",
  "Outdoor",
  "Palm Tree",
  "Plant",
  "Sky",
  "Tree"
]
```

2. Alternatively, to get the exact format you asked for, a simple python script that can be run with `osxphotos run` will give you the output.  Save the script below into a file called `album_names.py` then run it with:

`osxphotos run album_labels.py "Test Album"`

```
Pumkins2.jpg,
Pumkins1.jpg,
41578245374_61d718bd40_o.jpg, Boat,Dock,Harbor,Machine,Mast,Outdoor,Pole,Sky,Vehicle,Water,Watercraft
[2020-08-29] AAF035.jpg, Blue Sky,Outdoor,Palm Tree,Plant,Sky,Tree
```

```python
"""Print name of all photos in a Photos album and their associated labels"""

import click

import osxphotos


@click.command()
@click.argument("album_name")
def album_labels(album_name):
    """Print name of all photos in a Photos album and their associated labels"""
    photosdb = osxphotos.PhotosDB()
    album = [album for album in photosdb.album_info if album.title == album_name]
    if not album:
        raise click.ClickException(f"Album '{album_name}' not found")

    # could be more than one album with same name so process them all
    for a in album:
        for photo in a.photos:
            print(f"{photo.original_filename}, {','.join(photo.labels)}")


if __name__ == "__main__":
    album_labels()
```

Finally, I assume by `labels` you mean what osxphotos refers to as labels which are the automated categories/labels assigned by Photos as it does image classification on each photo.  If you mean user assigned keywords, you'd have to replace `labels` with `keywords` in the above examples.

**Comment by hanchangdong** [comment]
> 



> I'm sorry I don't quite understand the question. I think you may be asking if you can get the labels associated with photos in a particular album. If so, here are some possible solutions.
> 
> 1. Use [jq](https://github.com/stedolan/jq) which can be installed via `brew install jq` to parse the json output of `osxphotos query`:
> 
> `osxphotos query --album "Album Name" --json | jq '.[] | .original_filename, .labels'`
> 
> gives output similar to this:
> 
> ```
> "41578245374_61d718bd40_o.jpg"
> [
>   "Boat",
>   "Dock",
>   "Harbor",
>   "Machine",
>   "Mast",
>   "Outdoor",
>   "Pole",
>   "Sky",
>   "Vehicle",
>   "Water",
>   "Watercraft"
> ]
> "Pumkins1.jpg"
> []
> "[2020-08-29] AAF035.jpg"
> [
>   "Blue Sky",
>   "Outdoor",
>   "Palm Tree",
>   "Plant",
>   "Sky",
>   "Tree"
> ]
> ```
> 
> 2. Alternatively, to get the exact format you asked for, a simple python script that can be run with `osxphotos run` will give you the output.  Save the script below into a file called `album_names.py` then run it with:
> 
> `osxphotos run album_labels.py "Test Album"`
> 
> ```
> Pumkins2.jpg,
> Pumkins1.jpg,
> 41578245374_61d718bd40_o.jpg, Boat,Dock,Harbor,Machine,Mast,Outdoor,Pole,Sky,Vehicle,Water,Watercraft
> [2020-08-29] AAF035.jpg, Blue Sky,Outdoor,Palm Tree,Plant,Sky,Tree
> ```
> 
> ```python
> """Print name of all photos in a Photos album and their associated labels"""
> 
> import click
> 
> import osxphotos
> 
> 
> @click.command()
> @click.argument("album_name")
> def album_labels(album_name):
>     """Print name of all photos in a Photos album and their associated labels"""
>     photosdb = osxphotos.PhotosDB()
>     album = [album for album in photosdb.album_info if album.title == album_name]
>     if not album:
>         raise click.ClickException(f"Album '{album_name}' not found")
> 
>     # could be more than one album with same name so process them all
>     for a in album:
>         for photo in a.photos:
>             print(f"{photo.original_filename}, {','.join(photo.labels)}")
> 
> 
> if __name__ == "__main__":
>     album_labels()
> ```
> 
> Finally, I assume by `labels` you mean what osxphotos refers to as labels which are the automated categories/labels assigned by Photos as it does image classification on each photo. If you mean user assigned keywords, you'd have to replace `labels` with `keywords` in the above examples.



> I'm sorry I don't quite understand the question. I think you may be asking if you can get the labels associated with photos in a particular album. If so, here are some possible solutions.
> 
> 1. Use [jq](https://github.com/stedolan/jq) which can be installed via `brew install jq` to parse the json output of `osxphotos query`:
> 
> `osxphotos query --album "Album Name" --json | jq '.[] | .original_filename, .labels'`
> 
> gives output similar to this:
> 
> ```
> "41578245374_61d718bd40_o.jpg"
> [
>   "Boat",
>   "Dock",
>   "Harbor",
>   "Machine",
>   "Mast",
>   "Outdoor",
>   "Pole",
>   "Sky",
>   "Vehicle",
>   "Water",
>   "Watercraft"
> ]
> "Pumkins1.jpg"
> []
> "[2020-08-29] AAF035.jpg"
> [
>   "Blue Sky",
>   "Outdoor",
>   "Palm Tree",
>   "Plant",
>   "Sky",
>   "Tree"
> ]
> ```
> 
> 2. Alternatively, to get the exact format you asked for, a simple python script that can be run with `osxphotos run` will give you the output.  Save the script below into a file called `album_names.py` then run it with:
> 
> `osxphotos run album_labels.py "Test Album"`
> 
> ```
> Pumkins2.jpg,
> Pumkins1.jpg,
> 41578245374_61d718bd40_o.jpg, Boat,Dock,Harbor,Machine,Mast,Outdoor,Pole,Sky,Vehicle,Water,Watercraft
> [2020-08-29] AAF035.jpg, Blue Sky,Outdoor,Palm Tree,Plant,Sky,Tree
> ```
> 
> ```python
> """Print name of all photos in a Photos album and their associated labels"""
> 
> import click
> 
> import osxphotos
> 
> 
> @click.command()
> @click.argument("album_name")
> def album_labels(album_name):
>     """Print name of all photos in a Photos album and their associated labels"""
>     photosdb = osxphotos.PhotosDB()
>     album = [album for album in photosdb.album_info if album.title == album_name]
>     if not album:
>         raise click.ClickException(f"Album '{album_name}' not found")
> 
>     # could be more than one album with same name so process them all
>     for a in album:
>         for photo in a.photos:
>             print(f"{photo.original_filename}, {','.join(photo.labels)}")
> 
> 
> if __name__ == "__main__":
>     album_labels()
> ```
> 
> Finally, I assume by `labels` you mean what osxphotos refers to as labels which are the automated categories/labels assigned by Photos as it does image classification on each photo. If you mean user assigned keywords, you'd have to replace `labels` with `keywords` in the above examples.

Great work, it solved my question exactly! thx very much!

I can get the labels associated with photos in my mac albums now. But, is that a way that  i can get all labels that photo APP support, maybe it stores in someone sqlite table. thx

**Comment by RhetTbull** [comment]
>  is that a way that i can get all labels that photo APP support. thx

I do not know of a way to get all the labels supported by Photos.app but you can easily find all the labels associated with photos in your Photos Library by doing this:

Run `osxphotos repl`

Then at the prompt (`>>>`) type `photosdb.labels` and it will print out a list of labels, for example:

```pycon
>>> photosdb.labels
['Water', 'Underwater', 'Jellyfish', 'Animal', 'Document', 'Table', 'Furniture', 'Container', 'Bottle', 'Interior Room', 'Bar', 'Drinking Glass', 'Drink', 'Liquor', 'Utensil', 'Tableware', 'Blue Sky', 'Sky', 'Plant', 'Tree', 'Palm Tree', 'Outdoor', 'Sunset Sunrise', 'Umbrella', 'Cloudy', 'Beach', 'Water Body', 'Ocean', 'Land', 'Cord', 'Food', 'Pizza', 'Child', 'People', 'Clothing', 'Grass', 'Dock', 'Mast', 'Harbor', 'Watercraft', 'Boat', 'Machine', 'Vehicle', 'Pole', 'Wine', 'Wine Bottle', 'Vase', 'Flower', 'Art', 'Flower Arrangement', 'Bouquet', 'Camera']
```

To see a count of how many photos are associated with each label, you can do this:

```pycon
>>> photosdb.labels_as_dict
{'Sky': 7, 'Outdoor': 7, 'Water': 4, 'Plant': 4, 'Cloudy': 4, 'Drink': 3, 'Blue Sky': 3, 'Tree': 3, 'Palm Tree': 3, 'Underwater': 2, 'Jellyfish': 2, 'Animal': 2, 'Table': 2, 'Furniture': 2, 'Container': 2, 'Utensil': 2, 'Sunset Sunrise': 2, 'Land': 2, 'Wine': 2, 'Wine Bottle': 2, 'Document': 1, 'Bottle': 1, 'Interior Room': 1, 'Bar': 1, 'Drinking Glass': 1, 'Liquor': 1, 'Tableware': 1, 'Umbrella': 1, 'Beach': 1, 'Water Body': 1, 'Ocean': 1, 'Cord': 1, 'Food': 1, 'Pizza': 1, 'Child': 1, 'People': 1, 'Clothing': 1, 'Grass': 1, 'Dock': 1, 'Mast': 1, 'Harbor': 1, 'Watercraft': 1, 'Boat': 1, 'Machine': 1, 'Vehicle': 1, 'Pole': 1, 'Vase': 1, 'Flower': 1, 'Art': 1, 'Flower Arrangement': 1, 'Bouquet': 1, 'Camera': 1}
```

**Comment by RhetTbull** [comment]
By the way, you can also run `osxphotos inspect` and it will display lots of information about which ever photo is selected in Photos (and you can change the selection to see the info for the new photo).  In the inspect window, labels are called "Categories".
