### ISSUE TITLE
ExifTool related fields not available when exporting >4GB files

### ISSUE THREAD

**Issue by nullpointerninja** [RhetTbull/osxphotos#722]
Hi, I identified an unwanted behavior when exporting large files (>4GB).

**Describe the bug**
When exporting video files that are more than 4GB in size, some ExifTool fields will not be available because it need the -api largefilesupport=1 parameter to properly read those files.

**To Reproduce**
1. Import a big file (>4GB) into a Photos Library (my sample video file was taken with an iPhone)
2. Export that file using some ExifTool fields as part of the directory (see below for full command)
3. Any ExifTool field (exiftool:EXIF:Model in the sample below) will not be found and the fallback will be used (a folder named Extra in this case)

Full command: Creates a variable where the taken date is stored, with multiple fallback options in case the files don't have a DateTimeOriginal. Usually happens with video files but the CreationDate takes care of that.
The folder structure uses this date and the camera model to create a path that looks like this: /2022/X-T30/2022-05-01/<files>.
The post command updates any extension to be uppercase.
The script can probably be improved quite a bit but it works :).
 
`osxphotos export ~/Original --directory "{var:photoDate,{exiftool:EXIF:DateTimeOriginal,{exiftool:QuickTime:CreationDate,{exiftool:File:FileModifyDate}}}}{%photoDate|sslice(0:4)}/{exiftool:EXIF:Model,{exiftool:QuickTime:Model,Extra}}/{%photoDate|sslice(0:4)}-{%photoDate|sslice(5:7)}-{%photoDate|sslice(8:10)}" --filename "{original_name}" --update --cleanup --not-shared --skip-edited --touch-file --post-command exported "mv {shell_quote,{filepath}} {shell_quote,{filepath.parent}/{filepath.stem}{filepath.suffix|upper}}"`

**Expected behavior**
Large files should be handled correctly, probably by adding the -api largefilesupport=1 parameter to ExifTool

**Desktop:**
 - OS: macOS 12.4
 - osxphotos, version 0.50.3

**Comment by RhetTbull** [comment]
Thanks -- I'll take a look. If this is an exiftool flag, does it work if you pass it with `--exiftool-option "-api largefilesupport=1"`?

**Comment by nullpointerninja** [comment]
If I only add `--exiftool-option "-api largefilesupport=1"` I get `Incompatible export options: --exiftool-option must be used with at least one of: --exiftool`. I added `--exiftool --exiftool-option "-api largefilesupport=1"` and it didn't complain but the behavior was the same.

**Comment by RhetTbull** [comment]
Hmmm...I'm not familiar with this option but surprised that didn't work as `--exiftool-option` should pass any options directly to `exiftool`.   I'll read up on `-api largefilesupport=1` and see how to implement this. If there's no performance impact then I might just leave it on all the time. However, if there as an impact, the code will need to check the file size and determine whether the flag is needed.

**Comment by RhetTbull** [comment]
I inquired over at the [exiftool forum](https://exiftool.org/forum/index.php) about `-api largefilesupport=1` -- will see what they say.  In the mean time, try adding `--exiftool-option -api --exiftool-option largefilesupport=1` to your export command and see if that helps.

**Comment by RhetTbull** [comment]
It appears [this does not impose a performance impact](https://exiftool.org/forum/index.php?topic=11906.0) so I'll add it to the default exiftool options. 

> I had to add --exiftool before the --exiftool-option

 Yes, that's as designed. Sorry I wasn't clear -- the `--exiftool-option` just passes extra options to exiftool when using `--exiftool`.

**Comment by nullpointerninja** [comment]
Thanks @RhetTbull!

**Comment by RhetTbull** [comment]
@nullpointerninja I think this is fixed in v0.50.5. Please update and give it a try. I don't have any large video files in my library with which to test but the large file flag is now passed to exiftool by default.

**Comment by nullpointerninja** [comment]
Hi @RhetTbull I just updated and tested with a large video file and works as expected. Thanks for the quick help with this!

**Comment by RhetTbull** [comment]
This may not be working right. See [this reddit comment](https://www.reddit.com/r/ApplePhotos/comments/11ppej7/comment/kubtdm2/?context=3)

See also [this](https://github.com/photostructure/exiftool-vendored.js/issues/109).
