### ISSUE TITLE
Exported size less than source?

### ISSUE THREAD

**Issue by dalisoft** [RhetTbull/osxphotos#729]
**Describe the bug**
The exported media folder is less than source size

**To Reproduce**
1. What' the full command line you used with osxphotos?
```sh
osxphotos --db "$PWD/Photos Library.photoslibrary" \
export "$PWD/Photos" \
--exportdb "$PWD/Photos/.osxphotos_export.db" \
--ramdb \
--exiftool \
--exiftool-merge-keywords --exiftool-merge-persons \
--ignore-date-modified \
--touch-file \
--skip-original-if-edited \
--jpeg-ext jpg \
--preview-if-missing --download-missing \
--retry 3 \
--strip --cleanup \
--update --force-update
```

2. What was the error output?

No errors

**Expected behavior**
Closer folder size to source

**Screenshots**
<img width="926" alt="Screen Shot 2022-07-20 at 06 40 16" src="https://user-images.githubusercontent.com/3511344/179877194-a242791e-7d7e-46d3-8252-666e8e9bf5a3.png">

![image](https://user-images.githubusercontent.com/3511344/179877365-baebaa64-ab35-44d7-802d-b9a8e2cb5fcd.png)

**Desktop (please complete the following information):**
 - OS: macOS, Big Sur 11.6.7 (20G630)
 - osxphotos version 0.50.6

**Additional context**

The items count also differs

<img width="235" alt="image" src="https://user-images.githubusercontent.com/3511344/179877467-069f453e-4fac-4647-82ba-600ad93fce6d.png">

<img width="209" alt="image" src="https://user-images.githubusercontent.com/3511344/179877507-f4f20333-eb4a-4639-9c2b-73f2bdd7137e.png">

**Comment by RhetTbull** [comment]
There are many reasons the sizes / counts could be different:

- The Photos library contains many files that are not exported: databases, plist config files, previews, etc.
- You only exported previews if missing and there are also many different preview variations and osxphotos only exports the highest quality
- You also skipped originals if edited so only one version of edited photos is exported wheres as Photos keeps both the original and the edited
- exiftool also rewrites the image headers which can change the size.  
- Live photos count as one item in Photos but osxphotos exports both the jpeg/heic image as well as the "live" video (2 items per Live photo)

It's impossible to know why this is different without seeing the export report or the verbose output.  You can re-create the report that would have been generated for the last export if you'd used the `--report` option using this command:

`osxphotos exportdb --report report.csv 0 "$PWD/Photos/.osxphotos_export.db"`

The `0` says to get the most recent report, using `osxphotos exportdb --report report.csv -1` would have generated the report for the export prior to the most the recent (one back), and so on.

I recommend you generate the export report (which will be in CSV format that can be opened in Excel or any CSV viewer or text editor) then look for files that had errors or were missing (Even with `--download-missing`, it might be possible that Photos couldn't download a file).  If you're comfortable with JSON or sqlite you can generate the report in those formats using `osxphotos exportdb --report report.json 0` or `osxphotos exportdb --report report.db 0` respectively.

**Comment by dalisoft** [comment]
@RhetTbull Thank you a lot for such detailed response and helpful information. 
I am newbie on Mac Photos as used just iOS Phones locally then decided to upload to iCloud but due of Apple buggy software I’m lost around 100 photos and videos which I don’t which videos or photos. So decided to it manually by Importing into Mac Photos and researched a lot way but found only your solution.
It works best and without bugs, all the issues opened by me is related to my not reading docs fully or not understanding how it works.

**Comment by RhetTbull** [comment]
@dalisoft no problem! Glad you find osxphotos useful. If you have any other questions, please don't hesitate to ask. If it's just a question and not a bug report or feature request, take a look at the [discussions](https://github.com/RhetTbull/osxphotos/discussions) forum.
