### ISSUE TITLE
Add `export_id` to SQLite report

### ISSUE THREAD

**Issue by infused-kim** [RhetTbull/osxphotos#731]
Hi,

First of all, I want to thank you for creating this incredible tool. It seems like you have thought of everything and I want to thank you for creating, maintaining and continiously working on this project.

I can only imagine how much work this was.

## Proposal
I like generating the SQLite report with the append option, but to be able to query it effectively, I think we should add a unique ID for each export that is run by the app.

It shouldn't be too difficult. You can just generate a UUID when the script is run and then add it as a `export_id` column to the `report` table.

The benefit is that then users would be able to see exactly which photos were exported or deleted.

For example, they could run queies like this:

```sql
select
	export_id,
	datetime(min(datetime)) start_time,
	datetime(max(datetime)) end_time,
	strftime('%s',max(datetime)) - strftime('%s',min(datetime)) as duration_s,
	sum(exported) as exported,
	sum(new) as new,
	sum(updated) as updated,
	sum(skipped) as skipped,
	sum(sidecar_xmp) as sidecar_xmp,
	sum(touched) as touched,
	sum(converted_to_jpeg) as converted_to_jpeg,
	sum(missing) as missing,
	sum(error) as error,
	sum(cleanup_deleted_file) as cleanup_deleted_file
from report_with_id
group by export_id 
```

Which shows you stats for each export:
<img width="1412" alt="Screen Shot 2022-07-20 at 17 18 48" src="https://user-images.githubusercontent.com/7404004/180019797-0b9a1e68-f957-4eb8-a140-c6f5b8810ddb.png">

Another use for this would be to for example show all the files that were deleted during a particular export.

## Workaround until added

For those who want to be able to run queries like this before the `export_id` column is added, you can use this query to create a view `report_with_id` that has a fake `export_id`.

This considers a new export if more than 20 seconds have passed since the last file was exported. This works well when each export is fast, but could break down if a file export takes longer than 20 seconds (for example if you use the text recognition function).

So it still makes sense to add this directly to the sqlite file.

```sql
drop view if exists report_with_id;
create view report_with_id
as

with

src_report as (
	
	select * from report 

),

-- Generate Fake Export ID
with_prev_row_datetime as (
	select
		*,
		lag(datetime, 1) over (order by datetime asc) as prev_row_datetime
	from src_report
),

with_prev_row_time_diff as (
	select
		*,
		strftime('%s', datetime) - strftime('%s', prev_row_datetime) as prev_row_time_diff
	from with_prev_row_datetime
),

with_new_export_started as (
	select
		*,
		case
			when
				prev_row_time_diff >= 20 or
				prev_row_time_diff is null
			then 1 
			else 0
		end as new_export_started
	from with_prev_row_time_diff
),

with_export_id as (
	select
		sum(new_export_started) over (order by datetime asc) as export_id,
		*
	from with_new_export_started
)

select * from with_export_id

```

**Comment by RhetTbull** [comment]
Thanks for the suggestion -- I'll take a look at this. 

In the meantime, you can reconstruct a report of the last export using `osxphotos exportdb /path/to/export --report report.db 0`

This generates a SQLite database of the report showing all files exported, deleted, skipped, etc. 

If you change the report extension to .csv you'll get it in CSV format and likewise for .json

The last 10 reports are stored and can be accessed by changing the number 0 (most recent) to -1 (one previous), -2 (second most previous) and so on.

Look at `osxphotos help exportdb` for more details.

**Comment by RhetTbull** [comment]
This will be easy to implement by updating the `ReportWriterSQLite` class.  In `__init__`, add a property for `export_id` set to `datetime.datetime.now().isoformat()` and then add a column to the table (will need a migration to deal with pre-existing report databases). 

https://github.com/RhetTbull/osxphotos/blob/1fadea8864911693a7e133578e4d402d442a72ec/osxphotos/cli/report_writer.py#L154-L183

**Comment by infused-kim** [comment]
Thank you so much for taking this request into consideration.

The datetime would work well enough, but may be a little confusing as it would look like a second date and it wouldn't be immediately obvious that the rows can be grouped by it.

But having an ID that is sortable would be great. Another way to achieve it is to run `select max(report_id)+1 from reports` and then use that as the report_id for the new run.

**Comment by RhetTbull** [comment]
> Another way to achieve it is to run `select max(report_id)+1` from reports and then use that as the report_id for the new run.

This would work but would be subject to a race condition in the (likely rare) event two exports were running at the same time and trying to append to the same report database (which sqlite would allow).  In that case, I think you could get two exports that used the same ID.  Of course this likely isn't the normal use case (though I did experiment with simultaneous exports as part of a multiprocessing fork in #582 ).  I could use just an integer time stamp or a UUID as you originally suggested but the ISO formatted datestamp has the advantage of carrying additional context for the user -- they can see exactly when the export started and I think a column name of `export_id` would be self-explanatory.  I'll think some more about this before implementing.

**Comment by infused-kim** [comment]
That makes sense.

What do you think of this idea...

When an export is run, a row is added to a `exports` table, which has an auto incrementing ID (`export_id`) and some columns for stats like start time, end time, duration, number of photos exported (similar to the screenshot in my first post)... 

An additional column it can have is `export_note`, which can be set through a `--export-note` argument.

I would like to add some information about what I did prior to the export, such as `Did a clean up of the 2022 photos. Deleted similar photos and adjusted faces."

Each row in the `report` table would include the export_id of the export.

This way it's easy to see a summary of all the exports including a "what happened before the export" as well as all the exported files.

**Comment by infused-kim** [comment]
Another idea for the `exports` table: Add the command line arguments and/or config that was used for the export to provide another context to what was done or intended to be done.

Sorry for the many comments, I am just coming up with ideas as I go along using the software.

**Comment by RhetTbull** [comment]
> Sorry for the many comments, I am just coming up with ideas as I go along using the software.

No worries -- I appreciate having feedback from users.

You can already get both the last command and the config file for the last run (even if you didn't save a config file).  Take a look at:

`osxphotos exportdb /path/to/export --last-run`

`osxphotos exportdb /path/to/export --save-config CONFIG_FILE.toml`

Try `osxphotos help exportdb` to see all the utilities built into the exportdb command.

**Comment by RhetTbull** [comment]
By the way, you can also try `osxphotos docs` to open the docs (fully searchable) in the browser

**Comment by RhetTbull** [comment]
I've implemented this in [0.50.7](https://github.com/RhetTbull/osxphotos/releases/tag/v0.50.7).  I resolved the possible race condition by adding a separate `report_id` table which stores the `report_id` as  date/time then the primary key of this table is used as the `report_id` column in the `report` table.  That makes the report_id a simple integer that increments with each export but also provides access to the date/time the report was generated.  One note: what is stored is the date/time the *report was generated* which may be different than the date/time when the export happened if the user used the `osxphotos exportdb --report` feature to generate a report after the fact.

Thus, you can your slightly modified query:

```sql
select
	report_id,
	datetime(min(datetime)) start_time,
	datetime(max(datetime)) end_time,
	strftime('%s',max(datetime)) - strftime('%s',min(datetime)) as duration_s,
	sum(exported) as exported,
	sum(new) as new,
	sum(updated) as updated,
	sum(skipped) as skipped,
	sum(sidecar_xmp) as sidecar_xmp,
	sum(touched) as touched,
	sum(converted_to_jpeg) as converted_to_jpeg,
	sum(missing) as missing,
	sum(error) as error,
	sum(cleanup_deleted_file) as cleanup_deleted_file
from report
group by report_id 
```
To produce a summary:

<img width="887" alt="Screen Shot 2022-07-23 at 3 28 35 PM" src="https://user-images.githubusercontent.com/41546558/180625325-dcffc241-445b-4cc3-85d2-1285417bcbf7.png">

If you append to an existing report database, the database will be migrated but the `report_id` column for all old exports will be `NULL`.

**Comment by RhetTbull** [comment]
I noticed there was a slight error in the code for the error summary as `error` isn't a numeric column but the actual text (if any) of the error message generated when exporting.  This `sum()` doesn't work correctly.  It would be more accurate to use this for the error summary:

```sql
SUM(CASE WHEN error = "" THEN 0 ELSE 1 END) as error,
```

While fixing that, I decided to just create a new view in the report database called `report_summary` so you can do this to get a quick summary of all your exports:

`sqlite3 report.db ".mode line" "SELECT * FROM report_summary"`

Which produces something like this:

```
          report_id = 3
          start_time = 2022-07-23 16:32:41
            end_time = 2022-07-23 16:32:41
          duration_s = 0
            exported = 33
                 new = 0
             updated = 0
             skipped = 0
         sidecar_xmp = 0
             touched = 0
   converted_to_jpeg = 0
             missing = 3
               error = 0
cleanup_deleted_file = 0

           report_id = 4
          start_time = 2022-07-23 16:32:52
            end_time = 2022-07-23 16:32:53
          duration_s = 1
            exported = 0
                 new = 0
             updated = 0
             skipped = 33
         sidecar_xmp = 0
             touched = 0
   converted_to_jpeg = 0
             missing = 3
               error = 0
cleanup_deleted_file = 0
```

The view is defined as:

```sql
            CREATE VIEW IF NOT EXISTS report_summary AS
            SELECT
                report_id,
                datetime(MIN(datetime)) start_time,
                datetime(MAX(datetime)) end_time,
                STRFTIME('%s',MAX(datetime)) - STRFTIME('%s',MIN(datetime)) AS duration_s,
                SUM(exported) AS exported,
                sum(new) as new,
                SUM(updated) as updated,
                SUM(skipped) as skipped,
                SUM(sidecar_xmp) as sidecar_xmp,
                SUM(touched) as touched,
                SUM(converted_to_jpeg) as converted_to_jpeg,
                SUM(missing) as missing,
                SUM(CASE WHEN error = "" THEN 0 ELSE 1 END) as error,
                SUM(cleanup_deleted_file) as cleanup_deleted_file
            FROM report
            GROUP BY report_id;
```

The new version with built in view is in [0.50.8](https://github.com/RhetTbull/osxphotos/releases/tag/v0.50.8)

**Comment by infused-kim** [comment]
Just tried this too and it works perfectly.

Thank you so much for implementing it so quickly!
