### ISSUE TITLE
Show full live photo size in inspect

### ISSUE THREAD

**Issue by infused-kim** [RhetTbull/osxphotos#734]
**Is your feature request related to a problem? Please describe.**
When inspecting a live photo, it shows the size only of the .heic file, but not of the corresponding .mov file.

**Describe the solution you'd like**
Show the size like `2.32 MB (Photo)  |  4.21 MB (Live Video)

**Describe alternatives you've considered**
Finding the files in Finder and checking the size that way.

**Comment by RhetTbull** [comment]
Good suggestion -- thanks!

**Comment by RhetTbull** [comment]
If I do this for Live photos, might also want to do for RAW photos.

**Comment by RhetTbull** [comment]
@all-contributors please add @infused-kim  for ideas

**Comment by RhetTbull** [comment]
Done, implemented in [0.50.7](https://github.com/RhetTbull/osxphotos/releases/tag/v0.50.7)

**Comment by infused-kim** [comment]
Works perfectly.

I love that it also shows the file paths now, which I think is also new.

Thank you so much for implementing it so quickly!
