### ISSUE TITLE
Add --skip-referenced as an option

### ISSUE THREAD

**Issue by nullpointerninja** [RhetTbull/osxphotos#738]
Hi, I was looking for a way of exporting all files that are managed by Photos, skipping any referenced files.
I see there's an `--is-reference` option but not the "not/skip" equivalent.
So for example, if a library had 3 managed and 2 referenced photos, a `--skip-referenced` would only try to export the 3 managed files, ignoring the 2 referenced photos.
In a perfect world, this would also _avoid_ deleting any existing files that were already in the destination when paired with the `--cleanup` option, but I believe that's not the expected behavior and it should delete anything present in the destination that's not being exported by osxphotos.
Thanks!

**Comment by RhetTbull** [comment]
This would probably be better as a `--not-reference` to complement `--is-reference` which would function like all the other query options -- that is, it would match only photos that are not a reference (that is, only managed photos). 

> In a perfect world, this would also avoid deleting any existing files that were already in the destination when paired with the --cleanup option, 

My guess is you're interested in exporting managed photos to the same location as currently referenced photos.  Yes, you're right that the `--cleanup` option isn't compatible with this. However, I'm looking into adding a `--keep` option (#730) which would allow you to specify files to keep (not cleanup).  If I also added the ability for `--keep` to read from a file, you could first generate a list of all files existing in the destination then instruct osxphotos not delete these on cleanup.,

**Comment by RhetTbull** [comment]
In the mean time, you can use `--query-eval "not photo.isreference"` to export just photos that are not references.

**Comment by nullpointerninja** [comment]
That would be an excellent solution. You are indeed right, I want to be able to export managed photos to the same folders as some referenced photos.
I tested the `--query-eval "not photo.isreference"` option and it did work as expected.

Thanks!

**Comment by RhetTbull** [comment]
@all-contributors please add @nullpointerninja for ideas

**Comment by RhetTbull** [comment]
I've add the `--not-reference` query option in [v0.50.11](https://github.com/RhetTbull/osxphotos/releases/tag/v0.50.11) that works just like `--query-eval "not photo.isreference"`

**Comment by nullpointerninja** [comment]
Thanks @RhetTbull!
