### ISSUE TITLE
Add `osxphotos import` command

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#754]
`osxphotos import [--album ALBUM_TEMPLATE] [--keyword KEYWORD_TEMPLATE] [--title TITLE_TEMPLATE] [--description DESCRIPTION_TEMPLATE] [--walk] FILES_OR_DIRS`

import files into Photos, optionally add to albums and set metadata.  Use [autofile](https://github.com/RhetTbull/autofile) plugins to allow template system based on metadata in the file to set the album and metadata attributes.

if FILES_OR_DIRS is dir then get all files in the dir, otherwise get all files

also use `--glob "*.jpg"` to limit only to jpgs, allow multiple --glob

Allow some timewarp functionality?  e.g. --timezone, --time-delta, --date-delta, --time, --date

--keyword "{exiftool:IPTC:Keywords}"

--album "{filepath.parent}"

--title "{sidecar:json:title}" (how to specify sidecar name?)

maybe 

--title "{json:filepath.stem.json:title}" or

--title "j{son,{filepath.stem.json:title},}" <-- not this as it makes the template system need special handling for :title

--title "{json:filepath.stem.json:title}" or

I like this version.  Could backport to autofile as a json plugin

--description "{xmp:filepath.name.xmp:XMP:Description}"

--title "{function:title.py::title}"  -->

```python
def title(path: pathlib.Path) -> List[str]:
    ...
```

**Comment by RhetTbull** [comment]
Include `--dup-check` to enable duplicate checking on import. This should be disabled by default as the duplicate check requires user interaction in Photos which is annoying when importing

**Comment by oPromessa** [comment]
When you manually import duplicated pics in Photos it warns you. Yes! It requires user interaction. Would an import via osxphotos 'catch' that same notice?

**Comment by RhetTbull** [comment]
> When you manually import duplicated pics in Photos it warns you. Yes! It requires user interaction. Would an import via osxphotos 'catch' that same notice?

It's possible to programmatically import photos with or without the dupe check. If the dupe check is enabled, it pops up a window in Photos requiring user interaction.  Without, it silently imports the duplicates. 

I suppose osxphotos could do it's own dupe check against the Photos database and do the prompt via the command line instead of the modal Photos window.

**Comment by RhetTbull** [comment]
Implemented in 0.51.0
