### ISSUE TITLE
Error on Export

### ISSUE THREAD

**Issue by allanimal** [RhetTbull/osxphotos#758]
Exporting 3000 photos ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━  43% 0:14:12
Something went wrong and osxphotos encountered an error:
Finder got an error: The Finder is busy. (-15260) app='Finder' range=140-198
Crash log written to '/Users/allan/osxphotos_crash.log'
Please file a bug report at https://github.com/RhetTbull/osxphotos/issues with the crash log attached.
[osxphotos_crash.log](https://github.com/RhetTbull/osxphotos/files/9333628/osxphotos_crash.log)
[osxphotos_crash.log](https://github.com/RhetTbull/osxphotos/files/9333631/osxphotos_crash.log)

**Comment by RhetTbull** [comment]
Thanks for the crash logs  -- I'll take a look later today.

**Comment by RhetTbull** [comment]
Both crash logs appear to indicate an AppleScript error writing extended attributes (specifically Finder comments).

`applescript.ScriptError: Finder got an error: The Finder is busy`

The osxphotos codes needs to use AppleScript to communicate with the Finder to set Finder comments. AppleScript can be very flaky at times.

The extended attributes feature has been well tested on Catalina 10.15.7 (which I run) but not on other versions of MacOS.  Which version of MacOS are you running? It might be helpful to reboot the machine and try again.  I've found that sometimes AppleScript gets into a state in which it constantly crashes and only a reboot fixes it. (This isn't something osxphotos can fix).  

If you reboot and still the same issue I'll see if I can find the problem though if you're running Big Sur or Monterey my ability to debug this will be very limited.

**Comment by RhetTbull** [comment]
Hi @allanimal are you still having problems with osxphotos crashing?

**Comment by allanimal** [comment]
Once I left out the writing of finder attributes and keywords, I have not had the crashing problems. 

I think the huge 1st time export of my entire library was causing the problem. I’ll try to update in smaller parts to add the finder keywords and attributes. 

Thanks for following up, and the other great help you’ve provided.

**Comment by RhetTbull** [comment]
Cannot replicate. Closing, will re-open if issue comes up again. Likely I'll need access to Monterey or Ventura machine to really test if this is an osxphotos issue or a Mac OS permissions issue.
