### ISSUE TITLE
path for templates directory incorrectly set in the context of sidecar_xmp usage?

### ISSUE THREAD

**Issue by gabhubert** [RhetTbull/osxphotos#77]
First of all thanks so much for this, it was a blessing to find it as I'm gearing up to export ~750GB to make the leap to Lightroom. 

In making use of the osxphotos module, when using `sidecar_xmp=True` I got the error: 

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/[me]/opt/miniconda3/lib/python3.7/site-packages/osxphotos-0.22.14-py3.7.egg/osxphotos/templates/xmp_sidecar.mako'

I fixed it by searching for and grabbing the `templates` folder from my local osxphotos repo but I wonder of the path is somehow getting set incorrectly? Apologies if it's something on my end only that I messed up when installing dependencies.

**Comment by RhetTbull** [comment]
Thanks for the bug report. How did you install osxphotos? (e.g. from github with `python setup.py install` or with pip from pypi?)

**Comment by RhetTbull** [comment]
@gabhubert Also, were you using the command line interface or writing your own export code?

**Comment by RhetTbull** [comment]
@gabhubert I think I fixed this: setup.py was not configured to pull in the template files from MANIFEST.in.  Please pull 0.22.17 from github or pypi and see if that fixed the problem.

**Comment by gabhubert** [comment]
I was writing my own export code on top (to keep the album structure as a file system in the export). Yes using setup.py

**Comment by RhetTbull** [comment]
I've not had opportunity to test on a library as large as yours--let me know if you encounter any other issues!

**Comment by gabhubert** [comment]
Yep—I'm definitely building unit test firsts :) I'll keep you posted. 

Just pulled 22.17, I'll let you know (but as I said it worked already for me by copying the templates folder so I don't expect to observe a change in behaviour
