### ISSUE TITLE
Are edited photo partially corrupted on export?  

### ISSUE THREAD

**Issue by gabhubert** [RhetTbull/osxphotos#78]
I'm testing out the photos that are exported. One test I ran was to re-upload to Photos a photo that had been edited (ie .hasadjustments=True) and then been exported. I get this message in Photos: 

<img width="627" alt="Screenshot 2020-03-14 at 16 30 49" src="https://user-images.githubusercontent.com/998689/76686808-900c5200-661e-11ea-9eae-c3f08af78bcd.png">

And it seems the photo can no longer be edited in Photos. 

For my primary use case this doesn't matter (I've imported the same photo in Lightroom and can edit it) but I was wondering if the export corrupted it in any way, at least in Photos' view of the world?

**Comment by RhetTbull** [comment]
It's unlikely the edited photo is actually corrupt as on export, the photo is copied (using `/usr/bin/ditto`) directly out of the Photos library.  It's possible there's some metadata in the image that Photos detects and causes Photo to associate this image with an adjustment ID which it can't find.  

Which version of MacOS are you using? How did you re-import into Photos (e.g. dragging it in, using File | Import, etc) Also, did you re-import into the same library from which you exported or did you import into a new library?

I tried this twice on 10.15.1 and could not replicate.  I looked at all metadata using exiftool and xattr and could not see anything which might indicate Photos specific metadata.  If you're willing to send me one of the offending images, I'm happy to explore this further (send to rturnbull+git @ gmail dot com). I suggest sending via Firefox [send](https://send.firefox.com/).

**Comment by gabhubert** [comment]
- Catalina 10.15.3
- Photos 5.0 (131.17.170)
- replicated with drag + drop and with file > import

Great; I sent you 2 examples via email!

**Comment by RhetTbull** [comment]
Thanks.  I've replicated the problem and found the issue.  Yes, the file is technically corrupt because it's really a jpeg not a CR2.  There's a bug in the export code that causes the edited image (which Photos stores as jpeg render of the raw image) to be exported with CR2 extension.  I don't use RAW images so didn't have a test case for this.  I'll work on a fix and update the test suite.  I did verify the unedited export file was correct, this just affects the edited render.

**Comment by gabhubert** [comment]
Woot!

**Comment by RhetTbull** [comment]
I think I've fixed this.  There were 2 issues, one of which may require change to your code. 

1. the command line client would sometimes use the wrong extension when exporting edited photos (fixed).
2. PhotoInfo.export() takes an optional filename argument. If provided, export would use the filename and extension provided regardless of the actual extension of the file being exported.  Sometimes, the extension of the original image is different than the extension of the edited image.  For example, if original is a raw .CR2 and you edit it, Photos creates a rendered .jpeg image.  e.g. if you called `export("/Users/Desktop", "photoname_edited.cr2", edited=True)` the exported file would be called photoname_edited.cr2 but the actual edited image might be a jpeg.  

Issue 1 has been fixed.  To address issue 2, `export()` has been updated to print a warning if the supplied extension in filename does not match the actual file.  To avoid misnamed files, ensure the filename argument matches the correct extension. For example, if using `edited=True`, you can get the correct extension from `path_edited`:
```python
>>> import pathlib
>>> pathlib.Path(p.path_edited).suffix
'.jpeg'
```
I thought about having the code change the suffix to the correct file extension but decided instead to print a warning.

I've also changed the return type of PhotoInfo.export from str to list so if you are using the return value, you'll need to change your code.  Rationale: export sometimes exports more than one file (e.g. the associated .mov of a live movie) so it now returns the path to all files that were exported.
