### ISSUE TITLE
Find people _UNKNOWN_

### ISSUE THREAD

**Issue by amlucca** [RhetTbull/osxphotos#783]
Hello,

I found out that through the command `osxphotos persons` the output for _UNKNOWN_ is 3607. 

    *UNKNOWN*: 3607

However, if I run the command `osxphotos query --person _UNKNOWN_ --add-to-album "No person"` the resulted album has 2.049 photos only. Where are the other 1.558 photos to complete 3607 from the first output?

I'm running macOS 11.6.8 and using the last compiled version of osxphotos.

**Comment by RhetTbull** [comment]
Some of the photos likely contain more than one unknown person. The `osxphotos persons` command lists the persons, not the photos.  The query command you ran looks for `photos with unknown persons` which is different than `how many unknown persons are in the database`.

**Comment by amlucca** [comment]
Oh, thank you so much for the super fast reply! And sorry for the dumb question! 

BTW, is it possible to query HEVC movies and add them to an album?

**Comment by RhetTbull** [comment]
Not a dumb question!

I'm not familiar with HEVC movies. Do they have a certain extension or UTI? If so, yes, they could be found.   Assuming extension is ".hevc" you could do something like this:

`osxphotos query --name ".hevc" --ignore-case`

**Comment by amlucca** [comment]
Thanks again for the quick reply! No, they don't have a certain extension as HEIC photos do. 

They have a specific codec, which is hvc1. However, I'm not familiar with python so I end up having no clue on how to use osxphotos.exif_info to query movies with codec hvc1 and add them to an album so I can export them separately.

**Comment by RhetTbull** [comment]
Try this: run `osxphotos inspect` then select a video in Photos you know is in this format. osxphotos will show the entire path to the file in the Photos library.  Copy that path then run this command in the terminal:

`exiftool -G /paste/path/here > exif.txt` then paste the exif.txt file here. I'll take a look and see if there's a way to identify these.

**Comment by amlucca** [comment]
[exif.txt](https://github.com/RhetTbull/osxphotos/files/9464552/exif.txt)

**Comment by RhetTbull** [comment]
> QuickTime]     Compressor Name                 : HEVC

Looks like you might be able to do this:

`--exif QuickTime:CompressorName HEVC`
