### ISSUE TITLE
Add the ability to select not uploaded photos

### ISSUE THREAD

**Issue by infused-kim** [RhetTbull/osxphotos#800]
Hi,

Here's another feature suggestion for an issue I just ran into.

I synced a library with over 90,000 photos to iCloud, but 170 photos just wouldn't upload. They didn't show up in the "can't upload" section of the app... the upload was simply stuck. Repairing the library didn't help either.

I inspected the database to identify which photos couldn't be synced. Although the photos existed in the database and the originals folder, they didn't show up in the search.

Eventually, what worked was to...
- Query the database for the photos that couldn't be uploaded
- Get the UUIDs of the photos from the DB
- Use the `--uuid-from-file` option to export the originals and the `--add-exported-to-album` to identify which photos are affected in Photos
- Delete the affected photos from the library
- Re-import the exported originals

The process above can be done using the SQL query I'll post at the bottom, but since according to google "iCloud Photo Upload" seems to be a common problem, perhaps this would be a useful feature to integrate for users who are not familiar with SQL.

I suggest adding a parameter like `--unuploaded`, which finds photos that have `ZASSET.ZCLOUDLOCALSTATE == 0`.

## SQL Query to find unuploaded photos
```sql

with 

asset_with_info as (
	select
		zasset.z_pk,
		zasset.zuuid,
		zasset.ZCLOUDLOCALSTATE,
		zasset.zfavorite,
		zasset.ZHASADJUSTMENTS,
		zasset.zdatecreated,
		strftime("%Y-%m-%d - %H:%M:%S", zasset.zdatecreated + 978307200, 'unixepoch') as date_created,
		zasset.zfilename,
		zasset.zuniformtypeidentifier,
		attr.zoriginalfilename,
		zdirectory || "/" || zfilename as path
	from zasset
	left join ZADDITIONALASSETATTRIBUTES attr
	on zasset.z_pk = attr.z_pk
)

select * from asset_with_info
where 1=1
-- and zaddeddate == zdatecreated
--	and ZFILENAME is null
--	and ZUUID = '8E649511-AE47-4CD7-A493-B49793FF1EC2'
	and ZCLOUDLOCALSTATE == 0
LIMIT 1000;
```

**Comment by seanconnors** [comment]
That would be an AWESOME and very helpful feature.

**Comment by RhetTbull** [comment]
Great feature suggestion and thanks for the sample query. I'll take a look at incorporating this. Currently in the middle of another project.

**Comment by RhetTbull** [comment]
I'm on mobile so can't test this at the moment but I *think* the following query will do this as `ZCLOUDLOCALSTATE` is already read by osxphotos:

`osxphotos query --query-eval "photo._info['cloudLocalState'] == 0"`  

I'll implement this as a new `PhotoInfo` boolean property of `uploaded` add query options of `--uploaded`, `--not-uploaded` to match the other options.,

**Comment by RhetTbull** [comment]
I did a little experimentation and I have no photos with `ZCLOUDLOCALSTATE == 0`.  If I turn off WiFi and add a photo, that photo has `ZCLOUDLOCALSTATE == 1`.  All photos that are synced to iCloud have `ZCLOUDLOCALSTATE == 3`.  I'm guessing 0=error, 1=not synced, and 3=synced. Not sure if there's a 2. If you still have any photos that are having issues, it would be helpful to get some more data.

If you save the following as `cloud_local_state.py` and run this command:

`python -m osxphotos inspect -T "{function:cloud_local_state.py::cloud_local_state}"`

You can use the inspect feature to check the ZCLOUDLOCALSTATE of any selected photo.

```python
""" Example showing how to use a custom function for osxphotos {function} template 
    Use:  osxphotos inspect -T "{function:/path/to/template_function.py::cloud_local_state}"

    You may place more than one template function in a single file as each is called by name using the {function:file.py::function_name} format
"""

import pathlib
from typing import List, Optional, Union

from osxphotos import ExportOptions, PhotoInfo


def cloud_local_state(
    photo: PhotoInfo, options: ExportOptions, args: Optional[str] = None, **kwargs
) -> Union[List, str]:
    """example function for {function} template; adds suffix of # if photo has adjustments and ! if photo is a favorite

    Args:
        photo: osxphotos.PhotoInfo object
        options: osxphotos.ExportOptions object
        args: optional str of arguments passed to template function
        **kwargs: not currently used, placeholder to keep functions compatible with possible changes to {function}

    Returns:
        str or list of str of values that should be substituted for the {function} template
    """

    filename = pathlib.Path(photo.original_filename).stem
    uuid = photo.uuid
    cloud_local_state = photo._info["cloudLocalState"]

    return f"{filename}, {uuid}, {cloud_local_state}"
```

**Comment by RhetTbull** [comment]
More data:
In my library, I had the following distribution of `ZCLOUDLOCALSTATE`:

```python
{3: 26444, None: 6617}
```

The photos with `None` are shared photos (photos in shared albums).  All others have a value of 3. As previously noted, when I added a photo and prevented sync, it had a value of 1 until it synced then the value was 3.

**Comment by RhetTbull** [comment]
I think `ZCLOUDLOCALSTATE` has the following values but cannot confirm without further data. I don't have any upload errors so can't confirm the values reported by @infused-kim which appear to be `0`.

null: Not an iCloud photo (this is the value in libraries that are not iCloud libraries as well as for photos in shared albums)
0: Error uploading to iCloud
2: *Unknown*
1: Not yet uploaded to iCloud
3: Uploaded to iCloud

**Comment by RhetTbull** [comment]
I've made an error -- the `ZCLOUDLOCALSTATE` that is currently read by osxphotos `ZCLOUDMASTER.ZCLOUDLOCALSTATE` which has different values.  The values above refer to this column, not `ZASSET.ZCLOUDLOCALSTATE`.

**Comment by RhetTbull** [comment]
More data from [here](https://github.com/ScottKjr3347/iOS_Local_PL_Photos.sqlite_Queries/blob/5e510da54fdb13dd1ce36c0ad7618afbfde72198/iOS16/iOS16_LPL_Photossqlite_Query.txt)

CASE ZINTERNALRESOURCE.ZCLOUDLOCALSTATE
    WHEN 0 THEN 'Cloud Int Resource Not Avil Local-0'
    WHEN 1 THEN '1-Pending Upload'
    WHEN 2 THEN 'Cloud Share Asset on Local-Device-2'
    WHEN 3 THEN 'Synced with Cloud-3'

CASE ZCLOUDMASTER.ZCLOUDLOCALSTATE
    WHEN 0 THEN 'Not Synced with Cloud-0'
    WHEN 1 THEN '1-Pending Upload'
    WHEN 2 THEN '2-StillTesting'
    WHEN 3 THEN 'Synced with Cloud-3'

CASE ZASSET.ZCLOUDLOCALSTATE
    WHEN 0 THEN 'iCldPhotos ON=Asset in Shared/Other Album/iCldPhotos OFF=Not Synced-0'
    WHEN 1 THEN 'iCldPhotos ON=Asset Synced with iCloud-1'

**Comment by RhetTbull** [comment]
Based on above data, I think `ZASSET.ZCLOUDLOCALSTATE` is the wrong value.  In my library, all the shared photos have `ZASSET.ZCLOUDLOCALSTATE = 0` and all other photos have `ZASSET.ZCLOUDLOCALSTATE` even if not yet synced to iCloud.  Perhaps `ZINTERNALRESOURCE.ZCLOUDLOCALSTATE` would be better.  I'll do some testing and compare all of them.

**Comment by RhetTbull** [comment]
I've done some testing and here's my data from testing multiple photos in each category.

asset_state = ZASSET.ZCLOUDLOCALSTATE
resource_state = ZINTERNALRESOURCE.ZCLOUDLOCALSTATE
cloud_state = ZCLOUDMASTER.ZCLOUDLOCALSTATE

Photo that has been synced to iCloud:
asset_state=1, resource_state=3, cloud_state=3

Photo not yet synced to iCloud:
asset_state=1, resource_state=0, cloud_state=1

Photo in shared album:
asset_state=0, resource_state=null, cloud_state=null

Based on this small sample size, I think the safest for a "photo_is_uploaded" property would be `uploaded = ZCLOUDMASTER.ZCLOUDLOCALSTATE == 3`, otherwise, not uploaded

**Comment by RhetTbull** [comment]
Doh! I'm an idiot. I just realized that this property is already built into photos and `PhotoInfo.incloud`. It's not yet in the query options as `--uploaded` but you can mimic this for the time being with the following query:

`osxphotos query --query-eval "not photo.shared and not photo.incloud"`

The `not photo.shared` is needed by shared photos will always show as not in the cloud (even though they are...they're treated differently by Photos than regular photos)

**Comment by RhetTbull** [comment]
Well this was a bit of a wild goose chase but I think I will still incorporate the other ZCLOUDMASTER values so they're accessible for future use.

**Comment by infused-kim** [comment]
Hi,

Sorry for not responding earlier. When I first got the notification, the issue was already fixed in my library and I couldn't reproduce. And later on I forgot to respond.

But now I have uploaded my girlfriend's library to iCloud and she ran into the same issue.

So here is what I found:

## Query
```
osxphotos query --not-shared --not-incloud
```

This worked perfectly and identified the non-uploading photos. The number of photos it found matched exactly the number of missing photos in iCloud.com compared to the macOS library.

## Exporting

Unfortunately, exporting the failing photos did not work. The `--not-incloud` option is not available for the `export` command:

```
photos@MBP photo_library_export % osxphotos export photo_library_export/icloud_upload_fail --load-config osxphotos_export.conf --not-shared --not-incloud --dry-run                                      
Usage: osxphotos export [OPTIONS] [PHOTOS_LIBRARY]... DEST
Try 'osxphotos export -h' for help.

Error: No such option: --not-incloud (Possible options: --not-hdr, --not-hidden, --not-in-album)
```

And...
```
osxphotos export photo_library_export/icloud_upload_fail --load-config osxphotos_export.conf --not-shared --query-eval "photo._info['cloudLocalState'] == 0"  --dry-run
```

As well as...
```
osxphotos export photo_library_export/icloud_upload_fail --load-config osxphotos_export.conf --not-shared --query-eval "photo._info['incloud'] == 0"  --dry-run
```

Did also not find the right photos.

### What did work...
First I exported the uuids of the failing photos:
```
osxphotos query --not-shared --not-incloud  --field uuid “{uuid}” > not_incloud_uuid.txt
```

Then I had to clean up the file a little-- remove the quotes and the header row.

Then I was able to export it with the options `--uuid-from-file --add-exported-to-album`.

After re-importing the photos, they seem to be uploading now.

Once again, thank you so much for implementing this! It does seem like a fairly common problem. At least in my experience.

**Comment by RhetTbull** [comment]
Glad you got this working. I'll add the `--not-incloud`, `--in-cloud` options to `export`.  Until then, if you need to do this again, you can use the `--print` option to avoid having to edit the uuid file.  The following will produce a UUID file suitable for  use with `--uuid-from-file`

`osxphotos query --not-shared --not-incloud --quiet --print "{uuid}"`

**Comment by RhetTbull** [comment]
I've added --incloud, --not-incloud to export; will be included in next release

**Comment by RhetTbull** [comment]
Added in [v0.56.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.56.0)
