### ISSUE TITLE
Database disk image malformed.  Running Mac OS 12.6

### ISSUE THREAD

**Issue by neebah** [RhetTbull/osxphotos#803]
**Describe the bug**
Running an export.  getting a database disk image is malformed error.  
Have repaired the library twice.  No luck.  

**To Reproduce
osxphotos export --use-photokit --directory {folder_album} --download-missing --deleted --sidecar XMP [folder name]

![Screen Shot 2022-10-13 at 9 58 51 AM](https://user-images.githubusercontent.com/71442026/195617766-543ae62c-67d3-4f9d-81b6-9ba59a141f89.png)

![Screen Shot 2022-10-13 at 9 59 03 AM](https://user-images.githubusercontent.com/71442026/195617757-d075734e-ef0f-4b72-9548-5c4040ef000f.png)

**Comment by RhetTbull** [comment]
This appears to be an error in the osxphotos export database which osxphotos uses to track state so it can resume or update an export.  Is this a folder you had previously exported to?  I suggest you delete `/path/to/export/.osxphotos_export.db` and try the export again.  If you have photos from a previous export, you may want to delete those (or move them to a different folder) as they'll cause name collisions with the newly exported photos (and osxphotos won't be able to match the images to it's export database which it normally uses to avoid collisions).

**Comment by neebah** [comment]
That did it.  Thanks
