### ISSUE TITLE
Photos exported to zero size jpeg

### ISSUE THREAD

**Issue by riccardo-casazza** [RhetTbull/osxphotos#807]
**Describe the bug**
While exporting my Library's photos with osxphotos export command, a certain number of photos come out zero sized.

**To Reproduce**
1. I run the following command: `/usr/local/bin/osxphotos export --verbose --db /Volumes/Photos/Libraries/2022.photoslibrary/database/Photos.sqlite --skip-original-if-edited --retry 3 --ramdb --update --convert-to-jpeg --jpeg-quality 1.0 --cleanup /Volumes/photos-1/Gallery/2022/`
2. The source Library is on an USB drive (/Volumes/Photos), destination directory is on a remote SMB drive (/Volumes/photos-1)

**Expected behavior**
having at destination the entire collection of photos, instead many photos are zero sized. 
I'm attaching some info of one of the source image that is exported to zero size:
![image](https://user-images.githubusercontent.com/10390360/196899381-0a68ff8f-4745-44f1-9d58-46544f2345bc.png)
![image](https://user-images.githubusercontent.com/10390360/196903130-8f581829-14f4-4c54-b0bc-9ca6ab8add49.png)

I attach the screenshot of the zero-sized destination image: 
![image](https://user-images.githubusercontent.com/10390360/196899540-a732f127-9cce-4ff7-b96d-49d49d46f6c3.png)

**Desktop (please complete the following information):**
 - OS: Darwin 11.7
 - osxphotos version: 0.51.8

**Comment by RhetTbull** [comment]
I've never seen this behavior before. It could be an osxphotos bug or could be something weird going on with the SMB drive. Here are a couple things to try to get additional data. 

1. Try to export one of the affected photos to a folder on the local computer.  You can limit the export by add the option `--uuid 6E3E4723-6933-4BDC-BDC3-D58DF4F83383`.  That limits the export to the one image in your example screenshot.  Alternatively you could use  `--name "Lou-9"` which would export any photo with a matching name to the one in your example.

2. Run the following command to get debug output and either post the output here or email it to me at rturnbull+git@gmail.com (note the output may contain sensitive information such as precise locations the photo was taken).

`osxphotos debug-dump --db /Volumes/Photos/Libraries/2022.photoslibrary/database/Photos.sqlite --dump photos --uuid 6E3E4723-6933-4BDC-BDC3-D58DF4F83383 > debug.txt`

**Comment by riccardo-casazza** [comment]
Hey, thank you for your answer!

Here is the dump:

Opening database: /Volumes/Photos/Libraries/2022.photoslibrary/database/Photos.sqlite
Done; took 0.64 seconds
_dbphotos['6E3E4723-6933-4BDC-BDC3-D58DF4F83383']:
{'UTI': 'public.jpeg',
 'UTI_original': 'public.jpeg',
 'UTI_raw': None,
 '_uuid': '6E3E4723-6933-4BDC-BDC3-D58DF4F83383',
 'added_date': datetime.datetime(2022, 9, 25, 22, 22, 25, 826251),
 'adjustmentFormatID': None,
 'adjustmentUuid': None,
 'albums': [],
 'alt_master_uuid': None,
 'burst': False,
 'burstPickType': 0,
 'burstUUID': None,
 'cloudAssetGUID': None,
 'cloudAvailable': None,
 'cloudLibraryState': None,
 'cloudLocalState': None,
 'cloudStatus': None,
 'cloudbatchpublishdate': None,
 'cloudownerhashedpersonid': None,
 'countryCode': None,
 'customRenderedValue': 0,
 'datastore_subtype': None,
 'depth_state': 0,
 'directory': '6',
 'extendedDescription': None,
 'favorite': 0,
 'filename': '6E3E4723-6933-4BDC-BDC3-D58DF4F83383.jpeg',
 'fok_import_session': None,
 'hasAdjustments': 0,
 'hasAlbums': 0,
 'hasKeywords': 0,
 'hasPersons': 1,
 'has_raw': False,
 'hdr': False,
 'height': 4480,
 'hidden': 0,
 'imageDate': datetime.datetime(2022, 4, 24, 16, 4, 39, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))),
 'imageDate_timestamp': 672501879,
 'imageTimeZoneOffsetSeconds': 7200,
 'import_session': 51,
 'import_uuid': '3A04E520-E936-4D15-9AAB-019A1B398916',
 'incloud': None,
 'intrash': False,
 'isMissing': 0,
 'isreference': False,
 'keywords': [],
 'lastmodifieddate': None,
 'lastmodifieddate_timestamp': None,
 'latitude': None,
 'live_photo': False,
 'localAvailability': 1,
 'longitude': None,
 'masterFingerprint': 'AbaBLVY8m17rLVgown4Wkj46nE9F',
 'masterUuid': None,
 'modelID': None,
 'momentID': 12,
 'name': None,
 'non_raw_master_uuid': None,
 'orientation': 1,
 'originalFilename': 'Lou-9.jpg',
 'original_filesize': 9075743,
 'original_height': 4480,
 'original_orientation': 1,
 'original_resource_choice': 0,
 'original_width': 6720,
 'panorama': False,
 'persons': [302, 498, 296, 382, 355],
 'pk': 911,
 'placeIDs': None,
 'placeNames': None,
 'portrait': False,
 'raw_data_length': None,
 'raw_info': None,
 'raw_is_original': False,
 'raw_master_uuid': None,
 'remoteAvailability': 0,
 'resource_type': None,
 'reverse_geolocation': None,
 'saved_asset_type': 3,
 'screenshot': False,
 'selfie': False,
 'shared': False,
 'slow_mo': False,
 'subtype': 0,
 'time_lapse': False,
 'trasheddate': None,
 'trasheddate_timestamp': None,
 'type': 0,
 'visibility_state': 0,
 'visible': True,
 'width': 6720}

**Comment by RhetTbull** [comment]
Nothing in the debug dump jumps out as abnormal. Did you try exporting to the local disk and if so, is the file still zero length?

**Comment by RhetTbull** [comment]
@riccardo-casazza Are you still having problems with zero-length files? Were you able to test an export onto local disk?

**Comment by riccardo-casazza** [comment]
@RhetTbull when I export locally, I don't have the problem. I assume it is my Ubuntu SMB server's fault, I tried to change some SMB server parameters, but I still get the problem.
Either you close the ticket and write in README.md that there might be problems writing on SMB, or you may try to reproduce. Still, I'll be available to test on my side as well, if you need help.

**Comment by RhetTbull** [comment]
The fact that this works locally but not on the SMB indicates an issue with the SMB, not osxphotos.  Currently osxphotos uses a native Mac API ([copyItemAtPath:toPath:error:](https://developer.apple.com/documentation/foundation/nsfilemanager/1407903-copyitematpath)) for copying files to take advantage of copy-on-write on newer file systems. It may be this that's causing the issue. The internal design of osxphotos makes it easy to support an alternative copy mechanism.  When I get a chance I'll implement an a copy that uses a different method (setting with a command line flag) and so you can test that.

**Comment by RhetTbull** [comment]
In [v0.54.2](https://github.com/RhetTbull/osxphotos/releases/tag/v0.54.2) I've added an `--alt-copy` flag to `osxphotos export` that causes the export to use an alternate copy method. I'm hoping this solves the problem with the zero-length file on the NAS. Please give your export a try with `--alt-copy` added to your command and let me know if it works.
