### ISSUE TITLE
Maker notes could not be parsed

### ISSUE THREAD

**Issue by dmd** [RhetTbull/osxphotos#812]
Using the `--exiftool` option, every photo I export reports e.g.:

```
❌️  Error exporting photo (E11BCF4D-3BD2-4DFC-B717-10994794C239: IMG_9832.HEIC) as /Users/dmd/photos-export/IMG_9832.HEIC: Error:  Maker
notes could not be parsed -
```

I don't see any actual issue in the exported files, though.

**Comment by RhetTbull** [comment]
I’d start with updated exiftool to the latest version. If you still get the error and don’t mind sharing one of the problem files with me (rturnbull+git@gmail.com) I’ll be happy to take a look.  The error you’re seeing is reported by exiftool, not osxphotos.

**Comment by dmd** [comment]
Aha! Upgrading (using brew) exiftool from 12.42 to 12.50 fixed this.
