### ISSUE TITLE
export by camera type

### ISSUE THREAD

**Issue by steff2632** [RhetTbull/osxphotos#813]
Im trying to export all items into folders based on what camera created them and then date.

Im sure this is possible but can't quite workout how, using either the {photo} template or using python but I can't quite work it out.

the {photo} template doesn't have any documentation, the link just links to a page that says the same things

**Comment by RhetTbull** [comment]
`{exif.camera_make}` should work. That’s listed in the template documentation. The `{photo}` template provides access to the internals of osxphotos but also assumes you’ve read the actual [API documentation](https://github.com/RhetTbull/osxphotos/blob/master/API_README.md)

**Comment by steff2632** [comment]
yep seen that just. Thanks for the response 👍
