### ISSUE TITLE
Bug - labels and search info not correctly processed on macOS 13

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#816]
Thanks -- weird.  It appears the psi.sqlite *is* being loaded (it happens right after this `Processing face details.`) but that the data is not being associated correctly with photos.  If there was an error parsing the data then osxphotos would log a warning which doesn't appear.  

My guess is the mapping of UUID in the psi.sqlite to UUID in the Photos.sqlite isn't working correctly.  In earlier versions of macOS, the UUID for the associated photos is stored as two INTs in the psi.sqlite (I have no idea why as it seems it would be more efficient to have a single primary key (UUID) than two).  osxphotos combines these two ints to produce the UUID for the photo which maps to `Photos.sqlite`.  The code that does the conversion is here:

https://github.com/RhetTbull/osxphotos/blob/2f9b0b8fa18995684a73cfa010989253dc79be16/osxphotos/photosdb/_photosdb_process_searchinfo.py#L196-L206

The ints are stored as little endian signed ints of lenght 8 bytes.  According to [this](https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon) both Apple Silicon and x86 use little endian format so that shouldn't be an issue. 

I don't have access macOS 13 machine so I can't test this directly.  I'll try to think about adding some debugging in to help figure this out.  In the mean time, if you don't mind creating a sample library that you could share, that would be helpful.  If you hold down `Option` while starting Photos you can create a new empty photos library. Then copy a few photos to the new library that should have easily identifiable labels (e.g. dog, cat, beach, etc). Allow the computer to sit overnight with Photos in the background then verify you can search for the appropriate terms in Photos. Then send me the zipped photos library. (rturnbull+git@gmail.com).  The AI/ML photo analysis only happens when Photos isn't being used, hence the need to wait a few hours for `photoanalysisd` to do its thing.

_Originally posted by @RhetTbull in https://github.com/RhetTbull/osxphotos/discussions/814#discussioncomment-4072140_

**Comment by RhetTbull** [comment]
Got the test library -- thanks! I figured out the problem.  The `psi.sqlite` file is where Photos stores all the ML analysis of each photo (including labels/categories) and the `groups.category` column indicates what the data is.  For earlier versions of Photos, the labels where `category = 2024` (determined by reverse engineering) but in your macOS 13.0 database, the labels have `category = 1500` thus osxphotos didn't detect this data as labels.  This wasn't caught in tests because the test library I have for 13.0 was one someone in the r/macos subreddit provided for testing and it didn't have any labels--this is expected when the library hasn't been in existence long enough for `photoanalysisd` to do its thing. 

I'll need to do some re-engineering to allow osxphotos to lookup the correct categories based on macOS version.  In the meantime, the following code will allow you to inspect the labels.

```python
import typing as t

import osxphotos

SEARCH_CATEGORY_LABEL = 1500


def get_photo_labels(photo: osxphotos.PhotoInfo) -> t.List[str]:
    """Return list of normalized search info labels for photo"""
    try:
        search_record = photo._db._db_searchinfo_uuid[photo.uuid]
    except KeyError:
        return []
    return [
        rec["normalized_string"]
        for rec in search_record
        if rec["category"] == SEARCH_CATEGORY_LABEL
    ]
```

```pycon
osxphotos repl --db testlibrary_13_0.photoslibrary
python version: 3.9.13 (main, Nov  6 2022, 18:33:56)
[Clang 12.0.0 (clang-1200.0.32.29)]
osxphotos version: 0.52.0
Loading database
Processing database /Users/rhet/Dropbox/Code/osxphotos/testlibrary_13_0.photoslibrary/database/photos.db
Processing database /Users/rhet/Dropbox/Code/osxphotos/testlibrary_13_0.photoslibrary/database/Photos.sqlite
Processing database.
Database version: 6000, 8.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Done: took 0.15 seconds
Getting photos
Found 4 photos in 0.00 seconds

>>> from labels import get_photo_labels
>>> for p in photos:
...     print(p.uuid, get_photo_labels(p))
34F18324-B20D-47C1-9858-136C7A6F585F
['fence', 'people', 'palm tree', 'tree', 'foliage', 'plant']
2CE9BAC2-7E61-4747-9C20-43337AA48B90
['rocks', 'people', 'fence']
B150DE83-3EDF-496A-A028-0504800A12F1
['hoodie', 'clothing', 'outdoor', 'land', 'beach', 'water', 'water body', 'ocean', 'people', 'child']
F6221127-3F65-40E5-9038-DBBD8CDA1D6D
['people', 'child', 'rocks']
>>>
```

**Comment by RhetTbull** [comment]
@all-contributors please add @dmd for bug

**Comment by RhetTbull** [comment]
@dmd I think labels are fixed for macOS 13.0 in [v0.53.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.53.0).  I can't create a test until I'm able to get a version of the osxphotos test library that's been analyzed by photoanalysisd on Ventura but I did test on the sample library you sent and it correctly identifies all the labels.  The other search categories such as activity, location, etc. are not yet correctly handled (so they won't show up in the `SearchInfo` object) because I'll need to examine an analyzed library from Ventura to identify the right category values.

**Comment by dmd** [comment]
Yes, I'm seeing labels now. Awesome!

**Comment by RhetTbull** [comment]
@all-contributors please add @dmd for userTesting

**Comment by RhetTbull** [comment]
Oooh.....on macOS 13, the search database contains the live text detected in the photo!  (category = 1203)

**Comment by RhetTbull** [comment]
I've fixed as many of the SearchInfo items as I can in [v0.54.1](https://github.com/RhetTbull/osxphotos/releases/tag/v0.54.1).  There may be other search_info items that are incorrect but until I am able to analyze a large Ventura library (e.g. when I upgrade) I won't be able to determine that categories are 100% correct for SearchInfo but I think they're close in this version.
