### ISSUE TITLE
pipx fails to build osxphotos

### ISSUE THREAD

**Issue by dmd** [RhetTbull/osxphotos#825]
```
$ pipx install osxphotos
Fatal error from pip prevented installation. Full pip output in file:
    /Users/dmd/.local/pipx/logs/cmd_2022-11-12_16.45.05_pip_errors.log

pip seemed to fail to build package:
    pyobjc-framework-Cocoa<9.0,>=7.3

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    TypeError: not enough arguments for format string
    error: metadata-generation-failed

Error installing osxphotos.

```
[cmd_2022-11-12_16.45.05_pip_errors.log](https://github.com/RhetTbull/osxphotos/files/9996023/cmd_2022-11-12_16.45.05_pip_errors.log)
[cmd_2022-11-12_16.45.05.log](https://github.com/RhetTbull/osxphotos/files/9996024/cmd_2022-11-12_16.45.05.log)

**Comment by dmd** [comment]
Guessing this is a python 3.11 thing (brew's pipx is now 3.11).

**Comment by RhetTbull** [comment]
Yes....osxphotos currently will not build on 3.11 (due to issues with dependencies, Ref. #817).  You can try this:

`brew install python@3.10`
`pipx install --python python3.10 osxphotos`

**Comment by RhetTbull** [comment]
It's a bit frustrating that pipx does this as the package metadata clearly states that the supported versions are 3.8, 3.9, 3.10.  Not sure if it's a pipx thing or a brew thing that's causing this.

https://github.com/RhetTbull/osxphotos/blob/5364e93e64a0d1f33e56e2389247ddf83cda9079/setup.py#L70-L72

**Comment by RhetTbull** [comment]
Version [0.54.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.54.0) should work with python 3.11.

**Comment by dmd** [comment]
Yep!
