### ISSUE TITLE
no such table: Z_27ASSETS

### ISSUE THREAD

**Issue by neebah** [RhetTbull/osxphotos#830]
most recent version 0.54.0

Mac OS Ventura 13.0

executing osxphotos export --directory {folder_album} --download-missing --deleted --sidecar XMP "DIRNAME"

failed with subject line message.

**Comment by RhetTbull** [comment]
See also #810 

Please verify the version of osxphotos that's actually running by typing:

`osxphotos --version`

This sounds to me like you have an older version of osxphotos that's in the path even though you've installed v0.54.0.

**Comment by neebah** [comment]
0.43.5

**Comment by RhetTbull** [comment]
That's why. You've got a very outdated version of osxphotos that's in your path before the latest version you just installed. You can find it by typing `which osxphotos` then deleting the file.

**Comment by neebah** [comment]
Thank you kindly
