### ISSUE TITLE
Add --find-orphans option to CLI

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#84]
Add option to find orphan photos (if any) -- e.g. those photos that are in the library but not referenced in the database

**Comment by RhetTbull** [comment]
@msg43 the orphans are photos that are in the .photoslibrary folder but do not appear to be referenced in the actual Photos database. They could be lost photos (due to an error) or photos that you deleted but (also due to error) they never got actually deleted off disk. I've never seen more than one or two. Can you send me the output of the orphans command to osxphotos.py@gmail.com? I'll take a look to verify it looks right and the command is running as intended. You could inspect these and see if they are photos you want to keep and if so, import them into the library.

**Comment by msg43** [comment]
Thanks for taking a look at my orphans output.  Here is the smaller
database output (1-10) and the bigger one (1-5).

**Comment by msg43** [comment]
Hi, what do you think of my files?  Is there any easy way for me to batch re-add these file links to the database?

**Comment by RhetTbull** [comment]
Hi @msg43 I just sent you an email reply. The email includes details for using the `--export` option to export the orphans then re-import them into the library.

**Comment by msg43** [comment]
Phenomenal!  Thank you!!
