### ISSUE TITLE
Add --date option to osxphotos import

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#843]
Would be good to have a templated way to set the photo creation date upon import. See discussion below. 

     Hi! 
I have a bunch of images lacking metadata but the file name contains the image capture date:
`001_2009-03-29_someText.png`
I'd like to set the {created} metadata from the file name. 

What would be the best strategy? 
1)  Upon import with a custom template function? Is that possible? 
2)  Once imported in Photos,   parsing all images and set  the creation date?

Second part of my question, experimenting with (1), I wanted to see if I understand the template function by setting  --album: 
` osxphotos import 0-ToPhotos/* --walk --album "{filepath|function:/Users/maizel/Code/scripts/template_function.py::get_shot_date}" --check-templates` 

where `template_function.py` is
```
import pathlib
import re

def get_shot_date(filepath: pathlib.Path):
    filename = filepath.name
    regex = r"^\d{3}_(\d{4}\-\d{2}\-\d{2})_.*\.png"
    match = re.search(regex, filename)
    if match is not None:
        date = match.group(1)
    else:
        date=""
    return date
```
 Running this returns an error: 
```
/Users/maizel/Code/scripts/template_function.py:20 in get_shot_date                              │
│                                                                                                  │
│   17 │   Returns:                                                                                │
│   18 │   │   str or list of str of values that should be substituted for the {function} templ    │
│   19 │   """                                                                                     │
│ ❱ 20 │   filename = filepath.name                                                                │
│   21 │   regex = r"^\d{3}_(\d{4}\-\d{2}\-\d{2})_.*\.png"                                         │
│   22 │   match = re.search(regex, filename)                                                      │
│   23 │   if match is not None:                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'list' object has no attribute 'name'
```
I do not understand, as I'm passing `{filepath}` a Pathlib object, correct? 
What am I missing?

_Originally posted by @AlexisMaizel in https://github.com/RhetTbull/osxphotos/discussions/840_

**Comment by oPromessa** [comment]
What I normally do is to set the EXIF create, original and modified dates with exiftool prior to loading them onto Photos. This way the original file will always have the correct dates. 

See: https://exiftool.org/forum/index.php?topic=8456.0;all

And also https://exiftool.org/faq.html#Q5

**Comment by RhetTbull** [comment]
This can now be done with `--parse-date`, #847
