### ISSUE TITLE
Filetype Is Incorrect

### ISSUE THREAD

**Issue by PetrochukM** [RhetTbull/osxphotos#884]
## Describe the bug

Is there some cache that I do not know about? I am not using `--update`, and yet, for some reason, it seems like `osxphotos` thinks that the PNG image is a JPEG image, even though I had fixed that issue a while ago.

```
% osxphotos export "/Volumes/Extreme SSD/osxphotos" --exiftool --exiftool-merge-keywords --album-keyword --retry 3 --download-missing --directory "{created.year}/" --touch-file --skip-edited --report export.csv
Using last opened Photos library: /Users/michaelpetrochuk/Pictures/Photos Library.photoslibrary
Exporting 29933 photos to /Volumes/Extreme SSD/osxphotos...
❌️  exiftool error for file /Volumes/Extreme SSD/osxphotos/2018/IMG_1943.PNG: Error: Not a valid JPEG (looks more like a PNG) - /var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_wpiqs7py/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
❌️  Error exporting photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG) as /Volumes/Extreme SSD/osxphotos/2018/IMG_1943.PNG: Error: Not a valid JPEG (looks more like a PNG) -
/var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_wpiqs7py/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
Retrying export for photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG)
❌️  exiftool error for file /Volumes/Extreme SSD/osxphotos/2018/IMG_1943 (1).PNG: Error: Not a valid JPEG (looks more like a PNG) - /var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_86hjnyx_/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
❌️  Error exporting photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG) as /Volumes/Extreme SSD/osxphotos/2018/IMG_1943 (1).PNG: Error: Not a valid JPEG (looks more like a PNG) -
/var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_86hjnyx_/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
Retrying export for photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG)
❌️  exiftool error for file /Volumes/Extreme SSD/osxphotos/2018/IMG_1943 (2).PNG: Error: Not a valid JPEG (looks more like a PNG) - /var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_thqsw0_e/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
❌️  Error exporting photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG) as /Volumes/Extreme SSD/osxphotos/2018/IMG_1943 (2).PNG: Error: Not a valid JPEG (looks more like a PNG) -
/var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_thqsw0_e/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
Retrying export for photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG)
❌️  exiftool error for file /Volumes/Extreme SSD/osxphotos/2018/IMG_1943 (3).PNG: Error: Not a valid JPEG (looks more like a PNG) - /var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_99uuu0e1/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
❌️  Error exporting photo (74D5E3D0-08D5-461D-B823-3B14DBC8D4A0: IMG_1943.PNG) as /Volumes/Extreme SSD/osxphotos/2018/IMG_1943 (3).PNG: Error: Not a valid JPEG (looks more like a PNG) -
/var/folders/9c/4358dkjn2wj_c0_89tpry1pm0000gn/T/osxphotos_export_99uuu0e1/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0_exiftool.jpeg
```

I ran a fresh export in a new location of all my photos, and I got this strange error: `IMG_1943.PNG: Error: Not a valid JPEG (looks more like a PNG)`.

This is strange because I had changed the photo to be a PNG, as you can see:

![IMG_1943](https://user-images.githubusercontent.com/7424737/210024447-a9545f01-64bb-41c4-b12d-c5649aeba900.PNG)

It's a PNG, through and through. I even ran `exftools` on it to confirm that it is in-fact a PNG image.

## To Reproduce

I am not sure how to reproduce it; however, I have attached the image. Here are the steps that happened:

1. This image was a JPEG
2. I exported it and it `osxphotos` threw an error
3. I deleted it and re-imported it as a PNG
4. I re-ran `osxphotos` with the command above and I am now receiving this funky error

## Expected behavior

I expect there is some sort of cache for the file type that I am not aware of, I would like to clear it.

## Desktop (please complete the following information):

OS: macOS Ventura Version 13.1 (22C65)

```
% osxphotos --version
osxphotos, version 0.55.5
```

**Comment by RhetTbull** [comment]
I'm guessing the Photos library still thinks this is a JPEG. I'm traveling but when I get a chance will send you some debug commands to run. Osxphotos creates a cache called `.osxphotos_export.db` in the export folder but only uses this when you use `--update` You could try to delete this file then run export again but I'd be surprised if it made a difference.

**Comment by PetrochukM** [comment]
Yeah, I tried to delete it. It didn't help.

That's really interesting when I export it with the Photos app, it exports as a PNG. That's interesting that it might think it's a JPEG still. 

Safe travels!

**Comment by RhetTbull** [comment]
Please try the following command and send the resulting `debug_884.txt` to me at rturnbull+git@gmail.com or post here. Note: the file may contain sensitive info such as location data so you may want to look at first and delete anything you don't want to share. What I'm most interested in are the `UTI_xxx` fields as these will tell me what Photos thinks the photo actually is.

`osxphotos debug-dump --dump photos --uuid 74D5E3D0-08D5-461D-B823-3B14DBC8D4A0 > debug_884.txt`

**Comment by PetrochukM** [comment]
Done!! Thank you!

**Comment by RhetTbull** [comment]
Got the data, thanks. osxphotos clearly thinks this is a jpeg which is why it's creating a temporary jpeg file for exiftool to operate on.  The data you sent shows the original file name is `IMG_1943.PNG` (correct) but shows the UTI (the file type) as `public.jpeg` and hence it thinks this is a jpeg.  Also, the file on disk in the actual library is a jpeg:

` 'filename': '74D5E3D0-08D5-461D-B823-3B14DBC8D4A0.jpeg',`

Is this the only image doing this?

Try the following commands in the Terminal and post output here or send it to me:

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite ".headers on" "select ZUUID, ZUNIFORMTYPEIDENTIFIER, ZFILENAME from ZASSET where ZUUID = '74D5E3D0-08D5-461D-B823-3B14DBC8D4A0'" > 884_uti.txt`

And also:

`exiftool -G ~/Pictures/Photos\ Library.photoslibrary/originals/7/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0* > 884_exiftool.txt`

**Comment by PetrochukM** [comment]
Thanks for those commands; I ran them. It looks like it is, in fact, a PNG image; however, for some reason, Apple has a JPEG extension.

This is the only image doing this. I was able to fix many other pictures with no issues by deleting and re-importing.

```
% sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite ".headers on" "select ZUUID, ZUNIFORMTYPEIDENTIFIER, ZFILENAME from ZASSET where ZUUID = '74D5E3D0-08D5-461D-B823-3B14DBC8D4A0'"
ZUUID|ZUNIFORMTYPEIDENTIFIER|ZFILENAME
74D5E3D0-08D5-461D-B823-3B14DBC8D4A0|public.jpeg|74D5E3D0-08D5-461D-B823-3B14DBC8D4A0.jpeg
% exiftool -G ~/Pictures/Photos\ Library.photoslibrary/originals/7/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0*
[ExifTool]      ExifTool Version Number         : 12.50
[File]          File Name                       : 74D5E3D0-08D5-461D-B823-3B14DBC8D4A0.jpeg
[File]          Directory                       : /Users/michaelpetrochuk/Pictures/Photos Library.photoslibrary/originals/7
[File]          File Size                       : 173 kB
[File]          File Modification Date/Time     : 2022:09:10 20:09:18-07:00
[File]          File Access Date/Time           : 2022:12:29 12:00:49-08:00
[File]          File Inode Change Date/Time     : 2022:12:29 10:46:24-08:00
[File]          File Permissions                : -rw-------
[File]          File Type                       : PNG
[File]          File Type Extension             : png
[File]          MIME Type                       : image/png
[PNG]           Image Width                     : 750
[PNG]           Image Height                    : 1334
[PNG]           Bit Depth                       : 8
[PNG]           Color Type                      : RGB
[PNG]           Compression                     : Deflate/Inflate
[PNG]           Filter                          : Adaptive
[PNG]           Interlace                       : Noninterlaced
[PNG]           SRGB Rendering                  : Perceptual
[XMP]           XMP Toolkit                     : XMP Core 5.4.0
[XMP]           Date Created                    : 2018:03:22 20:22:58
[XMP]           User Comment                    : Screenshot
[Composite]     Image Size                      : 750x1334
[Composite]     Megapixels                      : 1.0
% file ~/Pictures/Photos\ Library.photoslibrary/originals/7/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0*
/Users/michaelpetrochuk/Pictures/Photos Library.photoslibrary/originals/7/74D5E3D0-08D5-461D-B823-3B14DBC8D4A0.jpeg: PNG image data, 750 x 1334, 8-bit/color RGB, non-interlaced
```

This is so funky!

**Comment by RhetTbull** [comment]
I know you've already tried to export this once from Photos and reimport but I suggest doing it once more. Export original from Photos, verify it's a PNG with exiftool and ensure it has PNG extension then re-import and delete the original. If that doesn't work, I'll craft a SQL command to directly modify the UTI in the Photos database.

**Comment by PetrochukM** [comment]
That worked this time around! Thank you! So, strange!
