### ISSUE TITLE
Add QuickTime:ContentCreateDate to photo exporter for --exiftool

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#890]
Reference #888

**Comment by RhetTbull** [comment]
Included in v0.55.6](ttps://github.com/RhetTbull/osxphotos/releases/tag/v0.55.6)

**Comment by oPromessa** [comment]
Quick question: once I upgrade to 0.55.6 will `osxphotos` re-export all the videos (MOV, MP4, etc) -- running with options `--update` and `--cleanup` -- to update the exported files?

Just want to be prepared if I have to run a huge export/update!

**Comment by RhetTbull** [comment]
@oPromessa yes, likely as the new exif metadata won't match and that's what osxphotos checks for update
