### ISSUE TITLE
Add ScoreInfo metrics to `osxphotos inspect`

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#899]
Add the most important `ScoreInfo` metrics to `osxphotos inspect` to see quality metrics in the inspector window.

**Comment by davebullock-ujet** [comment]
I approve this message. Looking forward to this!

**Comment by eecue** [comment]
Looking forward to this one

**Comment by RhetTbull** [comment]
Added in [v0.56.2](https://github.com/RhetTbull/osxphotos/releases/tag/v0.56.2)
