### ISSUE TITLE
Issue using export() with convert_to_jpeg

### ISSUE THREAD

**Issue by eecue** [RhetTbull/osxphotos#913]
**Describe the bug**
I am unable to use the `convert_to_jpeg` flag:

```
>>> photos_to_process[0].export(os.getcwd(), filename="test.jpg",overwrite=True,convert_to_jpeg=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: export() got an unexpected keyword argument 'convert_to_jpeg'

export() got an unexpected keyword argument 'convert_to_jpeg'
```
I am running the latest version, I installed with pip:

```
Name: osxphotos
Version: 0.55.7
Summary: Export photos from Apple's macOS Photos app and query the Photos library database to access metadata about images.
Home-page: https://github.com/RhetTbull/
Author: Rhet Turnbull
Author-email: rturnbull+git@gmail.com
License: License :: OSI Approved :: MIT License
Location: /Users/eecue/mambaforge/lib/python3.9/site-packages
Requires: bitmath, bpylist2, Click, Mako, more-itertools, objexplore, osxmetadata, packaging, pathvalidate, photoscript, ptpython, pyobjc-core, pyobjc-framework-AppleScriptKit, pyobjc-framework-AppleScriptObjC, pyobjc-framework-AVFoundation, pyobjc-framework-Cocoa, pyobjc-framework-CoreServices, pyobjc-framework-Metal, pyobjc-framework-Photos, pyobjc-framework-Quartz, pyobjc-framework-Vision, pytimeparse2, PyYAML, requests, rich, rich-theme-manager, shortuuid, strpdatetime, tenacity, textx, toml, wrapt, wurlitzer, xdg
Required-by: 
```

**Comment by RhetTbull** [comment]
convert_to_jpeg needs to be passed as an [ExportOptions](https://github.com/RhetTbull/osxphotos/blob/master/API_README.md#exportoptions) argument to [PhotoExporter.export()](https://rhettbull.github.io/osxphotos/reference.html#osxphotos.PhotoExporter.export).  There are two ways to export a photo: 

1. Using [PhotoInfo.export()](https://rhettbull.github.io/osxphotos/reference.html#osxphotos.PhotoInfo.export) which is a "legacy" method with a limited number of arguments.
2. Using [PhotoExporter.export()](https://rhettbull.github.io/osxphotos/reference.html#osxphotos.PhotoExporter.export) which provides a much more robust way to export photos. In this method, you must use an `ExportOptions` instance to pass the parameters including `convert_to_jpeg`.

**Comment by eecue** [comment]
Thanks!
