### ISSUE TITLE
Find photo in iCloud but not downloaded

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#920]
Is there any way to find a photo that is in iCloud but has not been downloaded? I am confused as to how to use the various query modifiers like "missing" "incloud" "cloudasset"

**Comment by RhetTbull** [comment]
If the photos are in icloud but have never been synced to the local computer, there's no way for osxphotos to know this as osxphotos only operates on the local Photos library.  However, if the photos have been synced to the local computer but the original image has not been downloaded yet (for example, you have "optimize Mac storage" set in Photos Preferences, then you should be able to find these photos using:

`osxphotos query --incloud --missing`

You could use `osxphotos query --incloud --missing --add-to-album "Missing"` to add the photos to the album "Missing"

In this case, `osxphotos query --cloudasset --missing` would also do the same thing. The `--missing` option looks for photos that are not on disk in the local library. `--cloudasset` finds all photos that are part of an iCloud library. `--incloud` finds all photos that have been uploaded to iCloud (and by definition, these are also cloud assets).

**Comment by narensankar0529** [comment]
So I have a weird issue in that iCloud.com and my iPad claim to have an extra photo compared to my Mac mini and air and iPhone. And I am trying to figure out how to locate this extra photo. 

So it seems that the actual database on disk is not the same as on iCloud.com - correct?

**Comment by RhetTbull** [comment]
> So it seems that the actual database on disk is not the same as on iCloud.com - correct?

This can be the case. For example, there could be a photo on the local Mac that hasn't yet synced to iCloud or in your case, a photo in iCloud that for some reason isn't syncing to the Mac. 

The following script will compare two libraries (for example, your Mac and iPhone) and tell you which photos are in one library but not the other.

1. You'll need to copy the photos library off your iPhone to the Mac.  I recommend using [iMazing](https://imazing.com/) to copy the Photos.sqlite file from your iPhone to your Mac (for example, to the Downloads folder).  

You will need to copy the following files from your iPhone to your Mac:
- /Media/PhotoData/Photos.sqlite
- /Media/PhotoData/Photos.sqlite-shm
- /Media/PhotoData/Photos.sqlite-wal

The free trial version of iMazing should work fine for this.

Then save the script in the attached zip file to your computer (it's called `compare_libraries.py`) and run it via:

`osxphotos run compare_libraries.py ~/Downloads/Photos.sqlite ~/Pictures/Photos\ Library.photoslibrary`

[compare_libraries.zip](https://github.com/RhetTbull/osxphotos/files/10416746/compare_libraries.zip)

**Comment by RhetTbull** [comment]
Also, you'll need to ensure osxphotos is upgraded to the latest version for this to work.
