### ISSUE TITLE
When exporting photos with --finder-tag-keywords, does not work with --dry-run

### ISSUE THREAD

**Issue by pweaver** [RhetTbull/osxphotos#958]
** Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version **

- If you installed with pipx: `pipx upgrade osxphotos`
- If you installed with pip: `pip install --upgrade osxphotos`
- If you installed the pre-built binary, download and install the latest [release](https://github.com/RhetTbull/osxphotos/releases)

**Describe the bug**

on export --finder-tag-keywords does not work with --dry-run.

looks like write_finder_tags should take a dry_run option and not do the final command if it is set.

**To Reproduce**
1. What' the full command line you used with osxphotos?
2. What was the error output?
osxphotos export --load-config "config.toml" "$PHOTO_DIR"

Config file:
added_after = 2023-01-26T00:00:00
album_keyword = true
append = true
directory = "{created.year}/{created.strftime,%Y-%m-%d}"
download_missing = true
exiftool = true
exiftool_merge_keywords = true
exiftool_merge_persons = true
finder_tag_keywords = true
ignore_signature = true
report = "export_report.csv"
sidecar = [ "xmp",]
strip = true
touch_file = true
update = true
verbose = true

**Expected behavior**
osxphotos shouldn't crash when testing --finder-tag-keywords and --dry-run

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS]
 - osxphotos version (`osxphotos --version`)

Ventura 13.1
osxphotos, version 0.56.6

**Additional context**

Crashlog:
Created: 2023-01-27 14:39:30.952491
osxphotos version: 0.56.6
Platform: macOS-13.1-x86_64-i386-64bit
Python version: 3.9.16 (main, Dec  7 2022, 10:16:11)
[Clang 14.0.0 (clang-1400.0.29.202)]
sys.argv: ['/usr/local/bin/osxphotos', 'export', '--load-config', '/Users/pweaver/Pictures/scripts/config.toml', '/Users/pweaver/Pictures']
CRASH_DATA: \nlocals: {'ctx': <click.core.Context object at 0x107fec550>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x103410b20>, 'db': None, 'photos_library': (), 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': False, 'alt_copy': False, 'append': False, 'beta': False, 'burst': False, 'cleanup': False, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'dest': '/Users/pweaver/Pictures', 'directory': None, 'download_missing': False, 'dry_run': False, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': False, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': None, 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': '/Users/pweaver/Pictures/scripts/config.toml', 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': False, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': None, 'save_config': None, 'screenshot': False, 'selected': False, 'selfie': False, 'shared': False, 'sidecar_drop_ext': False, 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': False, 'update': False, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose': False, 'xattr_template': (), 'year': (), 'sidecar': (), 'skip_uuid': ()}
cfg: {'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': datetime.datetime(2023, 1, 26, 0, 0), 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': True, 'alt_copy': False, 'append': True, 'beta': False, 'burst': False, 'cleanup': False, 'cloudasset': False, 'convert_to_jpeg': False, 'current_name': False, 'db': None, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'directory': '{created.year}/{created.strftime,%Y-%m-%d}', 'download_missing': True, 'dry_run': True, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': True, 'exiftool_merge_keywords': True, 'exiftool_merge_persons': True, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': None, 'finder_tag_keywords': True, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_signature': True, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': False, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'photos_library': (), 'place': (), 'portrait': False, 'post_command': (), 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': 'export_report.csv', 'retry': None, 'screenshot': False, 'selected': False, 'selfie': False, 'shared': False, 'sidecar': ('xmp',), 'sidecar_drop_ext': False, 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid': (), 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': True, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': True, 'update': True, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose': True, 'xattr_template': (), 'year': ()}
osxphotos version: 0.56.6
Error: file does not exist: /Users/pweaver/Pictures/2023/2023-01-27/IMG_4861.HEIC
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/osxphotos/crash_reporter.py", line 36, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/osxphotos/cli/export.py", line 1634, in export
    tags_written, tags_skipped = write_finder_tags(
  File "/usr/local/lib/python3.9/site-packages/osxphotos/cli/export.py", line 2694, in write_finder_tags
    md = OSXMetaData(f)
  File "/usr/local/lib/python3.9/site-packages/osxmetadata/osxmetadata.py", line 80, in __init__
    raise FileNotFoundError(f"file does not exist: {fname}")
FileNotFoundError: file does not exist: /Users/pweaver/Pictures/2023/2023-01-27/IMG_4861.HEIC

**Comment by RhetTbull** [comment]
Definitely a bug. Looks like the same is try for --xattr

https://github.com/RhetTbull/osxphotos/blob/770d85759da6acf94a08d046aea29e101daa3fc7/osxphotos/cli/export.py#L1637-L1664

**Comment by RhetTbull** [comment]
@all-contributors please add @pweaver for bug, ideas

**Comment by RhetTbull** [comment]
Fixed in [v0.56.7](https://github.com/RhetTbull/osxphotos/releases/tag/v0.56.7)
