### ISSUE TITLE
Crash on --cleanup deleting a file with OSError 16 Resource Busy | Granted! .smbdelete files should not be there in the first place ;)

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#987]
**Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version**
* Running 0.57.0 and not the latest one 0.57.1
 
**Describe the bug**
* Crash while performing delete files based on `--cleanup` which found a `.smbdeleteAAA3e0272` locked file which was unable to delete from the export folder.
* Still investigating... such files come up from MAC accessing a SMB NAS resource. Must cleaned them up. They only now started showing up!
* A quick workaround I'm testing is to tell `osxphotos` not to bother with such files for now with `--keep ".smbdelete*"` option.
* Resulted in a crash which generated a `osxphotos_crash.log` of 365MB (as I believe is dumping all data structures from a 90K pics database)! The last few lines are:

```python
(...)
'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose': True, 'xattr_template': (), 'year': ()}
osxphotos version: 0.57.0
Error: [Errno 16] Resource busy: '/Volumes/photo/(...)/.smbdeleteAAA3e0272'
Traceback (most recent call last):
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/crash_reporter.py", line 36, in wrapped
    return func(*args, **kwargs)
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/export.py", line 1638, in export
    cleaned_files, cleaned_dirs = cleanup_files(
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/export.py", line 2474, in cleanup_files
    fileutil.unlink(p)
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/fileutil.py", line 139, in unlink
    filepath.unlink()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1354, in unlink
    self._accessor.unlink(self)
OSError: [Errno 16] Resource busy: '/Volumes/photo/(...)/.smbdeleteAAA3e0272'
```

**To Reproduce**

* Command line
```sh
osxphotos export "${DSTFOLDER}" --exportdb ${FOLDER}/.osxphotos_export.db --load-config ${WORKFOLDER}/colibri.toml >> ${LOGFILE} 2>&1
```
* TOML file
```toml
[export]
cleanup = true
db = "/Users/Shared/Pictures/iPhoto Shared Library.photoslibrary"
description_template = "Album:{album,}{newline}Description:{descr,}"
#directory = "{album[/,.|:,.]}"
directory = "{album|filter(startswith 1|2)[/,.|:,.]}"
dry_run = true
exiftool = true
exiftool_merge_keywords = true
exiftool_merge_persons = true
keyword_template = [
    "{keyword}",
    "{label}",
    "{searchinfo.activity?activity:{searchinfo.activity},}",
    "{searchinfo.venue_type?venue_type:{searchinfo.venue_type},}",
]
no_progress = true
not_hidden = true
ramdb = true
retry = 2
skip_bursts = true
skip_live = true
skip_original_if_edited = true
strip = true
timestamp = true
touch_file = true
update = true
verbose = true
```
**Expected behavior**
* For now I've added the following entry to the `toml`file in order to bypass attempting to delete it.
```toml
[export]
cleanup = true
keep = ".smbdelete*"
```
* and building up a try/except code change... checking how to test it out now!
https://github.com/oPromessa/osxphotos/blob/1f8c6134c7d2811d9a125165fd693d8691d86ffa/osxphotos/cli/export.py#L2489-L2503

**Screenshots**
N/A

**Desktop (please complete the following information):**
```sh
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
$ osxphotos --version
osxphotos, version 0.57.0
```
**Additional context**

**Comment by RhetTbull** [comment]
I'll add a try/except around the unlink to catch errors. For cleanup, failure to delete a file shouldn't be a fatal error. I'm head down in another project at the moment but sounds like you have a workaround until I get to this.

**Comment by RhetTbull** [comment]
The try/catch should be added around the unlink here, both for files and for directories. If there's an error, print a warning to the user but continue.

https://github.com/RhetTbull/osxphotos/blob/715d874306948497b885a3a7e007d2b39f06e494/osxphotos/cli/export.py#L2488-L2505

**Comment by oPromessa** [comment]
Uau! thanks for the prompt reply. 

0. No worries. I got it going!
1. Yup... maybe this code might help [From my forked repository](https://github.com/oPromessa/osxphotos/blob/1f8c6134c7d2811d9a125165fd693d8691d86ffa/osxphotos/cli/export.py#L2489-L2503)
```python
    for p in pathlib.Path(dest_path).rglob("*"):
        if p.is_file() and normalize_fs_path(str(p).lower()) not in keepers:
            verbose(f"Deleting [filepath]{p}")
            try:
                fileutil.unlink(p)
                deleted_files.append(str(p))
            except OSError as e:
                # Catch OSError: [Errno 16] Resource busy
                if e.errno == 16:
                    verbose(f"Bypassing OSError: {e} while deleting [filepath]{p}")
                    # It might be intereting to save the failed entry into a results = ExportResults() list
                else:
                    raise OSError(
                        f"Error Deleting [filepath]{p}: {e}"
                    ) from e
```
2. With `lsof` I could easily find the culprit...our friend Preview. Closed it and the file was released and disappeared.
```sh
$ lsof .smbdeleteAAA3e0272 
lsof: WARNING: can't stat() smbfs file system /Volumes/.timemachine/colibri._smb._tcp.local./3E91D313-5C98-479F-AC55-AD666E867006/Time Machine Folder
      Output information may be incomplete.
      assuming "dev=360005aa" from mount table
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
Preview 39452  MSP  txt    REG 54,676  1535027 4063858 .smbdeleteAAA3e0272
```
